### ISSUE TITLE
Virus total behaviour report - strange queries

### ISSUE THREAD

**Issue by 60plus** [TeamNewPipe/NewPipe#10107]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my question isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the question will be dismissed otherwise.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### What is/are your question(s)?

Hello
I wanted to ask about strange queries performed by NewPipe.

Queries several sensitive phone informations
Queries the unqiue device ID (IMEI, MEID or ESN)
Queries list of running processes/tasks
Queries the phones location (GPS)

Why do you need this data?

**Comment by TobiGr** [comment]
We do not query that data. How did you come to the conclusion that we access and process that data?

**Comment by 60plus** [comment]
https://www.virustotal.com/gui/file/9e7842ffa959ae8e588af90fb4069949a940cccde05d2568eeb0b5a00ca44532/behavior

**Comment by TobiGr** [comment]
Hm. I think VirusTotal is a bit off there. We do not access the unique device ID, but model information to enable/disable certain features within the app, such as auto-focus and visual effects. That is done for example in these methods: [isFireTV()](https://github.com/TeamNewPipe/NewPipe/blob/df430badbc948805464e1d3ef7f3ca3b1ae83534/app/src/main/java/org/schabi/newpipe/util/DeviceUtils.java#L42), [isTV()](https://github.com/TeamNewPipe/NewPipe/blob/df430badbc948805464e1d3ef7f3ca3b1ae83534/app/src/main/java/org/schabi/newpipe/util/DeviceUtils.java#L52), [isDesktopMode()](https://github.com/TeamNewPipe/NewPipe/blob/df430badbc948805464e1d3ef7f3ca3b1ae83534/app/src/main/java/org/schabi/newpipe/util/DeviceUtils.java#LL86C27-L86C40) as well to disable media tunneling in expoplayer because certain Android TV models (or better their processors) do not support that feature (e.g. see https://github.com/TeamNewPipe/NewPipe/pull/5969). As you can see the data obtained is available or used in those methods and not passed to other parts of the app.

I have no idea how virus total come to the conclusion that we query the phone's location. We do have some preferences keys which allow to set the content country and language. Maybe that is misinterpreted by virus total. I also do not know what could possibly be mistaken to as "Queries list of running processes/tasks", especially because the related info box on the linked virus total page says 

> Recent Android security enhancements have made it more difficult to obtain a list of running processes. On Android 7 and later, there is no way for an application to obtain the process list without abusing elevated privileges. This is due to the Android kernel utilizing the hidepid mount feature. Prior to Android 7, applications could utilize the ps command or examine the /proc directory on the device

The whole scan looks to me very wrong, e.g. it says that NewPipe "Loads advertisement". NewPipe certainly does not load advertisements at all. The related endpoints aren't even contacted in the first place. However, NewPipe contacts endpoints which return the video info which results in ads being loaded in other apps. I think what the scan is doing is looking at the contacted API endpoints / domains and just giving some standard "discovery info" about those contacted endpoints. But that is exactly the problem here. We do not submit the same data to those endpoints as others (e.g. YouTube) does and do not use all of the returned data as well.

**Comment by TobiGr** [comment]
That's not what I said. I have no idea where you took that from.
