### ISSUE TITLE
Swipe up and swipe down for volume control isn't working

### ISSUE THREAD

**Issue by MUNadeem** [TeamNewPipe/NewPipe#10189]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.25.1

### Steps to reproduce the bug

Just watched a video full screen and tried to control the volume by swiping up and down. When it didn't work I clear the cache and data, still it didn't work.

### Expected behavior

While watching a video on full-screen, swipe up and swipe down to control the brightness (left side) and volume (right side).

### Actual behavior

Recently I noticed while watching a video on full-screen, swiping up and down on the right side of the screen does not control the volume. Though the icon for volume changes showed up on the screen but the volume doesn't increase or decrease.
FYI: On the left side, it controls the brightness all fine.

### Affected Android/Custom ROM version

Android 13

### Affected device model

Samsung Galaxy S20 FE

**Comment by AudricV** [comment]
I am not able to reproduce the issue on my device.

Could you reproduce the issue on a debug build like the one in https://github.com/TeamNewPipe/NewPipe/actions/runs/5266219846 or [on the latest nightly version of the app](https://github.com/TeamNewPipe/NewPipe-nightly/releases/latest)?

More swiping gestures settings have been added, so you may try to set volume gesture on the left side of your screen if you can still reproduce the issue with these builds without changing anything.

If the issue is always here, then I think that's a device or system issue, in this case logs captured from Android's logcat may be useful to debug the issue.

**Comment by AudricV** [comment]
@MUNadeem Could you explain why did you close the issue?

**Comment by MUNadeem** [comment]
I didn't do anything specifically but it's started working now. My phone might update itself recently. I checked my NewPipe version and it's still same. Thank you
