### ISSUE TITLE
Missing new videos from a subscribed channel

### ISSUE THREAD

**Issue by kiuKisas** [TeamNewPipe/NewPipe#1066]
Hi ! First of all, I never had a chance to thank's you for your working, I use your app since several month and I enjoy it so.. Thank you !
I notice a weird bug, I follow my Likes on newPipe to be able to listen quickly to my favorite music, and it's work well ! Except since several days, my new likes doesn't appear. It's weird because when I share my likea from youtube official app to newPipe, these new like are there. I took some screenshot to show you:
<img src="https://user-images.githubusercontent.com/12698940/35767006-a1023da8-08e3-11e8-8d08-2426a65e722b.png" width=350px/>
This is from the subscribe section.

<img src="https://user-images.githubusercontent.com/12698940/35767011-ce6c9ce8-08e3-11e8-8f29-c98d3b37a84e.png" width=350px />
And this is when I share from youtube official app

I try to unfollow and follow again, but nothing change. Maybe a cache issue ?

**Comment by mauriciocolli** [comment]
I just figured it out, the extractor is parsing everything that the `/videos` contains, this implies in:

- When the user has no uploads but has their likes public:
<img src="https://user-images.githubusercontent.com/13389907/35767210-0be57c9e-08cf-11e8-92ba-a535be3d8240.PNG" width="280">

- When the user has uploads and their likes public, the uploads is the default:
<img src="https://user-images.githubusercontent.com/13389907/35767220-29dbe094-08cf-11e8-87ed-54382d68dfe7.PNG" width="280">

- When neither is available:

<img src="https://user-images.githubusercontent.com/13389907/35767238-b887f364-08cf-11e8-9aed-f6f28d7cf58b.PNG" width="550">

The first case is what happening to you, the new videos are not showing up because of what you expected, cache.

I'll open an issue in the extractor because this is not the correct behavior, you can see at your channel screenshot that the videos are as if they were uploaded by you, because it expects to.

The likes will not show up anymore in your channel after this is fixed, but don't worry, we are going to add the "Playlists" tab soon, and when the user make their liked playlists public, it will show up there.

**Comment by justanidea** [comment]
But can you like any video with newpipe? I cant do it at all

**Comment by justanidea** [comment]
Okay, i found it weird to see someone doing that with newpipe, thats why i asked for more infromations :)

**Comment by theScrabi** [comment]
He was not doing it with newpipe. I @kiuKisas has his own channel where he can like videos. Now he can subscribe to his channel via NewPipe, and se his liked videos there.

Except it seems it does not work anymore.

**Comment by kiuKisas** [comment]
Still no news about it ? I noticed that this behaviour is not only for newer "liked videos" but for some random one, take a look:
YouTube:
![screenshot_2018-12-12-12-43-56-201_com google android youtube](https://user-images.githubusercontent.com/12698940/49867816-e0897400-fe0b-11e8-9b72-c8435fa4515e.png)!!!!!£!!![screenshot_2018-12-12-12-44-02-604_com google android youtube](https://user-images.githubusercontent.com/12698940/49867812-dff0dd80-fe0b-11e8-9064-770e2bc81835.png)
NewPipe:
![screenshot_2018-12-12-12-44-20-311_org schabi newpipe](https://user-images.githubusercontent.com/12698940/49867814-dff0dd80-fe0b-11e8-8129-b6009b81d900.png)
![screenshot_2018-12-12-12-43-21-785_org schabi newpipe](https://user-images.githubusercontent.com/12698940/49867815-e0897400-fe0b-11e8-8536-99095407dc5f.png)

**Comment by kiuKisas** [comment]
Currently I'm working on a YouTube parser in Elixir on my free time, when I'll reach this point in my library I'll have a look at NewPipe behaviour regarding "liked videos" but that can be in several months..

**Comment by kiuKisas** [comment]
I also tried to see my "liked videos" trough YouTube mobile website:
![screenshot_2018-12-12-12-59-03-082_com android chrome](https://user-images.githubusercontent.com/12698940/49868477-dc5e5600-fe0d-11e8-9225-edaa1af788db.png)

.. and that match what newPipe give me, so now I'm a bit confusing about what happening..

**Comment by Stypox** [comment]
In #2650 it's said that the problem lies in unavailable videos from channels not being loaded. Is it true? If it is then this is not a problem on NewPipe's end

**Comment by kiuKisas** [comment]
it was a problem with the web/mobile version of youtube that didn't display all the videos I liked for some reason. After a quick check, this issue doesn't seems to appear anymore. We can close this issue I guess.
