### ISSUE TITLE
Cant import youtube subscription list from takeout 

### ISSUE THREAD

**Issue by shijogeorge24** [TeamNewPipe/NewPipe#10759]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

v0.26.1

### Steps to reproduce the bug

1.got to settings 
2.choose content
3.choose import database 
4.choose zip file  

### Expected behavior

1.ask for file permission 
2.show fail or pass  or status of new import

### Actual behavior

1.wont ask for any type of file permission 
2.try to import from the zip file 
3 error with warning: could not import all files 
4.no subscription are imported 

### Affected Android/Custom ROM version

LineageOS 20

**Comment by evilrobotdrew** [comment]
I do not open this bug report but I am experiencing the same issue.

In a different file manager app I'm able to see the file and interact with it. I can see both the zip file and the CSV inside it, on the default files application and on the file manager application I just downloaded from the Play store.

To be clear, new pipe will see the zip file, allow me to select it, but fail to import anything due to the error documented above. 

When I decompress the zip file, new pipe will not even give me the option to select the CSV file. This is why your highlighted option 7 does not work, new pipe does not seem to allow the import of CSV files. I have attempted renaming the file to dot txt and.json in case there was some file extension issue preventing the import. No file extension I attempted allows the import of the file. The option remains gray, clicking on it within the UI does nothing. All other tested file managers are able to open and extract the zip file, and are able to open the CSV file without issue.

I wish I could use this application, but I am not willing to sit and manually transcribe several dozen subscriptions from my YouTube account.

[subscriptions.csv](https://github.com/TeamNewPipe/NewPipe/files/14114571/subscriptions.csv)

Included is the subscriptions.csv I'm attempting to import

**Comment by evilrobotdrew** [comment]
Okay there's a lot of issues that mention Google Takeout, can you be a little more specific?

Is there a way to simply import the CSV itself? Based on some of the other issues that I saw I should be able to select the CSV but it is simply grayed.

I'm not willing to take the time or effort to try to convert the CSV into a JSON, if I'm not sure I can import the JSON when I'm done.

**Comment by evilrobotdrew** [comment]
Yeah bro I'm going to be real with you, I'm not going to do all that. I do
enough of this BS at work, I just wanted to watch YouTube videos on my
phone without an ad every 5 minutes.

I'll try the app again in a couple months.

**Comment by FlameWolf** [comment]
Having the same issue with version 2.6.1.

**Comment by lukstafi** [comment]
Note: I couldn't import a file from Google Drive, after reading through the discussion on another issue about this and scratching my head, I downloaded the file, selected the local file (using the same UI), it worked.

**Comment by chris122380** [comment]
> Note: I couldn't import a file from Google Drive, after reading through the discussion on another issue about this and scratching my head, I downloaded the file, selected the local file (using the same UI), it worked.

I believe this is a problem specifically with Google drive and not Newpipe. I have had this issue with other apps that let me back up their files to Google drive. If I try to do a restore it refuses to but will work if I restore from the downloaded local copy.
