### ISSUE TITLE
Improve resolution selection

### ISSUE THREAD

**Issue by ghost** [TeamNewPipe/NewPipe#1103]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

As follow-up of https://github.com/TeamNewPipe/NewPipeExtractor/issues/71, we should add a better resolution selector. It should only show resolutions and choose the best streams for that resolution that the device supports (like YouTube does). We should also add adaptive streaming (e.g. YouTube's Auto resolution). But we should also have an advanced option to choose the specific streams manually.

**Comment by speednroll** [comment]
it's a great idea! especially because I hope this can correct some errors, like watching a video when you have a certain resolution and the video is not compatible with that resolution, it gives an error like "the video is not available". change the resolution to a lower one automatically than if it is available

**Comment by theScrabi** [comment]
Ok souds good.

**Comment by karyogamy** [comment]
There was an attempt on a similar concept in the [play queue PR](https://github.com/TeamNewPipe/NewPipe/pull/680). Though this was done by merging all available stream sources and use ExoPlayer's default track selector to do the work. However, this can have a huge overhead on the network, since Exoplayer wants to load all the headers to make the track switching faster. Also, the default track selector doesn't pass the metadata from extractor internally, so the actual mimetype and framerate data is lost and only 60fps is chosen. We can probably roll our own solution by extending Exoplayer, though I imagine that is going to require some hefty research and maintainance in the future.

We can also use the dash manifest from the extractor, but this is not a universal solution, even on Youtube. Apparently, these manifests are [uncommon](https://github.com/rg3/youtube-dl/issues/3763), and after testing on Youtube-dl, there seems to have manifest for audio only streams in the videos I have tried. 

Both solutions requires the same change to the players, mainly on track selection. The same mechanics are used for subtitles already, so it shouldn't be too difficult implement (this will need to be done eventually due to livestream uses hls manifests). But if we want to continue support for resolutions under both 24 and 60 fps, then it might take some more effort.

**Comment by litetex** [comment]
Closed due 
* to inactivity
* already implemented: Best resolution is already implemented
