### ISSUE TITLE
Player not working

### ISSUE THREAD

**Issue by BILALMBAK2000** [TeamNewPipe/NewPipe#11291]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.27.0

### Steps to reproduce the bug

Trying to play any video

### Expected behavior

Play the video

### Actual behavior

Throwing error and not playing any video

### Affected Android/Custom ROM version

Android 12 miui 14.0.5

### Affected device model

Redmi note 10

**Comment by RamoxCode** [comment]
interestingly, the audio-only playback still works

**Comment by ShareASmile** [comment]
> - [x] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).

Already have been fixed in v0.27.1.
Please check next time whether you are using latest version(as you ticked in template above) before opening an issue as well as for duplicates from existing issues first, Thank you.

If you have not updated to latest version yet, this info shall help [how to get latest version](https://github.com/TeamNewPipe/NewPipe/discussions/11286#discussioncomment-10044517)
