### ISSUE TITLE
I've started with the tutorial

### ISSUE THREAD

**Issue by theScrabi** [TeamNewPipe/NewPipe#1131]
I just wanted to announce that I've started to create the [tutorial](https://github.com/TeamNewPipe/tutorial) for the NewPipeExtractor, which in combination with the [documentation](https://teamnewpipe.github.io/NewPipeExtractor/javadoc/) should make it easyer to write own services for NewPipe.

**Comment by speednroll** [comment]
this is great! 😉

**Comment by wb9688** [comment]
@theScrabi: I was about to start with a tutorial (until I saw this), do you already have some parts finished?

**Comment by TobiGr** [comment]
Sounds good! Tell me when it is in a good state so we can link it from our website and write a blog post about it :+1:

**Comment by theScrabi** [comment]
@wb9688 not yet, but I structure things in my head already.
I probably start with a page telling how to setup the dev environment for the Extractor.

**Comment by wb9688** [comment]
@theScrabi: Yeah, I'd recommend creating a new Gradle Java application, then cloning NewPipeExtractor in its folder and then including it, so you could easily see if your extractor works.

I also wouldn't say anything specific to an IDE, since someone should be able to use their prefered IDE.

Btw maybe we could create an Etherpad first?

**Comment by theScrabi** [comment]
@TobiGr that will take a while. I'd like to write a post once the tutorial is usable, however I don't expect that for the next few months.

**Comment by theScrabi** [comment]
> I also wouldn't say anything specific to an IDE

I'd like to give an easy start. If somone is willing to use a different ide he can do so, I will show one way with one ide.

**Comment by wb9688** [comment]
>I'd like to give an easy start. If somone is willing to use a different ide he can do so, I will show one way with one ide.

Why? It'd be a tutorial about implementing a service extractor, not about how to use an IDE. And I think we don't need to explain things that are specific to an IDE, for example "import the Gradle project" or "run it" or "create a new class" should be enough for the people following the tutorial, since I think if they can't figure that out, they probably can't figure out how to write a service extractor either. So I think we shouldn't say anything specific to an IDE (like "click on File in the bar at the top of Eclipse, then click Import, a pop-up will appear, in that pop-up choose Gradle > Existing Gradle Project and click Next, then click on Browse and select the folder you made for this tutorial, then click on OK and finally click on Finish").

**Comment by theScrabi** [comment]
I see. I'll try not to get to specific. :)

**Comment by FaizKhan5** [comment]
Close this.
