### ISSUE TITLE
Videos run haltingly since version 0.27.2

### ISSUE THREAD

**Issue by Mithgarthsormr** [TeamNewPipe/NewPipe#11380]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.27.2

### Steps to reproduce the bug

1. Start a video (I can always reproduce it with this video: https://www.youtube.com/watch?v=Yxb5HgG8oWA&t=148 but also with most other videos, this one is the worst).
2. Look at the elapsed time to see if it sometimes jumps

### Expected behavior

Elapsed time should not jump for several seconds permanently.

### Actual behavior

Elapsed time jumps for 1-3 seconds, sometimes more than once per second.

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/96b7c76a-83a7-4534-8d3d-5a7806db4ef8

### Affected Android/Custom ROM version

Android 12

### Affected device model

Samsung Galaxy S10e

**Comment by Mithgarthsormr** [comment]
> Regardless of when it started, you're supposed to test and report it on the latest version at the very least.

Oh, I accidentally wrote the wrong version into the issue, I use v0.27.2

**Comment by WagnerGMD** [comment]
> ### Affected version
> 
> 0.27.0

**Just to confirm ** 
No @Mithgarthsormr you are wrong because :
-  [The "NewPipe-v0.27.0"](https://github.com/TeamNewPipe/NewPipe/releases/tag/v0.27.0) was published on the 23 April 2024 !
- 3 weeks ago we got the previous version which was [the "NewPipe-v0.27.1"](https://github.com/TeamNewPipe/NewPipe/releases/tag/v0.27.1) !
- That's why you are very late as you can see the latest is [the "NewPipe-v0.27.2"](https://github.com/TeamNewPipe/NewPipe/releases/tag/v0.27.2) !

Meaning : No offense but to receive (except) any help, you must **remember one thing :** at the beginning, **you have to always check the link from the 1st line.**
Otherwise the staff behind NewPipe will decide to close (ignore) your report (basically you must respect the template).

**Comment by Mithgarthsormr** [comment]
@WagnerGMD I did check the version but somehow between switching from NewPipe to the browser app I forgot the patch version number each time. Where I live it was already late evening and I have ADHD which doesn't really help with such stuff 😖

**Comment by vmp9** [comment]
Likely use fast forward during silence 
![IMG_20240801_092905](https://github.com/user-attachments/assets/be88ed18-8cff-4ae2-823c-c05d7ca82f89)

**Comment by Mithgarthsormr** [comment]
@vmp9 thank you, it seems I accidentally activated that funktionality and that really was the cause!

And for everyone else sorry for making you work for my mistake!
Will close the issue since it was my fault from the beginning.
