### ISSUE TITLE
NewPipe start playing music again after beeing paused if a SMS is received

### ISSUE THREAD

**Issue by Massedil** [TeamNewPipe/NewPipe#1139]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

1. Listen to a music on NewPipe with headphone
2. Screen off, remove the headphone so the music is paused automatically
3. Screen off, receive a SMS (with sound)

Actual :
The NewPipe music is playing again after the SMS sound stops.

Expected : 
The NewPipe music stay paused.

**Comment by theScrabi** [comment]
We had that bug once. Seems to still exist.

**Comment by Massedil** [comment]
I think I can reproduce it easily now, but it takes time for me to understand that it seems the bug occurs only with headphone. Not with the direct pause button.

**Comment by theScrabi** [comment]
Yes of course, when pulling the plug the player goes into a special state. We are aware of this issue however it should be fixed.

**Comment by theScrabi** [comment]
@karyogamy If you join the TeamNewPipe I could assign you to certain issues. I would have assigned you here if you where part of the team.

**Comment by karyogamy** [comment]
Seems like a [one-liner](https://github.com/TeamNewPipe/NewPipe/blob/3088778a9f46b93474a28dfa82b8dd25917a0113/app/src/main/java/org/schabi/newpipe/player/BasePlayer.java#L348). Change `simpleExoPlayer.setPlayWhenReady(false)` to `onVideoPlayPause()` should fix this.

@theScrabi
Alright =D 
Don't take this the wrong way, but please set an explicit expectation for the team members and notify them before removal in the future. I was under the impression that my removal was because the members are expected to be active and show presence constantly, so I didn't rejoin as I preferred working in bursts and not having that kind of pressure.

**Comment by theScrabi** [comment]
@karyogamy Oh I just saw I exigently removed you. I'm sorry.
