### ISSUE TITLE
Crash when opening video from start page

### ISSUE THREAD

**Issue by mueller-ma** [TeamNewPipe/NewPipe#1149]
I opened a video from the feed page. Only crashes on that video.

{
   "user_action": "requested stream",
   "request": "https:\/\/www.youtube.com\/watch?v=7LzsRXPlFTw",
   "content_language": "GB",
   "service": "YouTube",
   "package": "org.schabi.newpipe",
   "version": "0.11.6",
   "os": "Linux Android 7.1.2 - 25",
   "time": "2018-02-26 20:29",
   "ip_range": "",
   "exceptions": [
      "java.lang.NullPointerException: Attempt to invoke virtual method 'int java.util.ArrayList.size()' on a null object reference\n\tat org.schabi.newpipe.extractor.services.youtube.YoutubeStreamExtractor.getAvailableSubtitlesInfo(YoutubeStreamExtractor.java:743)\n\tat org.schabi.newpipe.extractor.services.youtube.YoutubeStreamExtractor.onFetchPage(YoutubeStreamExtractor.java:558)\n\tat org.schabi.newpipe.extractor.Extractor.fetchPage(Extractor.java:61)\n\tat org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:248)\n\tat org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:240)\n\tat org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3$ExtractorHelper(ExtractorHelper.java:109)\n\tat org.schabi.newpipe.util.ExtractorHelper$$Lambda$3.call(Unknown Source)\n\tat io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:45)\n\tat io.reactivex.Single.subscribe(Single.java:2801)\n\tat io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)\n\tat io.reactivex.Single.subscribe(Single.java:2801)\n\tat io.reactivex.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)\n\tat io.reactivex.Maybe.subscribe(Maybe.java:3749)\n\tat io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)\n\tat io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)\n\tat io.reactivex.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)\n\tat io.reactivex.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)\n\tat io.reactivex.Flowable.subscribe(Flowable.java:13068)\n\tat io.reactivex.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)\n\tat io.reactivex.Maybe.subscribe(Maybe.java:3749)\n\tat io.reactivex.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)\n\tat io.reactivex.Single.subscribe(Single.java:2801)\n\tat io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)\n\tat io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:452)\n\tat io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)\n\tat io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:237)\n\tat java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)\n\tat java.lang.Thread.run(Thread.java:761)\n"
   ],
   "user_comment": ""
}

**Comment by theScrabi** [comment]
Please don't just post the error here.

However which channel did you subscribe for getting this video?

**Comment by mueller-ma** [comment]
https://www.youtube.com/channel/UC6C1dyHHOMVIBAze8dWfqCw

**Comment by karyogamy** [comment]
Looks like 11.6 is using a bad version of Extractor where the subtitles extraction can cause NPE, as seen [here](https://github.com/TeamNewPipe/NewPipe/compare/v0.11.6...dev#diff-39e7d8c00954e920b98e7636f0ac30b2L58). This problem was fixed in the [next commit](https://github.com/TeamNewPipe/NewPipeExtractor/commit/ccc8cde80e8d791f50007fa730b56932ec8c9b6b) to the extractor but wasn't integrated into that release. It should be fixed in 12.0 though. My apologies.

@theScrabi Have we released 12.0 beta to fdroid yet? The webpage is still on 11.6.

**Comment by theScrabi** [comment]
12.0 is marked as a beta version which might be a reason why it does not show up.

However is 0.12 stable enogh to be relased as stable?

**Comment by justanidea** [comment]
There is maybe one thing to correct before to do it :  when i load a channel or my subz page, i have got "sorry some errors occured" but i see no errors... xD

**Comment by karyogamy** [comment]
Oh, I was referring to the beta page on fdroid. I think they've just updated to 12.0, after my last comment. 

With all the problems of 11.6, it might be a good idea to go straight to 12.0. We should also consider using the commit after #963 was fixed for releasing stable, since `getQuality` seems to fail almost everywhere.

**Comment by TobiGr** [comment]
> 12.0 is marked as a beta version which might be a reason why it does not show up.

The version is listed in F-Droid's metadata.

**Comment by TobiGr** [comment]
> With all the problems of 11.6, it might be a good idea to go straight to 12.0. We should also consider using the commit after #963 was fixed for releasing stable, since getQuantity seems to fail almost everywhere.

I agree. I'd suggest to use the last commit before #1147 was merged.

**Comment by Stypox** [comment]
The crash doesn't happen anymore, but before closing I will investigate

**Comment by Stypox** [comment]
I don't think this problem still exists, since the line that crashes the extractor has been modified to not crash anymore. Now the object on which "size()" is called is always non-null, see https://github.com/TeamNewPipe/NewPipeExtractor/blob/4488c217659d2e923f125fd923e1b28812cf217f/extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/extractors/YoutubeStreamExtractor.java#L800-806
