### ISSUE TITLE
Player Ignoring Rotation setting

### ISSUE THREAD

**Issue by DanGLES3** [TeamNewPipe/NewPipe#1156]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

if i start playing a video with rotation off and then turn it on the player won't rotate unless reopened

**Comment by mauriciocolli** [comment]
That's a bad UX present in the player, we should alter the icons and add an "Automatic rotation" to the cycle.

**Comment by ao2** [comment]
Please also check the behavior when the screen rotation is **Locked** in the Andoird settings.

In my case the player insisted in opening the video in portrait mode by default even if the tablet display setting was locked to landscape. I was able to fix the issue with the rotation icon inside NP, but I didn't expect I had to do it explicitly.

Thanks,
   Antonio

**Comment by theScrabi** [comment]
> we should alter the icons and add an "Automatic rotation" 

Is it necessary to override the systemwide autorotation though? I thought that only having an option to rotate on tapping the icon if autorotation is disabled is enough.

> In my case the player insisted in opening the video in portrait mode by default even if the tablet display setting was locked to landscape

That's because the last rotation when auto rotation was disabled might have been portrait.

So far we only remember the last rotation if the rotation button was used, however we do not change this value when auto rotation is enabled.

@mauriciocolli Maybe we should:
1. Listen to if the "autorotation enabled/disabled" get changed while the player is open, so we don't have to reopen the player in order to behave acordingly.
2. Remember the last rotation even when autorotation is enabled, so that the screenrotation does not suddenly change when someone switches to "autorotation disabled"

**Comment by ao2** [comment]
But is an explicit rotation button necessary at all in the player? Even when autorotation is disabled?

Can't the player derive the current orientation from the system when rotation is locked in Android settings? And avoid remembering the last orientation altogether?

I don't know the history nor the code of the projects, so forgive me if I am missing something obvious.

**Comment by moneytoo** [comment]
I confirm this issue. I didn't even know about the in app rotation button - I kept reopening the video after enabling auto rotation in system.

**Comment by ronidee** [comment]
Please do *not* remove the rotate button from the full screen player. 
It's almost the most convenient feature of NewPipe for me. 
I never use auto rotate on my phone and hence set the full screen player to always be in horizontal mode, so that it always uses the entire screen.
Not sure if you're planning to remove it or not, so please don't!

**Comment by moneytoo** [comment]
@ronidee That should still work as before. The fix only allows system "auto orientation" to be properly detected (when already in video and user enables/disables auto rotation in system via quick setting tile).

**Comment by theScrabi** [comment]
@ronidee you have my word. I'd never remove that button :)

**Comment by ronidee** [comment]
I know it doesn't really belong here, but I've btw modefied the popupl player, so that it snaps below the toolbar on longpress (and maximizes). Including a switch in settings xml.

Any chance you'd merge that, or is that some kind of niche feature only I find to be handy

**Comment by gkeegan** [comment]
@ronidee I think that is a useful feature. I think submitting a pull request with a video or it in action or something would be much appreciated, and since you already have it made it wouldn't be too much work I would think.
