### ISSUE TITLE
A very Minor GUI change request

### ISSUE THREAD

**Issue by chris47368** [TeamNewPipe/NewPipe#1170]
Dear newpipe developers,
I love your app it works fantastic compared to the other players.I have one simple request for this app that i think will make the user experience much better.Could you change the prompt you get when you share a video from another app into the newpipe app,so the prompt you get that allows you to choose what mode to play the video in as normal but has a 'ok' button and a tick box option not selected by default that says 'Always use this option',instead of the two buttons 'Always' and 'just once' buttons.I ask this because its very easy to slip up and press the 'always' button by accident and it gets annoying when you have to go into the settings to restore the selection prompt.The tick box will make an accident like this harder to do.
Thank you for reading my suggestion!!!

**Comment by karyogamy** [comment]
You can double-click on the selection and it works the same as selecting 'Just once'.

**Comment by GaryMericano** [comment]
I second this request and add that a 'better open with' style countdown would match the name preferred player a little better. If you could designate a preference, say popup, and if background or show info or video player wasn't clicked in 3 or 5 seconds it would default to popup.
At that point if a direct download button and/or open in other app buttons were added I could finally set NewPipe to default on Android. Current options are between 4-6 clicks from a YouTube link (8-10 if I want to download) and this would reduce any path down to 1-3 presses.

**Comment by anoraktrend** [comment]
This, I believe, is a ROM based thing. I get the check mark usually.

**Comment by GaryMericano** [comment]
I get a tick box on nearly everything but the preferred player selection, including the initial option to open with NewPipe vs gettube vs firefox etc

**Comment by SebiderSushi** [comment]
I'm also for a checkbox instead of "Just Once" and "Always".
With the checkbox users who never want to set a default can choose their preferred action every time they open a link with _just a single tap_. If anyone wants to set a default they can do that _once_ with two taps. So it's one tap every time and two taps for one time only.
With the current design it's two taps _always_.
In light of that the Just-once-and-always design doesn't make any sense, right?
It's bad enough that google implemented this into android. So I'm totally for reducing this behavior wherever you can!

**Comment by trymeouteh** [comment]
Please remove the just once and always buttons? When I go to share a video to the NewPipe app, I sometimes hit the always button and have to go into the NewPipe settings to fix revert this. Please remove the just once and always buttons.

**Comment by Stypox** [comment]
Closing in favouf of #4102
