### ISSUE TITLE
Question: Does the playlists update themselves when you save an internet platlist?

### ISSUE THREAD

**Issue by justanidea** [TeamNewPipe/NewPipe#1184]
Like : if I create a playlist directly from a channel feed, does it be updated? 
If not : could this functionnality be added?

**Comment by theScrabi** [comment]
I'd say no, since the playlist gets copied and store locally.

**Comment by justanidea** [comment]
Could it be updated ?

**Comment by theScrabi** [comment]
@karyogamy can it?

**Comment by karyogamy** [comment]
Not trivial, since we need to update the database schema and create a special playlist just for doing this. Also, it's probably difficult to explain this functionality to other users.

It's best to just wait for the new feed system and add a playlist control panel (background/play all/popup) to that instead.

**Comment by justanidea** [comment]
Okay
