### ISSUE TITLE
Play video in details page (as popup)

### ISSUE THREAD

**Issue by Rubylion** [TeamNewPipe/NewPipe#1200]
Hi. Would it be possible to make the video play in the resultpage.
Meaning, when you click a video in the list, the next page opens, where the video is on top and other sruff,incl. suggestions are displayed.
I would like to playback the video in that top window, instead of going to fullscreen imediatley. Therefore i can read the notes and browse the suggestions while watching the playback.
Very beautiful app by the way. Thanx

**Comment by theScrabi** [comment]
@avently is currently working on this https://github.com/TeamNewPipe/NewPipe/pull/834

**Comment by Rubylion** [comment]
great

**Comment by opusforlife2** [comment]
@theScrabi I think it would be far simpler if there is a toggle in app settings so a popup can automatically play in the video details page for those users who want it (should it be the default option?). This will require some small changes in the mechanics of the popup:

- The default position and size of the popup is changed so that it occupies the full screen width and is placed over where the thumbnail should normally be.
- Swiping down on this auto popup could shrink and place it at the bottom right just like in the official app. From there, it can be moved around or resized as needed. The closing method stays the same.

This can emulate the convenience of the official app, without causing the complications that came with the PR you linked to.

@Stypox  This is an alternative for the instant playback solution I proposed here. https://github.com/TeamNewPipe/NewPipe/issues/2583#issuecomment-529401640

**Comment by Stypox** [comment]
Fixed by #2907

**Comment by opusforlife2** [comment]
Done.
