### ISSUE TITLE
An issue with release 0.13.0

### ISSUE THREAD

**Issue by justanidea** [TeamNewPipe/NewPipe#1204]
Hi! Amazing release, thanks everyone :) 
However, i just wanted to show that we may need to adapt the text size relative to the translation for the live word: with the french version for instance, when i start a live i should see "DIRECT" at the bottom right corner, but the word is too long, so I only see "DIRE", so its quite consfusing... :')

**Comment by theScrabi** [comment]
Please send a screenshot related to this.

**Comment by justanidea** [comment]
Yup

**Comment by justanidea** [comment]
Here they are :
http://i66.tinypic.com/xaw2et.jpg

http://i66.tinypic.com/25zpcib.png

http://i65.tinypic.com/av6h06.png

**Comment by theScrabi** [comment]
confirmed

**Comment by karyogamy** [comment]
Yeah, I did this to prevent people from using words that are too long for the LIVE button as some translations were over 10 letters and that just looks bad, especially on the popup window. One solution I can think of right now is to simply make LIVE not translatable, so that part of the UI is uniform across languages, but if there's better solution please suggest it.

**Comment by theScrabi** [comment]
> LIVE not translatable

I'd be fine with that.

**Comment by justanidea** [comment]
You solved this problem :)
