### ISSUE TITLE
Audio loss after clicking notification

### ISSUE THREAD

**Issue by TobiGr** [TeamNewPipe/NewPipe#1223]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

We got a bunch of feedback on our blog. [Chris](https://newpipe.schabi.org/blog/pinned/NewPipe-needs-feedback/#isso-32) had following problem:

> I am currently using a Pixel 2 XL running Android 8.1. I was watching a video in full screen mode. I got a notification and swiped down from the top of the screen to see it and then dismissed it quickly. After this the audio for the video wouldn't come back on.

**Comment by karyogamy** [comment]
Can't seem to reproduce the bug under the same settings on emulator. Since receiving notifications during playback should be a common event and this bug would've been reported a long time ago, I think this might be an individual occurrence. This was tested on the latest build, so the problem might've been fixed already.
