### ISSUE TITLE
get rid of beta again

### ISSUE THREAD

**Issue by theScrabi** [TeamNewPipe/NewPipe#1225]
We where trying that thing with beta about three months now, and honestly, I don't think it worked out the way I thought it would.

The initial idea was that beta could lead to a more stable code in the release branch, so people using release don't encounter so many bugs. This is something you could expect to work on a normal project. For us however it created some problem. If we don't keep the extractor up to date it will eventually fail to crawl the YT website because YT changes its site on a regular basis. However our currently latest stable release is v0.11.6 and that like a stone age version by now, and it failes 50% of the time.

My idea however was to go back to only one type of version. And try to release as offten as possible. However that had downsides for us as well. If a major change was about to be developed updates tended to not get applied on a regular bases. We really have to make sure we do a proper QA there and do NOT merge features to fast into the dev branch in order to prevent waiting for a feature to be fixed on dev.
This however is mostly a statement to my self as well.
Also instead of marking multyservice as beta we simply mark the other services (only SoundCloud so far) as beta.

By the way ownCloud uses rebase in order to move commits between internal branches. What are your thoughts about that?

**Comment by Lionirdeadman** [comment]
I think so too. Cancelling the Lite version is probably a good idea too.

**Comment by karyogamy** [comment]
I think replacing the beta with lite is a good solution.

One of the reasons why we stayed for so long on 11.6 is because the rollout window is way too long on F-droid, so we wanted to make sure everything is working properly before doing a stable release. However, with beta, we need to have fast turnaround time, so bugfixes can be rolled out as quickly as possible. 

In comparison, new versions only take about 3-4 hours to roll out on play store, meaning we can have a much quicker response time from the users. This way, we can frequently push bugfixes and new features to the lite version, while on the stable version, slow down and release periodic snapshots of lite version if it is stable enough. Though if we are going to do this, we should be very careful, as any reference to youtube (or even the stable app) will likely get the us banned from the play store.

**Comment by karyogamy** [comment]
> uses rebase in order to move commits between internal branches

Which internal branch? Feature branches are good for rebasing, but for public branches like `master` and `dev`, the slightest chance of rebase + force push can create nightmares =\

**Comment by Kexim6** [comment]
What about adding a toggle in the settings to activate beta features? It can be off by default with a warning that the user may experience bugs when turned on. Any features considered unstable or incomplete could be gated behind this switch, eliminating the need for two separate apps.

**Comment by theScrabi** [comment]
> What about adding a toggle in the settings to activate beta features?

This would become a coding nightmare. ... I guess.

**Comment by speednroll** [comment]
As a regular user, I vote to go back to the simple design of the Newpipe versions. As it was at the beginning, maybe it's not the best method but it's not the worst (?

the only strange thing I would add is the more "light" version of Newpipe to respect the rules of google and add them to gplay.

**Comment by theScrabi** [comment]
> the only strange thing

You need to stop using google translator xD

> ... the only exception I would make is the more "light" ...

Sounds better :)
La próxima vez correctas mi español  :sweat_smile:

Anyway, I've strated to remove beta here https://github.com/TeamNewPipe/NewPipe/pull/1227

**Comment by speednroll** [comment]
jajaja, no puedo simplemente hablar en mi idioma?

**Comment by theScrabi** [comment]
No, pero pronto :D. Aprendo tú idioma. ;D

**Comment by FaizKhan5** [comment]
Close this.

**Comment by Stypox** [comment]
Beta version does not exist anymore, as far as I know, in #1227
