### ISSUE TITLE
[feature request] Oreo native pop up by home button

### ISSUE THREAD

**Issue by hansip87** [TeamNewPipe/NewPipe#1249]
Please implement pop up by home button to perfect this app :)

**Comment by techguyone** [comment]
I too wondered why we get a clunky interface for this instead of hitting the home button when playing a video to  get PiP

Instead you have to click a 'pop out' icon before the video starts playing, then once the PiP is running you have to minimise the newpipe main screen to get to desktop, just seems a bit clunky.

Vs enable PiP in settings, then play a video, hit Home and your main screen is already gone and your PiP is playing happily on the desktop (also clears up space on the UI as you won't need a 'popout' icon.

Can one of the devs explain why the no standard methods was chosen?

**Comment by karyogamy** [comment]
> why the non standard methods was chosen?

Because we don't really have PIP. The popup feature uses overlays which can used by almost all phones that can run the app. PIP is a relatively recent android feature that is only available to phones on Oreo, which also happen to be less than [6%](http://gs.statcounter.com/android-version-market-share/mobile-tablet/worldwide) of the market share. So there is not enough incentive to do an actual PIP implementation and might be a while to before someone takes a look into it.

However, if you are only looking to have a feature where hitting the home button does the same as hitting the popup button, then it is already done in #1354. If nothing goes wrong, then it should be out in the next release.

**Comment by techguyone** [comment]
Thanks for that information, I'll look forward to the next release.

**Comment by Stypox** [comment]
This has been implemented with the "On lost focus" option.
