### ISSUE TITLE
[feature request] able to download to SD card

### ISSUE THREAD

**Issue by placidcasual98** [TeamNewPipe/NewPipe#1250]
[feature request] downloading to an SD card,
 at the moment you can only do it to internal memory so I "request the feature" of being able to download to an SD card.
Before closing this request please link to the already open one if you think this is duplicate.
No redirect to  other fault threads
For example
#315 as this is a fault NOT an feature request

**Comment by theScrabi** [comment]
https://github.com/TeamNewPipe/NewPipe/issues/412

**Comment by speednroll** [comment]
> you guys are good at keeping up with your work

hahaha, this was the funniest thing. You threw the last poisonous drop that filled the glass. this shows that you can not read, you made about 3 or 4 requests and they answered that the problem should be solved in next versions, currently the developers are focused on other issues of the application. you should know how to put yourself in the place of others, if you are so upset that there is still this problem you should help develop it, support it economically, or report other bugs. but if you come to criticize because it seems free to you go back where you came from. I would like to know how it would take you to develop something as ambitious as this application. pathetic...
