### ISSUE TITLE
[feature request] download to SD card

### ISSUE THREAD

**Issue by placidcasual98** [TeamNewPipe/NewPipe#1252]
- [x]  I carefully read the contribution guidelines and agree to them.

- [x] I checked if the issue/feature exists in the latest version.

[feature request] downloading to an SD card,
at the moment you can only do it to internal memory so I "request the feature" of being able to download to an SD card.
No redirect to other fault threads
For example
#315 
#412 
Are bugs, NOT an feature request.

**Comment by switchtegrax1** [comment]
That's the thing IT IS A BUG you can download to sd card on older versions of android but newer ones broke that,so the feature IS there it just BROKEN on newer versions of android

**Comment by wb9688** [comment]
That's because newer Android versions use a special way to access external
storage. We didn't want to change that part of the downloader, since we're
going to replace the downloader with a whole new much better downloader. So
until I've implemented the new downloader (which will probably take a
while, since I don't have that much time), this is still going to be an
issue.

**Comment by theScrabi** [comment]
I'm not sure, I took a look into gigaget, maybe we can morph it a bit at make it work with storage framework. The part with which you can get access permission is already written.

**Comment by theScrabi** [comment]
closing if favour of https://github.com/TeamNewPipe/NewPipe/issues/962

**Comment by knoddix** [comment]
Quick question guys, I have noticed with a number of applications on Android including newpipe that I can set the SD Card as the default download/save location but when I go to actually download/save something it fails to write I've only noticed this since starting to use newer Android devices running Android 5 or later, so my question is, is this an issue specific to the applications code? And does it need to be corrected on a per app basis by the developer? I should mention there are some apps that will save/Download data to the SD Card no issue and all apps affected have permissions to access storage.
