### ISSUE TITLE
remove items from last played/most played in the bookmarks tab

### ISSUE THREAD

**Issue by MrSoke** [TeamNewPipe/NewPipe#1266]
I have the history deactivated, but I just noticed that the "last played" and "most played" categories in the new bookmarks tab is showing all my video history up until the point in which I deactivated my video history (if I for example installed newpipe 5 days ago and deactivated history 3 days ago, those categories in the bookmarks show the history from the first 2 days).
This means my history prior to the moment I deactivated it is still stored somewhere, and I don't see an option to remove it from the bookmarks, so it would be nice to have that option in the bookmarks or to delete my entire history altogether in the moment I turn the history off.

**Comment by theScrabi** [comment]
I see, this is an actual issue yes.

**Comment by Shan11812** [comment]
We can clear from History page... adding History to context menu should be fine?
Also an option to clear history in settings page also would be helpful.

**Comment by Stypox** [comment]
The "clear watch history" button exists in the settings, doesn't that solve your problem?

**Comment by B0pol** [comment]
It's not an issue anymore: when you disable history, it's not retroactive, and hopefully, because you can want to disable history for a session, so for that session history is not stored, reenable it later, and keep your old history. Just use the clear history button if you want to delete old videos from history.
