### ISSUE TITLE
[Feature Request] Couldn't we make the left panel available everywhere in newpipe?

### ISSUE THREAD

**Issue by speednroll** [TeamNewPipe/NewPipe#1277]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

I have to constantly go to the start of newpipe to see the history or downloads. everything would be easier if they improve the left panel so that it is always available.

**Comment by theScrabi** [comment]
Hm yes, but from a UX point of veiw how should this be done?

**Comment by daufinsyd** [comment]
May be just swipe ?

**Comment by theScrabi** [comment]
yea.

**Comment by mauriciocolli** [comment]
If we just enable the drawers in other parts of the app, it will just not make that much sense because the button that was supposed to open the drawer (hamburger icon) is not present. The user can't know in advance that there's a drawer without the hamburger icon.

I also don't know if the service-switching is reliable or even make sense at all in another parts of the app. That's a thing to improve.

So I would revert this change as it is not user friendly.

Related #1263

**Comment by speednroll** [comment]
and can't you put the two buttons? the back and the hamburger icon or would it be ugly?

if you consider adding the drawer in other parts, it should work like this: when selecting souncloud, it sends you to the beginning, with the latest soundcloud trends, but when you select YouTube (already being in that service and in a video) simply do nothing

**Comment by Stypox** [comment]
I don't think having both the drawer and the back button follows material design guidelines. Also, the back button brings you directly to the home screen, so the left drawer is just one click away. See #2358
