### ISSUE TITLE
Add setting to display hardware buttons while watching a video

### ISSUE THREAD

**Issue by TobiGr** [TeamNewPipe/NewPipe#1283]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

A request by Gabe (blog):

> However, I noticed that when watching videos in full-screen mode on my Galaxy S9 that the software buttons (home, menu, back) disappear. The only way to get the buttons back on the screen is to pull down my notification drawer. Could you possibly make it so that if you tap anywhere on the screen they will reappear as well?

**Comment by mauriciocolli** [comment]
This was changed in #1147.

I agree with showing the hardware buttons. Besides the mentioned issue, mainly because it causes bad UX when you want them to appear with the swipe gesture (and the player's gestures enable), I almost always end up messing with the brightness/volume (sometimes it causes an audio blast, very annoying).

This was the default when I first added the players and MX Player also uses the same strategy and logic to solve the issue.

@karyogamy do you think that having this option it's worth? The gesture issue can be somewhat fixed and I don't know of any extra side effects. Just one disadvantage: take it into account every where in the players implementation, which could increase the maintainability debt a little.

**Comment by karyogamy** [comment]
There were a couple reasons why I made the change:

- The video view would shrink when the system UI is shown
- The status and nav bars are opaque, so when we fixed the above problem, the system UI would hide a good portion of the video.
- With the nav bar showing at the same time as the rest of the player UI, it is very easy to misclick when trying to open the dropdown menu.

Now that I think about it, we can rollback to our solution before the change and just change the window color to translucent. 

The only problem is the last one, since the buttons are relatively small and I suspect that is the reason why the official youtube app is hiding the nav bar as well. 

[Two Hours Later...](https://www.youtube.com/watch?v=K9yuDdCyQhs)

How's this for a change?

<img src="https://user-images.githubusercontent.com/5570482/38461314-9042f82a-3a81-11e8-8bef-e2f050135d47.png" width="400"><img src="https://user-images.githubusercontent.com/5570482/38461315-905a498a-3a81-11e8-9fcf-3e9a52b7896b.png" width="225">

Available as the newest commit on #1226. The only problem with this solution is the transparent system UI only works on Lollipop and later. Older versions will have an opaque black bar still. Also, we still need to address the problem where the dropdown button is too close to the nav bar. @mauriciocolli How do you think we should address this?

**Comment by theScrabi** [comment]
> UI only works on Lollipop and later.

In my opinion that would not be a problem. It does not look good on 4.x devices yes, but it does not brake support for them.

**Comment by trymeouteh** [comment]
I like this option. If you want to make everyone happy you can make it an option that can be enabled/disabled in the settings.

**Comment by TobiGr** [comment]
> I like this option. If you want to make everyone happy you can make it an option that can be enabled/disabled in the settings.

Yes, @karyogamy please do so.

**Comment by karyogamy** [comment]
> If you want to make everyone happy you can make it an option that can be enabled/disabled in the settings.

Well, I'd prefer not adding toggles to UI elements and keep its code simple. I've been using this new layout for a while now and am starting to like it. The misclick doesn't really happen, so I take that issue back.

**Comment by amnesiac-kid** [comment]
I experience the same issue. The full screen UI is broken in the current release due to regression. When you click on the screen, the system UI stays hidden in full screen (but the app UI appears) and there is no leave fullscreen button, which is very annoying and cumbersome. Temporary fix: Install v0.11.6.

**Comment by theScrabi** [comment]
> layout for a while now and am starting to like it. 

I was a bit confused at the beginning to, but I like it as well.

> The full screen UI is broken in the current release due to regression.

I don't think its a regression, I think its intentional. However you can open the system UI when you swipe from the bottom (in portrait) or the left (in landscape) into the screen.

**Comment by amnesiac-kid** [comment]
> However you can open the system UI when you swipe [...].

I think the average user would tap on the screen to display the UI and then there would be two steps (a swipe and a click) instead of a single to close a video. Also when you swipe in portrait most of the time you accidentally skip forward and in landscape mode, you accidently lower the volume. If the swipe feature should be implemented the way it is now, then the app UI elements should be moved out of the way of the swipe zone in portrait mode and the volume gesture in landscape should then also be moved to a different place, to not confuse the user.

> The screen simple looks less overloaded. 

Isn't usability and ease of access more important than looks?

**Comment by theScrabi** [comment]
> Isn't usability and ease of access more important than looks?

I think UX contains both.

**Comment by TobiGr** [comment]
Fixed in #1226.
Thanks again
