### ISSUE TITLE
How to set subtitle background color

### ISSUE THREAD

**Issue by DanteAndroid** [TeamNewPipe/NewPipe#1286]
In `setupSubtitleView` I tryed `view.setBackgroundColor(Color.parseColor(captionBackgroundColor));` but it doesn't work. I just want to make caption background transparent coz it blocks the video content.

**Comment by karyogamy** [comment]
Setting the view background doesn't work because it would be overriden by the caption style.
To change the background to transparent, try using the following:

```
            final CaptionStyleCompat captionStyleCompat = new CaptionStyleCompat(
                    /*textColor=*/CaptionStyleCompat.DEFAULT.foregroundColor,
                    /*textBackgroundColor=*/Color.TRANSPARENT,
                    /*viewColor=*/Color.TRANSPARENT,
                    /*textEdgeStyle=*/CaptionStyleCompat.DEFAULT.edgeType,
                    /*textEdgeColor=*/CaptionStyleCompat.DEFAULT.edgeColor,
                    /*typeface=*/CaptionStyleCompat.DEFAULT.typeface);
            view.setApplyEmbeddedStyles(false);
            view.setStyle(captionStyleCompat);
```

Just FYI, setting the view background to transparent is the same as changing the `viewColor` to transparent while leaving the `textBackgroundColor` as default. Meaning, the view is actually transparent, but the text is still using a default(black) background overlay on top of the underlying view. 

No custom caption styling is actually an oversight when I was implementing the subtitles. Instead of having the caption as part of our settings, we should use `CaptioningManager` to obtain the system-wide caption style and scale settings. I'll open a separate PR on this later.

**Comment by DanteAndroid** [comment]
Thanks for your detailed instruction. And I'm looking forward to the next version. 👍

**Comment by TobiGr** [comment]
Should be fixed now.
