### ISSUE TITLE
fingerprinting

### ISSUE THREAD

**Issue by thomiel** [TeamNewPipe/NewPipe#129]
Great thing that you refer to the C3S website when GEMA prohibits playing a video!

NewPipe is essetially a player, so I wonder if it would be an easy thing to download the audio data and get a fingerprint from it. We are looking for a prototype for mobile devices to work with a service we develop; 'Adore'. See http://www.adore-music.com or developer info at https://redmine.c3s.cc/projects/adore/wiki . We use EchoPrint for the prints: https://github.com/echonest/echoprint-codegen

**Comment by theScrabi** [comment]
Generally as is said, I'm interested, but first I have to work my self into the technical details. Also since we already have a lot of other stuff to work on, this could be something that has to wait for a longer period of time.

Of course if you ore someone else is interested to implement this, the code is always welcome !!!

**Comment by FaizKhan5** [comment]
Close this

**Comment by thomiel** [comment]
can be closed as Adore is currently not under active developmen
