### ISSUE TITLE
Headphone play/pause control

### ISSUE THREAD

**Issue by justanidea** [TeamNewPipe/NewPipe#1311]
#1178 seems to be merged but I still cant control play/pause with my headphone..

**Comment by switchtegrax1** [comment]
The headphone pause control is for the background player,not the main player

**Comment by justanidea** [comment]
Nice to know. Thx.

**Comment by justanidea** [comment]
But It still doesnt work on my phone. Dont you?

**Comment by switchtegrax1** [comment]
It works ok here to me,what android version are you running? i heard it doesn't work on oreo

**Comment by justanidea** [comment]
Lollipop 5.1.1

**Comment by theScrabi** [comment]
I seem to have problems as well on LOS 14.1

**Comment by karyogamy** [comment]
In case anyone's wondering, 13.1 doesn't use `MediaButtonReceiver`, which can cause a noop as shown [here](https://developer.android.com/guide/topics/media-apps/mediabuttons.html). 

@theScrabi Can you check if this is fixed with 13.2? If not then we might need to implement `MediaBrowserService`.

**Comment by Somethingweirdhere** [comment]
> The headphone play/pause control is for the background player,not the main player

Do we want it in the main player too?

**Comment by justanidea** [comment]
For me, i would like to :)

**Comment by theScrabi** [comment]
@karyogamy It still does not work for me :/

**Comment by karyogamy** [comment]
Is the problem specifically play/pause? Or does it not work on other buttons such as previous/next? What kind of peripheral are you using? Bluetooth headphones or wired? Please provide as much context as possible since it seems to happen to some devices and not others (and might not have anything to do with the OS version, as @switchtegrax1 pointed out).

Btw, the current media session implementation should allow media button control on the video players, if you have lollipop and up.

@theScrabi If time permits, can you please debug the `onStartCommand` in `BackgroundPlayer` to see if you are actually receiving media button intents when they are clicked?

**Comment by adrium** [comment]
It does not work for the background player for me, either. I am connected with my bluetooth headphones.

Works flawlessly with segler-alex/RadioDroid

Version: 0.13.3, ResurrectionRemix Nougat 5.8.5

**Comment by BeeeQueue** [comment]
Can confirm that no media actions work with my bluetooth headphones on Android 7.0, NewPipe 0.13.4.

**Comment by karyogamy** [comment]
Just found out I didn't activate the media session after creating it, which was mandatory according to the docs. Strangely though, bluetooth works perfectly on my device even without having it activated. Here's the fix, please give it a shot: [app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/2045605/app-debug.zip)

**Comment by BeeeQueue** [comment]
Yep, works for me!

**Comment by justanidea** [comment]
Thank you very much <3

**Comment by justanidea** [comment]
Can i close?  Or the changes need to be merged ?
