### ISSUE TITLE
thumbnail does not update when removing item from local playlist

### ISSUE THREAD

**Issue by IamJithendra** [TeamNewPipe/NewPipe#1330]
@theScrabi   The Wish list on the Bookmark Section the Thumpnail Remains There Even after that Video is Removed From the Wishlist

**Comment by theScrabi** [comment]
Please add steps to reproduce this.

**Comment by IamJithendra** [comment]
On Removing The Video Remove The Thumpnail  and Update the Wish list Thumpnail Needs To Be Updated with The Video Left on The Wish List

**Comment by Stypox** [comment]
I don't think this is really an issue. This is the expected behaviour, since the user can choose the thumbnail himself, by long-pressing on playlists items. So when an item, whose thumbnail is used as the playlist thumbnail, is removed from the playlist, it is ok not to touch the playlist thumbnail. If the user wants he can choose another one.
