### ISSUE TITLE
Background player starts a empty stream

### ISSUE THREAD

**Issue by DanGLES3** [TeamNewPipe/NewPipe#1343]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
If i'm inside a video and press the headset button to play/pause and then exit the video newpipe will start playing an empty background stream
![screenshot_20180421-201455](https://user-images.githubusercontent.com/32078304/39089562-b0514584-45a0-11e8-80c1-52619e8fa433.png)

**Comment by karyogamy** [comment]
This might be another thing that works differently on lineageos. As you've mentioned, you are on 14.1, which is API 24-25 and according to [this](https://developer.android.com/guide/topics/media-apps/mediabuttons.html), when a video player is active, media button events should be sent to the `MediaSession` (that allows button control on video players) instead of the `MediaButtonReceiver` which is intercept all media button events on the background player only. 

This problem _might_ be solved later, as we eventually implement player state saving, to get rid of the unknown states, and media browser service, which _may_ be why lineageos is not notified about the media session.

**Comment by opusforlife2** [comment]
@DanGLES3 Still an issue in 0.20.0?
