### ISSUE TITLE
UI improvement ideas for Download Section

### ISSUE THREAD

**Issue by goxr3plus** [TeamNewPipe/NewPipe#1387]
It's been 4 months using this amazing application and until now waited to see if the Downloads section of the application will be improved. I will put below the problems and solutions :

**1)**   Many times i press to play a downloaded song and accidentally press delete which is down from me Play option on the pop up. Guess what happens next. Oups no question for the user just deleting it accidentally. It happened really way a lot of times.

Please add a notification for the user to accept if he wants or not to delete the downloaded file.

**2)**   Add album cover on the downloaded songs.

Very important, i have to read all the name sometimes of the song to understand which one i am searching, album cover image can make it more easier.

Please add album cover images for each downloaded song. Either by dowing it via (Discogs API) for example or downloading the. png or jpg somewhere on the phone.

**3)**  Add a search bar on the downloaded songs section.

**4)** When the download fails for some song or video it is left as error.

Add an option to retry download.

Thanks for reading all the above and be happy, waiting to be implemented :)

Love for this awesome application.

**Comment by goxr3plus** [comment]
Llll

**Comment by Stypox** [comment]
See #1014 for the album cover

**Comment by opusforlife2** [comment]
For point 3, from #4150:

"Feature

In order to provide a better offline mode, we should add a search in the download section to search all downlaoded files.
Additonally, one could make an additon to the "do you want to delete the download history?" dialog, to explain that clearing the history makes the items unsearchable through the integrated search.

Problem

People with temporary internet access tend to bulk download many videos at once for later usage. It is also comlicated to find the correct video, when downloading a series with multiple videos which have the same file name except for the last few letteres."

**Comment by SameenAhnaf** [comment]
@litetex This repo now focuses on one feature requests per issue. This issue includes respectively https://github.com/TeamNewPipe/NewPipe/issues/6162, https://github.com/TeamNewPipe/NewPipe/issues/4341, #4150 and https://github.com/TeamNewPipe/NewPipe/issues/3332. It’s better to close this one.

Note: #4150 needs to be reopen.
