### ISSUE TITLE
Unable add subscriptions

### ISSUE THREAD

**Issue by Muscarv2** [TeamNewPipe/NewPipe#1413]
When I tap the import from YouTube option, it downloads the "subscription_manager" file, but when I try to open it in NewPipe with the import previous export option it just says "could not import subscriptions". In the files app it says unknown file type, and if I change it to .opml it still won't work in NewPipe.

**Comment by theScrabi** [comment]
I think its not ompl. Youtube uses a json format.

**Comment by theScrabi** [comment]
@Muscarv2 we may need ur file. (You can modify it for privatisation)

@mauriciocolli could you take a look at it.

**Comment by rm-root** [comment]
I've got the same problem, I downloaded the same file "subscription_manager" from the link that provide the app (or from the button "export subscription" on [this page](https://www.youtube.com/subscription_manager?)). This is my OMPL file, modded for privatisation (I left only 3 channels) and zipped because github doesn't support ompl upload:
[sub.zip](https://github.com/TeamNewPipe/NewPipe/files/2407552/sub.zip)

**Comment by Stypox** [comment]
For me it works just fine with the file you provided. Version 0.16.1.

**Comment by Stypox** [comment]
Fixed in TeamNewPipe/NewPipeExtractor#160
