### ISSUE TITLE
Tor leaking

### ISSUE THREAD

**Issue by ghost** [TeamNewPipe/NewPipe#147]
I noticed traffic isn't routed through Tor correctly. (Yes, I enabled it in settings)
To prevent leaking I dissallow direct internet acces to applications that are supposed to use Tor ensuring the only way it can access the internet is through the Orbot app.
But I noticed that as soon as I block internet access to Newpipe it no longer loads meaning it isn't using Orbots proxy.

Someone with more expertise should probably have a look at this. If this is in fact the case we might need to temporarily remove the feature untill it is fixed. Now users might believe their traffic is secure but really it isn't.

**Comment by gerroon** [comment]
Also It should make sure that it is not leaking dns. 

@JasperWeiss 
Check out this tutorial
https://github.com/ukanth/afwall/wiki/HOWTO-OrWall-together-with-AFWall

The idea is that the app is limited to use the local network so the app by itself cant reach the internet except when it is routed through a proxy.

**Comment by gerroon** [comment]
I also looked at the conenctions. It seems like it loads the thumbnails from the proxy but tries to stream from non proxy ips which means that it is not safe to use if you need to rely on tor anonymity

**Comment by JasperWeiss** [comment]
I use Netguard which uses a VPN so it doesn't require root. I have disabled internet access for all applications that use Orbot and they still work (as long as I set them to use orbot, otherwise they can't connect to the internet) 
Newpipe however no longer works when I dissable it's internet access. Doesn't that mean it's not using the orbot proxy?

**Comment by JasperWeiss** [comment]
*note: I talk about Orbot and Tor but it's the same in this case.
Update:
Search querries sent and the list of videos received are not routed through Orbot.

Only video details are routed through Tor (the page you get when you tap a video in the list of search results where you can hit play etc)

This makes little to no sense to me :D
When Tor is enabled, ALL internet traffic should be routed through Orbots proxy (including video streams and downloads etc). So that even when you deny internet access to newpipe in a firewall app it would still work for 100% because everything is routed through Orbot, which is not the case right now. With Tor enabled it should make 0 direct internet connections.

**Comment by JasperWeiss** [comment]
If you want to see what I mean.

- Download orbot and activate it
- set newpipe to use Tor

when Orbot is transmitting any amount of data 2 arrows show up in the icon on your statusbar.

Now do a search in newpipe, notice how there's no network activity in orbot?

Now tap a video, notice how the Orbot has 2 arrows indicating it's being used.

**Comment by gerroon** [comment]
It is quite bizarre that this app bypasses Orbot's transparent proxy. It should not happen.

**Comment by JasperWeiss** [comment]
Transparent proxy is something different, it requires root and makes apps use the proxy without the app itself knowing.
By default Orbot just acts as a proxy on localhost and apps can then use that proxy if it supports proxies (which isn't neccessary with transparant proxy)
Newpipe should support orbots proxy but it only uses it when loading a video details page, not search querries, streams, etc

**Comment by gerroon** [comment]
I have rooted device with Orbot and I am using transparent proxy for Newpipe (not tor option in NP). It still tries to connect to outside of the transparent proxy. At least that is how it looked to me.

The reason I know if that normally "all" possible Google ips are blocked on the device. So when an app tries to use normal connection, it cant connect to Google stuff. However when an app goes through orbot proxy, it can connect since Orbot uses its own iptables. Anyway, in transparent proxy mode, Newpipe fails to load the videos but not the thumbnails. Therefor I conclude that it is not fully proxied properly (because it is trying to connect to blocked ips).

**Comment by theScrabi** [comment]
Yup I found the error, that its not using Tor for searching. Here this line https://github.com/theScrabi/NewPipe/blob/master/app/src/main/java/org/schabi/newpipe/Downloader.java#L84. It's my fault. I was working on that code, and for some reason, I removed NetCipher here. Later I forgot to put it in again. I'll fix it but you  have to wait until Thursday. I'm blocked right now.

**Comment by JasperWeiss** [comment]
@theScrabi Great, Could you make videos stream over Tor aswell? Basically so that Newpipe would work fully even if it's internet access is blocked (because it uses orbots proxy)

P.s what do mean with blocked?

**Comment by theScrabi** [comment]
Studing. I take it serious. No coding until the tests are over, otherwise it would distract me to much. However by the end of the week I have time again, and the I hope I can finaly get NP a bit further.

Videostreaming via tor needs exoplayer. We need to switch to that first, which we will do someday.

**Comment by JasperWeiss** [comment]
All right, good luck with your tests :)

**Comment by theScrabi** [comment]
NewPipe is sill leaking heavily. Even thumbnails are bypassed. Therefore Tor is almost useless right now :/

**Comment by JasperWeiss** [comment]
It is. Isn't possible to set an application-wide proxy setting? meaning individual parts of the app (like the video player) don't have to be manually configured to use a proxy nor does a library have to support it. That would be ideal. 
Is NewPipe using [NetChiper?](https://github.com/guardianproject/NetCipher) It allows NewPipe to support orbot it a more native fashion in that it starts orbot when it's not running, it shows a prompt if it's not installed etc. It should also allow transparant proxying all data through orbot so that individual parts don't have to be configured to use the proxy.
You might want to ask a dev from the guardianproject for some help

**Comment by theScrabi** [comment]
Yes we use NetChiper and as long as I know, the one who implemented tor for newpipe, eighthave is part of the Guardien project.

**Comment by gerroon** [comment]
Is it possible to just offer some kind of proxy setting that can enforces proxy in a more strict way? That way we can just enter the proxy manually.

**Comment by JasperWeiss** [comment]
I keep opening Android-studio thinking "lets have a look" and find myself puzzled with the complexity of it. I did manage to change the action bar color so that's a start :)
Could you try to add more comments in your code so it's more clear what's going on?

**Comment by theScrabi** [comment]
Yap I see commends wouldn't bee that bad xD. Also I have a documentation in mind that tells the general architecture of NP. Which would be necessary too, because I got some contributions witch broke that idea slightly. Which again is no wonder because the architecture is still just documented in my head :/

**Comment by JasperWeiss** [comment]
I'd love to help out with that, unfortunately I can't read your mind :)

**Comment by theScrabi** [comment]
My goal is to focus on functionality now. But once version 1.0 is there I want to care about documentation a bit more, since we will need it for version 2.0.

**Comment by theScrabi** [comment]
But of course thats no excuse for bad comenting xD. I'll do my best to improve that, and if you have questions, or got stuck somewhere feel free to ask me (via mail or slack) :)

**Comment by JasperWeiss** [comment]
All right, thanks!

**Comment by JasperWeiss** [comment]
Any progress on this? It seems searching and video details are now properly proxied. Only the video previews and the actual video's itself aren't proxied yet.

**Comment by theScrabi** [comment]
Yes the video and thumbnails. The thumbnail thing is something i should care about, but so far I didn't.

**Comment by JasperWeiss** [comment]
Have you been able to make any progress with Orbot support? 
Some other thoughts, what sort of information does NewPipe supply in the web requests? Screen resolution? Fonts, systems version, user agent? Anything that makes individual NewPipe users stand out besides their IP address? Anything that makes NewPipe web requests in general stand out?

**Comment by theScrabi** [comment]
There is a user agent that is always the same. You can find it [here](https://github.com/theScrabi/NewPipe/blob/master/app/src/main/java/org/schabi/newpipe/Downloader.java#L35).

**Comment by itspull** [comment]
> I use Netguard which uses a VPN so it doesn't require root. I have disabled internet access for all applications that use Orbot and they still work (as long as I set them to use orbot, otherwise they can't connect to the internet)

@ghost can you share your netguard configuration with usage of orbot? I'm having an impossibly hard time finding a correct way to set it up. Have you made use of the port redirection rules? It seems, at least for me, trying to make use of the socks5 proxy inside netguard standalone (127.0.0.1:9050) doesn't work.

I have noticed this is an out-of-date issue, but I'd appreciate any help with this, given that you or anyone else are willing to lend it.

**Comment by theScrabi** [comment]
The tor backend of newpipe got removed dueto that leaking problem. NP can acces tor only via vpn now.

**Comment by wb9688** [comment]
I'm closing this issue, because we don't support Tor anymore. Also, if we were to implement it today, we could just add some setting to set a SOCKS proxy and just put that in `DownloaderImpl` as now everything (except ExoPlayer stuff) goes through that thanks to me. Then we should obviously do something to make ExoPlayer use the SOCKS proxy as well.
