### ISSUE TITLE
Newpipe beta is gone and...

### ISSUE THREAD

**Issue by bilgedodo** [TeamNewPipe/NewPipe#1533]
...standart version stopped downloading audios and videos? What is going on? Youtube Red and githubs new owner microbe-soft did something to you my dear coders? I will kill them if i thats the stuation! First Bill Gates and next Mr. Google... Like I killed Job's before! muhahahahahahaha! Muhahahahahahahahahaha!

XXX
Trully yours hitman bilgedodo

**Comment by gkeegan** [comment]
Bro you're weird

**Comment by theScrabi** [comment]
@bilgedodo If download is not working that's probably a bug. Beta got removed because the concept didn't work.

I disagree with Google and Microsoft as well, but Id never wish any person of them something bad. Commending to kill someone on the Internet is a very bad idea, so please remove this issue.

**Comment by TacoTheDank** [comment]
kek
