### ISSUE TITLE
[Feature Request] Make 'Unhook' the default for altered playback speed (or remember it)

### ISSUE THREAD

**Issue by dardoor** [TeamNewPipe/NewPipe#1536]
I watch most videos on faster than default speed and I have to check 'Unhook' every time, if I don't want a pitch change as well.
Youtube and almost every other video player out there alters the speed without changing the pitch, so it seems like a reasonable thing to do.

I wouldn't even mind if the altered playback speed itself was remembered across videos.

**Comment by pmiossec** [comment]
I also watch videos at faster speed and would like to see usability improvements to be done.

I also check 'unhook' every time, so remembering it is a very good idea.

I'm also interested by a setting next to "nightcore" and "default" that remember the last speed used.

Because every time I have to set my custom speed (around x1.5) with the slider and it's not as easy than just clicking on a button with already the good settings. And this operation should be as quick as possible because the video is playing at the same time and you are not focused on it....

**Comment by dardoor** [comment]
Yeah, I wonder how many people even want altered pitch, ever.
Removing that section entirely from the playback speed menu would clean up the UI, which now looks a bit cluttered (now there's also a skip silences feature, which looks cool on paper, but properly produced videos don't have many silences, so I'm not sure it's that useful).
For people who do use that feature, you could have an option in the settings to bring it back to the menu...

I don't want to impose my preferences on everyone else, feel free to chime in. But as I said, pretty much every video player (web or not) leaves the pitch intact when changing speed. The only one I remember that didn't do that by default was MPC-HC...

**Comment by theScrabi** [comment]
@dardoor I'm with you here when it comes to cluttered UI. I like it simple but functional, and for the actual task apropriate UI. 
In my opinion I would remove the __Pitch__ section, __Percentage select__ and the __Unhook__ button.  The __Silence button__ it think could remain for now, I guess for some podcast it might be usefull.

**Comment by ag-eitilt** [comment]
I understand why linking the two is an option -- if you've ever tried listening to music (or paid attention to it in the background) the "may cause distortion" is very much true.  If you're watching for the speech, though, people quickly become unintelligible with even a little pitch shifting.  Luckily, not many viewers are going to be switching between music and spoken videos with particular frequency, so making that toggle "sticky" as suggested would be a perfectly workable fix.

**Comment by karyogamy** [comment]
I agree with regards to the UI cluttering, though I think this really is just an eventual outcome of giving more controls to the user. However, from a technical side, ExoPlayer's speed changer uses an implementation that works well when changing the tempo or the speed (tempo + pitch), but is horrible when changing only the pitch.

This means, for now, there is no real need to have two separate sliders. We can potentially merge the two into one and have a checkbox to toggle between tempo changing and speed changing (which links the tempo and pitch). Just FYI, VLC app also does something similar, but the unlink toggle is hidden beneath the options and is not so easy to use. This is especially true when its use case is designed to let the user determine if the audio playback is speech or music. So, I recommend renaming the unlink button instead of removing it, and making the tempo (rather than speed) change default or having the toggle persist as @ag-eitilt suggested.

The percentage select is there to replace preset percentages because there are two different sliders. If we get rid of the pitch slider, then we should go back to preset percentages. This should also open up that percentage button for other uses, since the pitch is then always synchronized with the tempo. @theScrabi Instead of using the button opening up the info, maybe we can embed the description view into the player UI itself and have that button change the view between the description and the play queue?

**Comment by theScrabi** [comment]
> @theScrabi Instead of using the button opening up the info, maybe we can embed the description view into the player UI itself and have that button change the view between the description and the play queue?

I would not do this, since we would just end up having the detail view twice.

What i suggest is to have a little player UI that will be shown on the bottom of the app.

**Comment by karyogamy** [comment]
Looks good to me. We can look into creating that bottom control after the bugfixing phase. This can probably be implemented as part of the base fragment.

Though, the issue with a dedicated detail view button is that it also creates the same workflow as using the detail option in the contextual menu. And if we were to get rid of the option in the menu, then there won't be any ways to get to the detail page without starting playback on a video. So we might want to think about the design again.

**Comment by theScrabi** [comment]
I want to add the refactoring of the context menu be part of the bugfix phase. That thing is already bothering me for a while

**Comment by Stallonious** [comment]
Yes please unhook and remember last played speed. 
I have to change it every time as I always watch videos fast.
I don't know why anyone would want the audio at a fast pitch. Like, really?

Also, Why can't NewPipe have the option to login to your yourtube account like [YouTube Vanced](https://youtubevanced.com/)?

**Comment by theScrabi** [comment]
> Also, Why can't NewPipe have the option to login to your yourtube account like YouTube Vanced?



NewPipe's goal is to as effectively as possible protect its user's privacy. This means, the app only sends information to external servers which is needed to view search results or watch videos.

Having said this, the developers of NewPipe hope it is understandable that they will not implement any form of authentication which might allow tracking a user.

**Comment by beccare** [comment]
+1 for remembering speed/pitch-coupling checkbox state permanently
+1 for keeping actual speed/speed setting for the next videos at least until closing the app.

**Comment by Tikotik** [comment]
+1 Remember last playback speed setting. [on/off] option.
More like this browser extension behaviour: [Video speed Controller](https://github.com/igrigorik/videospeed).

- switch for whether to remember last speed setting in options.
- `global.preferred_speed = user defined value` (useful to set ur base speed)
- `if event.touch simple_visual_button then toggle current.speed = (global.preferred_speed, 1x)` 
- `current.speed = individual speed changes from both slider and/or above button`
- remember both current.speed, global.preferred_speed after app closing. Export settings global.preferred_speed value.

**Comment by dardoor** [comment]
Speaking of cleaning up the UI, I just recently saw that the old speed selector was simpler and easier to use, so might as well just bring that back (maybe as an option). Here's a thread about it: [https://github.com/TeamNewPipe/NewPipe/issues/1381](https://github.com/TeamNewPipe/NewPipe/issues/1381)

The current one is really not that good. If I hold the phone horizontally I even have to scroll down to get to the checkbox to leave the pitch unaltered, which should really be the default behavior anyway.

**Comment by nikolayhg** [comment]
+1 for remembering speed/pitch-coupling checkbox state permanently

**Comment by tumukei** [comment]
+2020 for such often used feature. If any other settings would require changing each video, people would be bringing out pitchforks already.

**Comment by gkeegan** [comment]
Reset button isn't useless. It's used for reverting changes in the video you're watching. Say you want to watch one part at 2x and the rest at normal speed. Way easier to press reset than slide everything back to 100.
