### ISSUE TITLE
[Feature request] Add Option to return to video from the notification when video is minimized

### ISSUE THREAD

**Issue by DanGLES3** [TeamNewPipe/NewPipe#1539]
only if the minimize function is set to background player of course

**Comment by Stypox** [comment]
You can click on "Switch to main" from the background queue. I don't think it would be a good idea to allow this inside the notification since there is not that much space.
![Screenshot_20190827-143539](https://user-images.githubusercontent.com/36421898/63771749-08583380-c8d8-11e9-9c1d-5a49b234df40.png)
