### ISSUE TITLE
Roadmap with Timetable

### ISSUE THREAD

**Issue by Teyro** [TeamNewPipe/NewPipe#156]
Well, first i want to thank you for your work ;) Did you know that the german c't magazine promoted your app in the Headline Story??? Ist true called "Android ohne Google" (Android without Google).

So they said NewPipe is a complete replacement for YouTube App ;)

Now i want to know if there is a release schedule for timetable for the next releases until 1.X ? Because on the main Page are many features in working but not all of them are implementated ;) Can you give me / us a short overview of upcoming features? What is planed for 0.8 0.9 .....

Best wishes from Hamburg Germany

**Comment by theScrabi** [comment]
Yea I noticed that it's in the magazine. However, there is a roadmap, but now timetable. Until 1.x I want NewPipe to be a stable and nice locking app, that implements pretty much all the features written in the "Comming Features" section inside the (READMY)[https://github.com/theScrabi/NewPipe/blob/master/README.md]. Until 2.x I also want support for services other than youtube.
However I can't tell when this will happen, since I only have time in my semester vacations to really work on that app. Also since I tend to still overestimate my self a bit, I think it may take longer than i say. But I think if everything works nicely we could be close to version 1.x by the end of the year. Version 2.x we could reach in about 1.5 years.
