### ISSUE TITLE
Background music doesn't launch if one is already playing in the background with the app

### ISSUE THREAD

**Issue by Dostoi** [TeamNewPipe/NewPipe#158]
If you launch a first video in the background and then want to play another one in the background, you can't do it by simply taping the background button, you have to manually stop the first one then launch the second one.
It would be nice if clicking on the background button automatically stopped the first one to play the second one.

**Comment by theScrabi** [comment]
Ok got it. Please w8 for two weeks than I'm able to write code again.

**Comment by Dostoi** [comment]
No rush don't worry :)

**Comment by newluck77** [comment]
Hi I'd also like to see this feature. Just voting this up, so it doesn't vanish somewhere at the bottom. :)

**Comment by theScrabi** [comment]
It will not, I already have it in my mind. But you know coding takes a while, and there are still a lot of other things. So be patient :)

**Comment by newluck77** [comment]
Of course, I understand. Don't feel pressed! This is not a show stopper, it's about improved usability of the background music feature.
PS.: In addition I could recommend NewPipe to my friends even better! :wink:

**Comment by theScrabi** [comment]
Hei no problem, I didn't take it that way either xD. I just wanted to tell you the state of the issue :) And its OK if you remind me on something, so its more likely that I remember it while coding.

**Comment by SkyzohKey** [comment]
Andy progress guys ? :p

**Comment by theScrabi** [comment]
No. I took a look at it though, but It looked a bit more complicated, so I thought it was not worth the work :/

**Comment by SkyzohKey** [comment]
What/where is the issue ? I know some Android developers maybe i could ask them to take a look at the code/issue in order to fix. 

That's something you'll be obliged to fix anytime soon cuz that's really borring to open the notifications drawer, stop the current song then listen another one, then repeat.

I use NewPipe in day to day usage and love it, no more ShitTube app which displays more ads than actual content, thanks for the awesome work guy ! 

Fact is that these types of issues are something which is needed to have a better UX, and by so, more users. 

Greets ! :)

**Comment by theScrabi** [comment]
You can find the entry point to the code [here](https://github.com/TeamNewPipe/NewPipe/blob/master/app/src/main/java/org/schabi/newpipe/detail/VideoItemDetailFragment.java#L434).
