### ISSUE TITLE
[ feature request ] Sync playlists / settings / etc with remote Git repo

### ISSUE THREAD

**Issue by andrewbanchich** [TeamNewPipe/NewPipe#1580]
- [ x ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ x ] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

I love NewPipe but the major disadvantage for me is that everything is saved locally. I want to back up the settings and playlists somewhere.

I would love if I could create a GitLab/GitHub repo and have it sync the metadata with that, or maybe add a more generic method like sync with Dropbox.

**Comment by MrOats** [comment]
Luckily, one can go to Settings>Content>Export Database for the time being.

**Comment by andrewbanchich** [comment]
Yes, but that's still pretty annoying to have to do.

**Comment by theScrabi** [comment]
Thats true, but I would not use a git repo for that, since you don't need to version your database.
However the idea with diffs is pretty good. I just think that it would not work the way we do it right now with a sql database. You would need a file formate like JSON, that can stand diffs better.

**Comment by andrewbanchich** [comment]
Right, JSON or some text-based format would be needed for Git.

I like the idea of Git because it's more of an open standard whereas if you want to sync a database then you'll probably want to use Dropbox or Google Drive, which needs an special API and an account.

However, either way would be a welcome addition.

**Comment by theScrabi** [comment]
Yea its open true, well lets see.

**Comment by airon90** [comment]
@andrewbanchich Also Nextcloud can be used to backup files
@theScrabi This request could solve two great limitations: 
1. Files can be automatically backed up so that if something goes wrong (broken or stolen phone) you don't have to worry about backups because it has automatically been done.
2. Other free software apps or website, such as [Invidio.us](https://invidio.us) or [FreeTube](https://github.com/FreeTubeApp/FreeTube), can use this data, without creating two datasets and without doing twice the same operations

**Comment by Stypox** [comment]
Closing in favour of #1163
