### ISSUE TITLE
[Feature Request] UbuntuTouch version

### ISSUE THREAD

**Issue by idekovets** [TeamNewPipe/NewPipe#1591]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

Good Day!

You made great app! 

I can not imagine how much this is possible, but maybe you can port your application to Ubuntu Touch?

Best regards!

**Comment by theScrabi** [comment]
Can ubuntu touch run android apps already? This or that way we would not maintain this. Wed need someone else help us here.

**Comment by TobiGr** [comment]
Well, Ubuntu Touch is only maintained by Ubports anymore since Canonical stopped to work on it... So I guess we won't work on a Ubuntu touch version, because Android an later a desktop version have a larger user base. 
However it might be interesting to for you to try [this guide](https://docs.ubports.com/en/latest/userguide/dailyuse/anbox.html) which explains how to get Android APKs running on Ubuntu touch with Anbox.
We can't test it without a device running UTouch, but if you try this out, it might be interesting for us to know whether it worked.

**Comment by idekovets** [comment]
Many thanks for answers and best regards!
