### ISSUE TITLE
[Request] Load http://cueyoutube.com playlists

### ISSUE THREAD

**Issue by zumodetalent0** [TeamNewPipe/NewPipe#1606]
The website http://cueyoutube.com/ allow to create playlists without using google play services, but newpipe is unable to load these playlists, so is requested to allow newpipe to parse the urls to this service, so playlists can be created and shared from a computer.

The cueyoutube service works this way:
you access to a http://cueyoutube.com/# url, and after the # it puts the youtube id (v= in the youtube url) in order, separated by commas (,), and the list of comma separated youtube ids are the id of the videos.

- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

**Comment by theScrabi** [comment]
If you get them to use https we can talk about it :)

**Comment by JuniorJPDJ** [comment]
@theScrabi it's just about URL parsing, not about web page parsing

**Comment by AnubrataDS** [comment]
The problem is that cueurl generates a weird URL like  http://cueyoutube.com/wsly/WslyLanding/?r=WslyAppIndex&code=cRf , and when you try to load that, it then redirects to the comma-separated URL like http://cueyoutube.com/#XmtRhfzp0ro,QRJ4rAWM2z4, 

It will be confusing for the users if we ask them to go to the URL, then copy the reloaded URL and paste in our app

**Comment by skyGtm** [comment]
@opusforlife2 The requested service doesn't exist anymore

**Comment by opusforlife2** [comment]
Thanks, @skyGtm!
