### ISSUE TITLE
Settings for published date language

### ISSUE THREAD

**Issue by zawawimanja** [TeamNewPipe/NewPipe#1626]
- [ ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

I want to show the published date in English but it seems I cannot find the settings to change. It shown in my native language Malays.

**Comment by TobiGr** [comment]
That's not a feature, it's a bug 😆 
There are three PRs with two different approaches which should fix this: #1616 and https://github.com/TeamNewPipe/NewPipe/pull/1465 respectively https://github.com/TeamNewPipe/NewPipeExtractor/pull/91 

I am closing this in favour of https://github.com/TeamNewPipe/NewPipe/issues/1457, so that we do not track this bug twice.
