### ISSUE TITLE
Autoplay next video

### ISSUE THREAD

**Issue by go2null** [TeamNewPipe/NewPipe#165]
It would be great to auto-play the next video like YouTube's _Autoplay_ feature.

Bonus if this works in _Background_ mode.

**Comment by theScrabi** [comment]
Hm ok.

**Comment by SRad90** [comment]
Yes! Very good app!  I think too! It would be great to auto-play the next video in background mode. Thank you!

**Comment by theScrabi** [comment]
Ok at the moment I'm about to switch to another player, that will accept some other features. So if this is done, we can talk about implementing this too.

**Comment by SRad90** [comment]
Yes! Thank you for your job! Can you tell me when your new player will be
available. Have a good day!

Simon Radelet

Ok at the moment I'm about to switch to another player, that will accept
some other features. So if this is done, we can talk about implementing
this too.

—
Reply to this email directly or view it on GitHub
<https://github.com/theScrabi/NewPipe/issues/165#issuecomment-180906290>.

**Comment by theScrabi** [comment]
No I can't. Maybe something will come in between, or maybe I can't see code for the next two weeks :P. I don't have a strict time schedule.

**Comment by SRad90** [comment]
Ok. It's not a problem. Thanks! ;)

**Comment by letkan** [comment]
My vote for auto play feature. Excellent app, thanks for it.

**Comment by lacolos** [comment]
I too would love to see autoplay next. In the same regard a play all videos and maybe even like YouTube music app, play next something similar

**Comment by dkanada** [comment]
This would be a great feature, it would work best as a toggle close to the suggestions in #710 and #643 since they would all be handled without dialogs.

**Comment by jjgh** [comment]
Definitely a must have feature! I am still bound to the official YouTube app just because of this.

Well I know Firetube has this, but Firetube no way near to the lightness and reactivity of NewPipe and also it can't download video/audio and doesn't have floating video...

Basically I'm tied to the original YouTube app because of YT account integration (managing playlists), but then I listen to playlists with FireTube, and then if I end up discovering something new I will have to open official YouTube app again to save it into a playlist...

Harmony is an interesting solution but it's only desktop based.

So... NewPipe to the rescue soon hopefully! 

(And no, for the record Spotify doesn't cut it for me. I tried liking it so many times, year after year, with all possible enthusiasm, but it always ended up bad for many reasons!)

**Comment by arvit1** [comment]
I also am very keen to have autoplay on this app, if comes around newpipe will replace youtube

**Comment by karyogamy** [comment]
Done as part #1147, since this seems trivial enough now. The auto-queuing, when enabled, will append a related stream of the last item of a play queue once it starts playing.

**Comment by jjgh** [comment]
@karyogamy this is fuckin amazing, thank you guys.
The only things missing are now:
- ability to play live streams
-  managing YouTube playlists
- desktop version

THANK YOU guys for working on this great app!

**Comment by mcarlo95** [comment]
Amazing! Is it coming out with next relase!?
I just wanted to ask for the same feature :)
Great app!

**Comment by arishkhan1** [comment]
> My vote for auto play feature. Excellent app, thanks for it.

Hello can you tell me how do autoplay tiktok videos
