### ISSUE TITLE
"No views" shown on some videos

### ISSUE THREAD

**Issue by gkeegan** [TeamNewPipe/NewPipe#1714]
Some videos that actually have a decent amount of views show "No views" while in the "next" section. The correct views appear in search and on the video page. Not sure why this happens, since when I found the same video suggested from a different video as the original, the view count worked. 

Image showing no views
![](https://i.imgur.com/Co7R3Sb.jpg)
Actual views 
![](https://i.imgur.com/xTZl3zI.jpg) 

I am on version 14.1 from the GitHub release. 
To replicate, go to any video and randomly select any "next" video. Keep doing this for like 2 or 3 times and a "No views" video will appear.

**Comment by gkeegan** [comment]
Four in a row!

![](https://i.imgur.com/PxBMwZM.jpg)

**Comment by MaX-Lo** [comment]
Can confirm that behaviour.

**Comment by MaX-Lo** [comment]
> To replicate, go to any video and randomly select any "next" video. Keep doing this for like 2 or 3 times and a "No views" video will appear.

Seems to be a general problem with displaying "next videos" view count. Got this error after clicking on a random video from the "Trends" section too.

**Comment by MaX-Lo** [comment]
After looking at the youtube website its clear why NewPipe can't display the view count...
On some videos youtube places "Recommended for you" instead of e.g. "188K views" so the newpipe extractor semms not to know what to do with that weird text.

Since thats not an issue in NewPipe but in the Extractor I would open (or link) that issue there if you don't mind.

Image 1: next videos in Newpipe
![grafik](https://user-images.githubusercontent.com/16520883/45927875-c5107a80-bf3a-11e8-9754-5d96670b507c.png)

Image 2: next videos for the same video on Youtube (desktop version, not logged in)
![grafik](https://user-images.githubusercontent.com/16520883/45927882-e8d3c080-bf3a-11e8-9b49-f4161547254d.png)

**Comment by copoer** [comment]
This might be able to be address if another string is added. An option to output 'Recommended' on the instance where the view count isn't a number.
@nicholasfagan

**Comment by Stypox** [comment]
Closing in favour of TeamNewPipe/NewPipeExtractor#117
