### ISSUE TITLE
[Feature Request] Categories or groups for subscriptions

### ISSUE THREAD

**Issue by juanfra684** [TeamNewPipe/NewPipe#1725]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

I've a lot of subscriptions. I would like something to organize the channels by groups or categories or labels or whatever is easier to develop for you. I could create groups like "AAA-electronics", "AAA-hardware", etc, to keep the important groups at the top of the list of subscriptions and everything else at the bottom.

Many thanks for the app, it makes youtube a quite better experience than the official app.

**Comment by trymeouteh** [comment]
+1

Would be cool and handy. I have so many channels I follow of so many variety and to be able to sort them out would be nice instead of scrolling through the whole list.

**Comment by juanfra684** [comment]
Bump.

**Comment by cpfree29** [comment]
This future would be a killer feature for NewPipe! Organizing our subscriptions? Would be awesome, more productive way of watching videos.

+1 very useful feature for the developers to implement.

**Comment by justanidea** [comment]
Yeah and would permit to refresh faster our feeds, and exactly what we would like too
+1

**Comment by Stypox** [comment]
Closing in favour of #1437

**Comment by ThomasLeigh** [comment]
First of all, thank You for such a fantastic app, thanks to You I’ve been able to help my Dad who is not so much accustomed to technology, to experience YouTube in a much better and much more convenient way. The only thing he’d ask for is regarding feed list and possibility to organize it into categories.

**Could it be possible to create feed groups to improve the feed list readability?** Now I can create only an RSS group which opens videos from its feeds. What I mean is it would be fantastic and give much better organization to see a list of feeds organized into categories - all displayed at once on a single page but with visually distinguished categories set by user.

Instead of a feed list like this:

• feed 1 name
• feed 2 name
• feed 3 name
• feed 4 name
• feed 5 name

I mean something like this:

category 1:
• feed 1 name
• feed 2 name

category 2:
• feed 3 name
• feed 4 name
• feed 5 name

and so on.

Could it be possible to introduce such a feature?
