### ISSUE TITLE
streaming doesn't work

### ISSUE THREAD

**Issue by mcirsta** [TeamNewPipe/NewPipe#1732]
I tried using NewPipe to play this youtube radio channel:  https://www.youtube.com/watch?v=tPE4wv7ob8Q
 Tried on two different devices, one Android TV Box with Androdi 7.1 and one phone with Android 6.0. NewPipe just says that the content is not available. I tried playing with the the country and content settings but still the same result.
 I can help with the debugging as I'm a programmer so let me know if you need any additional info.

**Comment by theScrabi** [comment]
Whats a youtube radio channel?

**Comment by mcirsta** [comment]
OK, sorry for the terminology. It's a livestream probably but for some reason it doesn't work in NewPipe.

**Comment by PeterBuhler** [comment]
I checked that youtube livestream on the youtube website, it no longer runs and from a skim through the comments section it appears to have ended about 7 or 8 months ago, there are comments from around 8 months ago, but then some unhappy unclear comments 7 months ago, then no comments at all until 3 months ago with people complaining that the livestream is off. I suspect the livestream was stopped pretty close to the time this bug was reported and so it's possible there is no bug at all. Either way, the live stream specified in this bug is done and has been for at least 3 months if not more so it's unlikely it will ever return and fixes cannot be tested if the content does not exist anymore. This bug report should probably just be closed.

**Comment by mcirsta** [comment]
I've found a new link for the same or similar Youtube stream:

https://www.youtube.com/watch?v=Wl2mrlhE5Ww

 I will check with the latest version of NewPipe.

**Comment by Cediddi** [comment]
Today I gave a try to NewPipe and got the same problem with any live stream I tried. Here's one which is live since 22 aug 2018.

https://www.youtube.com/watch?v=hHW1oY26kxQ

**Comment by Stypox** [comment]
For me it works. Are you using the latest version? v0.17.3

**Comment by Cediddi** [comment]
No, I was using 0.17.2 from fdroid, seems like I should've updated the repos first. Seems like this fixed the bug. NewPipeExtractor#195

**Comment by Stypox** [comment]
OK, thanks 😃
