### ISSUE TITLE
Reduce from 2 'tap' to 1 'tap' to play video

### ISSUE THREAD

**Issue by ort163** [TeamNewPipe/NewPipe#1859]
- [X] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [X] I checked if the issue/feature exists in the latest version.

Lets say you open the app. It loads the Trending. Now you click on one video (either thumbnail) or title. Then it opens another screen with the video in large preview + Add To, Background + more stuff... next video on the bottom... etc.

Can you add an option so from the first screen I can directly play video? This will reduce the number of clicks by one. Thanks

**Comment by Gymcap** [comment]
Maybe instead of a long tap menu for the videos, it could be a "drag and drop interface". The user could long tap on the video, a menu would show up on the video (possibly over the text). You could have all your regular icons, then release over the thumbnail to play. This might be a little complicated though.

Alternativly, an option to make tapping thumbnails play the video/audio directly.

**Comment by Stypox** [comment]
See #2383
