### ISSUE TITLE
Loading any video takes a long time. 

### ISSUE THREAD

**Issue by PopeRigby** [TeamNewPipe/NewPipe#1911]
Loading any video takes a long time.

**Comment by heberjeur** [comment]
I have the same problem ,I use the lowest resolution 144p

**Comment by Riotous** [comment]
@PopeRigby @theScrabi We need to update to the latest Exoplayer 2.9.2

**Comment by francoism90** [comment]
This seem to be fixed with latest commits, could you please try to compile the app with Android Studio?
Video's are start playing here instantly.

**Comment by yausername** [comment]
On Dec 16, 2018 6:22 PM, "François M." <notifications@github.com> wrote:

This seem to be fixed with latest commits, could you please try to compile
the app with Android Studio?
Video's are start playing here instantly.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/TeamNewPipe/NewPipe/issues/1911#issuecomment-447640966>,
or mute the thread

**Comment by dmlemos** [comment]
I am having this problem with version `0.7.4`

**Comment by bioblatt** [comment]
The same for me, using version 0.18.0 on Android 10. The video freezes right after ~8 seconds. I just reverse 10 seconds by double tapping to fix this. 

The other problem that occurs is, videos aren't mostly starting to play right away, using fullscreen mode. I usually have to wait 20-30 seconds. The fix for this is using the pop up mode. Or switching between both, if it still doesn't want to start.

If I change to the exernal player, this issue goes completely away. Every video plays after 1-2 seconds, but unfortunately, the sound is missing in 1080p.

**Comment by dmlemos** [comment]
@bioblatt I also have the second issue with the long load in full screen.

**Comment by gkeegan** [comment]
For some reason it seems like switching resolutions to 720p, letting it load, then switching back to 1080p seems to fix the issue on a case-by-case basis.
