### ISSUE TITLE
Can You Please Update The App

### ISSUE THREAD

**Issue by GKid94** [TeamNewPipe/NewPipe#1972]
The app needs to be updated often

**Comment by gkeegan** [comment]
You post this every now and then, and every time nothing happens. The things that are going to be added in the next update aren't all finished yet. 

If you want to try the newest possible version of the app (it may be unstable), I suggest you clone the repository and build an apk in Android studio or something.

**Comment by GKid94** [comment]
Because the app is really buggy and the developers are rarely releasing updates, and the app sometimes crashes when I open it and when I play a video in 720p in popup mode the phone lags and it get's really slow

**Comment by trymeouteh** [comment]
The devs don't get paid to make this app. They make it since they want this app to exist and want to share it with the world. Since it is a free project patience is required. I have been waiting too for the next update and features such as comments but again patience.

I am thankful for all they have done and even more thankful it is open source and free for all.

Also it is the holidays and no one wants to work during the holidays so I wouldn't expect much to be done until next year.

**Comment by gkeegan** [comment]
What phone do you have @Gkid94 ?

**Comment by AnotherLife** [comment]
720p is a high resolution to use for the popup player! Lower it...

**Comment by GKid94** [comment]
@gkeegan Tesla 3.1 Lite

**Comment by GKid94** [comment]
@AnotherLife They need to add an option to set a default resolution for a popup player

**Comment by gkeegan** [comment]
Setting default resolution for popup is already a setting.....

**Comment by GKid94** [comment]
@gkeegan I have set it to 360p and it still plays in 720p

**Comment by gkeegan** [comment]
So report it as a bug in a separate issue with a descriptive title.

**Comment by GKid94** [comment]
I think that I already reported some bugs

**Comment by GKid94** [comment]
I think that this app needs more attention, we need to share the app so that more people would start using it and developers won't quit developing it

**Comment by gkeegan** [comment]
Reporting a few bugs, then not reporting other bugs, then complaining that those other bugs aren't fixed is idiotic. 
Also, this project has many people working on it. 
Where do you suggest we share the app if you want more people to use it?

**Comment by GKid94** [comment]
Facebook, Instagram, Reddit

**Comment by gkeegan** [comment]
Are you suggesting ads on those platforms? An account to post about the app? You're very vague. Also, who would run these accounts? 

I don't think those things are going to happen.

**Comment by GKid94** [comment]
Maybe make a page on Facebook and post the updates on the app

**Comment by justanidea** [comment]
Guys, just see #1912
TheScrabi is busy for now, and as trymeouteh said, none is paid for doing this app
So please try to be patient like everyone and wait the end of his exams :)

**Comment by gkeegan** [comment]
@justanidea I very much agree with you. I was trying to get him to realize he is a tad unrealistic at times.

**Comment by lionirdeadman** [comment]
Please don't spam this issue with 20comments in a row. Some people might have quite a few emails because of this which can be annoying.

Furthermore, more people using the app will not result in the current developers developing the app more, they're simply busy and doing this as a work of love. 

Also, I don't think it'd be appropriate to create social media accounts without the approval of said developers and without it being controlled by them (since whoever owns it could use it maliciously).

Lastly, please be patient and feel free to share the application as yourself with your friends if you wish to do so and if you know any developers personally, see if they can help *if they want to*.
