### ISSUE TITLE
Infinite loading in lists when streams aren't filling the screen

### ISSUE THREAD

**Issue by ghost** [TeamNewPipe/NewPipe#1974]
- [ x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ x] I checked if the issue/feature exists in the latest version.

Hello.

I am now getting tired of using the **List** view. I wanted to go back to **Grid** view for my tablet as it feels better. 
Whenever I search for something (e.g. *Music*), the first few videos load. Scrolling down won't work as its got 'one page' or screen you could say, of videos. Stuck there and cannot load more, I'm missing one video to have the whole page/screen filled with videos. Just need another one after that to be able to scroll down and load more if that's how it works. Using **SM-T813**. **LineageOS 15.1** latest.
Tested on my phone. There are no problems there.

**Reproduce:**
× Own a tablet.
× Use the Grid view.
× Search for anything. I searched for *Music*.
× Try to load more than 'one page'.

Works? Not for me!

**Comment by B0pol** [comment]
![IMG_20200509_130106_1](https://user-images.githubusercontent.com/58657617/81472021-e217c100-91e4-11ea-9137-8463c9d1643a.jpg)
![IMG_20200509_130123_1](https://user-images.githubusercontent.com/58657617/81472035-e93ecf00-91e4-11ea-8ad1-22f7141f7795.jpg)
![IMG_20200509_130156_1](https://user-images.githubusercontent.com/58657617/81472042-efcd4680-91e4-11ea-874f-ad7384dd876b.jpg)

**Comment by B0pol** [comment]
It also happens on my phone with SoundCloud playlists

**Comment by opusforlife2** [comment]
@B0pol I can only reproduce it on SoundCloud and nowhere else. Do you know how to reproduce it on other services?

**Comment by Stypox** [comment]
@opusforlife2 this can be reproduced on every list that loads items in chunks smaller than the size of the screen. So probably SoundCloud is the only one that loads playlist videos 5 by 5

**Comment by AbduAmeen** [comment]
Has any progress happened on this issue? If not, I wouldn't mind making this my first contribution to the project. I would just like some guidance to where the code would be.

**Comment by Stypox** [comment]
@AbduAmeen 

For local lists (e.g. history):
- The `local` subpackage contains the code to show lists, in particular `LocalItemListAdapter`
- The base list fragment, extended by all local list fragments, is at `local.BaseLocalListFragment`

For "remote" lists (e.g. trending):
- The `info_list` subpackage contains the code to show lists, in particular `InfoListAdapter`
- The base list fragment, extended by all remote list fragments, is at `fragments.list.BaseListFragment`

And then there is `local.feed.FeedFragment` which implements yet another different type of list (which probably already works as expected, since it is handled by the `Groupie` library).

Yes, lists in NewPipe are quite a mess...
