### ISSUE TITLE
[Feature Request] Share URL with option to add starting time

### ISSUE THREAD

**Issue by Pablohn26** [TeamNewPipe/NewPipe#2000]
- [X] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [X] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

Youtube website provides an option to share a video starting at some point in the video.

![seleccion_743](https://user-images.githubusercontent.com/1228418/51044110-a2c16c00-15c0-11e9-937e-1bc06c50fe53.png)

Youtube Android app does not provide that feature either.

Would be possible to add that feature to NewPipe?

**Comment by Gymcap** [comment]
Can we also get the ability to open such links at their specified time? These features together would be awesome.

**Comment by Somethingweirdhere** [comment]
Also, clicking on timestamps in the discription!

**Comment by dadosch** [comment]
I think it would be useful to provide a share option which as available from a playing video then.

**Comment by Stypox** [comment]
I'm implementing this. I added a share button inside the main player, in the "more options" section. When clicking on it, the sharing dialog is opened with the URL of the video starting at the current time. That URL that **always** contains `&t=SECONDS` at the end (where `SECONDS` is the current playback seek, obviously). There is no way to manually change (or unset) the video starting time.
Even though this is a limitation, I don't think it is a good idea to show a dialog that lets users choose, because most of the times the video starting time they need is the current one. On the other hand I think it would be a great idea to add an option to the settings that makes it so that video starting time is **never** added.   
![NewPipe share](https://user-images.githubusercontent.com/36421898/55561725-f5f41800-56f2-11e9-87e8-017f28a4ab7c.jpg)

@Gymcap I think that has already been implemented (tested on 0.16.1)

**Comment by TobiGr** [comment]
That's good to hear :+1:
I think we should not add too much settings and there are enough possibilities to share a video without a timestamp (e.g. from the video detail page or the playlist menu). In other words, I'd vote to not introduce an extra setting.
CC @theScrabi What's your opinion?

**Comment by Stypox** [comment]
inside fragment.BaseStateFragment there are these two protected functions: `shareUrl` and `shareUrlInBrowser`. But I don't think they have anything to do with a StateFragment (all the other functions in that class are related to loading the fragment content with error handling). Shall I move them to a separate class in the utils folder (e.g. `utils.ShareUtils`), so that I can use them from anywhere in the app? Since player.MainVideoPlayer doesn't have BaseStateFragment as a base class (and neither do any of its members, afaik), I had to duplicate the code for sharing, and moving the functions to utils would solve the problem.

**Comment by Stypox** [comment]
The method would become something like this:
```java
public static void shareUrl(Context context, String subject, String url) { /* code */ }
```

**Comment by Stypox** [comment]
@TobiGr @theScrabi

**Comment by Stypox** [comment]
I think this can now be closed since the changes have been merged
