### ISSUE TITLE
Crashes when i go to a video page

### ISSUE THREAD

**Issue by mouarfff** [TeamNewPipe/NewPipe#2013]
Hello

Since the last version updated from f-droid, newpipe crashes always, when i go to a video page.
I'm in a HomTom HT70 with android7

**Comment by B0rlaug** [comment]
Please close this issue, this issue has to do with the extractor and it's currently being worked on here [https://github.com/TeamNewPipe/NewPipeExtractor/issues/133](url)

**Comment by gkeegan** [comment]
See this issue in the extractor: [#133](https://github.com/TeamNewPipe/NewPipeExtractor/issues/133). This has also been mentioned many other times. Please check to see if what you put up an issue about has been mentioned before.

Since theScrabi has said in that feed I linked that he will push a new version later, and that this is a duplicate, could you close this please?

**Comment by ReDDAtlas** [comment]
lul My dudd idk what this #133 means but i expect update tomorrow?? Just askin Man
