### ISSUE TITLE
Different packet names of f-droid and github versions, please!

### ISSUE THREAD

**Issue by DI555** [TeamNewPipe/NewPipe#2046]
I'd like to ask about different packet names of f-droid and github versions, please!
I came up for this when tryed to update f-droid v. by the github's new one and got error). Yes, it's signes))).
But really great to have possible having two versions together,- f-droid's "stable", and github's "testing" one! And another benefit - possible to track/search/play 2 different video/music together!
Many thanks in advance!

**Comment by gkeegan** [comment]
1 (Updating): If you wish to update to the 0.15.0 version via F-droid, you are going to have to wait. In order to get that version now, backup the Newpipe data, then uninstall Newpipe. Then download the 0.15.0 github release from [this link](https://github.com/TeamNewPipe/NewPipe/releases/download/v0.15.0/NewPipe-v0.15.0.apk) (direct download). Install it, then restore the settings. 

2 (Multiple Installs): You can't have both the F-Droid and GitHub versions on one device, as they both have the same package name.

3 (Playing two video/audio streams at the same time): Please post this in a separate issue here. This helps the devs maintain organization and tracking features they implement. 

If this has solved your issue, feel free to close this issue. If you get stuck somewhere, let me know.

**Comment by theScrabi** [comment]
They are signed with different keys, that is the issue.

**Comment by TobiGr** [comment]
As @theScrabi said, this should be fixed with setting up reproducible builds. I'll therefore close this in favour of #1981.

**Comment by DI555** [comment]
No, it was just FR for second copy of NP in github site... . So, I ment - why if github's and f-droid build had differs signes, why not to have differs appnames ??? Just to use 2 copyes of app officially!

**Comment by theScrabi** [comment]
We want to go the other way and make them have the same signature :D

**Comment by DI555** [comment]
@theScrabi , ok then, any plans for betas with different packet names ;)?

Really, the NP is so great, that another copy is really needed!
And, why the idea of diff.packet names of github and f-droid isn't good ? , -whould it be possible using together 2 NP , sinc. its together, also test new betas from github's place, 
but f-droid's ones would be 'stable' ones, and f-droid's would be updated by the 'stable' code from github... Why not ?

**Comment by theScrabi** [comment]
We had beta, but it didn't work as people would not use stable anymore.

**Comment by TobiGr** [comment]
Once our own F-Droid repo is set up completely, we might want to discuss daily snapshots or a beta again. But I guess, we should do this when we have nothing important to do :)

**Comment by DI555** [comment]
@theScrabi , but, i saw one example...where GH version is bit more reacher,- supports more sites(i hope NP will support much more 2 sites ;) ), has and experimental features, and so on.
 .... and FD version is more conservative. And these 2 versions have diff. app. names.
