### ISSUE TITLE
Add a warning about instability

### ISSUE THREAD

**Issue by def0x099** [TeamNewPipe/NewPipe#2069]
- [X] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [X] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

This app is constantly crashing and breaking. I think a warning should be added to the README.

**Comment by theScrabi** [comment]
Lol no. It is under development, that is why we have a zero in front of our version number.

Please remember that you are using NewPipe for free, and you are not forced to use it. 
So instead of spamming around and telling people how bad things are you could help make it better, because we know it is broken in many places, but we do our best in order to make it better.

You can donate, or you could help with code contributions.

**Comment by def14nt** [comment]
@theScrabi The average user doesn't understand the semver system, or any other markers associated with a development version, except the word `beta`/`alpha`, *or* a warning in the README, which is the first thing they see. When a user finds out the app is buggy, you'll lose stars, and you'll have some bad reviews coming straight at you. 

You don't have to take my advice, but please remember Github is a social platform, and any contribution such as an issue, pull request is almost always constructive (except some trolls).

**Comment by theScrabi** [comment]
I here what you are saying, and I feel you with that anger. But the fame of NewPipe is something good as something bad at the same time. It is simply not stable yet, but it will not become stable by magic, even though many people are using it already. Just like you I want it to get better with bugs, but this is not so simple, and trust me we are doing our best. At the end almost all of us are students and do this in our spare time.

Constructive is good you are right, but just saying `This is so broken` sounds more demotivating than constructive, so I rather count it as trolling. :/ Correct me if I'm wrong.

**Comment by def14nt** [comment]
@theScrabi I've corrected the title, and I apologise for approaching this in a condescending tone, but I do think users should be warned about the instability, because they'll just blame the developers otherwise. Nothing in the README screams **THIS IS A BETA**, aside from the branch name which is `dev`, and users will probably miss that.

If you want, I'll submit a Pull Request with these changes, and I'll put it in caps like the play store warning.

**Comment by theScrabi** [comment]
Yes, now I get it. This is actually a good idea :)

**Comment by theScrabi** [comment]
@def14nt If you want to can also help and check the next upcoming v0.15.1 release for stability: https://github.com/TeamNewPipe/NewPipe/issues/2068

**Comment by def14nt** [comment]
@theScrabi #2094
