### ISSUE TITLE
Have some sort of content on the homescreen

### ISSUE THREAD

**Issue by energ1zer** [TeamNewPipe/NewPipe#208]
It'd be nice if, when you open the app, it just shows you whatever videos are trending or something, as the blank screen makes me think the app is still loading/launching, and just not as nice-looking as it could be.

**Comment by theScrabi** [comment]
You are right, you see, the app is not yet finished. I'm planing to put content there.

**Comment by Zero3K** [comment]
Any news regarding the implementing of this suggestion?

**Comment by wb9688** [comment]
@Zero3K: Subscribing to channel has already landed in NewPipe, which has a
tab on the homescreen. In NewPipeExtractor, we've already added 'kiosk'
support with extractors for YouTube's Trending and SoundCloud's Top 50 and
New & hot, but that hasn't landed yet in NewPipe, because we're waiting for
a PR.

**Comment by TobiGr** [comment]
Fixed, https://github.com/TeamNewPipe/NewPipe/pull/1461 will bring even more customizable tabs to the main page
