### ISSUE TITLE
Webm formatted videos suffers from a vertical, multiple tearing effect

### ISSUE THREAD

**Issue by Leopard1907** [TeamNewPipe/NewPipe#2144]
Simply ; issue exists like i described in the title. If same video has mpeg4 option , you can clearly spot the issue to switching that.

Service: Youtube
OS: Android 5.0.2
Version: 0.15.1

- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

**Comment by Stypox** [comment]
This issue is probably device specific. Is it still there, after some updates of the exoplayer?

**Comment by Leopard1907** [comment]
If you mean " we've updated exoplayer in Newpipe , does it still persist? "

Yes , it still exist.

I'm on Newpipe 0.17.2

My device is LG G2 but that would be a surprise if that is device specific.

Example video for repro purposes: https://www.youtube.com/watch?v=Lfgf9HatIHI

WebM 720p is the highest quality option on that video and it causes vertical tearings. They're very easy to spot.

**Comment by Leopard1907** [comment]
Just tried on 0.17.3 and problem is still exists.

I tried same video on official Youtube application and it works normally. Without tearings.

@Stypox

**Comment by Stypox** [comment]
Strange, I cannot reproduce... this is probably a device-specific issue.

**Comment by Leopard1907** [comment]
Well , it doesn't happen on official Youtube app though. So there must be something they're doing different than NewPipe to avoid such issues.

**Comment by Stypox** [comment]
Sorry about the comment I wrote minutes ago, I only did a fast check and didn't notice anything ;-). 
After investigating further I see that with the specific video you provided the issue is there even on my phone. On my end it happens with every resolution, though with smaller resolutions it is less and less noticeable.

I tried to play the same video in the official YouTube website and the issue is there (720p), so I assume this is a problem with how the video was produced: https://www.youtube.com/watch?v=Lfgf9HatIHI
The official YouTube app probably uses lower resolutions, that's why the tearing is not visible. Can you please check again on the official app with maximum resolution (720p) on that video? Thanks :-)

**Comment by Leopard1907** [comment]
@Stypox Thanks , i tried it aswell and tearing is not so noticable on official app like it does on Newpipe.

However i found the ultimate repro case where it doesn't have any tearing on official app while it tears on Newpipe.

https://www.youtube.com/watch?v=llyiQ4I-mcQ

WebM format is available on 720 , 1080p is MP4.

Compare between 0:28 and 0:33. When camera moves there is a massive vertical tearing on Newpipe while it doesn't exist on official app.

**Comment by Stypox** [comment]
Mmmh, strange. I can't reproduce any tearing with that video, which means this has something to do with the device.

**Comment by Leopard1907** [comment]
YTou have to be sure you're on 720p. 1080p doesn't have any tearings on both clients.

**Comment by Stypox** [comment]
Related (or probably duplicate): #2075

**Comment by opusforlife2** [comment]
@Leopard1907 Is this still a problem in 0.20.0?
