### ISSUE TITLE
View count in the history page is incorrect.

### ISSUE THREAD

**Issue by snappyapple632** [TeamNewPipe/NewPipe#2164]
- [X] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [X] I checked if the issue/feature exists in the latest version.
- [N/A] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

Possibly related to #221 and #220.

Expected behavior: The view count in the thumbnails of the history page should reflect the view count on the video page.

Actual behavior: The view count on all videos in the history page read a value far below their actual count.

![capture _2019-02-28-14-59-15](https://user-images.githubusercontent.com/40573129/53604843-824a7280-3b6a-11e9-8862-3ece66e266e9.png)

The actual count:

![capture _2019-02-28-15-12-36](https://user-images.githubusercontent.com/40573129/53605185-8aef7880-3b6b-11e9-9d0f-2e07bafdfc77.png)

**Comment by TobiGr** [comment]
Okay, we should rename "views". This is the number of times you played the video and not the number of the total views in YouTube.

**Comment by shah26000** [comment]
Hi sir my name is Shah Khan and i would like to say your app is good but need to add some more features.

(1) Need to give loging youtube account instead of importing data from youtube and give option to clearing watch history as well.

(2) Need to add Auto Embed subtitle with video in single file so that not need to download subtitle seperately.

(3) Give option for our subscribes chennals in main menu. Like i write in blew photo. Thank u and i hope you will.
(4) Give to add.like. and comment option as well

**Comment by TobiGr** [comment]
Hey @shah26000,

I think you didn't get what NewPipe is all about. Take a look at our [FAQ](https://newpipe.schabi.org/FAQ/bugs/), this should answer all the points. Nevertheless, please open a new issue next time. Your post has nothing to do with this topic.
