### ISSUE TITLE
Unable to import really long YouTube subscription list

### ISSUE THREAD

**Issue by wolttam** [TeamNewPipe/NewPipe#2226]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

[Here](https://gist.githubusercontent.com/wolttam/d56586d2c677565071c4e935812d39c9/raw/dba803bc29f694afaf6bc51faaeffcdf2f5866bf/subscription_manager) is the roughly 90KB file I'm trying to import. I simply get the message "Could not import subscriptions." When I remove a large chunk of the list at random from the middle of the file, reducing it to about 40KB, I can get it to import. I'm not sure if it's related to the size of the list or if there happens to be a single entry in it breaking things. I'm happy to provide any other information I can to help track down the issue.

This is when running version 0.16.1 from fdroid on Android 9.0

Thanks!

**Comment by manoelnascimento** [comment]
Same problem here. I had to build 20 lists from the original "subscription_manager" file to import my YouTube subscription list. Running version 0.16.1 from F-Droid on Android 7.1.2 .

**Comment by DuelToDeath** [comment]
Encountered the same problem here too. Running on the 0.16.1 on Android 9

**Comment by buckket** [comment]
I bisected my `subscription_manager` file until I found the culprit: It’s a deleted channel with empty `title` and `text` tags, that YouTube still includes in the exported list but NewPipe apparently can’t handle.

To reproduce one can try this minimal example:
```
<opml version="1.1"><body><outline text="YouTube Subscriptions" title="YouTube Subscriptions"><outline text="" title="" type="rss" xmlUrl="https://www.youtube.com/feeds/videos.xml?channel_id=UCxCmitIuHqjM_Gl72cu_ylA" /></body></opml>
```

**Comment by Delta2333** [comment]
> I bisected my `subscription_manager` file until I found the culprit: It’s a deleted/suspended channel with empty `title` and `text` tags, that YouTube still includes in the exported list but NewPipe apparently can’t handle.
> 
> To reproduce one can try this minimal example:
> 
> ```
> <opml version="1.1"><body><outline text="YouTube Subscriptions" title="YouTube Subscriptions"><outline text="" title="" type="rss" xmlUrl="https://www.youtube.com/feeds/videos.xml?channel_id=UCxCmitIuHqjM_Gl72cu_ylA" /></body></opml>
> ```
> Obvious workaround: Manually delete the problematic entry.

Thank you soooooooooooooo much!!!! That's really helpful

**Comment by Stypox** [comment]
I found where the bug lies: in the NewPipeExtractor repo. The problem is that the youtube extractor explicitely throws an exception when the title is empty. See [lines 66-68 at YoutubeSubscriptionExtractor.java](https://github.com/TeamNewPipe/NewPipeExtractor/blob/dev/extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/extractors/YoutubeSubscriptionExtractor.java#L66-L68).

I opened a pull request: TeamNewPipe/NewPipeExtractor#160

**Comment by mauriciocolli** [comment]
Spot on, @buckket and @Stypox!

It's a little unexpected that YouTube put that in the export (because the title is empty, it "knew" it wasn't available when exporting), but looking at my subscriptions list I can find some channels that were removed as well, but they still show their names, maybe because YouTube don't delete subscriptions because a channel can be reinstated after a suspension (still, a bug in YouTube side).

But it's a problematic check nonetheless, it should only see if the url exists, because that's what matters.

**PS**: I don't think size matters (maybe in _very_ memory contraint devices?), here it is importing a 6MB file:
<img src="https://user-images.githubusercontent.com/13389907/56852558-2f373680-68f3-11e9-98e2-23e03ef992fc.png" width="350" />

[1]: https://github.com/TeamNewPipe/NewPipeExtractor/blob/dev/extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/extractors/YoutubeSubscriptionExtractor.java#L66..L69

**Comment by wolttam** [comment]
Right on for finding the **actual** cause of this issue! Size alone did seem like an unlikely cause.
