### ISSUE TITLE
No support for the "SD Card Write Access" on Android 6.0

### ISSUE THREAD

**Issue by robertx46** [TeamNewPipe/NewPipe#2230]
The app doesn't ask for this permission at the storage selection of the download section, if you pick an SD folder this result an "error 1003: action denied by system"(sort of)
Code: Java.io.IOException:open failed: EACCESS (permission denied)
When you try to download something.

**Comment by snappyapple632** [comment]
This is an issue with our current downloader. We are still trying to make a new downloader that would fix these issues, but as far as I'm concerned no one has made any progress on it in a while. The only solution would be to root your device.

**Comment by theScrabi** [comment]
We could make the downloader use the android storage framework

**Comment by kyungjin** [comment]
Hello
I run on Android 7.0.
NewPipe can access the external SD Card on its standard folder Android\data\org.schabi.newpipe (I read somewhere else that it's an Android rule since Kitkat ?) 
Thus I can create subfolders in this folder and make them the default folders for downloads.
Maybe this could be useful for other users.

**Comment by gkeegan** [comment]
I don't think it's good practice to put files into the data folders, as I'm pretty sure they are removed when you uninstall the app. But I am not sure on that.
