### ISSUE TITLE
[Issue] Long videos won't start playing

### ISSUE THREAD

**Issue by BugReporter2** [TeamNewPipe/NewPipe#2324]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

Steps to reproduce:

- Open a long video. The video does not start, the circle just plays. Example: https://www.youtube.com/watch?v=2qjff_o66JQ

- Short videos start playing almost immediately. Example: https://www.youtube.com/watch?v=6OBtKnMbgrA

**Comment by ReekyMarko** [comment]
I've actually noticed that if a video doesn't start playing, changing the quality makes it play almost immediately. You can even change it back and it still works after that.

Sadly, this has been happening increasingly more for the past few weeks and newpipe is almost unusable as a music player because of it

**Comment by ReekyMarko** [comment]
As a related note, I remember seeing an issue here a while a go that was related to this. If memory serves me right it was identified as some sort of a cache problem

**Comment by Stypox** [comment]
Check #2337
The length of a video does not seem to matter.

**Comment by ReekyMarko** [comment]
Yeah I think it's wise to close this as a dup and continue discussion there
