### ISSUE TITLE
[Feature Request] Mute or adjust volume of this app (only) 

### ISSUE THREAD

**Issue by AndydeCleyre** [TeamNewPipe/NewPipe#2370]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [-] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

It would be helpful to be able to adjust or mute the volume of this app, without interfering with the volume of other running applications. 

As an example use case: I'm playing music for my family over a bluetooth speaker using spotify. I want to silently watch an informational video using newpipe. But if I try to mute the video, instead newpipe goes ahead and mutes all media from my phone.

**Comment by gkeegan** [comment]
This seems like an extreme outlier use case. I'm not sure something like this would have enough usage to warrant its own feature, especially since [this app](https://play.google.com/store/apps/details?id=com.spycorp.appvolumecontrol) may get the job done for you. 

Try using that, and let me know if it works.

---

Another option could be to download the video, then open it in VLC and turn off the audio track.

---

 Anyways, I don't think it would be a good idea to enable different audio levels for different apps within NewPipe itself, as this could lead people to thinking their phone is muted when it really isn't, or vice versa. A mute might be a better option, but then it opens the question of whether or not to still get the audio stream (if it's even an option for that stream quality).

**Comment by AndydeCleyre** [comment]
OK, thanks. I just want to be able to mute the video, so I can play my own music. I'm not going to install an entire app just for a mute feature, though. 

If this request is rejected, ok. I'll just not use the same device.

**Comment by gkeegan** [comment]
The app is less than 2 mb. There is no need to have as few apps as possible on your phone, as they don't run 24/7

**Comment by AndydeCleyre** [comment]
From the suggested app description:

> This app adjust the volume when the foreground app change.
It's not possible to have a background app and a foreground app with different volumes, this is an Android limitation.

This indicates the best move forward would be to have a mute/disable-sound button. Also, at least when trying to test without bluetooth, I can't even get spotify and newpipe to play simultaneously.

I understand this issue is closed because the developers don't like the idea of this feature, I'm just adding a correction for posterity: the proposed workaround is not helpful.
