### ISSUE TITLE
Add new labels to better classify issues

### ISSUE THREAD

**Issue by Stypox** [TeamNewPipe/NewPipe#2416]
- [X] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.

After #2411 I took care of the first 5 pages of issues and labelled them. But I think some new labels should be added, to better organize issues and make them more accessible:
 - `gui` for GUI related issues (e.g. the text is too big, red color is too bright, #1170, ...)
 - `downloader` for issues with downloading videos
 - `more-info-needed` for issues that are lacking useful information, and the author has not yet updated the issue after he has been asked to (e.g. #2443)
 - `pr-open` for issues that will be fixed by a pending pull request, as suggested by justanidea

If you have any other suggestion for labels write it in this thread.

Thanks :-)

**Comment by justanidea** [comment]
Maybe "waiting for merge" :)

**Comment by gkeegan** [comment]
* `meta` for issues discussing NewPipe policy and the like (this issue is an example of this)


* `youtube`, `soundcloud`, `mediaccc` for issues that are specific to only those services. I don't really think this one is that good an idea however, as it would lead to a lot of clutter and unnecessary comments asking for a `youtube` label to be added to an issue

I also think the number of labels added should be kept to a point where they are not *too* specific. It's best to encourage good titles for topics.

**Comment by Stypox** [comment]
@TobiGr @theScrabi bringing this to your attention in case you didn't see it. Feel free to close the issue if you don't think this is a good idea :-)

**Comment by TobiGr** [comment]
@Stypox It's a good idea. Labels like `downloader` or `GUI` are important to find related tickets. I had the same idea some time ago, but didn't have time to add the labels to that many tickets, because reviewing and testing PRs is more important. Feel free to do it.
Btw. I might be a bit slow in responding to mentions because I have a bunch of exams to write atm.

**Comment by Stypox** [comment]
I don't have the permission to do that... I don't see the "New label" button.
Could you please do that, or give me permission (if possible)? Take as much time as you want, and good luck with your exams :-)

**Comment by TobiGr** [comment]
I created the labels. It seems like I can only give you permission to create labels while granting you a bunch of other permissions, too. In case you need some more labels or anything else, feel free to ask.

**Comment by Stypox** [comment]
Ok, thank you :-)

**Comment by Stypox** [comment]
I think another label should be added:
- `multiservice`: for issues with the multiservice option, new service proposals (e.g. #1137 #1134 #1141 #1166)

I think the "stale" bot was removed after #1921, since I haven't seen any "stale"d issue after 4 December 2018. But with the removal of the bot, I think the `stale` label *should be removed*, too. It doesn't add anything to issue classification and it just uses up space.

@TobiGr hope not to bother you :-)

**Comment by TobiGr** [comment]
@Stypox Thanks for going through the bug tracker! I removed the stale label and added one for multiservice. Once we support more services, we might want to think about categorizing labels like
`service: youtube`, `service: soundcloud` etc.

**Comment by Stypox** [comment]
Mmh I agree. I had to travel for 8h with nothing to do, so I decided to do this :-D
