### ISSUE TITLE
network error since today morning

### ISSUE THREAD

**Issue by test2a** [TeamNewPipe/NewPipe#2439]
app is refusing to work since morning

**Comment by gkeegan** [comment]
Works fine for me. Please provide the version of the app you are using, your device model, your version of Android, and your region. Also, does the regular YouTube app work?

Also, what features are giving a network error, and how can somebody reproduce your issue?

**Comment by test2a** [comment]
0.16.2
India region
android 7

I reinstalled the app but network error. Retry.

App was working fine 2 days ago. Then I got an error page, couldnt save that. Any way to get the log data?

**Comment by gkeegan** [comment]
What parts of the app aren't working? Or is it just that when you open the app you immediately get an error?

If things like reading comments, loading pages, watching videos, and stuff like that do not work, could you please try to access YouTube through their website on your phone and see if it works?

About logs, I think it would be best to answer these questions first, then I could advise you on if NewPipe is the issue here, or if it is something else.

Anyways, if you really want to get logs you could download [matlog](https://play.google.com/store/apps/details?id=com.pluscubed.matlog) and use that.

**Comment by test2a** [comment]
no. the app is not working at all.

**Comment by gkeegan** [comment]
Could you please try to access YouTube on their website on the phone? I have asked multiple times now.

**Comment by test2a** [comment]
Ok. Got it. Blokada was interfering with the app and not letting it check youtube. Found out with a different app. So the app was fine on its own. I am closing the issue. Thanks for your time mate

**Comment by gkeegan** [comment]
No problem! I figured it was some sort of networking issue.
