### ISSUE TITLE
How to save a channel as a bookmark

### ISSUE THREAD

**Issue by 11fen** [TeamNewPipe/NewPipe#2452]
How to save a channel save a bookmark。
The bookmark save button was not found after searching for a channel. (not a subscription)

**Comment by Stypox** [comment]
What do you mean by "save a bookmark"? The option to subscribe already exists (but if I understand correctly that's not what you want). You can also add tabs to the main screen containing a channel.

Currently there is no way to bookmark channels as you would bookmark a website in a browser.

**Comment by gituby** [comment]
Hi,

I really agree with 11fen. Even more, i think it could be very useful if it was possible to add also channel (and even playslist's channel) to the bookmarks page (tab),  inside one of the playlist we can create, as we already can do for individual videos.

In the actual configuration of NewPipe, you just have a page (tab) to the Channels you have subscribed, and another page (tab) for the bookmarks of channel's playlist or to create our own playlist to group individual videos.

One of the problems with suscribed channel and bookmarks in general, is that you are quickly overwhelmed with tons of them, you keep because you like them or to watch later.

This is why i don't like much the design of the channel's subscription page (tab), because on my smartphone it ends up with a very long list to browse, and it is not even possible to sort them manualy as you wish, to organize them by categories for example.

In the bookmarks page (tab), if the playlists we can create could include any type of bookmark or subscription (channels, playlists's channels or individual vidéos), we could organize them by categories (news, tech, sport etc.) to find them very easily.

**Comment by Stypox** [comment]
Ok, then you issue will disappear after #2309

**Comment by opusforlife2** [comment]
2309 is merged.
