### ISSUE TITLE
APK?

### ISSUE THREAD

**Issue by Smultie** [TeamNewPipe/NewPipe#250]
Would it be hard to release apk's as well? Can't seem to find 0.7.7 and 0.7.8 on F-droid nor on Github.

**Comment by CHRINIMUE** [comment]
Hi,
0.7.7 was manual disabled in F-Droid because it contain broken native code. 
And the 0.7.8 will be in the F-Droid repo until the next days. The new version have been added, but it take a while until F-Droid creates a signed APK and add it to the repository.
But I think it would be a good idea. But will it be used and the time worth?

**Comment by Dostoi** [comment]
It can easily be done with travis, you just have to set it up and it will automatically create an apk for every new functioning commit.
It make beta testing the app easier.

**Comment by theScrabi** [comment]
Sounds nice. If you like, you can add this option to the travis config.

**Comment by Dostoi** [comment]
I don't know how to set it up, I just now it can be done because another app I'm using his using it ^^
And when setting it up you have to watch out for the apk signature, you can choose to use the same for every apk or not (which make you delete the app every time you want to test another apk)

**Comment by theScrabi** [comment]
You could send a link to the app, so we can take a look into their config.

**Comment by Dostoi** [comment]
Here : https://github.com/raulhaag/MiMangaNu

**Comment by theScrabi** [comment]
Aha it seems like its this line here: https://github.com/raulhaag/MiMangaNu/blob/master/.travis.yml#L26

**Comment by rancidfrog** [comment]
Adding apk to [releases](https://github.com/theScrabi/NewPipe/releases) section would be much appreciated

**Comment by theScrabi** [comment]
A simple bump... Alright, but could someone of you try to make that possible with travis?

**Comment by rancidfrog** [comment]
Maybe,
http://szagurskii.com/blog/how-to-deploy-apk-to-github-releases-with-travis-ci/
example:
https://github.com/zsavely/AutoDeployExample

Another example here: http://blog.fossasia.org/push-your-apk-to-your-github-repository-from-travis/

**Comment by theScrabi** [comment]
But why would you want that? Every version besides the taged ones are unstable, or not ready. The taged ones get build by f-droid anyway.

**Comment by rancidfrog** [comment]
Personally would rather download from [releases](https://github.com/theScrabi/NewPipe/releases) than fdroid.
Not sure how other devs do it but most have apks with source available: 

- https://github.com/k9mail/k-9/releases
- https://github.com/ukanth/afwall/releases
- https://github.com/indywidualny/FaceSlim/releases
...

**Comment by icasdri** [comment]
F-Droid builds are built by the F-Droid team and guaranteed to correspond to the given source code. Considering that they also serve over HTTPS, offer GPG signatures, and the source tarball (that again is guaranteed to correspond to the built binary), I scarcely can see how automatic GitHub releases would be superior. If greater noticeability is desired, each release can link out to the F-Droid build.

**Comment by rancidfrog** [comment]
Why rely on 3rd party when github provides everything you need to do it here, yourself?
Also, apk gets built. It is just a matter of copying/uploading it back to release section along with source.
All that needs to be done is set it up properly once and everything is automatic.

Following your direction,, (icasdri): 
Why have a release section at all? 
FDroid has source, why attach source in release section? 
just put changelog.md in source root directory.
Like you said, F-Droid builds are built by FDroid team, NewPipe is not developed by FDroid though.
I do not see why having the apk alng with source in release section is such an issue

**Comment by Dostoi** [comment]
The advantage of having faster release than f-droid is to be able to do easier testing of the app for people who don't want to set everything up to build apk themselves and just find bug before release

**Comment by killoid** [comment]
requested the same thing on #475 , hope dev will figure it out!

**Comment by archon810** [comment]
Now that APKs are attached to releases, I noticed they're signed with a different key from fdroid. Is it possible to generate them using the same key? Otherwise, they're mostly useless to almost everyone (because they'd need to uninstall the fdroid version first).

**Comment by theScrabi** [comment]
That is the main Problem about that thing. Fdroid signs aitomaticly, and only they have the key (which in my opinion is ok!!!) However, I can only sign with my own key, or not sign.

In other words, if you don't burst because you can't wait for the new version to be finally available on fdroid, you should probably be calm and wait for fdroid to release it in a few days.

**Comment by archon810** [comment]
@theScrabi I see no good solution here if you can't acquire the key fdroid uses at this point.

**Comment by theScrabi** [comment]
So you think I should not put the apk online than?

**Comment by archon810** [comment]
Well, I think it'll only confuse people. They'll see a corruption message or whatever the failure to install due to mismatching signatures looks like these days, and it'll create problems for you.

**Comment by theScrabi** [comment]
Hm yes you are right.

**Comment by rancidfrog** [comment]
![](https://s14.postimg.org/q46imfppt/Screenshot_20170429-190534.png)
@archon810 
Are you worried people will stop going to apkmirror to get app?
Otherwise you should know all about signatures.
Having users uninstall before reinstalling is also standard for testing purposes.
Debug apps usually force users to uninstall first to make sure issues are with new release.

@theScrabi 
If you want fdroid to be main place than you can treat github as debug app, or for people who know what they do or do not care to use fdroid.
Most people would not notice until new update available through fdroid.

Having multiple points of access is never a problem.
Many apps are already both in play store and github at the same time.
So I do not see issue.
If @archon810  has an issue of not wanting to uninstall, then 1 he can either get all u[dates from github or wait for fdroid robots to build new update.

**Comment by mauriciocolli** [comment]
If some one bother enough (is so anxious about a new release, or just wanna test it) to come to GitHub and download a DEBUG release, I don't see a problem uninstalling the installed version first...

So yes, continue to attach the apk in the new releases (in my opinion).

**Comment by theScrabi** [comment]
Ok :) ... I may write a warning beneath so people will now whats up with the apk.

**Comment by archon810** [comment]
@rancidfrog I do know all about signatures, and I was not commenting here out of some selfish reasons. On the contrary, I deal with people confused about how signatures work and why their app updates fail in such cases every day, and I know how much confusion it can generate. You're making a lot of assumptions about people knowing more because they find the APK here instead of fdroid or apkmirror.com, but if a search engine lands them here, they'll try to update from here.

If @theScrabi wants to keep the APKs with different signatures after all, my recommendation would be to 
1. Name APKs here explicitly stating "debug" in the name. So instead of NewPipe-0.9.4.apk, it'd be something like NewPipe-0.9.4-debug.apk.
1. "Downloading the APK from here is not the official way to get the app. It's for debug purpose only, so please get the full release from f-droid!!!" is not a good enough warning IMO - it should explain more clearly that debug APKs have different signatures from fdroid and other sources, and what the implications are (i.e. the need for full uninstallation of fdroid APK in case of updating).

**Comment by theScrabi** [comment]
How do people even think APKMirror was a reale source? I don't support it therefore you should stay away from it.

**Comment by archon810** [comment]
@theScrabi FYI, https://f-droid.org/repository/browse/?fdfilter=newpipe&fdid=org.schabi.newpipe which you add to your releases is a broken link.

**Comment by killoid** [comment]
https://f-droid.org/packages/org.schabi.newpipe/
this is the new link. f-droid has changed website layout & stuffs.

**Comment by mauriciocolli** [comment]
I've updated the release message, do you guys think it's informative enough?

**Comment by TobiGr** [comment]
@mauriciocolli The new description is good. But as said, people who download the apk from GitHub instead using the official way should know what they do... 
Btw. The link in the README.md is wrong too. But there is another problem with it: the F-Droid app does not open links to the new F-Droid website (F-Droid was able to recognize the old links and open the app page directly). So if we want to support opening the link with the app _and_ the browser, we'll need two different links/buttons.
