### ISSUE TITLE
Newpipe version 0.7.8 chrashes on lollipop

### ISSUE THREAD

**Issue by Spielmops** [TeamNewPipe/NewPipe#258]
Newpipe 0.7.8 on Lollipop - If you search, click on one of the search-items, you have that one item and information. If you go back to the list, Newpipe exits (with notification). Settings at standard

The same version on Kitkat is Ok, everything works normal. Settings at standard.

Version 0.7.6 on Lollipop is OK, Setting at standard.

Spielmops

**Comment by theScrabi** [comment]
Please provide a log.

**Comment by Spielmops** [comment]
How?

Am 31.03.2016 um 13:46 schrieb Christian Schabesberger:
>
> Please provide a log.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/theScrabi/NewPipe/issues/258#issuecomment-203894530>
>

-- 
------------------------------------------------------------------------
"Ich habe keine besondere Begabung, sondern bin nur leidenschaftlich 
neugierig." (Einstein)
spielmops.org <http://spielmops.org>

**Comment by theScrabi** [comment]
Plug your smartphone into your computer and get a log with adb, or download [aLogCat](https://f-droid.org/repository/browse/?fdfilter=logcat&fdid=org.jtb.alogcat).

**Comment by Spielmops** [comment]
I have to much around my head at this time. Forget the log and forget 
that issue, everything is fine with version 0.7.6 ...

Spielmops

Am 31.03.2016 um 20:48 schrieb Christian Schabesberger:
>
> Plug your smartphone into your computer and get a log with adb, or 
> download aLogCat 
> <https://f-droid.org/repository/browse/?fdfilter=logcat&fdid=org.jtb.alogcat>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/theScrabi/NewPipe/issues/258#issuecomment-204073786>
>

-- 
------------------------------------------------------------------------
"Ich habe keine besondere Begabung, sondern bin nur leidenschaftlich 
neugierig." (Einstein)
spielmops.org <http://spielmops.org>

**Comment by theScrabi** [comment]
Hm. Forget about loging. I just realized that bug reporting can be done more proper. Wait until the next version it will report crashes automatically. But thanks for patients.

**Comment by vanitasvitae** [comment]
I think this is the same issue. App crashes after going back to search results from a video (Nexus 5, CopperheadOS)

> D/AndroidRuntime( 8950): Shutting down VM
E/AndroidRuntime( 8950): FATAL EXCEPTION: main
E/AndroidRuntime( 8950): Process: org.schabi.newpipe, PID: 8950
E/AndroidRuntime( 8950): java.lang.RuntimeException: Unable to start activity ComponentInfo{org.schabi.newpipe/org.schabi.newpipe.VideoItemListActivity}: java.lang.RuntimeException: Parcel android.os.Parcel@44d91a6: Unmarshalling unknown type code 3801188 at offset 1936
E/AndroidRuntime( 8950): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
E/AndroidRuntime( 8950): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
E/AndroidRuntime( 8950): 	at android.app.ActivityThread.-wrap11(ActivityThread.java)
E/AndroidRuntime( 8950): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
E/AndroidRuntime( 8950): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 8950): 	at android.os.Looper.loop(Looper.java:148)
E/AndroidRuntime( 8950): 	at android.app.ActivityThread.main(ActivityThread.java:5417)
E/AndroidRuntime( 8950): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 8950): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
E/AndroidRuntime( 8950): 	at com.android.internal.os.ExecInit.main(ExecInit.java:53)
E/AndroidRuntime( 8950): 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
E/AndroidRuntime( 8950): 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:251)
E/AndroidRuntime( 8950): Caused by: java.lang.RuntimeException: Parcel android.os.Parcel@44d91a6: Unmarshalling unknown type code 3801188 at offset 1936
E/AndroidRuntime( 8950): 	at android.os.Parcel.readValue(Parcel.java:2340)
E/AndroidRuntime( 8950): 	at android.os.Parcel.readArrayMapInternal(Parcel.java:2614)
E/AndroidRuntime( 8950): 	at android.os.BaseBundle.unparcel(BaseBundle.java:221)
E/AndroidRuntime( 8950): 	at android.os.Bundle.getSparseParcelableArray(Bundle.java:856)
E/AndroidRuntime( 8950): 	at com.android.internal.policy.PhoneWindow.restoreHierarchyState(PhoneWindow.java:2033)
E/AndroidRuntime( 8950): 	at android.app.Activity.onRestoreInstanceState(Activity.java:1008)
E/AndroidRuntime( 8950): 	at android.app.Activity.performRestoreInstanceState(Activity.java:963)
E/AndroidRuntime( 8950): 	at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1163)
E/AndroidRuntime( 8950): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2389)
E/AndroidRuntime( 8950): 	... 11 more
E/AndroidRuntime( 8950): Error reporting crash
E/AndroidRuntime( 8950): java.lang.RuntimeException: Bad file descriptor
E/AndroidRuntime( 8950): 	at android.os.BinderProxy.transactNative(Native Method)
E/AndroidRuntime( 8950): 	at android.os.BinderProxy.transact(Binder.java:503)
E/AndroidRuntime( 8950): 	at android.app.ActivityManagerProxy.handleApplicationCrash(ActivityManagerNative.java:4425)
E/AndroidRuntime( 8950): 	at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:90)
E/AndroidRuntime( 8950): 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
E/AndroidRuntime( 8950): 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
I/Process ( 8950): Sending signal. PID: 8950 SIG: 9
I/ActivityManager( 1900): Process org.schabi.newpipe (pid 8950) has died
W/ActivityManager( 1900): Force removing ActivityRecord{81610e6 u0 org.schabi.newpipe/.VideoItemListActivity t394}: app died, no saved state
W/WindowManager( 1900): Failed looking up window
W/WindowManager( 1900): java.lang.IllegalArgumentException: Requested window android.view.ViewRootImpl$W@d475991 does not exist
W/WindowManager( 1900): 	at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:8736)
W/WindowManager( 1900): 	at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:8727)
W/WindowManager( 1900): 	at com.android.server.wm.WindowManagerService.removeWindow(WindowManagerService.java:2698)
W/WindowManager( 1900): 	at com.android.server.wm.Session.remove(Session.java:187)
W/WindowManager( 1900): 	at android.view.ViewRootImpl.dispatchDetachedFromWindow(ViewRootImpl.java:3099)
W/WindowManager( 1900): 	at android.view.ViewRootImpl.doDie(ViewRootImpl.java:5606)
W/WindowManager( 1900): 	at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:3409)
W/WindowManager( 1900): 	at android.os.Handler.dispatchMessage(Handler.java:102)
W/WindowManager( 1900): 	at android.os.Looper.loop(Looper.java:148)
W/WindowManager( 1900): 	at android.os.HandlerThread.run(HandlerThread.java:61)
W/WindowManager( 1900): 	at com.android.server.ServiceThread.run(ServiceThread.java:46)
