### ISSUE TITLE
0.17.2 (from releases) is not notifying of 0.17.3 update

### ISSUE THREAD

**Issue by bughit** [TeamNewPipe/NewPipe#2669]
android 10
the updates pref is on

**Comment by TobiGr** [comment]
CC @TheAssassin 
``` HTML
<html><title>500: OK</title><body>500: OK</body></html>
```

**Comment by TheAssassin** [comment]
Guys, please just mail me next time directly, and I'll fix it earlier. I still have no idea why this is happening. But I just refined the Docker container's `HEALTHCHECK` to specifically grep for this line, and if it finds it, trigger a restart. That should auto-fix it in the future.

**Comment by TheAssassin** [comment]
Err... okay, strange, there's an actual bug right now in the code it seems, as I keep getting 500s. Probably an issue in some upstream system?

**Comment by TheAssassin** [comment]
Heh, finally found out why there was something as strange as `500: OK`. Looked at the code and got curious why I once had `send_error` and once `write_error`. Turns out I should've used the former only. Changed the code, and it now sends a 500 status correctly.

Now let's see why this errors out at all. Luckily we know at which spot it breaks, as I just changed that line.

**Comment by TheAssassin** [comment]
Seems on the server the F-Droid related request fails...

**Comment by bughit** [comment]
Why does this check need to involve seemingly unnecessary points of failure, your servers, custom code, F-Droid requests?

Isn't github api sufficient? https://api.github.com/repos/TeamNewPipe/NewPipe/releases/latest

**Comment by TheAssassin** [comment]
After 2 darn hours I fixed the issue by adding the following line to the docker-compose config:

```yml
    dns: 46.182.19.48
```

Some more details: When you use docker-compose for deployments, every deployment gets its own *user-defined network*. These networks nowadays get their own DNS servers. Turned out they don't support reverse DNS lookups! What the heck!

Took me two hours to debug, I even added the app to some Sentry instance to get more context data. There I saw the issue wasn't limited to a single service we contact, and occurred in the reverse DNS lookup (I suspected that from the existing data, though). Then I tried `nslookup` in the container, and well, no hostname can be looked up reversely.

@bughit first of all, users' privacy is protected if we proxy the information. Otherwise, every user of NewPipe would have to contact some services like GitHub, GitLab, ..., which we don't want. We're privacy-friendly, remember? The code wasn't bulletproof, and the main issue was that I wasn't notified earlier (@TobiGr looking at you! (I don't monitor the whole NewPipe repo, so I didn't get any notification we had an issue until @theScrabi notified me; please, *please*, just mail me if there's issues that don't get fixed, I don't mind getting tens of mails even if I'm on it already)).

My monitoring has been fixed, same goes for things like the container healthcheck and many more little features. Our system got, once again, a bit more robust. Let's hope this will last for a bit again.

**Comment by TheAssassin** [comment]
P.S.: the reason you were not notified is that the guys built the API client in NewPipe to just ignore such errors. Imagine what kind of flood of issues we might've got if it showed errors. I am live monitoring the logs since I fixed it, and I can see around 30-150 requests per minute (of course, I cannot tell whether they're unique visitors, we log IP addresses anonymizedly, please refer to our privacy policy for more information). We have a lots of users, that's awesome!

**Comment by bughit** [comment]
@TheAssassin 

> first of all, users' privacy is protected if we proxy the information

This argument makes no sense for the following reasons:

- Considering you don't proxy youtube access (nor should you) an anonymous github request is relatively a privacy non-issue. But even if your goal is to hide from github that an IP of a newpipe user is interested in the latest newpipe release, you fail to accomplish that, because ....
- ... you only proxy the version check (https://newpipe.schabi.org/api/data.json), not the apk download.
- Furthermore you delegate the apk download to the browser, which transmits cookies and your github identity if you're logged. How "privacy-friendly" is that?

Let's move on to security.

- Hosting the update urls on your server means if it's hacked it can become a malware vector, unless the app does some verification of the version check payload, does it?
- I am assuming the apk has to be signed by a private key that's not on that server, in order to upgrade, but users are likely to just uninstall the old version if they run in to an upgrade problem, and then the new infected one with a different signature will install.
