### ISSUE TITLE
Videos will not scale to notch area

### ISSUE THREAD

**Issue by haistakaavittukaikkisaatana** [TeamNewPipe/NewPipe#2682]
When scaling videos they will not reach the notch area, so videos are not truly fullscreen.

Device: Note 10+
OS: Stock Pie 9.0

**Comment by Stypox** [comment]
Have you tried clicking on the "fit" button in the submenu of the main player, to change how the video renders?

**Comment by haistakaavittukaikkisaatana** [comment]
Yes, and it will not fill to notch area.

**Comment by haistakaavittukaikkisaatana** [comment]
If there is a beta version you'd like me to test just send me a message.

**Comment by moneytoo** [comment]
I confirm this behaviour. It's because ``LAYOUT_IN_DISPLAY_CUTOUT_MODE_SHORT_EDGES`` is not specified. It's pretty straightforward to add (I can send a PR, it works fine for me when added).

But the question is in what viewing modes (Fit/Fill/Zoom) should the view actually extend to the cutout area. I would expect it at least in the Fill and Zoom modes. Personally I would also extend it in the Fit mode. Here's why:

1. I basically only use MX Player (on OnePlus 7) and it extends to the cutout in all viewing modes (including "Fit to screen").

2. I prefer to extent to view to cutout in Fit mode because 16:9 videos (on my 19.5:9 screen) are better horizontally centered and don't go near the non cutout side where display has rounded corners.
