### ISSUE TITLE
Is the NewPipe bitcoin address even secure anymore?

### ISSUE THREAD

**Issue by worried-newpipe-user** [TeamNewPipe/NewPipe#2719]
So I was planning to do a donation to this project so, of course, I checked what was going on with the address (nice bitcoin feature). One thing surprised me though:

![16a9j59ahmrqklszjhyj33n9j3fmztfxnh](https://user-images.githubusercontent.com/56457180/66688088-acbdeb80-ec74-11e9-90b4-d9dd9743d5bc.png)

On the day 26/06/2019 the account had been emptied and being the curious person I am, decided to see where the money went:

https://www.blockchain.com/btc/tx/ec2400a2aa7a37d1c062c4987a54ae98ef9730c99fa0700a8da48431c905dedf

Hmm, okay, let's see the what the address `bc1qjmyxwhyjxqjwfyspptvyjhr6kreehxjveec3md` might be with a Google search. There we go, a GitHub issue with people that had been scammed, and surprisingly, the response of a member of this repo's team, @theScrabi:

https://web.archive.org/web/20191011201911/https://github.com/spesmilo/electrum/issues/5183#issuecomment-505852243

The strange part is that I can't find any issue or announcement that this had occurred,
so please, I'm waiting for some response before proceeding with the donation.

**Comment by theScrabi** [comment]
I got scamed. In the beginning of the year when the bitcoin price rose I wanted to cell our coins. However I fell to the Electrum 4.0 scam, so we lost all our coins.

I went to the police for a report, and as far as I know there is already a research going on in Berlin due to a bigger issue.

We should have made a Blockpost about this toppic and I had in mind that we did that, however apparently we forgot that. I'm sorry for that.
@TheAssasine can we create a blog post about this?

**Comment by TheAssassin** [comment]
@worried-newpipe-user indeed we had a problem with the Bitcoin donation system. Unfortunately, a scammer tricked @theScrabi into transferring the shown amount of BTC to their address. Those BTC are lost, we couldn't find a way to recover them.

The scam was a one-time-success attack, as it didn't involve phishing or anything. Basically, @theScrabi downloaded a nearly-perfect fake copy of a software called Electrum, as the BTC-EUR rate was pretty attractive and we wanted to save those donations in a real currency. Instead of helping us get the money though, that fake software unfortunately stole the entire sum.

Please note that @theScrabi reported this incident to the police, and we see progress in these investigations actually (normally, when you lose money this way, the chances are pretty bad you see any of it ever again; however, it's still required way to report these incidents, otherwise you'd give up directly). We apologize to every of our donors whose money was lost in this scam. We will post an official statement soon.
