### ISSUE TITLE
Add translation for pirate speak (PR)

### ISSUE THREAD

**Issue by tusharpandey13** [TeamNewPipe/NewPipe#2729]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

Hi!
I use newpipe everyday and i think it'd be cool if we had pirate speak as language option in the app. Just this okthx.

**Comment by Stypox** [comment]
If you intend to translate and maintain the new language then go for it, but I don't think this would add much to the app even though it requires time.

**Comment by B0pol** [comment]
It's selectable in the app since #2921 . But…, untranslated, so it displays english.
Plus I looked it seems like a troll language from a film or something.
So maybe we should remove the file and the matching codes / name in language selector arrays.
Anyway it has been addel, and is translatable via Weblate, so it should be closed
