### ISSUE TITLE
Cannot add (NewPipe) playlists to queue

### ISSUE THREAD

**Issue by milklineep** [TeamNewPipe/NewPipe#2752]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

Long-pressing the "Background" or "Popup" button in a NewPipe-created (native) playlist doesn't do anything - whereas I expect it to add the videos of the playlist to the corresponding queue, same as it does for YouTube playlists. This is annoying as when I queue music, I have to queue the native playlist before the YouTube playlist and I can't queue several native playlists.

Steps to reproduce:
1. Create a playlist with any videos
2. Open a YouTube playlist and queue it, for example on the background player
3. Open the playlist from Step 1 and try to add it to the queue without removing the videos that are already in the queue. Long-pressing the button doesn't work.
4. Open another YouTube playlist and attempt to queue it by long-pressing the background button. This works, as opposed to Step 3.

**Comment by B0pol** [comment]
It's already fixed by #2636 , on long click on « background » or « popup » in a playlist, it queues.
But there is a thing not solved by this PR : 
On long press on a video, it show a menu : wait for edit
but on long press on a playlist, it either displays nothing (online playlists), or just a "do you want to delete" menu : screenshot edit
IMO online playlist should have the same options, and local playlist should also have a delete button instead of add to playlist, that delete button would open the current confirmation of deletion popup which is currently displayed on long press

**Comment by Stypox** [comment]
@B0pol see #2583

**Comment by Stypox** [comment]
Fixed in 0.19.3
