### ISSUE TITLE
NewPipe freezes 

### ISSUE THREAD

**Issue by gloschtla** [TeamNewPipe/NewPipe#2832]
Whenever NewsPipe starts playing in Background Player, it starts freezing. This happens since I updated Android. 

Is there any logging feature, so I can send a log file for the bug report?

**Comment by TemporaryAccount0x1** [comment]
In Android the log file is called logcat you can access it via `adb logcat > log.txt` there are also apps that can access the logcat if you have trouble with adb. If you copy it it's probably better for privacy reasons to remove lines that don't contain `org.schabi.newpipe` since that's the newpipe app id and so only lines that contain that are useful for debugging. 

before you trigger the erratic behaviour again be sure to check the time so the devs know which lines are important.

**Comment by opusforlife2** [comment]
@gloschtla Check if it's still happening with the unified player?
