### ISSUE TITLE
Will the scraper expire?

### ISSUE THREAD

**Issue by xlinulx** [TeamNewPipe/NewPipe#286]
How often do you update the youtube extractor?
What do you do when it stops working?
How can I contribute into ensuring that the extractor works?

**Comment by rrooij** [comment]
When YouTube will update its site, the scraper can indeed get outdated. It is not updated at regular intervals, but I'm sure someone will fix it when YouTube changes its site. People make issues on GitHub when that happens.

Read the contributing guidelines for more information about how to contribute. You can find a link to it in the README.md file.

**Comment by theScrabi** [comment]
@xlinulx of course, that's the downside of a scraper. It will not work forever, and if no one ever cares about this project anymore NewPipe will expire. But since there is an active community, and since I use it my self, a complete "Fallout" will not happen, or it wouldn't least for long.

You may have experienced some smaller issues, and it's true NewPipe does not do its jop 100% perfect. But for that reason I've designed the whole App as dynamic as possible, so it can handle the lack of information. Also I've add an bug report feature which (should) lead to more frequent updates. At the moment I just couldn't find time to care about them. But I also may have to go away from "single man development".

I may need a def team but at the moment I have almost no time to coordinate this. Please wait until my next semester brakes, than I will try to announce some more developer/maintainer, in order to keep the project running even if I'm not there.

`How can I contribute into ensuring that the extractor works?`
You can always send pull requests. However for the future I want to announce some more maintainer/developer, but I need to ensure they are reliable.

**Comment by timofonic** [comment]
When you semester brakes? :D

**Comment by theScrabi** [comment]
Sorry these are my perfect english skills.
You know the spare time between two semesters.

**Comment by theScrabi** [comment]
Tried to compile version 0.3 today, which was the first version ever released. This version still works nicely :)
