### ISSUE TITLE
default Country and  home Video 

### ISSUE THREAD

**Issue by rahuldeshwal21** [TeamNewPipe/NewPipe#2864]
- [x] I checked if the issue/feature exists in the latest version.
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.
____> You have A Function For Default country use the network  area. Auto change Country trending Video like I from India (Bharat) but Default country is   U.K. & U.S (Not Full Sure).
----> And Home Video based On Subscribe  
<----and local Store Videos ((optional))

**Comment by abhishekshah67** [comment]
- Auto changing country would need location permissions probably. I like this app because it does not ask for extensive permissions. 

- You can import your subscriptions from Youtube and What's new section should give you all the new videos. 

- If by "local store videos" you mean the ability to save them then you can download them in various formats already.
