### ISSUE TITLE
Video Play On The Video Page

### ISSUE THREAD

**Issue by GKid94** [TeamNewPipe/NewPipe#2930]
Make the videos so that they play on the video page not in fullscreen like on YouTube

**Comment by gkeegan** [comment]
Duplicate issue. This is also being worked on in a PR.

**Comment by GKid94** [comment]
@gkeegan PR?

**Comment by gkeegan** [comment]
Pull request. See #2907.

**Comment by GKid94** [comment]
@gkeegan Oh ok, when will it be finished

**Comment by gkeegan** [comment]
When it gets done... Asking when something will be finished is a question nobody can answer when it comes to software. If you want to use that feature now you can just use the apk shared there. You'll have to uninstall your current installation of NewPipe (don't forget to backup data) to install it.

Please close this issue, since #2882 is more relevant. Also, please be sure to check that the issues you open aren't already requested/known about by searching the open issues.

**Comment by GKid94** [comment]
Ok thx
