### ISSUE TITLE
[Feature Request/Android 10 Bug] Move the video controls at the very bottom of the screen up to prevent accidental touches by fullscreen users

### ISSUE THREAD

**Issue by Kizzy1226** [TeamNewPipe/NewPipe#2931]
Ever since the Android 10 update, whenever I'm playing a video in the background and have NewPipe open, the video controls such as the time along in the song & etc are at the very bottom of the screen. When I try and swipe up on my home screen (since I have a fullscreen phone), it will always accidently hit the bar and send my current song that I'm listening to into the middle of the song. It's getting to be a bit annoying, and I dunno why this only started with the latest Android 10 update.

Hopefully my description of the issue is accurate and understandable enough.

**Comment by snappyapple632** [comment]
Android 10 officially introduced a new method of navigation that replaces the nav bar via gestures. In this case, the problem is that trying to move the seek bar, which is at the very bottom of the screen, also activates the "back" command (swiping left/right at the bottom of the screen). The first solution that comes to my mind would be to move the seek bar away from the navigation zone, though it doesn't seem like a clean way of doing it.

**Comment by harshlele** [comment]
Also on an Android 10 device here, another problem is that when you try to move the seekbar from left to right, it also activates the Android 10 app switch gesture. 

I think moving the seekbar up is the only way to solve this problem. It's just too close to the "pill"(or whatever its called).

**Comment by B0pol** [comment]
[Here is a video of the problem](https://v.redd.it/wne9fbdri0p41/DASH_1080) (from [reddit](https://www.reddit.com/r/NewPipe/comments/fpauph/request_gestures_interact_with_the_seek_bar_too/))

**Comment by TobiGr** [comment]
Can you please tell us if the problem is solved in this APK?
[app-debug.apk.zip](https://github.com/TeamNewPipe/NewPipe/files/4623840/app-debug.apk.zip)
