### ISSUE TITLE
Projects to keep track of similar issues

### ISSUE THREAD

**Issue by Stypox** [TeamNewPipe/NewPipe#2937]
Some time ago (~two months) I finished labelling every issue in the NewPipe repo. Through the journey of reading every issue I collected a list of the common/important ones. Currently I have it in simple raw text, but I thought I could create a GitHub Project for every category. This would make it easier both for us and for new contributors to know which issues are important and supported by the team (*) and start working on one. Also, since many issues are really similar (i.e. both feature requests aim to solve the same need // both problems arise from the same bug) but not identical (so they cannot be considered duplicates), it would help to compare proposed solutions and find the one solving the most problems.

(*) I collected the issues that I thought as being compatible with the vision of NewPipe and that I considered having a great usefulness/effort ratio or priority/effort ratio. But since this is heavily biased on my opinion, feel free to add/suggest anything :-). Also, I could have skipped or forgotten to add some important issue, but I don't think this is a big deal since Projects are editable.

Here are the issues I collected (I didn't put any time in formatting this, since it will be far more accessible once in Projects):
<details><summary><b>Issues</b></summary><p>

Long-press menu: #437 #2198 #2354 #2368 #2383 #1907 #2510 #2583
Share menu: #1170 #1487

Yt problems: #2509 #2525 #2673 #2415 #2600 #2647 *#2674* #2680 #2683 #2750 #2754 #2765 #2766
Replace drawables/resources #1199 #1603
Auto-play video when opened #1200
Link support: #598 #621 #868 #928 #2425 #1556 #2132 #2266 #2313 #2351 #2526 https://github.com/TeamNewPipe/NewPipe/issues/621#issuecomment-521578931
More settings #735 #981 #1113 #1329 #1489 #1536 #1761 #1780 #1795 #1823 #2392 #2613 #2811
Description links: #1025 #2526
Language: #578 #1013 #1130 #1132 #1215 #1588 #2848
Exporting database: #1163 #1281 #1493 #1788
Missing SoundCloud trending?? #1228
Channel page: #2414 #1066 (missing videos) #1269
Main page tabs: #2477 #2565 #2088 #1647 #2438 #2678
Playlist #1473 #1188 #1956
Premiered videos not working: #1517
Introduction/tours #859 #1814

Popup: #1159 OREO-pip #2223 #2455 to-info #1832 #1032 embedded #1200
Background player: #1221 #1265 #1967 #1780 #1660
Main video player: #1064 #1317 #1600 #1634
Douple tap forward seek changeable #1401
Auto-select quality: #518
Refresh expired link: #938 #1265
Shuffle only first n: #875
Android TV: #1363
Play when already backgrounded continues in fullscreen: #1366
Long press enqueue paused #2611
Request audio focus on/off: #2681

Collections: #1317 #1387 #1448 #1603 #1717 #1872 #1922 #2610 #2743
More info to crash reports: #1816

Channel crashes if only one item (e.g. avatar ) could not be loaded https://github.com/TeamNewPipe/NewPipe/issues/2228
</p></details>
@TeamNewPipe/appdev @karyogamy @kapodamy @PeterHindes @jimbo1qaz @timfbfbfbfb 

Related: #2523

**Comment by B0pol** [comment]
> feel free to add/suggest anything
#2590

**Comment by TobiGr** [comment]
Thank you for the effort! That's a massive list :O
I agree that creating projects for large issue groups is useful (e.g. link support, settings, ...). But we  have issue labels which help us to group certain things, too (e.g. we have the youtube label). How should we proceed with them?
Please be aware that we should not open 15< projects because that would make it messy again.

**Comment by Stypox** [comment]
> IMO #2590 deserved to be quoted here

@B0pol I added it below, thanks ;-)
<br>

> we should not open 15< projects

@TobiGr I grouped the issues in 8 categories, so 8 projects should be ok. One of the last entries of the above list is `Collections`, i.e. issues that group a broad set of issues and propose a common solution. Since those are not "issues to be solved" but more some kind of "guidelines", I think we should open and pin an issue containing the list of collections.
Here are the 8 categories:
- Menus: #437 #2198 #2354 #2368 #2383 #1907 #2510 #2583 #1170 #1487 #1956
- Under the hood enhancements: #1199 #1603 #1816 #859 #1814 #2228 #1600
- Links: #598 #621 #868 #928 #2425 #1556 #2132 #2266 #2313 #2351 #2526 #1025 #1029 #2526
- Database: #1163 #1281 #1493 #1788
- Main page tabs: #2477 #2565 #2088 #1647 #2438 #2678
- Usability enhancements: #1473 #1188 #1832 #1032 #2223 #2455 #1200 #1265 #1967 #1660 #1064 #1317 #1634 #875 #1363 #2681 #2611
- Missing service functionality: #1517 #2414 #1269 #1815 #2251 #2590
- Settings: #735 #981 #1113 #1329 #1489 #1536 #1761 #1780 #1795 #1823 #2392 #2613 #2811 #518

**Comment by cool-student** [comment]
@Stypox I would put all the Notification bugs into one project. I'm talking about these here:
https://github.com/TeamNewPipe/NewPipe/issues/1660 https://github.com/TeamNewPipe/NewPipe/issues/2943 https://github.com/TeamNewPipe/NewPipe/issues/2845 https://github.com/TeamNewPipe/NewPipe/issues/1104 https://github.com/TeamNewPipe/NewPipe/issues/1207 https://github.com/TeamNewPipe/NewPipe/issues/2233 . 
most of these are about adding the colored notification that can be added starting with Android Lollipop and up and then some about the new Android 10 Seekbar in the media notifications with the others being minor bugs that are most likely caused by us not using a media style notification, then there's the last bug which is about improving the download notifications.
I would also like to work on that. I'm going to use https://github.com/TeamNewPipe/NewPipe/issues/1660 as the main issue for the colored notifications since it seems to have the most useful information.

**Comment by TobiGr** [comment]
@Stypox's categories plus a notification category look good to me 👍 

> The projects I will be creating contain only important issues, while labels cover every issue (e.g. a bug observed by only one user would be labelled, but not inserted in any project)

@Stypox sounds good.

**Comment by Stypox** [comment]
> Btw. I try to open milestones for further releases to help us focusing on a small number of PRs to be reviewed to speed up release cycles.

Yeah, it helped recently, thank you :-)

**Comment by Stypox** [comment]
Done, thank you :-D

**Comment by TobiGr** [comment]
Thank you :)

**Comment by fightthepower** [comment]
not a dev, can I also request https://github.com/TeamNewPipe/NewPipe/issues/2256 for  **Under the hood enhancements**.

**Comment by Stypox** [comment]
@fightthepower that's not really under the hood ;-)
I added it to missing service functionality
