### ISSUE TITLE
Player in the notification do not vanish if the app is closed

### ISSUE THREAD

**Issue by fedthedual** [TeamNewPipe/NewPipe#2976]
Dear new pipe team

Thanks for the update and the great work so far.

Regarding the app, it seems that I cannot close the app via the player notification. Once I touch the cross, to close the app, the app closes, the notification vanish and comes back right away. The app is closed and pushing play do nothing. 

Happy to help if necessary.

**Comment by cool-student** [comment]
which Android / Newpipe version are you using ?

**Comment by fedthedual** [comment]
Sorry , should have be more precise. I use the 0.18.1. the latest one. I hope it helps

**Comment by cool-student** [comment]
It would be good to have your android version as well.
If the error still happens could you use this app: https://play.google.com/store/apps/details?id=scd.lcex&hl=en_US (or any logcat app really) and then on the sidebar select per-app logcat then try to trigger the error in newpipe then go back to the logcat app and make a screenshot of the last few pages so that we can see what the error might be.

**Comment by opusforlife2** [comment]
@fedthedual Can you try the apk in #3178?
