### ISSUE TITLE
Subscriptions and saved playlist swapped

### ISSUE THREAD

**Issue by milklineep** [TeamNewPipe/NewPipe#2995]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

In the latest 0.18.2 hotfix, the "subscriptions" and "saved playlist" tabs are swapped atound: the subscription tab has the name and icon of the playlists tab and vice versa. See screenshots.
I think that the contents got swapped as I remember having the subscriptions list directly on the left of the subscription feed for easier access in 0.18.0. I think this was also a bug in 0.18.1 RC1 but I don't have enough space to install it again.

![20200124_133439](https://user-images.githubusercontent.com/28508187/73070200-06f35d00-3eb0-11ea-9e21-99d8458afa8b.jpg)
![20200124_133552](https://user-images.githubusercontent.com/28508187/73070211-0fe42e80-3eb0-11ea-8f33-622f4bc3e401.jpg)

**Comment by Stypox** [comment]
This might be related to #2871. @atpamat could you take a look into it?

**Comment by B0pol** [comment]
I don't have this issue but I might know why
#2871 let us custom main page tabs.

How I have to reproduce (works everytime):
1. Custom your main page, for example put subscriptions in the first page.
2. Export your data
3. Uninstall your app
4. Install NewPipe again
5. Look at main page. You have default look
6. Import your data
7. Go back to the main page, you will see the wrong tab displayed.

If you wanna reproduce again, you can skip steps 1 and 2 if you already have a backup file with tabs customised 

Workaround: just reload the app once and it will never happen again (unless you uninstall and reinstall)
I guess you were on F-Droid, uninstalled because of different signatures, and downloaded the build from Github?

**Comment by atpamat** [comment]
I don't think it's related to #2871 as the issue persists after I reversed the commit.

Also it's enough to clear storage instead of reinstalling the app while reproducing.

**Comment by milklineep** [comment]
That is correct, I had to delete & reinstall because of signatures. I
already had an export from this morning because I was testing the 0.18.1
RC1 for the video decoding bug. Indeed, force-stopping the app and starting
it again fixes the issue. So this must be a restore bug.

Le vendredi 24 janvier 2020, Paul <notifications@github.com> a écrit :
> I don't think it's related to #2871 as the issue persists after I
reversed the commit.
>
> Also it's enough to clear storage instead of reinstalling the app while
reproducing.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci6.googleusercontent.com/proxy/oDRQt2Epy9w5Pu9w-Oqy7vVt2wavJQYZQZGfDEwWtekB4m9HNH2VqL2vIRJQtLkaDscSSnIlpkb5oTaYlcvcz7shK3lI5BqkC9V8arj9DSeEVS4gAqwsmKKO6G0Vl92uoQxCT_Tztx5ivD0v8g3E69APN8PFjT8pJc_73VMPASRXpHeZT_kEJU0PU32I00USXpAwoAGu2Mva1ss2Qk_fYsOqXO68TB7DcjxZ4-ioaw=s0-d-e1-ft#https://github.com/notifications/beacon/AGZQAG7NYN5PI4GXXG2FFDTQ7NLLPA5CNFSM4KLFU732YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEJ4EABY.gif>

**Comment by Stypox** [comment]
From the reproduction steps explained by @B0pol it seems like #3312 is duplicate
