### ISSUE TITLE
FireTV wonky aspect ratio: far too wide

### ISSUE THREAD

**Issue by ChairmanMkay** [TeamNewPipe/NewPipe#3015]
Of the functions I have tested the most problematic is emailing a crash report. There is no email client available. I'm researching a side load option. Popup video always crashes on my 4k stick.  I am using a USB ethernet bridge for throughput.

I am able to navigate with fire remote.

I had hoped to watch (skim) 8 daily hours of senate trial video. After a frustrating 9 minutes of searching the video does play full screen but the aspect ratio is extremely wonky. It fills the screen width but the height is not commensurate. I selected 720p video.

https://github.com/TeamNewPipe/NewPipe/issues/899
Comment moved

**Comment by sorryusernameisalreadytaken** [comment]
There is no official AndroidTV support nor FireTV support.

@alexander-tx did a pr but do give DPAD support. I dont yet understand the reasons exactly why it was not possible to get the code changes into Master. I build an older version of this but sadly since some days no Videos played anymore:
https://github.com/TeamNewPipe/NewPipe/issues/1363#issuecomment-575906782

I will try to Integrate the code into the master, the next days. 

Your aspect problem fits for me into this category.

**Comment by opusforlife2** [comment]
What is the situation with this on the latest unified player apk? Can you guys try it out and see?

**Comment by TobiGr** [comment]
https://github.com/TeamNewPipe/NewPipe/files/5022321/app-debug.zip
###### please link that APK next time ;)

**Comment by opusforlife2** [comment]
@ChairmanMkay Could you test 0.20.0? Make sure you backup database of 0.19.8 in case you want to revert.
