### ISSUE TITLE
Polish white theme: make app bar text and icons white

### ISSUE THREAD

**Issue by Stypox** [TeamNewPipe/NewPipe#3042]
This is how the white theme looks like:
<img src="https://user-images.githubusercontent.com/36421898/73567740-44835780-4467-11ea-9de9-b0b009c91d9d.png" width="200"/>

As you can see text and icons in the title bar are black, even though they are on the exact same red background as in the dark theme. Black on red looks strange, so text and icons should be white, as in the Retry button

**Comment by B0pol** [comment]
Should they really be white?
Shouldn't they match the slider page (grey for icons, light dark for text)?
<img src="https://user-images.githubusercontent.com/58657617/73596876-5ffd6980-451e-11ea-96df-722b27db8ea6.png" width="200">

**Comment by IAmSSH** [comment]
Hey @Stypox ,
May I work on this bug?
I had a look at the code and I believe that only the `LightTheme` style in `styles.xml` needs to be modified to have white color instead of black.
Do mention if I am missed something. 
Thanks

**Comment by Stypox** [comment]
I don't think you can just change the color of icons in styles.xml, because some of the icons used in menus are also used in other places. So if you were to change the colors in styles.xml you would get the correct white color in menus, but an invisible icon in other places.
I think what you need to do is force the theme of every toolbar to always be the dark one, by setting the `android:theme="@style/..."` attribute in toolbar XMLs. Check out this: https://stackoverflow.com/questions/26503149/how-do-i-style-appcompat-v7-toolbar-like-theme-appcompat-light-darkactionbar#26504082

**Comment by IAmSSH** [comment]
Alright, shall I give it a try then?

**Comment by Stypox** [comment]
Yeah, go for it, thank you :-)

**Comment by IAmSSH** [comment]
I changed the theme of the toolbar to `DarkTheme` to make the toolbar white : 

![Screenshot](https://user-images.githubusercontent.com/34162350/79940682-0d2db100-8480-11ea-8fc0-67935fafb38d.png)

The icons are, however, being styled according to the ones defined in `LightTheme`. 
Shall I replace them with the ones used for `DarkTheme`?

**Comment by Stypox** [comment]
Yes

**Comment by IAmSSH** [comment]
All the changes are done. The app is working fine.
I just wanted to describe the approach I took before submitting a PR.

- Simply changing the theme of the Toolbar to `LightTheme` did not work. It resulted in some of the text in the app being unreadable.

- I had to create a new `ToolbarTheme` to apply to Toolbar. It correctly applies text color and contains all icons from the dark theme so that the icons that will be used in the toolbar (eg. share, search etc.) will be fetched from this theme.

- The tabs' icons (eg. What's Hot, Bookmarks etc) were being fetched based on the theme of the app. So, I changed the code, which was responsible for returning the resource id based on theme, to always return the id of resource of white color.

**Comment by Stypox** [comment]
Yes, the steps you have taken seem correct to me, thank you :-D

**Comment by IAmSSH** [comment]
I have made a PR. Request your review on it.
Thanks.

**Comment by ingingin** [comment]
I like the black on the red. Love it actually :p

**Comment by Stypox** [comment]
@ingingin ok but... the color should stay the same indelendently of theme changes, that's what material guidelines say. And white is the default color, so we will keep that for every menu in every theme

**Comment by ingingin** [comment]
Sound good :)

**Comment by KLL535** [comment]
I still haven't figured out what to do to remove the red color in the top toolbar (where the clock is). Changing the theme doesn't help.
