### ISSUE TITLE
Background Player stuck in Notification Bar

### ISSUE THREAD

**Issue by pliskin7** [TeamNewPipe/NewPipe#3071]
On Android Q, (using Pixel 4 XL) if I play a video on Background, the X button will not close the notification and will randomly repop up and disappear even if I haven't used it in days.

**Comment by opusforlife2** [comment]
How far have you tested this?

After going from Oreo to Pie I've noticed that the Newpipe background notification doesn't close immediately upon tapping close, even though the audio does stop instantly. The touch area (?) of the close button has also decreased somewhat, making it difficult to tap.

If Newpipe was your last played audio app, then events such as connecting a headphone can automatically try to start such apps. If you have the ability to change tracks using the volume button, that can have this effect as well.

**Comment by cool-student** [comment]
@pliskin7 @opusforlife2 hello guys I'm currently working on improving the notifications
could you test my latest test build from here: https://github.com/TeamNewPipe/NewPipe/issues/1660#issuecomment-581321212 ?

one major flaw with the current notifications is that they are being recreated too often which can lead to all kind of issues I fixed this and some other issues in my new notification implementation however I cannot promise that this issue in particular is solved yet since I haven't changed anything related to the close action.

**Comment by pliskin7** [comment]
@opusforlife2 It will happen when I stopped listening to the music for awhile (days even) and it'll repop up empty, not showing the last video I was playing. The close button looks fine, and highlights when I press it, but will not make the notification disappear.

@cool-student, Sure thing. I will be happy to test it out. No worries if the issues isn't fixed just yet, I know that you guys are doing a lot of work and I appreciate this app that you guys have put together. I will check it out and come back in a couple of days to see what I notice.

Thanks for your hard work.

**Comment by opusforlife2** [comment]
@pliskin7 That is exactly what happens. If you connect a headphone/use volume long press and Newpipe was your last played media app, then an empty notification will show up. The title is "Unknown", isn't it? If your music app is the last media app, a song would start playing instead.

If your close button doesn't close your notification even after several seconds, then that's something different from what I experience. Can't help you there.

@cool-student I'd be happy to test it if I can install it side by side with the official app. Is that the case?

Regarding the close action, I'm sure this is not a Newpipe issue. This happens to all apps that create notifications on my phone. The notification stays on for a few seconds, minimum, even if its task is done. In Oreo (LOS 15.1) a notification could appear and disappear within a second, not giving me enough time to even see which app it came from. So this could be a security feature so that the user can know what is going on (never heard of it, though) or it could be a bug in my ROM (LOS 16). I see this as a positive change, even if it turns out to be a bug.

**Comment by B0pol** [comment]
Same here. Audio automatically stops, but notification stays few seconds later.

But as you mentioned @opusforlife2 , I think this is not a NewPipe bug: I'm also on Lineage 15.1 (well actually /e/ OS but it's based on LOS15.1), and also I have the exact same behavior on Spotify.

**Comment by Stypox** [comment]
@opusforlife2 you can install it alongside the official app since it is a debug build

**Comment by opusforlife2** [comment]
@Stypox Is it possible to install only one debug build at a time or can several exist side by side?

@cool-student After playing a background audio, I immediately felt the jarring lack of forward and rewind buttons and progress bar. I'm on Pie. Is it necessary to remove them?

**Comment by Stypox** [comment]
@opusforlife2 unfortunately only one debug build at a time can be installed (the difference is just in the package name: in debug builds a .debug is added)

**Comment by soshial** [comment]
I also had the problem with notification not closing fast enough in v18.3.
