### ISSUE TITLE
Add option to reduce thumbnail resolution

### ISSUE THREAD

**Issue by AlbahrawyTiger** [TeamNewPipe/NewPipe#3121]
It consumes a lot of data to download the video and thumbnails page. Please put an option to reduce the quality of the thumbnails

**Comment by gkeegan** [comment]
Please change issue name to "Add option to reduce thumbnail resolution" or similar. I'm not entirely sure that doing this is possible, since I don't know if YouTube provides different sizes. In the meantime, you can try disabling loading thumbnails entirely.

**Comment by Stypox** [comment]
@gkeegan YouTube provides different sizes, but the extractor only extracts the one with the highest resolution

**Comment by TobiGr** [comment]
I though about this while working on the extraction of the new YouTube version, too. I think we should extract all thumbnails and let the client decide which thumbnail to load.

**Comment by wb9688** [comment]
@TobiGr: I was just about to reply the same thing.

**Comment by B0pol** [comment]
### about peertube extractor

[This line](https://github.com/TeamNewPipe/NewPipeExtractor/blob/4bc5b8d33f4cf52925a02184870225fac490001a/extractor/src/main/java/org/schabi/newpipe/extractor/services/peertube/extractors/PeertubeStreamExtractor.java#L62) give the highest quality.

For lower quality, use ``thumbnailPath`` instead.
Also, [on this line](https://github.com/TeamNewPipe/NewPipeExtractor/blob/4bc5b8d33f4cf52925a02184870225fac490001a/extractor/src/main/java/org/schabi/newpipe/extractor/services/peertube/extractors/PeertubeStreamInfoItemExtractor.java#L30), it don't give the max resolution. ``previewPath`` gives higher resolution.

But, list items don't need high quality, it's already showing fine, at least on mobile. 
I changed only for video detail, because it's really visible: [low quality](https://user-images.githubusercontent.com/58657617/72723546-ce364980-3b78-11ea-9a97-bf478b7e2e03.png) | [high quality](https://user-images.githubusercontent.com/58657617/72723582-e1e1b000-3b78-11ea-82ed-04a1ff290c25.png).

### Idea
I think we should change [Load thumbnails setting](https://github.com/TeamNewPipe/NewPipe/blob/c430a0f9e2cdd2d6e7b4cdc02004132c92f59d3a/app/src/main/res/xml/content_settings.xml#L54,L59), from a ON/OFF switch, to a list:
+ max resolution: it would typically be used for TV, tablets, or other big screen
+ default: optimized resolution: it would get the max resolution for the things that need it, for example the thumbnail in video detail page would be max res, but in list it wouldn't be max res. typically be used by phones, and set default setting.
+ lowest resolution
+ thumbnails disabled

**Comment by AlbahrawyAlalimi** [comment]
Not only is the problem with thumbnails, but when thumbnails are disabled, a lot of data is still used to load the video page itself.

**Comment by AlbahrawyAlalimi** [comment]
Not only is the problem with thumbnails, but when thumbnails are disabled, a lot of data is still used to load the video page itself

**Comment by Stypox** [comment]
That can't be reduced, it's just the page size provided by YouTube, so we can't change it...

**Comment by B0pol** [comment]
> That can't be reduced, it's just the page size provided by YouTube, so we can't change it...

In fact, it can with pbj=1 parameter. See TeamNewPipe/NewPipeExtractor#262.

**Comment by wb9688** [comment]
With pbj=1, pages will be more like 20-30 KB gzipped.

**Comment by Stypox** [comment]
> In fact, it can with pbj=1 parameter. See TeamNewPipe/NewPipeExtractor#261 (comment) and TeamNewPipe/NewPipeExtractor#262.

Yeah, now I've seen @wb9688's improvements, 6 days ago I didn't ;-)
Also, this issue was probably about pre-0.18.5.
@AlbahrawyAlalimi fixed in next version

**Comment by wb9688** [comment]
@Stypox: The thumbnail stuff isn't fixed in the next version though. I'll fix that on the NewPipeExtractor-side soon™ though

**Comment by AlbahrawyAlalimi** [comment]
Version 0.18.7 and still takes more than 1MB to download the video page with thumbnails disabled!
