### ISSUE TITLE
Rounding of number of subscribers

### ISSUE THREAD

**Issue by bovergaauw** [TeamNewPipe/NewPipe#3152]
For channels with over a million subscribers, the number of subscribers is rounded down to an integer since v0.18.5, previous versions showed at least tenths of a million.

**Comment by wb9688** [comment]
Could confirm this happens in NewPipe. I'll look into this tomorrow.

**Comment by wb9688** [comment]
NewPipeExtractor gets the correct amount, it's just NewPipe that rounds it.

Thanks @B0pol

**Comment by B0pol** [comment]
In fact it happens since 0.18.4, we switched to rounding because youtube gives us rounded number, so showing exact number is wrong.
The problem is [Localization.shortCount()](https://github.com/TeamNewPipe/NewPipe/blob/ab4e1819c1d08bf53c6c3ca0e820a5e5ba4774af/app/src/main/java/org/schabi/newpipe/util/Localization.java#L148) doesn't give decimals.

How to reproduce:
[5 minutes craft](https://www.youtube.com/channel/UC295-Dw_tDNtZXFeAPAW6Aw), 64.7M subs, on NewPipe 64M

**Comment by B0pol** [comment]
Should we round to 1 or 2 (or even 3?) decimals @TobiGr ?
