### ISSUE TITLE
Can't download or play newpipe

### ISSUE THREAD

**Issue by tbanda75** [TeamNewPipe/NewPipe#3232]
- [ ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

**Comment by Stypox** [comment]
I don't understand what you mean. Could you provide more information?

**Comment by LWKoehler** [comment]
Same here... Newpipe used to work perfect on this tablet. Installed update 18.6, now nothing but the banner accross the top with a black screen with the "busy working" continuously goinground and round below. Nothing ever loads. Samsung Galaxy Tab  S2

**Comment by wb9688** [comment]
@LWKoehler: I think I saw a report of that elsewhere as well, iirc on some Samsung phone. Could you tell me whether v0.18.5 works? If you have NewPipe from F-Droid, you'll have to uninstall it first (make a back-up of your DB first) and then install v0.18.5 from https://github.com/TeamNewPipe/NewPipe/releases. I'd also like to know whether the APK from #3201 works, which would install alongside your already installed NewPipe, as then it's already fixed in the next release.

**Comment by LWKoehler** [comment]
@wb9688 Hi, sorry for such the delay. So I tried;

18.5 - downloaded and ran package installer, installer ran and ran, at the 1 minute mark, I backed out of the installer and checked my app drawer, nothing thre,  ran insaller again, said yes to the "update"(although not anupdate obviously, but it must have registered something to think it was an "update") installer finished in normal amount of time.  No improvement from 18.6.

18.4 - Same as 18.5 above.

18.3 - First version to install in normal (5-10 seconds) amount of time. Still no change from 18.6.

18.2, 18.1, and 18.0 -  same as 18.4 and 18.5, still not working. 

17.4- installed in normal amountof time, but still not working.

At this point, I decided to jump to 16.2 - normal install, program working as expected.

I'm willing to try 17.3, 17.2 etc, down to this working 16.2 version if it would be helpful, and/or run along side any other package you might want.

Thank you for your time,

Lance

**Comment by wb9688** [comment]
>Nothing ever loads.

@LWKoehler: Could you please be more clear? What doesn't load? Trending, videos, search, channels, playlists, all of them? Do other services like PeerTube work?

Anyway, thanks a lot for testing those versions. If you confirm what exactly doesn't work, I'll make a test app so that we could know if NewPipe or NewPipeExtractor doesn't work. If that test app works, I'll want you to try all versions in-between v0.16.2 and v0.17.4.

**Comment by LWKoehler** [comment]
@wb9688 For the versions that do not work, nothing works, this includes; trending, subscriptions, whats new, bookmarked playlists, downloads, history, search, and channels. Nothing even loads, screen stays blank with busy/working gif going round and round. 

I'll be happy to test anything you would like.

Samsung SM-T713
Android 7.0 with Android Security Patch Level July 1, 2019
Kernel Version 3.10.84-14953299

**Comment by wb9688** [comment]
@LWKoehler: Could you tell me whether [this APK](https://github.com/TeamNewPipe/NewPipe/files/4345024/app-debug.apk.zip) shows a list of the titles of trending videos? You don't need to uninstall anything as it's a separate app called "CrappyPipe" that's not really useful.

**Comment by LWKoehler** [comment]
@wb9688 Hi, yes, eventually Crappy Pipe loads, displays a bluish-purple banner across the top, then approx 30 to 45 seconds later, a left justified text list of what i assume are from videos, loads in the screen area under the banner.

**Comment by wb9688** [comment]
@LWKoehler: You mean that it looks like:

![this screenshot](https://i.ibb.co/pQWGhWd/Screenshot-20200317-215130-Crappy-Pipe.jpg)

If so, it's working, but it shouldn't take that long. And you're sure NewPipe doesn't work after waiting the same amount of time?

Could you please try all versions in-between v0.16.2 and v0.17.4? Then I could more easily find out what has changed and make some more APKs for you to test.

**Comment by LWKoehler** [comment]
@wb9688 Haha, yep, other than the size of the font, it looks exactly like that. I guess what is confusing is the fact that i have used NewPipe 2-3 times a week for at least the last 10-12 months, and as soon as the program would load, i never had to wait for the previews to load,  they would just be there. Same tablet, same WiFi connection, nothing has changed. Throughout this testing, i have continually been checking the speed of my WiFi, because that is what the lag feels like, as it is trying to load the previews. However, it has consistently been 290-300 Mbs. 

I will try those other versions and get back to you later today.

Thanks again!

**Comment by LWKoehler** [comment]
@wb9688 So, first, I am so sorry for wasting your time, I am such an idiot. I have found the issue. Adguard 2.8 is the culprit. It has never caused a problem with anything to the point of I have forgotten it was even running. With AdGuard disabled, 18.6 shows previews as fast as the program loads, which is pretty much instantaneously.  

Pretty much problem solved. However, if you want any other info or testing, just let me know.

Again, my apologies for wasting your time.

**Comment by opusforlife2** [comment]
Closing as resolved.
