### ISSUE TITLE
Doble tap open a video in popup

### ISSUE THREAD

**Issue by BruceMoustache** [TeamNewPipe/NewPipe#3256]
I don't like have to be in view page to then open a video. Instead I suggest this gesture

**Comment by angriness-sleek** [comment]
This sounds like a useful feature. I suggest you add the "Enhancement" label to your issue.

**Comment by Stypox** [comment]
@BruceMoustache @angriness-sleek something like this was already reported, I also implemented it a while ago (with background player, though). The problem is there is that double-tapping is bad practice in Android, and also that there is no agreement on which action should be taken. This is the plan, feel free to add some feedback there ;-) : #2583
