### ISSUE TITLE
Just want to say: Thank you!

### ISSUE THREAD

**Issue by Offerel** [TeamNewPipe/NewPipe#3308]
No real issue. I just want to say thank you for this wonderful piece of an app.

**Comment by dietrich-stein** [comment]
I also want to thank you for developing this app. It is very high quality. You have done some amazing work here. Thanks!

My use case is that I have a 7-year-old who enjoys a lot of benign YouTube channels that simply aren't available from the "YouTube Kids" app. I refuse to let her use the full YouTube app because there are so many toxic personalities on YT creating daily content that she ends up watching on there due to the auto-play and recommendations features.

I needed something that would allow me to disable those features and give her the subscriptions she wants without the risk of exposing her to former camgirls spewing their negativity and sarcasm out onto the world as endless reaction videos.

NewPipe was nearly the perfect solution! I simply removed the "Trending" option from the main tabs and the side-navigation and et voila. My daughter loves it!
