### ISSUE TITLE
ReCaptcha Issue

### ISSUE THREAD

**Issue by hassanseoul123** [TeamNewPipe/NewPipe#3338]
Hi, thanks for this amazing app. I want to ask that is there any way to turn off the reCaptcha which appears every time I open up NewPipe and start the video. Do you use youtube Api? If yes then I think if there is an option to use custom api, it would resolve the issue. Sorry if what I'm saying doesn't make any sense.😬

**Comment by hassanseoul123** [comment]
sorry I didn't want to label it as bug. Now

**Comment by Stypox** [comment]
Check #3272 and #3310
We do not use any Youtube API, and ReCaptchas should be solvable, though I have no idea why sometimes we fail to get cookies.

**Comment by hassanseoul123** [comment]
ok thabks @Stypox ❤️

**Comment by tusch001** [comment]
Coming from issue #3272
(Version 19.2 on Stock Android 6.0.1)
When using Orbot (not as VPN but Newpipe data is sent to orbot in my firewall) I have the also problems while updating the channels. I get repeated recaptchas with the picture shown in issue #3272. My guess is it is connected the specified URL (https://www.youtube.com/results?search_query=test&pbj=1). Is it necessary to use search_query=test&pbj=1 while searching for channeld? Because this could trigger youtube when too many people update / open the app within a short time (esp. when using the Tor network or certain vpn providers). Maybe this id also the reason for issue #3310? 

(Sorry for double post with #3272. I saw the closed flag too late)
