### ISSUE TITLE
Poor connectivity hangs UI

### ISSUE THREAD

**Issue by MilkManzJourDaddy** [TeamNewPipe/NewPipe#3376]
Slow internet hangs the UI with no way to pause, other than to defocus the app' to otherwise check connectivity, or rewind slightlyv back to buffered content and hit pause.  It would be great to be able to pause, however, and hope for buffering to catch up with***OUT*** having the queue evaporate, which is frustrating if you've strung together a long cue but don't want a semipermanent playlist, but just cover some recent content.

**Comment by opusforlife2** [comment]
@Stypox Hasn't this been fixed by your PR? Queued streams remain where they are now.

**Comment by MilkManzJourDaddy** [comment]
No, read it **again**, the **entire** issue, and not just the part of the title where you stopped reading.  **ONLY** the dequeueing part is solved.

**Comment by MilkManzJourDaddy** [comment]
If, for testing this, you do not have an ISP/WiFi slow network in which packets may also be delayed, throttled or deprioritized, et cetera, then connect via a router with QoS, et cetera, and slow the queueing that way.  🤷‍♂️

**Comment by vertigo220** [comment]
Just ran into this issue and was disappointed to find it suffers from this problem just like YouTube and many other players. You can't pause while buffering, so if the internet is really slow or bogged down, playback will freeze for a few to several seconds to buffer, then play for a split second before freezing again, and continue doing so throughout the entire video. Meanwhile, if the user doesn't want to deal with the constant freeze/play/freeze/play and wants to just pause it and let it buffer (which, I assume, is what most people would do), they can't, because it can only be paused during the very brief moments of playback, which are hard to catch, especially since the control overlay goes away after a few seconds even when repeatedly pressing the pause button trying to catch it.

If you want to simulate it, you may not even need a slow connection. Just bog it down with a heavy download that saturates your bandwidth then try playing a video.

Another issue that's related to this is that when the connection is so slow or bogged down that it causes this problem, it can also cause playback to _start_ when it's not wanted. I just tried playing a video and, after several seconds of NewPipe not even opening after selecting the pop-up player option due to the connection being so slow, I finally gave up and turned off the screen of my tablet, only to have it start playing half a minute later. So there are a few problems here: NewPipe should open immediately and show a loading graphic instead of waiting for the video to load before it opens, it should allow the playback to be paused when the video isn't playing, so a video can be opened then paused when NewPipe loads, before the video even starts playing, and, perhaps most importantly, it shouldn't start playback when the display is off.

**Comment by MD77MD** [comment]
I'm having this issue too!

**Comment by opusforlife2** [comment]
> You can't pause while buffering

We should definitely be able to pause while buffering. It's just common sense. The play/pause icon shouldn't also act as a buffering indicator. It should just be play/pause. The buffering indicator can just show up below it whenever it needs to. (Or a better place that anyone else can suggest.)

**Comment by MD77MD** [comment]
@opusforlife2 thank you for understanding our pain😔. moreover as you said, it definitely needs to show that it's still buffering after pausing... otherwise people would think pausing stops video
buffering as well, which defeats the purpose of the whole thing.

**Comment by Trojgarb** [comment]
The app (21.5, 21.6) very often hangs when starting playing a video on WiFi, making a longer pause and trying to resume the play on data plan (4G, weak signal). The only way of resume is to restart the app, which is quite cumbersome - first have to tap the screen many times to have pop-up saying the app is not responding, then close it (it's impossible to close it earlier from notification panel) and restart it twice (at first the app crashes immediately). In such cases the app doesn't remember last position played and resumes from earlier saved position, sometimes few minutes, sometimes over 10 minutes ago. The situation also happens when switching to background while playing. It's a very frustrating bug.

**Comment by Stypox** [comment]
> You can't pause while buffering

This was solved in one of the latest versions
