### ISSUE TITLE
Parsing CSS on android

### ISSUE THREAD

**Issue by theScrabi** [TeamNewPipe/NewPipe#338]
Hello,

can someone help me, I'm trying to parse CSS in NewPipe using [this](http://cssparser.sourceforge.net/) library. Is this a good idea? For now I'm using Regex, but I hate Regex.

Importing that lib via maven also impies I have org.w3c.dom.css.* available, but that is not available on android. I've tried to make it available using [this package](https://mvnrepository.com/artifact/xml-apis/xml-apis). But that turned out to be an even worse idea.

**Comment by icasdri** [comment]
IMO, I think it would be a good idea to move to a proper CSS parser, instead of regex, which inherently would be brittle and difficult to work with/maintain.

I do not understand the issue you are having, however. Does the library depend on an `org.w3c.dom.css` being available, and Maven is not properly resolving/downloading the dependency? Maybe `org.w3c.dom.css` is provided by the [SAC](http://www.w3.org/Style/CSS/SAC/) mentioned on the library project's page?

**Comment by icasdri** [comment]
I was able to get the example code on CSS Parser library's website with the following Maven dependencies. 

```xml
<dependency>
    <groupId>org.w3c.css</groupId>
    <artifactId>sac</artifactId>
    <version>1.3</version>
</dependency>
<dependency>
    <groupId>net.sourceforge.cssparser</groupId>
    <artifactId>cssparser</artifactId>
    <version>0.9.20</version>
</dependency>
```

See full example here: https://gist.github.com/icasdri/3bbba90ea9c57b8426f7483fcbba95da

**Comment by icasdri** [comment]
After some experimenting, it seems CSSParser may be a little too inflexible for NewPipe's purposes (which I presume is fetching specific values out of rules). For instance, it seems the most granular level is a "rule", with that being something like `h1 { background: white; margin: 12px }`. And that's as far as it gets. Maybe something like https://github.com/phax/ph-css would be better?

**Comment by theScrabi** [comment]
All right use regex workaround for now :P
