### ISSUE TITLE
Some video takes exceptionally long to load (Possibly cannot load)

### ISSUE THREAD

**Issue by chantisnake** [TeamNewPipe/NewPipe#3497]
### Version

- 0.19.2

### Steps to reproduce the bug

For These videos (video ID):
v=8l0v_vXKJWk
v=fPll9RVxkDo
1. Open these video's info page in newpipe
2. Click the play button

### Expected behavior

Typical video would take less than 2 second to load

### Actual behaviour

I have waited more than several minutes, and nothing has loaded, including the watched time and the total time at the bottom timeline.

### Screenshots/Screen recordings

![ScreenRecord-2020-04-27-11-37-04](https://user-images.githubusercontent.com/10100995/80391587-74db6600-889d-11ea-9b51-25f5af4787c1.gif)

**Comment by androidSwDev099** [comment]
@chantisnake,
The reason for this issue is the the video is not available in the default resolution of 1080p WebM which is specified in your NewPipe settings. The only way I know of to find a valid resolution is to click Download and see which resolutions have a file size next to them, then go back and change the resolution in the top left corner of video info screen to a valid choice and it should play now. 

Apparently this problem has been around for quite some time. If it doesn't get fixed, I hope at least an error message can be displayed to the effect that the default resolution is not available for this video so we have half an idea of what's going on. 

See #2415, which I believe is intented to address this issue. Search for the word resolution if you can't/don't want to read the entire PR.

**Comment by chantisnake** [comment]
Thank you so much for your speedy reply, I really appreciate it.
I think this is the issue, and when I switched the format to MPEG-4, the video actually loads successfully.

Thank you again.
