### ISSUE TITLE
Add “watch later”

### ISSUE THREAD

**Issue by MuntashirAkon** [TeamNewPipe/NewPipe#3508]
#### Describe the feature you want

This should be obvious as YT has this already. “Watch Later” should be available in the Menu that comes when long clicking/tapping a video. This should also appear in the regular playlist section as well.

#### Is your feature request related to a problem?

No.

#### Additional context

The current alternative is to create a ”watch later“ playlist manually as a playlist and then add the desired video to the playlist.

#### How will you/everyone benefit from this feature?

Currently, there's no default “watch later” where we can save all the videos that we may want to watch in future. Even if we add an “watch later” playlist manually in the playlist section, it takes two clicks/taps to add it to go to that playlist and another to add it, which isn't *convenient*. It should be done within two clicks/taps.

**Comment by Stypox** [comment]
The solution we chose for this was to add a button to local playlists to remove all of the watched videos. This change will be in the next update, i.e. 0.19.3

**Comment by MuntashirAkon** [comment]
> The solution we chose for this was to add a button to local playlists to remove all of the watched videos. This change will be in the next update, i.e. 0.19.3

How's that solved this? I don't understand.

**Comment by Stypox** [comment]
We decided not to add a "watch later" playlist, but rather to add the option to remove watched videos in a playlist by pressing a button

**Comment by MuntashirAkon** [comment]
> We decided not to add a "watch later" playlist, but rather to add the option to remove watched videos in a playlist by pressing a button. This way one can create a playlist that behaves like watch later.

These are not the same. At least not how the YouTube's watch later works.

**Comment by Stypox** [comment]
I know, but it achieves the same, and also provides more flexibility. See the discussion in #3095

**Comment by MuntashirAkon** [comment]
> I know, but it achieves the same, and also provides more flexibility. See the discussion in #3095

Ability to remove watched videos from a playlist is probably a good feature but I don't know to whom though since non-special playlists are made to catalog our preferences into lists rather than just storing unwatched videos there. It is also not something quite relevant to what I mentioned here. After all, in watch later (or watchlist), you may still want to keep videos there after you've watched it. Also, in this issue, I talked about the accessibility of such playlist rather than whether it's possible to remove watched videos. However, my arguments are irrelevant if you've certain roadmap or something.

Also, I don't know how the linked discussion is relevant here.

**Comment by Stypox** [comment]
Then I don't see the purpose of a special watch later playlist, when playlists already exist

**Comment by besweeet** [comment]
> Then I don't see the purpose of a special watch later playlist, when playlists already exist

The point is that YouTube makes adding videos to watch later faster and more convenient than a standard playlist.

I'll be sticking with PowerTube due to this missing feature.

**Comment by christopher-wilson** [comment]
To help explain the request better so that it can be revisited.

Right now, there isn't a good way to queue videos for later. It takes multiple presses and a custom "Watch Later" list, when it should be a one-press action. 

One can think of it like a music player:
1. You have an arbitrary number of playlists for whatever purpose
2. You have a queue of what you want to listen soon

This is suggestion is for #2.

It is also important to note, that essentially every media player, from YouTube to Spotify to Plex, have the ability to add videos to a persistent queue.

**Comment by WagnerGMD** [comment]
Apparently I'm not only to thing about this feature :
- 1 Create 3 lists such as : "Watch Later" and "Keep 1 view" and "Watch again"
- 2 In the case we had view the video just once, you move it from "Watch Later" to the list "Keep 1 view"
- 3 Another case we had view the video several times, you move it from "Watch Later" to the list "Watch again"
- 4 Don't forget the people need sometimes to think about the name for each playlist. It we be the purpose for 3rd list until they find a good name.

Now we are in 2024, could you clarify your opinion @opusforlife2 about this example ? 
Because it's clear the function "Mark as watched" could be improve and a long time has past (here we count 4 years) perhaps you have another vision (or change your mind).

PS : Indeed I had try a view times to find something with the search.
From my point of view, there is one match at least (and I'm agreed create another one is useless (over the last decade, it was very boring on several forums because at the end, the conclusion remain : it's easier (good enough) to follow just the first one))

**Comment by MFlisar** [comment]
Another issue is following: with the current solution it is impossible to have partly watched videos inside the "watch later" list, because if it is watched partly only you can't remove if from the feed.

I do hear podcasts a lot and those are long, some I hear when driving, some only while doing cardio - so I often have a few partly watched podcasts in my feed where they actually do not belong to...

**Comment by WagnerGMD** [comment]
@opusforlife2  Sorry I made a confusion with [the 1st post](https://github.com/TeamNewPipe/NewPipe/issues/3508#issuecomment-622848562).

> We decided not to add a "watch later" playlist [...]

In fact I was referring to [this decision](https://github.com/TeamNewPipe/NewPipe/issues/3508#issuecomment-627836249) which was write by @Stypox a fews years ago (2020).

Somebody is aware about a plan about to add the function search inside the history ? That would help a lot to find something you had almost totally forget.
Because after a little look, the result has give 10 pages (that's too much).

**Comment by MFlisar** [comment]
> What are you talking about? This option exists right alongside the one to remove fully watched videos.

In do hide all seen videos from my feed. This means, I can't move a 50% watched video from my feed without marking it as seen. A really working "watch it later" solution would allow me to also enqueue partially watched videos inside the list AND at the same time, remove this partly watched video from my feed without being forced to mark it as watched which does clear my watch progress what I do not want...

What I would like to achive is following:

* watch multiple videos
* move those partly watched videos into my "watch it later" list
* keep the progress on all of those videos
* AND remove those videos from the feed (because I have put them on my "watch it later" list) but without marking it as seen, because this would make my "watch it later" list a "already watched"

If I accept that I can only remove videos from my feed that are marked as watched, I still have a problem: as soon as I start the video from my "watch it later" list, it pops up in my feed again if I do not watch it fully because then it's not marked as watched again and this has the side effect that it pops up in the feed again...

Hope that explains the issues with the manually "watch it later" list.

**Comment by MFlisar** [comment]
I made a full feature request that suggests a simple solution for my use case (https://github.com/TeamNewPipe/NewPipe/issues/11450)

_To make it easier here, I simply ask a quesiton that shows the main problem I see:_

I want to have unwatched / partly watched videos in a "watch it later" list (actually you don't watch watched videos later...) and at the same time, I want all those videos to be removed from the feed. As far as I can see, there is no work around for this, because to remove the videos from the main feed I have to mark them as watched (which does delete the watch progress of course)
