### ISSUE TITLE
Android TV os oreo: Pop up Permission required 

### ISSUE THREAD

**Issue by bumjrah** [TeamNewPipe/NewPipe#3531]
Asks for pop up Permission when switching to background mode. 

In the system settings, only storage dialog is available. Other apps that make use of pop-up also do not have the appear on top of other apps settings. As this feature seems baked in to the apps rather than a setting toggle-able by the user.

Would be happy to provide any further info if required. 

Side note: Big thank you to the devs for making this wonderful app available on Android TV!

**Comment by Alexander--** [comment]
The app does try to ask for permission via the standard intent.

If you don't see the dialog, your OS does not support it (seems like it is no longer included by default in recent Android TV versions).

**Comment by bumjrah** [comment]
Okay. Just for clarification. PIP floating video mode is what has missing implementation as at now. In the menu I have setup settings for newpipe to continue playing in pip mode when I press the home key. 

 The OS has support for this as mentioned above since other media apps *can make use of this function.

**Comment by peat80** [comment]
Have a similiar issue on fire tv:

(Fire os 6 is not based on oreo but nougat atm i think.)
There is no os setting available in fire os to allow pip permission for apps. Pressing Pop-Up in NewPipe only shows a toast "This permission is needed to open in popup mode" for a few seconds but there is no way to set the required permission. 🤔

Anybody knows if the permission could be granted via adb? And if yes what would be the command for this?

**Comment by TobiGr** [comment]
We though about removing the buttons to play a video in pop-up mode, because we could not think of a use-case and good implementation with a dpad.
However, #2907 will bring a new player UX [currently not working well on TV. Help with reporting and fixing bugs is welcome :) ].So we might keep the player and will look for a solution later.

**Comment by peat80** [comment]
I agree with that.
One want it to function just because its there. 🤭

I think it would be a good idea to remove / hide pop-up-mode and also gestures & touch related settings if a device without touch controls (android-tv / fire-tv) is detected. 🤔

The unified player ui is a great improvement (but currently only for touch devices).
Hopefully some developers who care for android-tv could be found to make it non-touch friendly too. 😎

**Comment by avently** [comment]
Since yesterday some changes were made for TV support and it's good now.

**Comment by peat80** [comment]
Thanks for all your efforts avently. D-pad support is good now in the latest test apk. 😎👌

Minimised player is not useable with dpad, but that should be no show stopper and could probably handled in the future.

NewPipe 0.20 will be a great release i believe.
Looking foward to this. 😀👍

**Comment by opusforlife2** [comment]
So... this is fixed?

**Comment by Stypox** [comment]
No, I think the popup player has not yet been hidden on android TVs where it is unusable

**Comment by peat80** [comment]
Since the upcoming 0.20 release (which already works great on android tv) will play videos in windowed mode alongside comments and next videos it could be a good idea to replace the (not working and useless) popup-button with an fullscreen-button when executed on android tv? This way one could quickly switch between background play and fullscreen video. 🤔👌

**Comment by Alexander--** [comment]
> Could it be a good idea to replace the (not working and useless) popup-button with an fullscreen-button when executed on android tv?

I would prefer to just fix the popup mode: let user move it around at resize at will. The popup itself can't intercept key presses, but it should be possible to create a special semi-transparent Activity for customizing it's bounds by remote.

**Comment by peat80** [comment]
If fixable why not. But it would only make sense when it also keeps playing while changing apps. If it only could be made working inside NewPipe it would not make sense with unified player arriving soon. 🤔
Just my opinion ofc. 🤷🏻‍♂️😃

**Comment by opusforlife2** [comment]
Is there really a use for having the popup player on Android TV?

**Comment by bumjrah** [comment]
Not

**Comment by pgnd** [comment]
>> Is there really a use for having the popup player on Android TV?
> Not
@tankaras

NewPipe on Amazon Firestick/TW works.  But player's not full screen.  On attempt to scale player to full screen, pop-up permission request does come up.  Afacit, no option to set/toggle the perm, so no full screen usage.

Is this^ still the relevant issue? Or has discuss/solution gone elsewhere in the issue queue ?
(haven't found it yet ...)

thx o/

**Comment by Stypox** [comment]
It went to #9023
