### ISSUE TITLE
[SUGGESTION] Comparison/collaboration with SmartYouTubeTV ?

### ISSUE THREAD

**Issue by forart** [TeamNewPipe/NewPipe#3532]
Hi there, someone at [e forums](https://e.foundation/) pointed me to your interesting app.

Some questions: 
1. how mutch it have in common with [SmartYouTubeTV](https://github.com/yuliskov/SmartYouTubeTV) or, if nothing, what can be shared with ?
2. do you plan to add more "author-friendly" video services (such as Vimeo that supports ALL CC licenses) ?

Thanks for your work and hope that inspires !

**Comment by Stypox** [comment]
After taking a brief look at it, it seems like it uses the YouTube API to fetch videos, since it provides a login (or, at least, it seems like the user is logged in in the screenshots). So it probably has no components in common with NewPipe on the extractor side.
On the other side, they also use exoplayer, and that could be a source of inspiration to solve the long-lasting HLS playing issue (not that I have ever looked much into how exoplayer works 😅)

**Comment by wb9688** [comment]
Afaik Smart YouTube TV is just a wrapper around YouTube's HTML5 TV interface

**Comment by forart** [comment]
> About 2: we have a project named NewPipeExtractor that can contain extractors for any service, so it's just a matter of having someone that is interested in Vimeo implement it

Well, seems that someone already thinked about this:
https://github.com/AdiY2j/VideoApp

**Comment by opusforlife2** [comment]
Yes or no?

**Comment by wb9688** [comment]
@opusforlife2: SmartYouTubeTV is very different technically and has different goals.
