### ISSUE TITLE
(Suggestion) Open youtube music video to background

### ISSUE THREAD

**Issue by penamerah** [TeamNewPipe/NewPipe#3535]
i thought video from youtube music open like soundcloud, when we tap on play video automatically open in background. because its just music, right? anyway, this is just a suggestion

**Comment by Stypox** [comment]
What is opened on click is video info, and from there the user can access description, uploader channel, next songs and finally download. So that intermediate step is needed (for now). A solution would be #2583, provide some feedback about it if you want to ;-)

**Comment by opusforlife2** [comment]
He probably meant tapping on the video thumbnail in the video details fragment.

Is this possible without making YT Music a separate service?

**Comment by Stypox** [comment]
Maybe there could be indications about which videos are music videos in a youtube's page code. But implementing this would be confusing for people who expect to view the video as they always do. Many music videos can be interesting to watch, so changing buttons for those videos would not be intuitive

**Comment by opusforlife2** [comment]
Actually, I don't see why a user should go to YT Music to watch videos. Youtube is the place for that. And since YT Music and YT share the same video library, they show the same video in any case.

@wb9688 I've said it before, I know, but I really think YT Music should be a separately selectable option in the service list, which should behave like SoundCloud or Bandcamp. It's kind of like an afterthought the way it is now, as a mere search filter.
