### ISSUE TITLE
Large layout not used on 7"9 tablet (Mi Pad 1)

### ISSUE THREAD

**Issue by test2a** [TeamNewPipe/NewPipe#3592]
I have an old xiaomi mi pad 1 running android 4.4.4.

Newpipe works wonderfully but the interface is for a phone, on a tablet it doesn't scale properly. Recently NP introduced basic android tv support. I am hopeful if NP allowed non tv to use that mode, the experience on tablets would be much better.

All I request is allow switching from phone mode to tv mode. Thats it.

**Comment by test2a** [comment]
maybe in future, the app checks the screen size, it could offer 10 foot user interface but i am requesting a switch intially

**Comment by B0pol** [comment]
I'm not sure it will do what you want. Do yo have a keyboard on your tablet, like this?
<img src="https://www.androidauthority.com/wp-content/uploads/2011/08/Asus-Transformer-keyboard-dock.jpg" width="400">
On some sort of controller? Otherwise it would be pretty much useless. The non-tv experience is designed for devices using touch, and tv for devices using a remote controller. There is no point of using tv newpipe experience with touch.

**Comment by B0pol** [comment]
I'm not sure it will do what you want. Do yo have a keyboard on your tablet, like this?
<img src="https://www.androidauthority.com/wp-content/uploads/2011/08/Asus-Transformer-keyboard-dock.jpg" width="400">
On some sort of controller? Otherwise it would be pretty much useless. The non-tv experience is designed for devices using touch, and tv for devices using a remote controller. There is no point of using tv newpipe experience with touch.

**Comment by test2a** [comment]
i have attached screenshots from my device below. i was looking the screenshots from https://github.com/TeamNewPipe/NewPipe/pull/2806
pull request 2806 and i do think the interface looks better suited towards wider screens. i don't know about the touch thing but that 10 foot interface imo would look so much better on a tablet. 

btw, my  [mi pad 1](https://www.gsmarena.com/xiaomi_mi_pad_7_9-6365.php) 

![Screenshot_2020-05-15-14-25-39-770_org schabi newpipe](https://user-images.githubusercontent.com/39449563/82033266-1e05c700-96ba-11ea-84eb-4a2b9f343ec9.png)
![Screenshot_2020-05-15-14-26-15-169_org schabi newpipe](https://user-images.githubusercontent.com/39449563/82033273-20682100-96ba-11ea-8c5f-59cf18761a8c.png)
![Screenshot_2020-05-15-14-34-53-213_org schabi newpipe](https://user-images.githubusercontent.com/39449563/82033278-2231e480-96ba-11ea-8819-047b421f30ab.png)
![Screenshot_2020-05-15-14-35-22-732_org schabi newpipe](https://user-images.githubusercontent.com/39449563/82033282-23fba800-96ba-11ea-885f-aeec2b758c54.png)

**Comment by justanidea** [comment]
You should try the grid mode maybe

**Comment by test2a** [comment]
ok  the grid mode is much better but it is only on search and front page. the following UI scheme of a video from the tv PR would look more suited for the screen size.
https://github.com/TeamNewPipe/NewPipe/pull/2806#issuecomment-612603444

**Comment by B0pol** [comment]
This is not about TV. This design was first designed for tablets, and is also used for TV. In fact, this design is used when NewPipe considers the device large enough to pick large layout, and it's not the case.

**Comment by opusforlife2** [comment]
@test2a How is the situation on 0.20.0?
