### ISSUE TITLE
Display which NEW videos have been added.

### ISSUE THREAD

**Issue by ghost** [TeamNewPipe/NewPipe#3611]
### Describe the feature you want

Ability to see which videos has been added after a subscription update.
### Is your feature request related to a problem? Please describe it

I have seen many people asking/telling us the former layout was better. #3607 is one that I just noticed. 

Yesterday I also thought about a way to see which videos had been added after a subscription update, instead of remembering which video existed before an update.
### How will you/everyone benefit from this feature?

Every person that likes the former layout will find it a little better maybe. ¯\_(ツ)_/¯

Most of us can actually agree that after a subscription update we kinda can't know which videos has been added to the subscription feed. We have to remember which videos were there before an update to then figure out which videos were added. Especially when we have over 100 subscriptions and haven't updated in a few days.

Would it not be better to add something to display which new videos have been added?

**Comment by Stypox** [comment]
> Every person that likes the former layout will find it a little better maybe.

Why?
Also, this would be fixed by #3371, wouldn't it?

**Comment by ingingin** [comment]
@Stypox I like you, you're my favorite. Anyways. 

> Why?

I seriously don't know why xD. I love the new layout so I wouldn't be able to answer this question, but maybe?!

> You just have to remember the last video, since videos are always sorted by date.

Yes, sure, but that is exactly what this issue is about. Making it so people wouldn't have to remember the last video, this can be especially annoying when we have hundreds of subscribers or when one haven't updated in a while. And can't find the last video. Some channels upload multiple times a day and people can have a hard time figuring out where the newest video is in their feed.

> Also, this would be fixed by #3371, wouldn't it?

Not really, I don't usually watch every video that is uploaded. Most people have subscriptions that they just subscribe to because they wanna see what they upload. Like most of YouTube, (the inactive subscribers). Hiding only watched videos would only sort out those. And not by newly updated videos / old updated videos

**Comment by ingingin** [comment]
Just having a separator ( **|** ) between the old videos and the newer videos would fix this issue really. But it isn't something major. Just a quick thought

**Comment by B0pol** [comment]
Related https://github.com/TeamNewPipe/NewPipe/issues/1448

**Comment by ingingin** [comment]
This could also be extended. Even adding dates, like the original YouTube app. So it displays which day certain videos were uploaded on. But that would require it's own separate issue I guess ¯_(ツ)_/¯

**Comment by test2a** [comment]
can i suggest that we maybe make the text of the video a lighter shade if its from an "older" sync ? currently we have a red bar in the video thumbnail for progress, how about a tick in the middle to signify that a user has completely watched a video?  or even hide it like that PR?

**Comment by Pentaphon** [comment]
@test2a Or a red line on the left side of the thumbnail to show new video that resulted from the feed update.
