### ISSUE TITLE
Podcasts support

### ISSUE THREAD

**Issue by kubo6472** [TeamNewPipe/NewPipe#3623]
#### Describe the feature you want

RSS reader like support for listening to iTunes-formatted podcasts and search in some database of them.
#### Is your feature request related to a problem? Please describe it

No, but I don't know, how to handle the database of podcasts for searching through them.
#### Additional context

I can imagine some features from existing new pipe integrated. E.g. Separate speed/pitch change. The app I'm using now for podcasts has a feature to skip quiet (non speaking) parts, that may be integrated into NewPipe's YouTube support as well.
#### How will you/everyone benefit from this feature?

Another integration expanding the feature set both ways. People trying to find the best podcast app also coming round to watching YouTube/soundcloud through it and vice versa. It's this step on the ladder to single best content consumption app.

**Comment by klondix** [comment]
This seems out of scope for this project. Although I could imagine rudimentary support for RSS feeds (with enclosures) though. A lot of features, which would make it a (complete) podcast app, are missing.

* How are podcasts managed? On the sidebar, as their own service? Navigating from YouTube to podcasts will be a bit complicated, at least how switching services is currently implemented.

* Are the podcasts you subscribe to being displayed as subscriptions. Just like with YouTube? Honestly I like it how it is done in AntennaPod better. Mainly because it's quicker to navigate to a podcast on the sidebar.

* While you are able to download video / audio and there's a list of your downloads. You need to play it back in an external app. NewPipe hasn't been able to playback downloaded content so far. Besides you can't sort or filter this list or add it to a queue. Nor are playback states being saved.

* As you mentioned you can't search in the database. I think NewPipe doesn't store information like description in the database, especially not of the Downloads.

* Playback states are only saved for the current video. Not for every file / url.

* The background player queue only shows the title of it's entries. There's no information on playback position and duration being shown.

* There is no support for chapter marks [yet](https://github.com/TeamNewPipe/NewPipe/issues/3578). They would also need to provide it for downloaded content.

> RSS reader like support for listening to iTunes-formatted podcasts 

Why iTunes specifically? RSS feeds always should be in the same format (YouTube is an exception, missing the enclosure).

> The app I'm using now for podcasts has a feature to skip quiet (non speaking) parts, that may be integrated into NewPipe's YouTube support as well.

* This does make sense for YouTube podcasts, or videos which mostly focus on spoken word. For videos this doesn't make any sense.

* Another feature for podcasts I'd suggest would be a sleep timer.

> People trying to find the best podcast app also coming round to watching YouTube/soundcloud through it and vice versa.

* I don't think people who'll want to listen to podcasts (mainly), will come around to watch YouTube solely because the app features this. They'll decide to use the app in the first place if it they want to do both. (There are podcasts hosted on YouTube after all (sadly).)

* [AntennaPod won't add support, because it would violate Google's terms and they don't want to maintain a version on F-Droid diverging even more from Google Play.](https://github.com/AntennaPod/AntennaPod/issues/3901) Overall it seems easier to implement NewPipeExtractor in AntennaPod than to convert NewPipe into a podcast app. Especially since YouTube provides rss feeds for channels (and other things) and you can subscribe to them with AntennaPod. You're just unable to download anything, because enclosures are missing.

* Maybe there are podcast apps out there which actually support YouTube?

**Comment by kubo6472** [comment]
> * Why iTunes specifically? RSS feeds always should be in the same format (YouTube is an exception, missing the enclosure).
This is a link to my podcast feed compatible with individual services. Tmk it's called iTunes compatible format. Idk why. 
https://anchor.fm/s/c984d18/podcast/rss




> * Maybe there are podcast apps out there which actually support YouTube?

I haven't done any research on this one, but since I'm already a heavy user of NewPipe, transition to something new isn't worth it for me. I can live with switching between the two apps rn, but as you said... 

> * (There are podcasts hosted on YouTube after all (sadly).)

This is my main reason, that rn, I'm able to queue up the background player with mixed content. And if I could add podcasts (Which now that I think about it are also on soundcloud).

> * While you are able to download video / audio and there's a list of your downloads. You need to play it back in an external app. NewPipe hasn't been able to playback downloaded content so far. Besides you can't sort or filter this list or add it to a queue. Nor are playback states being saved.

I don't understand this. I know there's a feature to automatically download your podcasts, but frankly I always listen online. 

I don't know how hard exactly this may get. But I want to at least try making full PR utilising my knowledge from making Minecraft plugins. Java like Java, right?!

**Comment by kubo6472** [comment]
Out of scope

**Comment by kubo6472** [comment]
Reopening if this ever gets reconsidered :)

**Comment by opusforlife2** [comment]
https://github.com/TeamNewPipe/NewPipeExtractor/issues/565#issuecomment-1214404107
