### ISSUE TITLE
Stop adding features

### ISSUE THREAD

**Issue by cherryland** [TeamNewPipe/NewPipe#3661]
With every release, more useless features for special puppies are being added. The app is becoming unusable. These additional features go beyond the basic functionality. It results in software bloat and over-complication, rather than simple design. NewPipe is making the same mistake as Microsoft did 20 years ago: Adding features by user request. Microsoft Excel 1997 for example was so filled with "features", it became unusable. 

Feature creep (also know as Featuritis, Creeping featurism or the spoonerism) kills good experiences.

https://en.wikipedia.org/wiki/Feature_creep

I appreciate NewPipe's efforts, but the time has come to add some project management. You should define what basic functionality means and what the roadmap is. And most importantly, learn to just say **no**.

![image](https://user-images.githubusercontent.com/24250517/83188487-0c97d280-a130-11ea-8375-729181a17abf.png)

@theScrabi @TheAssassin @yausername @karyogamy @nv95 @Redirion

**Comment by ingingin** [comment]
I think you have a point. In one way or the other. But I seem to like the features they add. What I don't find very good, is the shortcuts to different actions. For example, the hold to enqueue. I didn't even know it existed. Which makes me think there are even more shortcuts or hidden features I don't know about. But making the app better and adding features that give the app useful meaning. I am all for that, the app still has a long way ahead to "compete" with the official YouTube app in terms of features. So I believe we shouldn't stop adding features. But making it clear what features the app actually have.

**Comment by TheAssassin** [comment]
@cherryland if you do not like these features, please feel free to fork the application and/or use an older version.

This application is built by a team of voluntary software developers. We do not want to order them to work on certain things, that is not how free software projects work. Every contribution is reviewed by our volunteers and merged if it fits the project's general goals and meets our quality standards. There is actual project management, but it's not comparable to a company's, so your claim there was none is just wrong.

By the way, the app runs perfectly on many-years-old devices, the performance argument doesn't hold at all IMO.

Feature creep is the entirely wrong term here. We don't have a project plan into which features could creep. We're not a company and don't charge any money for our "product", nor do we pay our developers.

By the way, your rude tone is not appreciated. You could've worded this in a more friendly way as well.

If you have the necessary skills and are willing to collaborate with Team NewPipe, I could imagine providing a Lite version, which only supports a limited feature set. But that's just an idea at this point, and the team has to discuss this at first.

**Comment by xdevelnet** [comment]
I was about to fall asleep but I just entered newpipe releases to check for a new version and missclicked to "issues" section. Once I saw your thread all sleepiness was gone.

First of all, I understand what are you talking about but I would like to see something concrete from you. If I were newpipe developer I wouldn't have any idea what to do with this thread.

>useless features

if the feature is useless for you it doesn't mean it's uselss for everyone else

It would be nice to have a list of features that you don't like or they seems redundant to you. From that people could discuss it.

>It results in software bloat and over-complication

Software that people are usually call "bloat" is usually bad designed, not reliable and lagging as hell. Good example of complex software with A LOT of features is ffmpeg, but still, I can't call it "bloat" becuase it just doing the job perfectly well and incredibly fast.

>NewPipe is making the same mistake as Microsoft did 20 years ago: Adding features by user request.

There is little difference between reason of adding features. In case of newpipe, there is no "business" between developer and user's request. It's free software.

>Microsoft Excel 1997 for example was so filled with "features", it became unusable.

While I'm not a microsoft fan (i am microsoft hater actually), I can argue with the point that Excel 1997 just solves most peoples requests and that's all.

>Feature creep (also know as Featuritis, Creeping featurism or the spoonerism) kills good experiences.

Nope. Performance issues, page decoding issues, video stuttering issues - all these kills good experiences. Newpipe still have some issues that forces me to use stupid web browser because newpipe is unable to play some videos properly.

In case of "feature creep" - well designed interface could solve decreasing user expeirence after adding new features.

>I appreciate NewPipe's efforts, but the time has come to add some project management.

I appreciate for everyone's efforts, especially people who add more critique, because during tight critique best ideas will born. The time has come to add some list of features that looks redundant for you and explanation why you don't like them.

Maybe your words will cause some changes then? Coz, in my expeirence, "blablabla I don't like it" will cause nothing.

**Comment by xdevelnet** [comment]
>By the way, your rude tone is not appreciated

IMO he's not rude, he's just worried.

**Comment by Stypox** [comment]
I agree with not adding too many features just to suit one user. This is clearly stated in the contribution guidelines. But imo the features that have been added lately were either very useful to most people (i.e. #2309) or not intrusive (i.e remove watched, mute button). So which features seem intrusive but useless to you?

**Comment by eshrh** [comment]
This is the right question to ask. It's easy to just say "too many features bad" but difficult to pinpoint which features are bad/unnecessary and why they are unnecessary. From there we can have a discussion of substance instead of this.

**Comment by Stubornyle** [comment]
I've been a NewPipe user for a year or two. I just wanted to say that I find NewPipe very balanced and parcimonious in its interface. Most features I don't use (the soundcloud and frama variants) don't bother me and are not intrusive. And I was happy to see some features useful for me implemented (Playback resume).

I don't know what features cherryland is talking about, but I hope the NewPipe continues introducing new options to the application. Its current policy seems balanced to me.

**Comment by brainchild0** [comment]
I'm not sure which specific new features prompted the original report, which mentions none in particular,  but I  do find myself having some sympathy for the author, as I look at the project page to learn that support is in development for services beyond Youtube, namely   SoundCloud, media.ccc.de,  and PeerTube.

Presumably, the essential purpose of the current project is to provide the best possible user experience for Android users accessing Youtube content. This objective has two parts, a superior user experience following from sound software design, and freedom from the more restrictive and intrusive policies of the service offering the content.

Realizing this objective seems to depend on building up, from a platform of a Youtube client, to superior performance and usability, rather than building out, to an ever-increasing set of service providers, mostly using their own service platforms.

Presently, the   interface has usability issues,  the main reason I currently use other methods for accessing Youtube content on Android. Due to a considerable and noteworthy effort currently nearing completion, the more prominent difficulties of the interface are likely to be resolved in future releases. The challenge exposed by the mere attempt simply to achieve good usability, however,  suggests a possible lack of wisdom in  expanding the set of supported services. 

Many volunteer-maintained projects collapse on their own weight, warning of the dangers of committing the limited available resources available in a volunteer effort to maintain so many different use cases, if any might be handled better by separate projects.

Concretely, since learning about the plans to support PeerTube, I have wondered why the community would be served better by such an expansion in  NewPipe than by  the separate project [Thorium](https://github.com/sschueller/peertube-android), leaving resources  in NewPipe available to seek to build a Youtube client better than any other.

**Comment by MD77MD** [comment]
I tried Thorium.... and it's hardly usable... my suggestion is join their project under the umbrella of newPipe.... this will benefit newpipe by having more contributors, on the other hand Thorium team will be working under a client that already have the infrastructure necessary to accelerate peertube implementation with spare time to support newpipe app as whole.

**Comment by brainchild0** [comment]
@MD77MD: Thorium has a very bare user interface, which some may find unusable. Presently, compared to NewPipe, it has better support for certain basic playback uses, including playing in the main view, in the background with another application using the screen, and with the screen off. I understand that these features are forthcoming in NewPipe. The larger issue is why recruiting developers from one project to another is better for either project or for the public, when the technology is open to share. If    one video player is lacking  in its user interface, then it may simply    adopt or adapt the interface of another. The impulse that one project should strive to have the most or best developers may be an artifact of familiarity with private industry.

**Comment by MD77MD** [comment]
>The impulse that one project should strive to have the most or best developers may be an artifact of familiarity with private industry.

@brainchild0 perhaps your right, maybe coexisting and helping each other is more advantages.

**Comment by opusforlife2** [comment]
What? xD
