### ISSUE TITLE
Suddenly Newpipe crashes for almost any youtube video

### ISSUE THREAD

**Issue by Atralb** [TeamNewPipe/NewPipe#3682]
### System
Android : version 9
Kernel : version 4.9.112
Newpipe : version 0.19.3
-

### Steps to reproduce the bug

Search for any video and try to play it.

Almost all videos that I find by making a search end up crashing the app. Only the ones listed by default on opening Newpipe don't make the app crash. But these are not strict rules : by going a long way, I can eventually find some videos that I can watch even though I specifically searched for. However, it's maybe 1% of all videos I click on.

I know you said you only support the latest version, but simply for reference, I uninstalled and reinstalled, and repeated this step for each version available (0.19.1, 0.19.2, 0.19.3) and also Newpipe Legacy. I. Get the same behavior for all of these.

**Comment by wb9688** [comment]
Upgrade to v0.19.4 and next time you create an issue, search for existing issues first

**Comment by Atralb** [comment]
@wb9688 Wow. You could hardly be more rude and inconsiderate.

The 0.19.3 is the most recent version that F-Droid (which is up-to-date) offers, and if you're referrimg to this issue https://github.com/TeamNewPipe/NewPipe/issues/3576, people are talking about livestreams and sayimg their error message is "couldn not play stream".Whereas the one I get is "could not parse website", so I believe my post was justified.

**Comment by ChiefMikeK** [comment]
### Is YouTube broking some videos via thier API?
Try and see if YouTube is blocking some videos if you are not signed ie. By using firefox incognito (private browsing).  And post a **SCREENSHOT** of the error message :neckbeard:  

> Today I started getting blocking of yt via duckduckgo.com `Error`

**Comment by wb9688** [comment]
@Atralb:

>You could hardly be more rude and inconsiderate.

It was not my intention to be rude.

>people are talking about livestreams

How are https://www.youtube.com/watch?v=ZEf9cRoTmzQ and https://www.youtube.com/watch?v=pjN_-nzzoiU, which are all the videos mentioned in that issue, livestreams?

>Whereas the one I get is "could not parse website".

That's what NewPipe says at the top for all parsing related errors. You have to look at the end of the first line under details for the actual error message.

>So I believe my post was justified.

No, both our issue template and readme clearly mention to read our contribution guidelines, and GitHub also provides a link to it on issue creation. Our contribution guidelines state: 

>Search the existing issues first to make sure your issue/feature hasn't been reported/requested before.

You didn't do this, as this is literally the 11th duplicate (if I counted correctly), plus the original issue is even pinned.

>Check whether your issue/feature is already fixed/implemented.

You also didn't do this, as this bug was already fixed when you created this issue.
