### ISSUE TITLE
Error report on audio downloads 

### ISSUE THREAD

**Issue by Kukulkan2019** [TeamNewPipe/NewPipe#3708]
### Version

-
0.19.3

**Comment by wb9688** [comment]
Please properly fill in the issue template. Now we don't know what exactly you mean.

**Comment by Kukulkan2019** [comment]
Your issue template is overly complicated, most apps simply have a comment
section... I gave you the version, latest, this is another audio download
issue, cause unknown, but it was working fine previously...


Brennan Mulrennan computer gaming technical contributor...♞

**Comment by Kukulkan2019** [comment]
> ### Version
> 
> 0.19.3
> 
> ### Steps to reproduce the bug
> ### Expected behavior
> ### Actual behaviour
> ### Screenshots/Screen recordings
> ### Logs

Audio not downloading, cause unknown, working fine previously... Will send bug report under separate cover...

**Comment by Stypox** [comment]
> Your issue template is overly complicated

Well, maybe that's true, but we need a detailed explanation. "Error report on audio downloads" is not meaningful, we can't solve anything with this little information. What error did you get? Is there an error report screen? If so use the [Incredible Error Report to Markdown Converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) before sending it. Also, you are using an outdated version, please update to 0.19.5 (as you have been told in the issue template, bug reports are accepted for the latest version, otherwise they could have already been solved).

**Comment by Kukulkan2019** [comment]
I tried sending this through Gmail... Measures attempted to correct the issue was clearing all Metadata, cache, etc., restarting the device to no avail... This version obtained through F-droid no newer presently available in their app... Audio download failure similar to video download failure some months ago, or last year, can't remember... I'm not familiar with how to work the markdown converter...

**Comment by ingingin** [comment]
Dude it's not hard. When you get the error, click the Share button. If you have the option, select Copy to clipboard / or / Open in Notes. So you can then select the text and copy it from there, open https://teamnewpipe.github.io/CrashReportToMarkdown/. Paste the copied text in "**Paste the JSON bugreport here**". Click _Transform_. And click Copy to clipboard. Then paste it here as a comment or edit your issue and paste the report there.

**Comment by Kukulkan2019** [comment]
Listen son, I'm pushing sixty years old, I'm not as tech savvy as you
younger individuals... I appreciate your help, just reporting an issue...
I'll look into it as soon as I get a chance, I've got a lot going on right
now... There is no newer update presently available in F-droid... Also,
another thing came up that you should be aware of, the carrier is no longer
crediting the data to the video bundle, therefore, it's consuming a lot of
open access data, previously it was working fine, this just now started
happening... As far as the bug report it's supposed to be send able by
Gmail...if you have a new 0.19.5 update, please send me the link...



Brennan Mulrennan computer gaming technical contributor...♞

**Comment by Stypox** [comment]
@Kukulkan2019 you can download the latest version [here](https://github.com/TeamNewPipe/NewPipe/releases/download/v0.19.5/NewPipe_v0.19.5.apk). Before installing you have to export the database from the previous version and uninstall it, only then you can install the new one, because the GitHub and the F-Droid versions have a different signature.

**Comment by Kukulkan2019** [comment]
Okay, got it, I'll let you know if anything comes up, thanks... 😎
