### ISSUE TITLE
Recaptcha challenge

### ISSUE THREAD

**Issue by noobie1111** [TeamNewPipe/NewPipe#3714]
Whenever I click any video it shows me reCAPTCHA challange and theere is nothing(white)
 On the screen except top red bar which shows done when solved
![Screenshot_20200601-132409_NewPipe](https://user-images.githubusercontent.com/66243164/83386740-3d675880-a40b-11ea-8d92-b4d38b84abd5.jpg)
. I waited for while but nothing happens the screen remains same. But it works completely fine when I use VPN. Need a help! 
   Tried clearing data and reinstalling latest version of newpipe.

**Comment by Stypox** [comment]
This is a known bug, with unfortunately no solution so far. That page is just rendering what Google provides us, and if it does not provide anything there is not much that can be done. Anyway, you could try downloading a debug apk (e.g. from release 0.19.4 here: #3670), connecting your phone to your computer, capture a logcat via ADB and sending it here, so that I can check whether there is anything strange.

**Comment by noobie1111** [comment]
Could you please explain more or maybe provide me links that could help me :)

**Comment by ingingin** [comment]
#3612

**Comment by ingingin** [comment]
Just download the APK from the link @Stypox gave you, then connect the phone to your PC, and use command I posted in that comment ^

**Comment by PacoBell** [comment]
Lately, I've been noticing that Torifying NP with VPN mode causes NP to completely bypass reCaptcha and just load the generic YouTube homepage for any link. It seems Google just DGAF about Tor users.

**Comment by aasutossh** [comment]
I'm facing the issue now. Sadly, no solution yet?

**Comment by MD77MD** [comment]
not sure if this is related, but i get this recaptcga only when i use 4g... not on WiFi

**Comment by opusforlife2** [comment]
Could you install a debug apk (for example from the pinned issue), connect your phone to your PC through USB, open Chrome, go to chrome://inspect, open that debug version of NewPipe on your phone, select that NewPipe instance in Chrome, go to the Network tab, try to reproduce the issue, and once you've successfully reproduced the issue, right-click in Chrome, select "Save as HAR with Content" and send us that HAR?

**Comment by Stypox** [comment]
HAR from @niuyaweiqq in #4282 (see that issue for more info)

I completed the error collection according to the operation you said. The following is the file you want, but this problem seems to be a robot verification problem, but after the NewPipe test version is entered, no video can be opened, all prompting me to need robot verification, but I can browse the video normally with the local webview, but I can’t download the webpage. I don’t know why this is. I don’t know if you can answer my doubts. Thanks again.
[ssssfdd.har.log](https://github.com/TeamNewPipe/NewPipe/files/5244040/ssssfdd.har.log)

**Comment by Stypox** [comment]
@stuffsearcher 

### Version

-0.19.8

### Steps to reproduce the bug




### Expected behavior

The video page will load normally.

### Actual behaviour


A ReCaptcha challenge is requested. Most of the time the ReCaptcha won't load (see image #1), if it does (see image #2) and you complete it, something like the YouTube mobile webpage will load instead of the normal UI (see image #3). If you click the checkmark it just closes the ReCaptcha challenge and the issue persists.

If you reconnect to Wi-Fi after encountering the issues they might still happen. The quick and reliable way to fix it is Force Stopping the app and opening it while connected to Wi-Fi.

### Screenshots/Screen recordings

Image #1: https://ibb.co/8DCK6yv
Image #2: https://ibb.co/6XLWV16
Image #3: https://ibb.co/zJ4sJ4R

### Logs

There is no Error Report page, but the issue seems similar to #4008.

**Comment by thiswillbeyourgithub** [comment]
I have this empty catcha issue as well when using a VPN.

**Comment by Stypox** [comment]
Could you all test if #5208 works?
