### ISSUE TITLE
What does "threads" do in the Download Manager?

### ISSUE THREAD

**Issue by StefanBrand** [TeamNewPipe/NewPipe#373]
Hey everybody,

in one of the latest releases the Download Manager was improved, now also giving the option to choose the number of "threads". Default is 3, but it goes up to 32. 

What does that value do exactly? Does a video/audio download faster if the number of threads is higher? Or is the resulting file of higher quality?

Maybe you could document the Download Manager somewhere.

Cheers, Stefan

PS.: I'm using Newpipe 0.8.5 on a Fairphone 1 / Android Kitkat 4.4.2  / MT6589 chipset.

- [x] I carefully ~~reed~~ **read** the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

**Comment by wb9688** [comment]
That's just to select how much threads to use for downloading…

**Comment by joaormatos** [comment]
Ideally, there should only ever be one download thread, for all videos.
Multiple connections per video? Sure.
But they should all be managed by a single thread.

Or at most as many threads as the number of cores (plus one(?)) if it actually turns out to be CPU-bound, but I'm fairly confident that it's going to be network or IO-bound in virtually all configurations.

I'm not familiar with this project's code or Android application development in general, but I spotted this [source code comment](https://github.com/TeamNewPipe/NewPipe/blob/master/app/src/main/java/org/schabi/newpipe/download/FileDownloader.java#L45) that makes me think this is a known design weakness that just hasn't been addressed yet.

**Comment by theScrabi** [comment]
I'm curious. FileDownloader shouldn't be in use anyway. We use [gigaget](https://github.com/TeamNewPipe/NewPipe/tree/master/app/src/main/java/us/shandian/giga) for downloading Files now.

**Comment by OffifialMITX** [comment]
Does that mean that the threads setting doesn't affect anything?

**Comment by theScrabi** [comment]
I don't think so, but to be honest, I have no idea.

**Comment by mauriciocolli** [comment]
I did a quick look on the code, and this is what I got (I could be horribly wrong, so if anyone knows this, please tell me):

First it gets the length of the download and divide by the `BLOCK_SIZE` (constant of 512 * 1024), getting the blocks number, then it compares if the threads value is greater, if it is, sets the threads count to this value.

Then it creates the number of threads and use those to download the blocks (chunks), till it finishes.

E.g.: Download of a 4MB music

- User set it to 5 threads
- Get the length: 4194304 bytes
- Divide it by the `BLOCK_SIZE`: 4194304/524288 =  8 blocks
- Compare if the threads number is greater than the blocks
- It is not, so let the numbers of threads being 5
- Threads start downloading the blocks (chunks), in paralell
- As the blocks are downloaded, and the threads are free, they keep getting blocks that don't have downloaded yet
- Keep downloading blocks (chunks) till it have all the file

So yeah, the number of threads do have effect, because it will download the blocks in paralell

**Comment by StefanBrand** [comment]
Does it have any effect on the user? Why isn't the highest number used always? (I assume that would result in the fastest download?)
-- 
This message was sent from my Fairphone 1 with K-9 Mail.

Am 28. Februar 2017 02:43:10 MEZ schrieb mauriciocolli <notifications@github.com>:
>I did a quick look on the code, and this is what I got (I could be
>horribly wrong, so if anyone knows this, please tell me):
>
>First it gets the length of the download and divide by the `BLOCK_SIZE`
>(constant of 512 * 1024), getting the blocks number, then it compares
>if the threads value is greater, if it is, sets the threads count to
>this value.
>
>Then it creates the number of threads and use those to download the
>blocks (chunks), till it finishes.
>
>E.g.: Download of a 4MB music
>
>- User set it to 5 threads
>- Get the length: 4194304 bytes
>- Divide it by the `BLOCK_SIZE`: 4194304/524288 =  8 blocks
>- Compare if the threads number is greater than the blocks
>- It is not, so let the numbers of threads being 5
>- Threads start downloading the blocks (chunks), in paralell
>- As the blocks are downloaded, and the threads are free, they keep
>getting blocks that don't have downloaded yet
>- Keep downloading blocks (chunks) till it have all the file
>
>So yeah, the number of threads do have effect, because it will download
>the blocks in paralell

**Comment by theScrabi** [comment]
Ah now I get it, this Thread thing belongs to gigaget downloader. So yea that is code that was merged into NewPipe, which came from another project.

**Comment by OffifialMITX** [comment]
So, again, does it do naything or not?

**Comment by theScrabi** [comment]
FileDownloader is not in use anymore. It was used during the phase where we (tried) to support tor. So if tor service was active FileDownloader was used, otherwise gigaget was started.
So I think FileDownloader can safely be removed. However everything else that belongs to gigaget should stay there.

**Comment by Lokesh-Krishna** [comment]
Could the option not be hidden from the user while the code remains?

**Comment by theScrabi** [comment]
It could. The download manager was once the GigaGet, which allows multithreaded downloads. I found out that a single thread sometimes makes downloading videos slower.

**Comment by Lokesh-Krishna** [comment]
Should I open an issue for hiding it or will this one do?

**Comment by theScrabi** [comment]
This will do.
