### ISSUE TITLE
Notification thumbnail to player

### ISSUE THREAD

**Issue by DmKaleid** [TeamNewPipe/NewPipe#3731]
<table>
<tr>
<th>If i touch here</th>
<th>goes here</th>
<th>it should go directly here, to the native player</th>
</tr>
<td><img width="200px" src="https://user-images.githubusercontent.com/66369488/83677666-e7cdb000-a5b2-11ea-877c-a67b12911260.jpg"/></td>
<td>
<img width="200px" src="https://user-images.githubusercontent.com/66369488/83677723-f4520880-a5b2-11ea-9de9-3bb33879b155.jpg"/></td>
<td>
<img width="200px" src="https://user-images.githubusercontent.com/66369488/83677806-151a5e00-a5b3-11ea-8dc1-b872a85ef710.jpg"/></td>
</table>

**Comment by DmKaleid** [comment]
@gkeegan why thumbs down?
i just want the option on menu or something .-.

**Comment by gkeegan** [comment]
If you are already playing in background mode it doesn't make sense to tap the picture to go to video mode imo.

**Comment by DmKaleid** [comment]
im not saying to remove the option to go to the background queue list, i just want the option to jump to the video .-. that's all

every music player or video player that i used is like this

select the thumb here:
![1T2kn](https://user-images.githubusercontent.com/66369488/83689428-66cbe400-a5c5-11ea-846f-2ff2081b294a.jpg)

goes here:

![download](https://user-images.githubusercontent.com/66369488/83689443-6e8b8880-a5c5-11ea-8e64-0d1f7606c91a.jpg)

**Comment by Stypox** [comment]
This is unfortunately not doable due to limitations in the Android notification system. For an update about the notification see #3178
Also, I agree with @gkeegan, it is not intuitive to click on the thumbnail to open the video. The intuitive thing is to go to the queue. And hiding options here and there is not a great idea, since NewPipe wants to be a mainstream app, not an application for a small group of people that know each of its options.
