### ISSUE TITLE
Background player selection to main (video player)

### ISSUE THREAD

**Issue by DmKaleid** [TeamNewPipe/NewPipe#3733]
<table>
<tr>
<th>
This video is playing on the background</th>
<th>If i select the thumbnail here</th>
<th>Just reset the video</th>
</tr>
<td><img width="200px" src="https://user-images.githubusercontent.com/66369488/83679099-3714e000-a5b5-11ea-83e5-feb770b29c75.jpg"/></td>
<td>
<img width="200px" src="https://user-images.githubusercontent.com/66369488/83679157-4c8a0a00-a5b5-11ea-8a1f-5d24434f604c.jpg"/></td>
<td>
<img width="200px" src="https://user-images.githubusercontent.com/66369488/83679170-53b11800-a5b5-11ea-9d02-bc2c83531b0f.jpg"/></td>
</table>
i think if im selecting the thumbnail of the video on a background list should just put the video on the foreground, resetting makes no sense

**Comment by Stypox** [comment]
There is already a way to switch players (see the three-dot menu). The thumbnail is already used as a drag point for reordering the queue, so I don't think it would be a good idea to assign it another purpose. Also, the "Switch to main player" is not an obvious choice when applied to an item, since it is more of a queue-related action. Eventually I would prefer to have "Show info" as the action of pressing on item thumbnails, though I don't think that's needed either since it can be accessed via the long press menu.

**Comment by DmKaleid** [comment]
>There is already a way to switch players (see the three-dot menu).
Yeah, i saw it
> The thumbnail is already used as a drag point for reordering the queue, so I don't think it would be a good idea to assign it another purpose. 
no, this is correct, this is not the part that i think should be changed, this is very intuitive and natural
> Also, the "Switch to main player" is not an obvious choice when applied to an item, since it is more of a queue-related action.
the thing is that i have no "direct access" to go to the player, and anything goes, something like this will be good enough:
![go to](https://user-images.githubusercontent.com/66369488/83687115-b3152500-a5c1-11ea-95da-716dded5c5a8.png)

every queue list i saw is something like this:

Select something here
![unnamed](https://user-images.githubusercontent.com/66369488/83687198-ce803000-a5c1-11ea-8342-623e15ba0085.png)

Goes here
![download](https://user-images.githubusercontent.com/66369488/83687216-d3dd7a80-a5c1-11ea-81d4-15d763805716.jpg)
