### ISSUE TITLE
Copy the media title

### ISSUE THREAD

**Issue by ryota-hasegawa** [TeamNewPipe/NewPipe#3768]
#### Describe the feature you want

I want copy the media title (example: long click the title text to copy)
#### Is your feature request related to a problem? Please describe it

No.
#### Additional context

Sorry for my Engrish :(
#### How will you/everyone benefit from this feature?

We will be able to copy the title and share it.

**Comment by rssoc** [comment]
+1 for this
I always catch myself long pressing the title thinking I can copy it.

**Comment by eladkarako** [comment]
I'm using two APKs to handle the missing copy title/URL think (not solved completely).

Copy to Clipboard which is only copying the URL. 

Share To Clipboard 
which I've config also copy title in addition to the URL and is useful for pasting to youtube description box (reference).

se.johanhil.clipboard
com.tengu.sharetoclipboard

you still need to edit the title out of the text just to get the title itself (if you know alternative please put here!)


https://f-droid.org/en/packages/com.tengu.sharetoclipboard

https://f-droid.org/en/packages/se.johanhil.clipboard 

https://f-droid.org/en/packages/de.k3b.android.intentintercept/
is somewhat of an alternative since it can help you show parts of the data in separated textarea-elements where you can more easily mark all and copy.


sadly all of those look like $hit!

![Screenshot_20200610-131129_Intent Intercept](https://user-images.githubusercontent.com/415238/84256004-0afce000-ab1c-11ea-93bb-bdfffeb4a639.jpg)

Sadly I've got reply here that it is out of their scope (not even considering it).. 

although copy title/copy url couldn't be more natural feature to have. 
https://github.com/TeamNewPipe/NewPipe/issues/3461

(along with open in YouTube, for example, https://github.com/TeamNewPipe/NewPipe/issues/3735).

**Comment by B0pol** [comment]
I agree it can be cool but we need to ensure that
+ the link can be shared to NewPipe and handled (it should be ok because I think it searches for the first link in the string).
+ it's not by default and available in settings, because some apps don't pick the first link in the string, _they expect to have **one link only**_, and we should not break that.

**Comment by test2a** [comment]
can i add to this, i would love to copy link to a video and not necesarily "share" intent with an app first. right now i end up sharing a video to firefox focus where i copy the url. I would say either a button to share link or a share intent to copy url, like there is with many apps

**Comment by B0pol** [comment]
You can share to clipboard in the share menu. 
Some devices don't have it, I suggest you to install [Share to clipboard](https://f-droid.org/en/packages/com.tengu.sharetoclipboard/) on F-Droid.
