### ISSUE TITLE
stop with the culturally insensitive "Guru Meditation" error message needs to change

### ISSUE THREAD

**Issue by mat-de-mystify** [TeamNewPipe/NewPipe#3776]
The open source community has serious issues with cultural appropriation going back to the origins.... [Apache,](https://en.wikipedia.org/wiki/Apache) are a group of people, not a web server for example... Kali is a god not a distribution....we can make our community better and less exclusive. A Guru is a spiritual and religious person, and meditation is a spiritual practice, a stack trace is not a spiritual experience....

### Version

-Latest and all

### Steps to reproduce the bug
Any time any bug is detected there is a screen that begins with the title "Guru Meditation" 

### Expected behavior

An error screen that has an amusing title that is'nt excluding and offensive to (approximation numbers here) 1.1Billion Hindus, 30 Million Sikhs, 520 million Buddists, 4.5 Million Jain's.....so about 21% of the global population.....(Thats nearly 5 times the population of the USA)....it's not a fringe issue.

### Actual behaviour

An Error screen beginnings with a prominent title "Guru meditation"

We can be better then this....

**Comment by puppykickr** [comment]
@mat-de-mystify 
Why not make your own app that says whatever you want it too when there is a problem?

Not everything on Earth needs to cowtow to the PC crowd.

**Comment by B0pol** [comment]
//just an easter egg

**Comment by wb9688** [comment]
See https://en.wikipedia.org/wiki/Guru_Meditation

**Comment by ofiala-a51** [comment]
"cultural appropriation" grow up lol

**Comment by StephenLynx** [comment]
The perpetually offended strike again.

**Comment by 0xaryan** [comment]
@mat-de-mystify  I see that your name contains the work "mystify".  This word's origin backs to early 19th century from French mystifier, formed irregularly from mystère ‘mystery’. And 'mystery' is a very religious word. In Christian theology, it means a religious belief based on divine revelation, especially one regarded as beyond human understanding. Worse than this, it also means the secret rites of Greek and Roman religions.

Please change your username. It's offending to bajilions of people lol.

**Comment by frozen-mechanics** [comment]
@mat-de-mystify I am a jew and personally `de` is a TLD of Germany, where my people were brutally murdered. I am offended by `de` part of your name. please use something that is not offending entire earth. thanks.

**Comment by ofiala-a51** [comment]
Does anyone know who marked the comments above this one "off-topic" or "spam"? @0xaryan 's comment is pretty on-point.

**Comment by StephenLynx** [comment]
@ofiala-a51 the same person that still haven't closed the ticket.

**Comment by ofiala-a51** [comment]
@StephenLynx Thanks, I thought that would be the case... I'm just kinda surprised GitHub gives someone perms to hide other people's comments in a repo he doesn't own...

**Comment by StephenLynx** [comment]
@ofiala-a51 im assuming it's the repo maintainers. They are probably just too afraid to take any decisive action.

**Comment by gkeegan** [comment]
Can you all please stop being rude and insensitive? GitHub isn't a place to start attacking people because you disagree with their idea. This user is one of the few people who actually used the issue template as designed and made a well-written issue. 

You're proving their point by continuing to act like children.

**Comment by StephenLynx** [comment]
@gkeegan making fun of absurd and petty demands is not being rude and insensitive. The internet is not a hugbox and the moment you make your ideas public, you are opening yourself to criticism.

**Comment by TheAssassin** [comment]
We've locked the issue as it has turned into a way too off-topic discussion, and every new comment spams people's inboxes. There's enough pro and con comments, and the issue will definitely be discussed in the team.

**Comment by TheAssassin** [comment]
After a couple days, the heat is gone, so we unlock this issue again.

First of all, a little context about the term. It has originally been introduced in the [Commodore Amiga](). It was shown on fatal crashs of the system, from which it could not recover, leading to a hard reset. Think "the blue screen of its era". [According to Wikipedia](https://en.wikipedia.org/wiki/Guru_Meditation), it originated from an in-house joke. Everyone can search for this on the internet, it's not any new information. We're sure you're aware of this.

Many software systems have since adopted this as a kind of "easter egg". NewPipe is no exception, it's merely been integrated as a joke. It's not meant to discriminate anyone, nor to exclude anyone.

We talked about this issue within the team and on IRC. We cleary want to express that Team NewPipe and its members are strongly against racism or discrimination of any kind, towards anyone, and welcome everyone to use and help develop NewPipe. The initial request however doesn't justify in any way how using this sentence was culturally insensitive. The argumentation doesn't hold in our opinion. One could see it more as an homage to Indian gurus, not as an offense. Nobody's ever claimed an error was spiritual, for instance. The numbers don't really help. We couldn't find any evidence on the Internet about similar discussions in other projects.

If there is someone with some expertise around the Asian culture who can really justify how this would be culturally insensitive or offending, we'd be open for a discussion. The original post doesn't provide that information at all. Our team internally cannot see any offense, and therefore we are not going to remove this easter egg. If there is clear evidence that we are wrong, we're open to a follow-up discussion, of course.

There is no point in harassing each other for their opinion and we don't tolerate that in our issue tracker. Other than the first few posts, the discussion immediately turned into a flamewar, even having a spammer (no, such people don't troll, they just hate) chime in. We marked all those comments as off-topic for this reason, and would ask for this not to occur again. Otherwise, we will have to block those people next time. Such behavior is definitely insensitive.
