### ISSUE TITLE
Request to explain License in simple words

### ISSUE THREAD

**Issue by mubashir-rehman** [TeamNewPipe/NewPipe#3846]
Description:
Kindly explain how the putting forks on Play store violates the license of NewPipe under GPL v3.
Reason:
There is a FOSS project named Trebleshot, that provides facility for file sharing like ShareIt. It has gained a lot of play store clones lately cuz of situation going in India. The problem is no one is giving credits to original project and contributers. Also, those apps have more than 50k downloads while original app has 10k. They only changed some UI and every code else is same.
Extra details:
Trebleshot is licensed under GPL v2 or any later version.
Source code can be found at GitHub.com/Trebleshot
Expected Answer:
A suggested modifications to GPL v2 or any later version to stop any fork from uploading on Play store without prior authorization.

**Comment by lionirdeadman** [comment]
Changing the GPL version in this case would not matter. The reason most forks on the play store violate the GPL license is because the license requires both attribution and source code. Most forks on the play store violate this because they don't do either or only one of them.

But the reason why NewPipe specifically can't be on the play store is unrelated to the GPL. It's because Google does not want Youtube downloaders or Youtube programs which allow for ad-free viewing since well, they charge for these features with their premium subscription.

I hope I explained it correctly.

**Comment by visvajeet** [comment]
How Pure Tuber app is available on play store?

**Comment by mhmdanas** [comment]
It violates Google's Terms of Service, and if its source code is not available publicly, it also violates NewPipe's license. I believe it has already been reported to Google; it's up to them now to delete it.
