### ISSUE TITLE
Battery Drain Issue

### ISSUE THREAD

**Issue by Kiran-0k** [TeamNewPipe/NewPipe#3847]
### Version

-v0.19.5
Device:Redmi Note 9 Pro(India)/Redmi Note 9 S(Global)
OS version: 10

### Expected behavior

Normal battery usage when the App is closed.
### Actual behaviour

The app doesn't use much CPU in the background but the battery stats still show it using the most Battery.

### Screenshots/Screen recordings

![Screenshot_2020-07-05-09-23-50-714_com miui securitycenter](https://user-images.githubusercontent.com/60058656/86525445-cc511000-bea4-11ea-8c1b-8a37ae3a7f47.jpg)
![Screenshot_2020-07-05-09-47-23-424_com miui securitycenter](https://user-images.githubusercontent.com/60058656/86525450-d3781e00-bea4-11ea-978d-eb764b005cd7.jpg)

**Comment by OmkiranSG** [comment]
I've tried restricting Background activity. Then the battery doesn't drain as much, but it gets killed when using Pop-up player or Background Player.

**Comment by msdlr** [comment]
Hello, I'm also experiencing this problem
Device: Redmi note 7
OS: MIUI 11.0.8
![Screenshot_2020-07-24-10-30-31-344_com miui securitycenter](https://user-images.githubusercontent.com/27902289/88374466-1c334080-cd9a-11ea-99a0-14892f888264.jpg)

![Screenshot_2020-07-24-10-36-43-146_com miui securitycenter](https://user-images.githubusercontent.com/27902289/88374490-25bca880-cd9a-11ea-9170-c48c17bc3618.jpg) 

I hope that these provide some useful information about the issue since it seems to affect various phone models

**Comment by Kiran-0k** [comment]
I'm currently on v0.19.8 seems to me the Issue have been resolved. Now the Battery Usage is according to my usage.
@msdlr Plz update to v0.19.8 and get back if the Issue has been resloved or not, so that I can close the Bug Issue.
