### ISSUE TITLE
Why stop at *3 speed???

### ISSUE THREAD

**Issue by chekmanh** [TeamNewPipe/NewPipe#3876]
#### Describe the feature you want

I think that some people would be really happy, to be able to watch videos at a greater speed than *3 (4 or 5 seems appropriate). 
My guess is that you would only have to change a variable (from 3 to 5).

#### How will you/everyone benefit from this feature?

This feature will save a lot of time, when we have to watch videos on a mobile phone.

**Comment by Stypox** [comment]
I don't see the benefits of this. Why would someone want to watch a video at 5x? Also, why 5x and not 10x or anything else? I think 3x is a pretty reasonable value. Moreover, making the speed slider span more values would make it difficult to choose the wanted value by seeking. Also, i.e. having 5x speed and 100% pitch would most probably cause audio wave issues.

**Comment by chekmanh** [comment]
I mean https://addons.mozilla.org/en-US/firefox/addon/videospeed/ supports *4 with sound. Vlc and mpv player also support *4 without any problems. 
And making the speed slider span more values shouldn't be a problem, since you can choose to increase the playbackspeed in discrete steps.
Could someone tell me, where exactly I can change the max speed, in the source code? I couldn't find it.

**Comment by Stypox** [comment]
This is the file: https://github.com/TeamNewPipe/NewPipe/blob/dev/app/src/main/java/org/schabi/newpipe/player/helper/PlaybackParameterDialog.java

**Comment by hunkjazz** [comment]
> Why would someone want to watch a video at 5x?

I know people who actually needs to watch YouTube at 8x. He's a LoL PRO player who needs to watch many matches per day. He says, he'd watch even faster if internet connection was fast enough.

> Moreover, making the speed slider span more values would make it difficult to choose the wanted value by seeking.

That's the real problem (UX), not the former.

I think 3x is enough for most NewPipe users. Hence, should be kept unless someone comes up with a good solution for both UX, UI and audio wave issues.

**Comment by mgolden356** [comment]
You can share the video to VLC app and get x4 functionality if needed, in addition to Chromecast functionality incidentally, already.

**Comment by chekmanh** [comment]
@Stypox thank you very much. I would really like that feature, for now I will manually compile it with higher playbackspeed

**Comment by Lattyware** [comment]
It may be a little niche, but I actually do listen to some particularly slow speakers at 4x speed in Firefox using a plugin, and so 4x would be useful for me as well.

My suggestion for the UI would be to allow the user to press the "+" button on the right of the playback speed control even when the slider is at it's max, to go up to higher speeds (the slider would just remain at its rightmost position, and interacting with it would reset it to the slider's speed). This makes it possible, but without clogging the UI with something most people will never use.

In fact, if this were done, it might improve the UI, as you could make the slider only go to 2x (which is probably the most people commonly used, making it easier for them). People who want 3x can just do as above.

Of course, the most complete option would be to let the user set a max speed to show on the slider in the settings, but I can understand not wanting to add such niche options.

**Comment by eladkarako** [comment]
It can save people from skipping (seeking) a long lecture (for example),  
I would even got the next step and provide a way to customize the on-screen controls,  
such as brightness/volume to be allowed to be switched one of those to control play-speed.

**Comment by lu4p** [comment]
Maybe make this configurable in settings, I think 3x is a reasonable default.

**Comment by MD77MD** [comment]
from comments, i think this should be closed

**Comment by Isssuemaker** [comment]
> from comments, i think this should be closed

Please open this issue

**Comment by Isssuemaker** [comment]
I also want 5× speed for many slow speaking lectures

**Comment by fajis1** [comment]
> I don't see the benefits of this. Why would someone want to watch a video at 5x? Also, why 5x and not 10x or anything else? I think 3x is a pretty reasonable value. Moreover, making the speed slider span more values would make it difficult to choose the wanted value by seeking. Also, i.e. having 5x speed and 100% pitch would most probably cause audio wave issues.

Increasing the slider should not make it more difficult to choose the wanted value by seeking. In Podcast addict you can go up to 5x and still easily seek the value you want. 

My wife and I would very much like faster speeds on new pipe. In fact speed was the reason why we found new pipe in the first place. We were looking for a way to get past 2x speed limitation on the android app. 

Here is a link to a video showing how podcast addict handles the slider, and how you can select preset speeds from the dropdown menu. 

https://user-images.githubusercontent.com/68034464/148804775-dbf0f5be-1fb7-4543-99c6-24ffa24e02d9.mp4

if that doesn't work then here is the same video. 

https://drive.google.com/file/d/1OKfRA_B-t0et_rQSxyxQNxgmqCRecZB7/view?usp=sharing

**Comment by Kladstein** [comment]
> @Stypox thank you very much. I would really like that feature, for now I will manually compile it with higher playbackspeed

Can you please share the apk as i auso need more than 3x playback speed

**Comment by GallusGallu** [comment]
This request was seemingly closed mostly due to the comment by @Stypox:
> I don't see the benefits of this. Why would someone want to watch a video at 5x? 
This is really just incredulity, but to submit some audio which I would prefer to listen to at >3× speed:
https://www.youtube.com/playlist?list=PL0TV2mCk83zBbWxnbA7ndfHFlctKzHGIL
https://www.youtube.com/watch?v=Myy5Wu5KUpE
Other examples such as lectures and gameplay footage have been raised too. There are definitely some videos (and in my experience they are not absurdly rare) where larger speeds would be useful. I'm not tied to a specific value personally, but I suspect 3 was chosen aerboitrarily, so I see no reason not to use a new arbitrary value, e.g. 5 as was suggested.
> Moreover, making the speed slider span more values would make it difficult to choose the wanted value by seeking.
The slider is already nonlinear, which I personally find unhelpful for seeking, but I think it is this way to allow easier seeking at slower speeds. Increasing the upper limit would therefore not affect the lower speed range by a large amount, did to the nonlinearity. I personally find the stepped controls far more useful for specific adjustments than seeking, so I can't speak as to the ergonomics of the slider.
> Also, i.e. having 5x speed and 100% pitch would most probably cause audio wave issues.
This should be investigated further instead of being used for dismissal, but I notice minimal unexpected distortion at 3×, and other services offer higher speeds, so perhaps NewPipe could follow their lead. Apparently several other services use an upper limit of 4×, suggesting this won't lead to serious issues.
I understand that there will always be some fraction of people wanting a faster maximum speed, but I think as there are several listed categories of video which could benefit from a higher maximum playback speed, this should be reopened/reconsidered.
