### ISSUE TITLE
Custom REGEXP

### ISSUE THREAD

**Issue by ghost** [TeamNewPipe/NewPipe#393]
I recommend the addition for adding custom regexps.
Why: The hardcoded one is just accepting alphanumeric characters (from what I've seen).

**Comment by theScrabi** [comment]
Please give a code example.

**Comment by AnotherJavaCoder** [comment]
For example, add in settings a dropdown of custom regexs and show them in the download dialog. I don't have a piece of code for now but I will try to submit it

**Comment by theScrabi** [comment]
I'm not sure if I understand what you mean.
What would be your gol if you select a regex from a menu?

**Comment by AnotherJavaCoder** [comment]
The regex will modify the file name because now, all non alphanumeric character are replaced by an underscore.

**Comment by theScrabi** [comment]
Oh I see it's about that download name. Hm would you like to change it so it would fit your needs, than you can commit the changes? :)

**Comment by litetex** [comment]
I don't think this is is applicable anymore.

> The regex will modify the file name because now, all non alphanumeric character are replaced by an underscore.

There is another option now "Most special characters".
Also it's now possible to use another replace char.

I'm closing the issue due to:
* Above reasons
* extremely poor description and title (5 comments have to be read until you find out it's about the downloader)
* 0 upvotes in ~5 years.
