### ISSUE TITLE
NordVPN CyberSec feature

### ISSUE THREAD

**Issue by slipstream01011** [TeamNewPipe/NewPipe#3962]
Greetings,
For my VPN I use NordVPN. It has a feature called CyberSec. This feature improves your ability to hide your IPTV streaming activity from your ISP.  The problem is it prevents NewPipe from connecting to the network and what you get is a network connection error.  Can NewPipe be fixed so it works correctly with the CyberSec feature enabled?  Right now NewPipe only works with the CyberSec feature disabled.  However, disabling CyberSec is a problem to me because then my IPTV streaming activity is not hidden from my ISP.  Thank you for your time. 

### Version = Latest version Installed

-

### Steps to reproduce the bug 
1. Launch NordVPN.
1. Enable NordVPN Cybersec feature.
2. Launch NewPipe.
3. NewPipe network connection failed message appears. It reads "Retry"

**Comment by Kusurisan** [comment]
sounds for me like a problem with NordVPN Cybersec, not NewPipe. what do you expect the devs doing? It's the Cybersec feature that is blocking the connection. So if you ask me, you need to contact the NordVPN Support, not NewPipe's.

**Comment by ingingin** [comment]
**This issue can be closed** 
The NordVPN feature is not helping you hide your IPTV streaming from your ISP. This feature called CyberSec is an adblocking feature and is not by any means going to help you with that. The design is to block IP addresses like any other malware/adbloking extension. This issue is also unrelated to NewPipe and should therefore be closed IMHO... NordVPN is already a trash service as I've been a NordVPN user for 3 years.

**Comment by FireMasterK** [comment]
Cybersec acts as a DNS server which blocks ads, malicious domains, etc. In this case, it's likely blocking a dns query required by NewPipe and hence prevents NewPipe from functioning.

2 things can be done:
- Close the issue as it's not a NewPipe Issue
- Implement DNS over HTTPS or something similar
