### ISSUE TITLE
No updated in F-droid

### ISSUE THREAD

**Issue by Joselpdj** [TeamNewPipe/NewPipe#4003]
Hi!,
I downloaded NewPipe from the F-Droid store, and it is outdated, right now the latest version in the store is 0.19.5 and here on Github is version 0.19.8.

I don't know if they're uploading the new versions from here, or if it's the right place to report it and update the F-droid repos.

Just in case, I'll leave you informed.

Best regards!

**Comment by Joselpdj** [comment]
I have reported in F-droid applications issues section too.

**Comment by gkeegan** [comment]
Please don't open issues with F-Droid or us about this. It takes some time for updates from any developer to be put onto their official repository since they need to build the releases themselves (and other reasons).

If you can't wait a bit, try using the NewPipe repository here: https://newpipe.schabi.org/blog/announcement/f-droid/pinned/f-droid-repo/

**Comment by wb9688** [comment]
Also see #3991

**Comment by Joselpdj** [comment]
Thanks, I have added the repository to Fdroid and I have already updated the application.
