### ISSUE TITLE
Brightness bug when "changing player" (after unified player, 2907)

### ISSUE THREAD

**Issue by B0pol** [TeamNewPipe/NewPipe#4043]
### Version

- https://github.com/TeamNewPipe/NewPipe/commit/d8b5549fd98e43f18b993c5f36f2385cf9a80620 (latest dev)

### Steps to reproduce the bug

1. Disable auto brightness 
2. Lower your brightness
3. Open a video, in fullscreen
4. Increase the brightness via the player, by swiping up
5. Exit fullscreen video (go to video details)
6. (Optional) Minimize and close the video

### Expected behavior

The brightness is back to system brightness. The fullscreen brightness is only used in fullscreen, not in video details or popup player (not the case with the last one).
### Actual behaviour

The brightness is the same as the fullscreen video brightness. With step 6, it's really stupid because the video isn't even playing but we still have this brightness, and no way to change it except play a new video and lower brightness.

**Comment by avently** [comment]
> it's really stupid because the video isn't even playing but we still have this brightness

You can still watch a video in portrait mode and the brightness you setup is needed in this case. 
Let's say you are watching video at night and have low brightness while browsing other apps. Then you opened NewPipe in portrait mode and trying to see something but you can't because brightness is too low. For video it is important. Maybe you didn't notice that on Amoled but on IPS there is not so much contrast and the brightness for a video should be higher even in portrait (actually it's more important than in landscape because picture is smaller and some details could be missing from your eyes because of low brightness). I'm telling you as a guy who has a bad eyesight if it matters.

**Comment by B0pol** [comment]
> hen you opened NewPipe in portrait mode and trying to see something but you can't because brightness is too low.

then play fullscreen, otherwise the rest of the screen will burn your eyes.
Video playing on video details should be treated like popup mode.

> here is not so much contrast and the brightness for a video should be higher

I agree, but you are on video details and scroll down you are not watching the video, but reading comments. Therefore the brightness should be lower -> system brightness. But there is no way to reduce brightness unless you play in fullscreen, lower brightness. It's really long and unecessary. 

If you want higher brightness on video details or minized, just increase your system brighntess, because **most** of the screen is not about the video. And even worse when you read comments or close the minimized state (when you scroll down), **nothing** on the screen is about video but we keep video brightness…

**Comment by avently** [comment]
@B0pol  check this PR #4223

**Comment by opusforlife2** [comment]
Wow, it was worse than I thought. The brightness value persists _across app restarts_ and shows up again when you open video details. But strangely, when you go fullscreen the brightness lowers to system level. And even more strangely, it goes back to the high value if you go back to video details. Very weird. Anyway, this was a much needed fix, so thanks, @avently.

**Comment by avently** [comment]
@opusforlife2 
> The brightness value persists across app restarts

This is how it works for years :)

>But strangely, when you go fullscreen the brightness lowers to system level

Nope, it's the same as was set in videoplayerfragment, no changes

> And even more strangely, it goes back to the high value if you go back to video details

Still no, if you just watched a video in fullscreen and than rotated to portrait the brightness will be the same as was set by videodetailsfragment after initial load.

Anyway, after the PR the brightness will work the same way expect it will be set only for fullscreen mode. Or will be system default otherwise.

**Comment by opusforlife2** [comment]
> This is how it works for years :)

Yes, but that was the correct behaviour in that case, because the video player was the only place with that high brightness. The video details page was still at system brightness. With the unified player, the video details page was consequently made high brightness as well, which is why this was considered a bug. The behaviour after your fix is more intuitive.
