### ISSUE TITLE
Better Kore Integration

### ISSUE THREAD

**Issue by Isayso** [TeamNewPipe/NewPipe#4063]
#### Describe the feature you want

Dear team, I compiled a version from the DEV branch code and my humbe opinion is that the change in the UI concept is heading into the wrong direction. Why? Because for simple basic operations you need double, sometimes triple the number of clicks as before. Example, the Back button is not the back button anymore, its a Player minimize or back in queue button. To close the player I need now press Back and Close in the now minimized player, or even worse, start the video, touch the video to make the close button appear and press it. Similar for the Kodi button. I use it very often, now I have to start the video, touch it, open the dropdown menu and press the Kodi button. Thats a mess.  
NewPipe is the most used App on my phone and I'm very thankful that it exist. The only function I miss is the "Upload Date" and "long video" filter function, especially in these shadow banning video times.
  
Please re-consider your future UI concept.
Thanks!

**Comment by avently** [comment]
> To close the player I need now press Back and Close in the now minimized player, or even worse, start the video, touch the video to make the close button appear and press it.

What stops you from swiping the player down without even touching back button?

I think this issue should be closed and communication moved to https://github.com/TeamNewPipe/NewPipe/issues/4039 because you have the same problem (with button) and the same possible solution as suggested in the issue. If you have another solution, tells us in the issue I mentioned.

And a question, do you feel that history (backstack with videos) is unneeded? Should back press redirect you directly to tranding page, for example, instead of to a previous video?

**Comment by MD77MD** [comment]
backstack is way useful... however UI corks will be ironed with time eventually and less clicking is always welcomed.

**Comment by Stypox** [comment]
> I think this issue should be closed and communication moved to #4039 because you have the same problem (with button) and the same possible solution as suggested in the issue. If you have another solution, tells us in the issue I mentioned.

I agree
