### ISSUE TITLE
Peertube instance home page default

### ISSUE THREAD

**Issue by pracarta** [TeamNewPipe/NewPipe#4118]
Hi Newpipe community 

I would like to know, if there is a possibility to code for a peertube instance home page instead of YouTube home page default on newpipe app code ? 

Thanks you in advance for your reply

**Comment by opusforlife2** [comment]
Can you specify? Do you mean that when you first install the app and open it, you want to see Peertube instead of Youtube?

Or just that whenever you open the app, it should start from the Peertube service instead? Because if this is the case, Newpipe already starts up with the service that was selected before it was closed.

**Comment by pracarta** [comment]
Sorry for my bad english, 

Yes it is the first thing that i would know if it's possible. Put in Newpipe code the Url of my specific Peertube instance for when people dowload and install apk, they fall on my Peerturbe instance choice.

**Comment by opusforlife2** [comment]
It's definitely possible to change the default Peertube instance in the code from Framatube to your own. But whether or not Peertube could be the default service instead of Youtube when opening a new installation... @wb9688?

**Comment by Stypox** [comment]
I guess this is just a matter of changing the default service values (if you Ctrl Shift F search Youtube you should find relevant code)

**Comment by pracarta** [comment]
Thanks for the suggestion but in which folder or document we have to find and change this. Sorry I'm not an expert in programmation but I think as you say it can be just an issue of Url. 

Thanks for you help ! :)

**Comment by skyGtm** [comment]
@pracarta Did you mean this?

https://user-images.githubusercontent.com/50160188/120894467-384d7280-c638-11eb-9705-2382724d6878.mp4


@opusforlife2 As per the question, this video tries to make Peertube as homepage. I think this solves the issue

**Comment by opusforlife2** [comment]
@skyGtm That's not it. @pracarta Wants it so that when people install their version of Newpipe, it should open directly to Peertube on first run, and their instance should already be selected by default. It's a programming question.

If it was just about selecting a Peertube instance manually, then I already answered that in my original reply.

**Comment by TobiGr** [comment]
I am currently working on a new onboarding experience. Selecting the service (and the instance) is part of it

**Comment by litetex** [comment]
Closing this:
1. Not sure how the onboarding experience is related to programmatically changing the default service to Peertube → should be a new issue
2. Peertube will definitely not be the default in NewPipe since most users use YT
3. If you can't code and want to change something inside your own fork don't ask us how to exactly (1 to 1 code) implement it, we are not your contractor ;)

**Comment by pracarta** [comment]
> Closing this:
> 
> 1. Not sure how the onboarding experience is related to programmatically changing the default service to Peertube → should be a new issue
> 2. Peertube will definitely not be the default in NewPipe since most users use YT
> 3. If you can't code and want to change something inside your own fork don't ask us how to exactly (1 to 1 code) implement it, we are not your contractor ;)

Sorry, I completely understand. Thank you for everything and for closing the topic.
At that time, I was discovering the digital community and I worked with a programmer.
See you soon

**Comment by opusforlife2** [comment]
> Peertube will definitely not be the default in NewPipe since most users use YT

For now. 👀
