### ISSUE TITLE
[Unified Player] Background playing stops if NewPipe is closed from recent apps

### ISSUE THREAD

**Issue by ryota-hasegawa** [TeamNewPipe/NewPipe#4159]
### Version

latest dev branch (after Unified Player PR merged, thank you @avently)

### Steps to reproduce the bug

1. Play any audio or video in the background.
2. Close NewPipe from recent apps in the navigation bar.

### Expected behavior

The playback will continue if NewPipe is closed from recent apps like before.

### Actual behaviour

The playback will stop and notification is gone.

**Comment by opusforlife2** [comment]
0.19.8 and unified apk both show the exact same behaviour for me. If 'Minimize on app switch' is set to 'None', they both pause upon going to Recent Apps. If it is set to background, they continue playing as audios.

Is your case different?

**Comment by avently** [comment]
@ryota-hasegawa  
> thank you 

You are welcome!

This behavior is implemented here if somebody interested: https://github.com/TeamNewPipe/NewPipe/blob/dev/app/src/main/java/org/schabi/newpipe/player/MainPlayer.java#L187

> The playback will continue if NewPipe is closed from recent apps like before.

Why do you want it? When you close the app from recents doesn't it mean you want to get rid of it completelly?

**Comment by ryota-hasegawa** [comment]
@opusforlife2 
I meant to go to the "Recent Apps" screen and close NewPipe with swiping. I'm sorry for misleading.

@avently
I sometimes use NewPipe as a music player. (I know NewPipe is not a music player.) And I usually close apps that are used only for the background to clean recent apps screen. Some other player apps don't stop playing if the app is closed from recent apps. So I want this behavior.

**Comment by opusforlife2** [comment]
@ryota-hasegawa No, my mistake, I just didn't swipe it from Recent apps because I thought the issue was with the minimize setting. My bad. You're right. There is a difference in behaviour between 0.19.8 and the unified player.

@avently I think it is expected behaviour for many apps, especially music apps, that if some ongoing process is _notification-based_, it wouldn't be killed by swiping the app away from Recents. So in the current release, playing in background or popup doesn't kill the stream when swiping the app away.

But your point about shutting down the stream when swiping away from Recents because you're done with the app is also correct.

Personally, I prefer the music app like behaviour for the background player. The stream shouldn't be shut down.

@TobiGr @Stypox @wb9688 @B0pol What do you guys think?

**Comment by TobiGr** [comment]
I think we need to set the default of the "minimize in APP switch" setting to background. That solved the problem for me on Android 9. Can you guys confirm this?

**Comment by opusforlife2** [comment]
Nope. This setting works on 0.19.8, but not on unified player. Did you swipe away from Recent Apps? I forgot that part too. It's the exact step where the current release and unified player differ.

But that only has to do with the main player getting minimized.

Even if you just directly play a stream in the background player in the unified apk, then swipe the app away from Recents, the stream shuts down and the player closes, while in 0.19.8, the notification will remain and the stream will continue playing.
