### ISSUE TITLE
Change YouTube user agent to load info faster

### ISSUE THREAD

**Issue by UltraBlackLinux** [TeamNewPipe/NewPipe#4164]
<-- I didnt type below the type-below-lines -->

#### Describe the feature you want

there is a plugin for firefox, that lowers the amount of the youtube loading time, cause of the stupid google chrome benefits. It works via user agent/url/...
https://addons.mozilla.org/en/firefox/addon/youtube-classic/

#### Is your feature request related to a problem? Please describe it

Newpipe takes ages to load videos.

#### How will you/everyone benefit from this feature?

Videos will load faster

**Comment by opusforlife2** [comment]
> <-- I didnt type below the type-below-lines -->

You absolute madlad. 🤭 

@wb9688

**Comment by Stypox** [comment]
Currently the scraper does not download the whole page, but uses the `pbj` mode, which provides a json with all of the data instead of html. So if what you are suggesting lowers the amount of data transferred for html pages, it wouldn't do much to us. But does that improve server response time, for some reason?

Also @wb9688 please check this ;-)

**Comment by B0pol** [comment]
No. 

YouTube classic is not supported anymore, it can be dropped at any time (it is already, this is a trick and is not stable for NewPipe).

**Comment by UltraBlackLinux** [comment]
Yeah the user agent now leads to infinitely loading youtube. I only downloaded thaz plugin, because, e.g. streams were unwatchable. Stupid google
