### ISSUE TITLE
Importing exported settings fails.

### ISSUE THREAD

**Issue by aksrikanth** [TeamNewPipe/NewPipe#4180]
I exported the data today and tried to clean everything out and import again. Import fails with toast "Could not import subscriptions". No subscriptions or playlists are imported.

Version of NewPipe both for export and import was 0.19.8

**Comment by aksrikanth** [comment]
I can't find a way to attach my exported data.

**Comment by opusforlife2** [comment]
What did you export? Subscriptions or database?

**Comment by aksrikanth** [comment]
It created a zip file that contains both.

Srikanth

**Comment by aksrikanth** [comment]
Update: Importing from the setting seems to work, but importing from the subscription page does not.

**Comment by opusforlife2** [comment]
Sorry, I must have missed this when you replied earlier.

If you got a zip, that means you exported database from settings. This can, naturally, only be imported through import database. Importing through the subscriptions tab wouldn't work, because that looks for a JSON backup containing only subscription info, and the zip file is invalid for that.

Can you confirm that if you export a JSON from the subscriptions tab, that you can successfully import it from there?

And that if you export a zip from settings, you can successfully import it from there?

**Comment by opusforlife2** [comment]
Closing until @aksrikanth replies.
