### ISSUE TITLE
Playlist video count doesn't match listed items if some videos were deleted

### ISSUE THREAD

**Issue by vkay94** [TeamNewPipe/NewPipe#4214]
**Version**: 0.19.8

If you search for a playlist on YouTube which contains deleted videos (removed by YouTube) they are shown as placeholders. The number of total videos is also "available videos + deleted videos". 
In NewPipe the number is the same, but deleted videos aren't shown (what should be) and the counter on the top shows both kind.

**Example**: Open this playlist in NewPipe : https://www.youtube.com/playlist?list=PLO_PZkaZtH1e5hXAe_UCiErc9eY8ga0Bo
On the top right there should be written "19 videos", in the actual list are 17 items.

**Comment by Stypox** [comment]
This is a problem with YouTube, it's not NewPipe's fault. NewPipe is not showing deleted videos because those do not provide any useful information to the user, but the number of streams counted by YouTube does not change and there is no way to calculate the number of non-deleted videos without fetching the whole playlist. So this won't be fixed.

**Comment by opusforlife2** [comment]
By "fetching the whole playlist", you mean fetching the stream information for each stream in the playlist, right? As if the user were to open each video one by one?

**Comment by Stypox** [comment]
@opusforlife2 no, I mean fetching every page of the playist info, in order to count how many videos are deleted and subtract that number from the one provided by YouTube to obtain the real number of videos (which I just realised is the same as counting the number of valid videos). This is obviously infeasible

**Comment by vkay94** [comment]
Ah okay, I understand. I hadn't thought about that playlists are also loaded by pages - sometimes it doesn't hurt to look into the extractor/fragments for a while I guess ^^
