### ISSUE TITLE
Add filter for incorrect youtube search results

### ISSUE THREAD

**Issue by teod0r** [TeamNewPipe/NewPipe#423]
Sometimes youtube and google show results that does not contain any search words neither in name nor in description. It would be nice if NewPipe have search filter that removes incorrect search results

**Comment by teod0r** [comment]
The same problem is in google play market. I already reported that problem for Yalp Store application

**Comment by coffeemakr** [comment]
If you search for "pppkmonn" you would show these results: [`Search instead for pppkmonn`](https://www.youtube.com/results?q=pppkmonn&sp=QgIIAQ%253D%253D)
instead of these: [`Showing results for pokemon`](https://www.youtube.com/results?search_query=pppkmonn)

or is it not related to the autocorrection?

**Comment by teod0r** [comment]
I hate that undisalable feature of google, but probably it is not related to autocorrection, because sometimes it shows similar to word results
