### ISSUE TITLE
Music.youtube.com

### ISSUE THREAD

**Issue by stralpt** [TeamNewPipe/NewPipe#4236]
please add youtube music and ability to download a songs or a playlist

**Comment by opusforlife2** [comment]
Always fill out the template we've provided, and always check for duplicates before opening.

Youtube Music streams already automatically play because they still come from Youtube. But Newpipe additionally added search filters to search on Youtube Music only. You can download songs just like any other Youtube video. Playlist download support is pending, you can check out the PR.

**Comment by AthenaZiff** [comment]
Yes, NewPipe is missing a YouTube Music tab
