### ISSUE TITLE
encrypt the exported database

### ISSUE THREAD

**Issue by panacist** [TeamNewPipe/NewPipe#4266]
just as the title states for security/privacy reasons i think you guys should provide a mechanism to encrypt the exported database either by using openpgp or a password

**Comment by Stypox** [comment]
In my opinion this should not be handled by the app, because the average user would not need this feature. Also, I think encryption libraries use some space, and we want to keep NewPipe lightweight. You can always install another app to encrypt and decrypt files, if you really need to. @opusforlife2 what is your opinion?

**Comment by opusforlife2** [comment]
OAndBackupX has encryption support for app backups. You can use that instead.
