### ISSUE TITLE
Make NewPipe available OEM Smart TV App Stores

### ISSUE THREAD

**Issue by mrpr3s** [TeamNewPipe/NewPipe#4270]
Please make NewPipe available on OEM Smart TV's like LG & Samsung inbuilt app stores. Both of them have different SDKs & app packages support though. 
Acc to my personal opinion Android based midrange Smart TV's are not much Powerful OR well optimized to run daily apps on such a low hardware specs its UI is somewhat sluggish/slow. But OS used by both of these OEMs (LG & Samsung) are well optimized to give optimal performance even in their midrange smart TV segments. So that's why i am requesting to make NewPipe for these OEM brands as these are widely used smart TV brands worldwide.

LG uses its own well know "Web OS"
Samsung uses its own "Tizen OS"
Here is the quick official Docs for building app for both OS

• LG's Web OS: [Docs](https://webostv.developer.lge.com/develop/building-your-first-web-app-webos-tv/) 
• Samsung's Tizen OS: [Docs](https://developer.tizen.org/development)

I hope soon an alpha/testing version of same will be released for both or any of one.
Thanks

**Comment by Stypox** [comment]
We already discussed this for other stores (e.g. AppGallery, XDA, etc.) and we decided this:
- Not if the stores require to remove features
  - Also not on e.g. Amazon Appstore, as then we'd need a separate build variant that uses Amazon's ExoPlayer, because their Fire devices are plain crap (i.e. buggy) and won't playback stuff otherwise
- Issue: other people publish without permission and nothing can be done about it. They should always ask for permission first. But legally they are allowed.
- Guidelines for packaging and management to streamline it:
  - policy issues: it is different if the code is recompiled, or just binaries are distributed
  - we do not support them officially
  - publishers take all of the responsibility
  - refuse and avoid distribution-specific issues

In particular, so, if someone wants to take the responsibility of publishing an app on another store with a prior discussion, we would be ok with it, but we (developers) do not want to do this ourselves because of the burden it would become. @TheAssassin did I explain correctly?

**Comment by Stypox** [comment]
Sorry for misunderstanding, I thought publishing on those stores would just be a matter of providing NewPipe's binaries to them, but it is not like that as Smart TVs do not support Android apps. So this is not related to NewPipe, which is an android-only app. See #1051 for more details
