### ISSUE TITLE
Popup restores bad size

### ISSUE THREAD

**Issue by TobiGr** [TeamNewPipe/NewPipe#4296]
### Version

- b69e477
- 0.19.8

### Steps to reproduce the bug
1. Open a video in popup mode while being in portrait mode
2. Rotate device to get in landscape and enlarge the popup to have a bigger height than the device width
3.1. Rotate to get back in landscape -> you'll have black bars at the top and bottom of the popup
3.2. [OR] Close the popup
3.2.1. rotate back to portrait mode -> player starts to play
3.2.2. Stop the player
3.2.3. Start the popup -> popup has the size from 2. and is only partly on the screen.

### Expected behavior
3.1. No black bars
3.2.1. Player does not start
3.2.3. Popup is not wider than the device width

### Screenshots/Screen recordings

[popup.m4v.zip](https://github.com/TeamNewPipe/NewPipe/files/5251239/popup.m4v.zip)

**Comment by avently** [comment]
Why did you marked the issue `[Unified]` if the same situation happens in 0.19.8?

**Comment by DoaaIkzamia** [comment]
Good afternoon all,

I need to join you to fixed this bug, Can I ?

**Comment by opusforlife2** [comment]
@DoaaIkzamia You're welcome to open a PR. :D

**Comment by DoaaIkzamia** [comment]
Dear @opusforlife2 and @TobiGr , 

About those bugs which you mention in this job issue, I studied the code (version 19.8)  and tried to solve them one by one and I started with this issue (3.2.1) it seems simplest than others. 

I wanna to ask you if you make paused for this video before closed pop up mode ? or without paused?

Thanks.

**Comment by DoaaIkzamia** [comment]
Dears,

About this bugs, You now that the version 19.8 is not available right now ((That exact version can't be run anymore because of YouTube changes. ))

- About bug 3.2.1 It fixed in the new version (20.8)  
- About bug 3.2.3 It still appear in the new version(20.8) and I fixed it in this commit c4f21c9 
- About bug 3.1 I will try to fixed it as soon as possible

Attached the video show you how it fixed it.
https://drive.google.com/file/d/1qDF-UjBEIDHosgxiLaTtMyX7BVMg9fGV/view?usp=sharing
Regards,
Doaa

**Comment by rancidfrog** [comment]
Pop-up does not keep the same size and position if you pause video and switch screen off and on. If you pause video into lockscreen and reopen player, no rotation, screen size and position resets.
Size and position should be persistent

**Comment by AudricV** [comment]
Is it still an issue on 0.26.1?
