### ISSUE TITLE
(Unified player) Unexpected behaviour upon tapping fullscreen button after video ends

### ISSUE THREAD

**Issue by opusforlife2** [TeamNewPipe/NewPipe#4322]
### Version

- https://github.com/TeamNewPipe/NewPipe/commit/b69e477ecdf576d0406c0de87db3c8a2866ce741

### Steps to reproduce the bug

Lock rotation to portrait. Let a video finish in fullscreen. The player will go back to video details and the replay button will show. Tap on the fullscreen button.

### Expected behavior

Not sure what the behaviour should be, actually.
- Should the fullscreen button just disappear when video finishes? Reappear if the user taps on Replay?
- Should the player go to fullscreen and start again? Stay paused?

### Actual behaviour

The player rotates to landscape, then back to portrait, and replays the video.

**Comment by avently** [comment]
Try this apk. I disabled rotation to portrait since it makes more issues than solves. When the video ends in fullscreen (in both orientations) the player will exit from fullscreen to non-fulscreen and will have the same orientation as had in fullscreen
[perf-with-orientation.zip](https://github.com/TeamNewPipe/NewPipe/files/5287514/perf-with-orientation.zip)

**Comment by opusforlife2** [comment]
This behaviour is fine, thanks! It also conveniently bypasses the lag issue when the player automatically rotated upon a video ending.
