### ISSUE TITLE
Exclude/Hide Channel/Group from general feed

### ISSUE THREAD

**Issue by Generator** [TeamNewPipe/NewPipe#4334]
#### Describe the feature you want

Ability to subscribe to a channel but not showing on general feed.
**Example:**
* **Documentaries:** Channel1, Channel2, Channel3
* **VLogs:** Channel4, Channel5, Channel6
* **Games:** Channel7, Channel8
Groups Documentaries and VLogs show on general feed, but category is excluded from general feed. Going to Subscription > Games (Group) shows the feed from all channel on that group.

#### How will you/everyone benefit from this feature?

People could subscribe to channels only for "bookmark" but not always show every time on feed, some channels upload several videos per day, spamming the feed.

**Comment by opusforlife2** [comment]
It's not compulsory to use the What's New feed. You can create your own and add them as tabs in the main page.

**Comment by RickyM7** [comment]
@opusforlife2 How can I do that? I want to add a channel group to the homepage but I can't find where to do that.
Note: This feature of hiding channel groups from the general feed would be very useful.

**Comment by opusforlife2** [comment]
Oh, sorry. I got confused. That's still a PR right now: #3556.

**Comment by RickyM7** [comment]
Got it!

**Comment by opusforlife2** [comment]
Closing in favour of #3319.

**Comment by amduae** [comment]
I would still like this feature separate from "Allow adding custom feeds as tabs" #3319 To me, they are not the same. 
This feature is specifically for the what's new tab "All" and having the option to exclude channels that you don't want to see because some channels your subscribed to fills it all. (Looking like spam as @Generator described it) 
The above is a case I'm going through and sadly my current solution is I unsubscribe myself from these channels cuz they ruin my "All" in channel groups and What's New Tab by forcing you to keep on scrolling down many times just to reach a new video by a different channel which posted just 2 days ago. 

Conclusion: It would be great to control What's New by excluding these type of channels (ones that publish every hour like news) or limiting X number of videos received from a channel (a number set by user in settings) This would still allow to get new videos from all channels but not takeover the whole What's New "All" feed. 

Would change the whole experience I think
