### ISSUE TITLE
[androidtv] Enable option to play automaticly in fullscreen

### ISSUE THREAD

**Issue by sorryusernameisalreadytaken** [TeamNewPipe/NewPipe#4387]
Would be needed on androidtv.
Nobody want autoplay in android without fullscreen. I really wanna say thank you for updating but from v19 -> v20 sadly its getting really difficult on androidtv (nvidia shieldtv).

It really hard to hit the fullscreen area with dpad controll. Can you add an auto-fullscreen.mode on android tv devices or devices with hdmi device?

**Comment by Stypox** [comment]
I'd rather make it simpler to get to the fullscreen button, instead of adding an option nobody would probably know about

**Comment by TobiGr** [comment]
what about a "double click"?

**Comment by peat80** [comment]
Just focus the video (play button), then press Down > Down > Enter. 🤷🏻‍♂️

A faster way to enter fullscreen (like the suggested double click) would indeed appreciated iated for a future release.

Anyways, 0.20 is a great release for me. On phone as on the SHIELD TV. 👍👍👍

**Comment by Generator** [comment]
0.20 was a big regression in my case, usually i share Youtube URLs to my Android Box, so they open with NewPipe, new i need to manually set the video fullscreen or always open with external app.  

Immediately downgraded to 0.19, the new version just became useless on Android Boxes/TV.

**Comment by TobiGr** [comment]
uhm, that's indeed a bug. The video should start playing automatically in fullscreen when sharing it and the video info is selected + autoplay is enabled in the settings.

**Comment by avently** [comment]
So you think pressing Down > Down > Enter is hard, right?

**Comment by anbuchelva** [comment]
> So you think pressing Down > Down > Enter is hard, right?

Yes for my mom, who is 60+. It was just easy till 19.8, hit play button and it plays full screen.

**Comment by XandrosDarkstorm** [comment]
I also think there should be an option to play video in fullscreen automatically without the need to push "Fullscreen" button. Playback on info page is not useful for me at all — video "window" is too small and i always watch videos in full screen (that is the reason why i got phablet, instead of smartphone in a first place).

**Comment by opusforlife2** [comment]
@XandrosDarkstorm #4152.

**Comment by avently** [comment]
You are talking about fullscreen after play, it can be easily implemented but the problem I see is when the device is in portrait mode. So what do you expect to happen after play when your device is in portrait?
• device stays in the same orientation but opens on fullscreen
• device switches to landscape and opens in fullscreen?

Automatic action can only be made when you have global autorotation disabled (I.e. locked to portrait or landscape).

And a part of the question, what should happen when you stopped watching the video (I.e. video finished or you pressed back button)?

What do you expert to see when the global autorotation is enabled?
• device should go into fullscreen
• nothing should happen?

The problem is these questions I don't have universal answers for. Because some people would want one behavior, another people want other behavior. From my point of view, the app shouldn't go into fullscreen when the rotation is not appropriate for the video. For example, when the device in portrait (with locked orientation) playing horizontal video in fullscreen should only be possible after automatic rotation to landscape. Same for vertical videos: fullscreen should only be possible when device already rotated or rotated automatically to portrait. The autorotation i'm talking about is already implemented (on phones) and you can test how it works in playlists with mixed horizontal and vertical videos: in locked orientation in fullscreen your phone will be rotated to different orientations appropriate for a video orientation.

**Comment by Generator** [comment]
@avently you can't put an AndroidTV device in portrait mode or rotate, they always in landscape. 

This issue is related to AndroidTV, not phones.

**Comment by avently** [comment]
@Generator it's a question for both this and #4152 because it's the same problem and should be handled in some way. It couldn't be just android TV specific setting

**Comment by Multipanda** [comment]
I would also love an option for it to automatically go full screen. It's a tad annoying having to push full screen every time. 

If I have to push anything I actually prefer the old app where when pushing play it went to full screen when starting.

**Comment by luminous706** [comment]
Hello, any progress on this? I would like to share a youtube link to a secondary phone and NewPipe would start the video in fullscreen automatically, this is for my toddler when he watches videos - I want to control what he watches and want the videos I share to open fullscreen.
