### ISSUE TITLE
Detect if sensors are disabled and show fullscreen button depending on it

### ISSUE THREAD

**Issue by 7ritn** [TeamNewPipe/NewPipe#4394]
### Checklist

- [x] I checked, but didn't find any duplicates of this issue in the repo. 

- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want
If sensors are disabled show the fullscreen button.

#### Is your feature request related to a problem? Please describe it
When rotation is disabled the fullscreen button is shown. However, when you disable all your sensors (possible starting from Android 10) you also can't auto rotate the screen and therefore not switch to landscape mode.

#### How will you/everyone benefit from this feature?
Well I hope it should be easy to implement and I bet there are more people than me, who disable their sensors so apps can't collect more data about me. So this would be a great quality of life change, because then I would be able to switch to fullscreen mode even if I have my sensors disabled but not the auto rotate as well.

**Comment by eladkarako** [comment]
True. Moreover full screen button should always be enabled, either at the bottom or at the opened menu for the sake of accessibility.

**Comment by blackbox87** [comment]
https://source.android.com/devices/sensors/sensors-off

>When Sensors off is enabled, the sensors stop reporting any data to the system or apps. An app can still request a sensor and register a listener when Sensors off is enabled, but either silence is returned for the mic or the onSensorChanged callback is never invoked for the sensors. As soon as the tile is disabled, those same listeners start to receive the actual output from the mic or the expected callbacks to onSensorChanged without needing to do any additional work. The default behavior of silenced sensors is as follows.

The setting is specifically designed for developers to test their apps. It's not something that you should be using as a privacy feature since some information (e.g. sensor name, version or vendor) is still accessible and the sensors aren't actually fully disabled.

We can't detect it the setting is enabled or not because we don't can't access SensorPrivacyManager to query isSensorPrivacyEnabled(). And Google has started to harden the use of hidden APIs, so reflection isn't an ideal option here either.

If you disable auto-rotate then you'll see the fullscreen button.

**Comment by blackbox87** [comment]
https://source.android.com/devices/sensors/sensors-off

>When Sensors off is enabled, the sensors stop reporting any data to the system or apps. An app can still request a sensor and register a listener when Sensors off is enabled, but either silence is returned for the mic or the onSensorChanged callback is never invoked for the sensors. As soon as the tile is disabled, those same listeners start to receive the actual output from the mic or the expected callbacks to onSensorChanged without needing to do any additional work. The default behavior of silenced sensors is as follows.

The setting is specifically designed for developers to test their apps. It's not something that you should be using as a privacy feature since some information (e.g. sensor name, version or vendor) is still accessible and the sensors aren't actually fully disabled.

We can't detect it the setting is enabled or not because we can't access SensorPrivacyManager to query isSensorPrivacyEnabled(). And Google has started to harden the use of hidden APIs, so reflection isn't an ideal option here either.

If you disable auto-rotate then you'll see the fullscreen button.

**Comment by 7ritn** [comment]
Thanks for the reply. I now understand that the sensor tile just supresses the output of the sensors. It would still be great to have the option to enable the fullscreen button all the time. But I guess that is a different issue.

**Comment by nbmrjuhneibkr** [comment]
Full screen button should always be visible, there's no reason to hide it under any circumstances.

**Comment by opusforlife2** [comment]
Considering @blackbox87's answer, I'm closing the issue. 👍

**Comment by blackbox87** [comment]
@eladkarako Why the nagative reactions? The title clearly says "Detect if sensors are disabled and show fullscreen button depending on it", but there isn't an API available to detect that setting, so that's why this issue was closed.

Maybe you should post to issues/4414 since what you're asking for is the functionality of v0.19.8 to be restored?

I agree with you by the way. I made it perfectly clear to avently (who is responsible for many of these changes) during development that people would complain and create issue reports like this, but he didn't seem to care and continued to create pull requests that further changed NewPipes behaviour. And of course now that v0.20.0 has released there's plenty of complaints and some people are upset with him.
