### ISSUE TITLE
[Bug] url signature

### ISSUE THREAD

**Issue by taguel** [TeamNewPipe/NewPipe#440]
- [ ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ] I checked if the issue/feature exists in the latest version.

I apologize for my english... 
When I try to open a link it says in French : "erreur lors du décryptage du lien" and it doesn't open anything. 
Kind regards

**Comment by hakusdream** [comment]
Same issue here. Seems to be something related to a new site design.

**Comment by muglyObserver** [comment]
I'm sure my French is worse than taguel's English :-), but I believe I am experiencing the same problem.  NewPipe will successfully launch and search, but if I tap on any of the results, I receive a message "Could not decrypt video URL signature." And NewPipe hangs until I press return.  This occurs on 0.8.7 and 0.8.8.  

I am using a Samsung Galaxy Tab 2  10.1 GT-P5113 running Android v4.2.2.

**Comment by hakusdream** [comment]
Issue appears here on 0.8.7 and 0.8.8, on an official AOKP Nougat ROM, on a
Droid Turbo.

Issue is not fatal, it can be escaped by tapping the "back" arrow.

On Feb 1, 2017 12:53, "muglyObserver" <notifications@github.com> wrote:

I'm sure my French is worse than taguel's English :-), but I believe I am
experiencing the same problem. NewPipe will successfully launch and search,
but if I tap on any of the results, I receive a message "Could not decrypt
video URL signature." And NewPipe hangs until I press return. This occurs
on 0.8.7 and 0.8.8.

I am using a Samsung Galaxy Tab 2 10.1 GT-P5113 running Android v4.2.2.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/TeamNewPipe/NewPipe/issues/440#issuecomment-276729651>,
or mute the thread

**Comment by Bahjesaispas** [comment]
Same bug for me version 0.8.8 on cyanogen OS

**Comment by tesla97** [comment]
Youtube has recently changed their site security
It gave trouble to **youtube-dl** too --- They fixed it the next day

And Newpipe is also effected with this
Waiting for the FIX...
error is

**"Couldnt decrypt video URL signature "**

**Comment by hakusdream** [comment]
Note: applicable *youtube-dl* commit is available here for reference:

https://github.com/rg3/youtube-dl/commit/3c90cc8b6fc069930264b41f5505dc34c1077442

**Comment by tesla97** [comment]
Awesome FIX
Working as usual
