### ISSUE TITLE
2 finger swipe to close player

### ISSUE THREAD

**Issue by wb9688** [TeamNewPipe/NewPipe#4469]
### Checklist

- [x] I checked, but didn't find any duplicates of this issue in the repo.
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

It would be nice if it's possible to swipe down with 2 fingers on the player in order to close it, like you could currently do by swiping down twice. In e.g. Android's notification bar, you could also swipe down with 2 fingers to do the same action as swiping down twice, so I think this gesture would make sense.

#### Is your feature request related to a problem? Please describe it

I usually don't want to have the bottom sheet, so I currently have to swipe twice, which is annoying, especially as the bottom sheet is a relatively (compared to the full player) small area that's on the, so it's harder to swipe at.

**Comment by vkay94** [comment]
I might look into it if you want to since currently I try to analyze/"rewrite" the `PlayerGestureListener` class for my feature request (make it more readable => abstract class for all logic and the inherited for UI - like server and client decapsulation ... more or less xD)

If you're interested what I mean: https://gist.github.com/vkay94/1ea052d13d347f462d76cce15eee3344

**Comment by avently** [comment]
@vkay94 cool! Will you adapt swipe in the middle of player to go to description? Or it's not a goal?

**Comment by avently** [comment]
Actually a fix for the issue located inside CustomBottomSheetBehavior (not in PlayerGestureListener)

**Comment by opusforlife2** [comment]
I didn't pay attention to this before, but the close button in the player in video details disappears when you go full screen. What if we were to have this button there as well?

**Comment by vkay94** [comment]
@avently 

>Will you adapt swipe in the middle of player to go to description? Or it's not a goal?

Firstly, I had it in mind to include this goal as well on the fly, but as you said the logic is in another class. 

Actually `CustomBottomSheetBehavior` is some kind of  singleton in the app like your `PlayerHolder`, so there could be a possibility to make it work with static variables and methods from outside I guess.

**Comment by avently** [comment]
@vkay94 

This text:

>fix for the issue located inside CustomBottomSheetBehavior

Related to this issue (not my question).

My question can be fixed by changing code in CustomBottomSheetBehavior or FlingBehavior and in PlayerGestureListener. The problem here is we need to pass through three gesture detectors and the final interceptor should be FlingBehavior because it can collapse appbarlayout. Complex task, yes.

**Comment by vkay94** [comment]
@avently 

>Related to this issue (not my question).

Yeah, I got that - basically both questions rely on the behavior class ^^

>The problem here is we need to pass through three gesture detectors and the final interceptor should be FlingBehavior because it can collapse appbarlayout. Complex task, yes.

I've played a little bit and made at least the two-finger-swipe-to-dismiss-feature work (with some agile development limitations of course): [app-debug-two-finger.zip](https://github.com/TeamNewPipe/NewPipe/files/5358006/app-debug-two-finger.zip)

Limitations:
- Works only in landscape (`isFullscreen` variable must be false)
- If you open a second video and close it with a single finger, the sheet disappears too. You have to wait until it begins to load (loading progressbar / controls need to be visible since the gesture).

I used `BottomSheetBehavior`'s `setSkipCollapsed`-method and the singleton / instance pattern to set it globally.

**Comment by avently** [comment]
@vkay94 just open a PR and I can say what's 100% wrong in implementation. Hard to say without seeing the code.

I think implementing double finger swipe to dismiss should be really easy and only custombottomsheetbehaviour should be used. And it will work regardless of fullscreen or orientation.  Basically you just need to add here 
https://github.com/TeamNewPipe/NewPipe/blob/dev/app/src/main/java/org/schabi/newpipe/player/event/CustomBottomSheetBehavior.java#L47 :
```java
&& event.getPointerCount() == 1
```

Or something similar to check number of fingers. If fingers == 1 the `if` will check other data but if fingers == 2 bottomsheet will intercept the touch. If this happened, you just need to temporary disable collapsed state. After bottom sheet established it's state in collapsed/hidden/expanded enabled collapsed stare in fragment. That's it

**Comment by vkay94** [comment]
Yeah, you're right, that's the better place to set it up, not `PlayerGestureListener` (but I also used `event.getPointerCount()` as the documentation describes :')).
