### ISSUE TITLE
Clear all user data while exiting the app

### ISSUE THREAD

**Issue by andiandi13** [TeamNewPipe/NewPipe#4570]
### Checklist

- [x] I checked, but didn't find any duplicates of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

It would be an option that would delte everything when the app is killed _or_ you can add an "Exit" button as well as an option to clear everything using that button.

**Comment by Stypox** [comment]
Thank you for the feature request! The checkboxes are not optional, though.

Anyway, I don't think this is a good idea, since it is a very niche feature that would involve adding a button and a setting, and what you mention can already be achieved with a few more taps. So I'd not implement something particular just for a very limited numer of users.

**Comment by andiandi13** [comment]
@Stypox I apologize, I forgot to check them, I edited my post.

You think so ? It's bothering to go to settings, history & cache, and delete everything each time we finished using the app... At least if there was a quick shortcut to clear every data in one click.

What do you think?

**Comment by opusforlife2** [comment]
Why not just disable history so that nothing is saved in the first place?

**Comment by B0pol** [comment]
> Why not just disable history so that nothing is saved in the first place?

On Firefox:
basically, you don't have history anymore at all. Clear data on exit is a good middle ground: you exit the browser, "everything" is deleted (ofc i'm talking about local data here).

On NewPipe i'd like something like that, and disabling comes with a huge downside (whereas on Firefox it's a minor thing): you lose playback if you leave the video and open it 5 seconds or 5 minutes later. That's why Iet history enabled and delete it regularly on NewPipe

**Comment by opusforlife2** [comment]
@B0pol For that, see #4056.

**Comment by opusforlife2** [comment]
Closing until @andiandi13 replies.
