### ISSUE TITLE
Display YouTube's "fake news" warnings and infoboxes

### ISSUE THREAD

**Issue by realpixelcode** [TeamNewPipe/NewPipe#4614]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want
NewPipe should display YouTube's "Fake News" warnings, for example when the video is about Corona and YouTube links to legit information from the WHO. And when a YouTube channel belongs to a public broadcast service there's also an info box NewPipe should display too.

![YouTube infocards](https://user-images.githubusercontent.com/52963327/97023533-299cca00-1545-11eb-81a5-842b80f0f25e.png)

#### How will you/everyone benefit from this feature?
NewPipe users will also be able to identify misleading contents, fake news and propaganda and to get legit facts about the respective topic.

**Comment by peat80** [comment]
Please not. I'm glad i don't have to see this. 🤣🤣🤣

**Comment by ADepic** [comment]
Sometimes it is very useful, for example when it shows that CGTN is Chinese state owned media. (So you know it is propoganda basically)

**Comment by johanw666** [comment]
If this is going to be implemented, please make it a setting to remove it. I don't need the US tech companies indoctrination.

**Comment by Sgt-Miller** [comment]
As long as its optional. I like NewPipe because its UI is very slim.

**Comment by realpixelcode** [comment]
> 
> 
> As long as its optional. I like NewPipe because its UI is very slim.

Well, yes, an optional implementation would be great.

**Comment by opusforlife2** [comment]
I think it makes sense for it to be an option. Those who wish to know which videos are flagged should be able to do so. It's just another tool.

**Comment by opusforlife2** [comment]
The next question is: should it be on by _default?_

**Comment by realpixelcode** [comment]
> 
> 
> The next question is: should it be on by _default?_

Well: As you see, there are some users who don't like this feature. But the regular user who switches from YouTube to NewPipe should find everything as usual from YouTube including those infoboxes. If he doesn't like the feature he's free to disable it. That's at least my idea of this.

**Comment by MapleWheels** [comment]
Honestly, this is a non-issue and a back burner feature. We already have a ton of issues with the new 0.20.x UI system that needs to be fixed. There's no reason to add an unnecessary feature at this point.

**Comment by HTSamurai** [comment]
I think it should be an option, in case someone doesn't want it

**Comment by Wahbam** [comment]
I think this is a terrible idea.  I can already tell when I come across false and misleading information.  It's called questioning everything and doing research.  It takes work, and there's no easy solution as simple as believing whatever Youtube says.  I don't need US tech companies doing my thinking for me.

The sources that companies like YT use to "fact check" are themselves highly dubious, obviously biased, highly political and propagandized, politically funded, and stuck in their filter bubbles.  Tech companies, media, academia, and so called independent entities and public organizations are frequently politically aligned, and this is not by accident.  They blatantly masquerade their confirmation bias circle jerking as critical discourse, and use it to quash legitimate critical thinking and healthy disseting views from reaching people.  On a plethora of important issues, the "official" fact checking has been legitimately contested by multiple respected sources and/or the original supporting data was cherry picked from inconclusive or disputed research (e.g. viability of solar/wind as eco-friendly primary energy sources, efficacy of masks), or outright debunked as false and politically motivated (e.g. efficacy of lockdowns in preventing infection or death, COVID danger to children or young teachers attending school, climate change as cause of US forest fires and hurricanes, Biden laptop being unverified or Russian-sourced disinformation).  No retractions were ever issued and in many cases big tech continues to enforce content restrictions based on these false narratives.

Big tech is carefully selecting which sources they use to fact check based on their own views and confirmation bias.  And the few parties actually fact-checking these fact-checkers are simply ignored.  In this way, big tech edits content and decides what gets published without being accused of editing or publishing and thus forfeiting their protected position as a platform under the legal limitations of the 230 clause.

I don't need protection.  I need information.  I can make my own decisions, and believe it or not, so can everyone else.  We've been doing it for thousands of years.  Every barrier you put in the way between an individual and the world they experience serves only to box them in from where they can go and what they can be; what they can sense and what they can know.  A marble rolling across a table strewn with pencils wont go very far, but will probably still fall off the edge.  You're not doing favours by adding any "feature" that discourages someone from exploring ideas, based on your own conclusions.  This only denies that person the growth of undertaking that thought journey themselves and arriving at their own conclusions.  And repeated warnings do discourage - that's the trick and the whole point.  You don't have to close down a road to prevent its use if you put down enough speed bumps.  This is tyranny, no matter how much they try to pass it off as benevolence.  Since at least the start of the 20th century, such "tyranny as benevolence" is the hallmark of every oppressive regime at its infancy: later comes the book burning, statue-topling, murder, misery, starvation, genocide.

Tens of millions of informed people think what YT does in regard to filtering, promoting, supressing, blocking and subjectively discrediting non-violent, non-extremist ideas is unhealthy to individuals and to society.  Many like myself believe it is reprehensibly evil.  I think at the very least ideas within the Overton window, as decided by the metacontent of overall public discourse and not by some academic or media think tank, should be treated with absolute neutrality, while anything outside it should be examined and acted upon only with serious accountability and responsive recourse.  Media and big tech, like politicians, should be in the business of detecting, not defining, where the overton window lies.  Any society where these entities do more of the latter can no longer declare itself a free society and has moved away from democracy.

I choose software that breaks these kinds of shackles wherever possible.  I'll stop using newpipe if such a feature, as requested by this thread, were implemented mandatorily, and would immediate seek alternatives if they were optionally implemented by default.  I would only support their opt-in implementation for the purpose of allowing users to test and compare the experience and for those few who don't trust in their own ability to discern between fact, fiction, deception, and dillusion (e.g. a schizophrenic).

**Comment by ADepic** [comment]
Oh no! It now links to the wikipedia page for climate change! THIS IS LITERALLY BIG TECH PROPOGANDA !!!!! 🤣🤣🤣🤣

**Comment by ADepic** [comment]
As far as I've seen, it literally links to wikipedia pages on the topic (and sometimes WHO).

Like I've mentioned, it can help identify state funded propaganda media, such as CGTN for example.

"It's called questioning everything and doing research"

Yeah. I'm sure you read a dozen scientific papers on a topic to confirm that a YouTube video is correct.

**Comment by ADepic** [comment]
Inb4 this gets 100% dislikes

**Comment by ADepic** [comment]
Oh shit you sounded like a condpiracy believer / conservative with your "do your research" nonsense, turns out you a actually are. Lol, this confuses me. The idea of free software is literally socialist (abolishing intellectual property for software, basically sharing your software among others, which sort of works like workers owning means of production).

It always confused me as to why so many conservatives are bound to this obviously anticapitalist movement??

Literally the values of free software go against that of capitalism (that is why it will never succeed because socialism doesn't work, so free software won't either).

Oh yeah, as for lockdown:

https://academic.oup.com/cid/advance-article/doi/10.1093/cid/ciaa1502/5917573

https://www.thelancet.com/journals/lancet/article/PIIS0140-6736(20)32034-1/fulltext

When you say "do your research" it means listen to random YouTube frauds, not actually read the science lmao.

Plus science isn't even written to be easily understood by average people, that is why degrees are done to be a competent scientists. Otherwise we could all just be freethinking high IQ individuals educated through YouTube and Bitchute 🤣🤣🤣🤣

**Comment by realpixelcode** [comment]
> 
> Oh no! It now links to the wikipedia page for climate change! THIS IS LITERALLY BIG TECH PROPOGANDA !!!!! 🤣🤣🤣🤣

This was exactly my first thought on this 😂

**Comment by TheGinGear** [comment]
Why not just, make it toggleable? it's a feature not a base function

**Comment by johanw666** [comment]
[quote]It always confused me as to why so many conservatives are bound to this obviously anticapitalist movement??[/quote]
You are probably confused because politics does not move on a one-dimensional scale. The relevant issues may depend per country, at the moment they seem to be "economics" and "social structure" (English is not my native language, I might be using the wrong terms here). but the classic situation (economic left combined with social left, economic right combined with social right) are definitely not the only combinations. In the US Democratic party there is a strong influence of mixing economic right with social left.

That leaves one option open, and the combination economic left and social right is gaining more popularity recently. Often by nationalistic parties. In the US it seems not to occur in any party or wing within it AFAIK. But I assume they feel better at home in the republican party because the social left in the US looks from the ouitside as dogmatic and intolerant of herretic opinions as the regime of the USSR in its worst days.

**Comment by TheGinGear** [comment]
Guys, this is a GitHub page for feature requests and issue tracking. Take the political debate to private messages or a different platform, seriously

**Comment by ADepic** [comment]
That being said I am skeptical this feature provides much use. If a climate change "skeptic" sees a link to the wikipedia page on climate change, is that really going to change their mind.

Also, can someone list out what pop-ups are shown?

1. Wikipedia links
Conspiracy believers will find this controversial.

2. Link to who on covid
Conservatives, conspiracy believers will find this controversial

What else is there?

I am pretty sure there aren't "fact-checks" like Facebook.

I would understand why people would be opposed to that.

**Comment by TheGinGear** [comment]
So? That's not on this application's plate to fix those issues unless he wants to hire a company to manually fact check every single video. That's on YouTube. This is a feature request to port over a single feature into the NewPipe app. 

The effectiveness of the feature in specific personal situations are not relevant, as NewPipe did not come up with it, nor does it manage it. The reason that it would be implemented is because the users want it, and because they can. Opinion on the effectiveness is purely extra motivation for actually working on it.

**Comment by Wahbam** [comment]
Wikipedia is not a reliable source of information.  Neither is WHO for that matter - without careful scrutiny - as they are politically compromised despite many good and respectable people working within.  Even so, big tech chooses to cite legitimate info put out by WHO and declare them a definitive authority when it agrees with their political priors, only to later willfully ignore info from the same source when it doesn't agree by silencing voices, stories and claims strongly supported by WHO, UN, and leading economists, researchers, scientists, educators, thought leaders, industry experts, etc.  Whatever variey of fact checking and validation YT uses, it is not neutral and has a demonstrably negative value in the overall dissemination of information which is arguably not balanced by its positive impact.


ADepic, you know nothing about me, my political inclinations, or my knowledge or lack thereof, or methods and standards by which I educate myself.  In my opinion, your ad hominem attacks are inappropriate to this forum.

By your rapidfire derogatory reactions, evidently replying before even reading my entire comment, you're clearly behaving as one of those really angry twitter types who likes to shut down anyone who disagrees with you and call others to do the same.  Your first recourse was to ridicule and taunt and suggest others do the same.  I've seen no evidence you have any impulse to have an honest and civilized discussion.  You don't care what others think because you already KNOW, is seems.  You make it seem there's nothing someone the likes of me could possibly have to say that's of any value to you.  Why listen to anyone when they're all just stupid people who don't think what you think, which is the only correct way to think?

I wish I could admire your fervor and passion, or applaud you for taking an individual position and sticking to it.  But everything you said is so cookie-cutter and typical of our brainwashed youth who've lost the ability to think critically and the tolerance to have a conversation with someone who disagrees with them.  Everything is binary, and anything that doesn't fall in your lane must be labelled conspiracy theory.  He world is much more nuancdd than that.

*sigh*  I imagine you can't look in the mirror and see the tragedy of your outlook and behaviour right now.  But I hope it's just immaturity and that one day you will see the rabid intollerance and narcissism in your treatment of others as you've exemplified here, and realize that you do indeed have have a lot to learn by being less judgemental and impulsively combative.  Even better would be if you're just having a really bad day, and this doesn't reflect who you really are.

Intelligent people know they exercise their intellect by listening, not speaking.  And good scientists know that it's not a sin to not know something, only to think you do when you clearly don't.  Also, "It's better to have questions you can't answer than to have answers you can't question."

With that, I feel I've adequately stated my position on the issue and responded to the ad hominem attacks directed at me.  I'm feel this discussion and all others should continue with an interest of improving the software and encourage all points of view be considered with due respect, with a focus on the user experience rather than morality or top-down regulation, in agreement with what TheGinGear suggested.  Beyond that I have nothing further to contribute.

**Comment by B0pol** [comment]
I locked this conversation, there are too many off-topic comments.
