### ISSUE TITLE
Background Player randomly stops playing

### ISSUE THREAD

**Issue by shmil111** [TeamNewPipe/NewPipe#4706]
Hello,
since updating to the 0.20 version of the app there was this constant bug, that i hoped would get fixed in future patches, where the background Player randomly stops playing in the middle of songs, and desplays a "loading" icon.
![Screenshot_2020-10-29-17-27-18-986_org schabi newpipe](https://user-images.githubusercontent.com/50473311/97605164-feb7e780-1a16-11eb-9cf6-8d8aa146897b.jpg)
when i skip back and forth through queue it keeps desplaying the "loading" icon.
![IMG_20201029_183708](https://user-images.githubusercontent.com/50473311/97605218-0ecfc700-1a17-11eb-9440-12ec69f83db3.jpg)
when i click on the song and press to "Details" and press the "Play in the background" button it resets the queue and goes back to normal, but it resets and delets the queue that way and the songs randomly stop so often that it makes the app almost unusable.
i don't think it's a network issue, but even hypothetically if that was the case that i lost connection for a second and that was the cause of the stuttering, theoretically when i gain back internet access it's supposed to go back to normal, but it seems that unrelated if the internet is working or not it keeps on being stuck with the "loading" icon.

**Comment by Idiotten** [comment]
Yeah, I still have it as well. It's issue #4432. 
PR #4562 fixed it, but that didn't have the fix for the constant parsing errors. So if you try to use that one now it just gives you an error over and over. We just have to wait. The only way "around" it is to set background play on one song, and stay on that song's screen. Turn on autoplay and it will keep going through fine. It sucks that you can't pick the queue, but  autoplay gives similar stuff to the first song and at least it plays something.

**Comment by shmil111** [comment]
> Yeah, I still have it as well. It's issue #4432.
> PR #4562 fixed it, but that didn't have the fix for the constant parsing errors. So if you try to use that one now it just gives you an error over and over. We just have to wait. The only way "around" it is to set background play on one song, and stay on that song's screen. Turn on autoplay and it will keep going through fine. It sucks that you can't pick the queue, but autoplay gives similar stuff to the first song and at least it plays something.

thanks for the detailed response! hope it will get fixed soon.
