### ISSUE TITLE
queuing download while offline for seamlessness

### ISSUE THREAD

**Issue by cauerego** [TeamNewPipe/NewPipe#4741]
this may sound very niche, but hear me out...

this is different from #155. my use case is also a bad internet connection. in fact, i think newpipe have 2 big usage cases: add to internet redundancy/backup and watching with no internet. right?

when internet is bad, more often than know i not, i can get the link. but i can't even load the page!

so, in a way, this is just another way to look at the same issue which might make it much easier to implement them all. 😘

hopefully. 😁

making just this possible would also help with #4195.

but, of course, integrating #478 and fixing #4460 could be a great addition to this, so the experience of bag internet connection can appear to be as seamless as possible!

which, in the end, is the goal of all those issues.

**Comment by opusforlife2** [comment]
Don't delete the template. Now I have to ask for info you would have already provided.

You can already queue downloads when offline. What specifically are you looking for?

**Comment by cauerego** [comment]
very strict, huh?

there, edited op.

i really can't queue download when offline. but i'll double check, take screenshots, and come back to report... by editing this and the op. 😁

thanks, and
cheers.

**Comment by cauerego** [comment]
well, editing doesn't allow to add screenshots, apparently.

so, here they are:

![Screenshot_20201031-145930](https://user-images.githubusercontent.com/560418/97782598-5460d100-1b8a-11eb-9f76-e9c81921b82e.png)

![Screenshot_20201031-145946](https://user-images.githubusercontent.com/560418/97782592-4d39c300-1b8a-11eb-8da1-2c667fbbf499.png)

**Comment by jwmh** [comment]
Bump.  Can this issue be re-opened, please?

**Comment by opusforlife2** [comment]
Whoops. No idea why this didn't generate a Github notification. Otherwise I would have reopened it... 1.5 years ago. Damn.

**Comment by opusforlife2** [comment]
A prerequisite for this will be to have default download settings (and fallbacks for every case where there is conflict), so that downloads can be started with just the link, without opening the download dialogue.

**Comment by vhda** [comment]
I think this is similar to what I'm looking for.
I'm assuming newpipe has a memory cache, what I think this person (and me) is looking for is a disk cache.
I see two use cases:
1. Sometimes I'm watching a video and in the middle of it I need to leave home. It would be nice to have a button to "Cache remaining (or complete) video", so that I could continue watching the video while offline. Cache would be automatically deleted when switching to a new video.
2. This is more what OP was looking for. I'm about to leave home for a longer travel and want to queue a bunch of videos. Now, this is not a simple cache but more about downloading and managing the videos, which is something you already made clear you don't want to do. As an alternative I'd propose that newpipe download the videos and queue them in an external media player. This would probably require the availability of an Android API that would allow this. Maybe the "Share" protocol would be enough? In this case users would need to manage the downloaded videos.

Note that 1. could be implemented through feature 2. Newpipe could download the video and pass it seamlessly to another media player using the current timestamp, instead of having to implement a disk cache.

Thanks in advance!

**Comment by opusforlife2** [comment]
@vhda How is 2 different from simply downloading stuff through NP and then watching using another app, which you can do even now?

**Comment by vhda** [comment]
I still have to open the second app a select *again* the videos I want to watch. And if I want to continue watching something offline, I have to open the video in the new app, go back to NP to memorize the current time, and then go back to the second app and skip until around that time. That is, if in the meanwhile NP still allows me to open the video due to now being offline (I've noticed some random breakages when NP reaches end of cache while offline).

**Comment by opusforlife2** [comment]
What I meant was:
- You know you're going to go out.
- You download a bunch of videos.
- You watch them using VLC etc.

No need to switch back and forth between apps.
