### ISSUE TITLE
Why does it take so much time for default F-Droid repo. to get NewPipe update?

### ISSUE THREAD

**Issue by bphd** [TeamNewPipe/NewPipe#4772]
Read wisely, I didn't asked how to get it faster, because I know how

I heard about hassle of reproducible compilation of F-Droid market, but it should be a one time problem (apparently resolved because you still in the store), so why does it takes so much time?

(3 days for 0.20.1; more than 6 days for 0.20.2 etc.)

_______________________________

### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

Something to get replies

#### Is your feature request related to a problem? Please describe it

Yeah, no replies

#### How will you/everyone benefit from this feature?

They'll know why they have to wait more time with default configuration

**Comment by PFDaily** [comment]
January 24th I asked FDroid team this same question. Here was the response I got. 

Hi Paul,

NewPipe is set up so that F-Droid automatically checks for updates. So
as soon as 0.18.2 is tagged, our updater should note this and queue it
for build (consider that the "automated way to kick off builds"). This
might take a little, though; usually between 1 day and 1 week (as after
the build there are also some manual steps to perform, including
signing the APK).

Best,
Izzy.

**Comment by bphd** [comment]
Okay I get it, it's not fully automatic so depending of team availability it can take a lot of time

Thanks!

**Comment by PFDaily** [comment]
I know you closed this issue, but you could consider posting to fdroid team's repo and maybe they can give more attention to a less manual process. 
https://gitlab.com/fdroid/fdroidclient/-/issues

It's my belief that it is an organizational risk to automate signing apks, but I agree it could go faster.

**Comment by bphd** [comment]
Already done 4 days ago https://gitlab.com/fdroid/fdroidclient/-/issues/2099

**Comment by tuxayo** [comment]
Here we can follow the fix of the root cause: https://gitlab.com/fdroid/fdroidserver/-/issues/797
