### ISSUE TITLE
What about supporting other sites over youtube-dl?

### ISSUE THREAD

**Issue by timofonic** [TeamNewPipe/NewPipe#48]
I know it's coded in Java. I wish it would be in C++ and usable easily over libmpv. This way, other projects would share resources and  support a lot more than YouTube easily.

But I'm just pipe dreaming...

Thanks for newpipe. Another little step to fight against the cloud dystrophy

**Comment by epitron** [comment]
There might be a way to automatically port most of the YouTube-dl extractors to Java - their definitions contain a lot of metadata. The remaining bits of code could be ported by hand.

There are only a few sites that most people use as well. Personally, the only one I need added is vimeo. It wouldn't be much work.

**Comment by kofalt** [comment]
I was just wondering if there's a future for NewPipe at > 720p, thanks to the separate streaming of audio & video above that quality. Something like triggering both & ffmpeg combining, etc.

Youtube-dl would be a potential solution for that problem. Open question if it's the best solution.

**Comment by epitron** [comment]
There's probably a less bulky solution to multiplexing audio and video streams then including all of ffmpeg and python. :)

At the very least, the necessary C muxer could be pulled out of ffmpeg's source. I would be surprised if there wasn't a java version of it either.

**Comment by theScrabi** [comment]
Well actually NewPipe is designed to accept more than only one Streaming Service. So far i didn't whant to add support for other services, witch has several reasons.
1. I first wanted to concentrate on getting ready with the youtube implementation, so that is working prober before moving on. 
2. The interfaces you have to implement in order to create your own (StreamingService) are not in their final design. Which means if someone does want to add support for another service, this peace of code might not continue working in a later version.

So for that i thought about a roadmap:
Until version 1.0 i what to get rid of bugs and implement all the features i imagined at the beginning.
These features are:
Propper downloading manager.
Propper music streaing.
Support for next or related videos.
Support for channels, and playlists.
Subscription and notifications for channels.

Up until version 2.0 I wanted to concentrate on Multi service support. Which means getting the interfaces involved into a final state, and document it, so that others can write code for additional services.

If you are interested, you will find the code related to it here:
In this file all the services listed witch are supported by this version:
https://github.com/theScrabi/NewPipe/blob/master/app/src/main/java/org/schabi/newpipe/ServiceList.java

In order to create a new Service you have to implement:
StreamingService
Extractor
SearchEngine
and then add it to this list.
But its not documented yet, so you might have a bad time trying to get thinks working at the moment.

**Comment by timofonic** [comment]
As an easy testing, maybe you can add support for simpler services. For example, FTP and DAV

I would suggest support for adult sites. Despite the taboo, many of us would love it and it would make your app quite popular xD

**Comment by theScrabi** [comment]
As I said, not write now. If we now implement support for serveral services, we might have to reprogram those at a later time, if the interfaces speaking with the extractors for that service change. And since not all functions yet implemented, it's very probable that these will change.

**Comment by timofonic** [comment]
I'm not sure if I wrote it earlier...

Why not adding a very simple service as a demo? Can WebDAV, UPNP/DLNA or
FTP be good candidates?

I'm not a developer, just asking as a mere user. You of course know this a
lot better than me.


Kind regards.

**Comment by theScrabi** [comment]
Yes you did, and still i think we should wait before diving into that topic !!!

**Comment by theScrabi** [comment]
Well we are about to make it real now. Currently we work on support for SoundCloud. The UI is the only thing that is missing right now. It will be coming soon tho.

**Comment by ildar** [comment]
Guys, actually there was an alternative <http://quvi.sourceforge.net/> to
YT-dl written on Lua. Lua is much lighter and easily used in many Android
apps.
One big problem is that quvi is abandoned and didn't receive any updates
since 2013. Yet I believe that:
1. some media providers still work;
2. it can (relatively) easily be updated to the working state.
http://quvi.sourceforge.net/
What do you think?

**Comment by ildar** [comment]
+ more fresh https://github.com/ZionDevelopers/playx/
