### ISSUE TITLE
能够在最新标签中隐藏已播放；一键播放最近更新；最近更新排序

### ISSUE THREAD

**Issue by GuanguangT** [TeamNewPipe/NewPipe#4970]
开发者你好
因为我大多数情况下把NewPipe当podcast使用，所以请求添加一些听podcast的功能
1：在最新更新列表中隐藏掉已播放的内容
2：能够自动把最近更新的内容添加到播放队列
3：排序，播放队列能提供一个从晚到新的排列方式

**Comment by Younes-L** [comment]
除非您编辑文本并将其翻译成英语，否则它将被忽略。

Google的翻译是可以理解的：

(Title : podcast features)

Hello, developers. 
Because I use NewPipe as a podcast in most cases, I request to add some functions for listening to podcasts. 
1: Hide the content that has been played in the latest update list. 
2: Can automatically add the recently updated content to the play queue. 
3: Sorting, the play queue can provide a sorting method from late to new

**Comment by opusforlife2** [comment]
@GuanguangT You could use a translation service to open issues in English. Secondly, only one issue per feature request is allowed. Thirdly, you MUST follow the template.

I'm closing this one. You can open new issues.
