### ISSUE TITLE
Add more detailed messages for unavailable videos

### ISSUE THREAD

**Issue by TotalCaesar659** [TeamNewPipe/NewPipe#4979]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

Services have different error messages for unavailable videos. For example:
https://www.youtube.com/watch?v=_PL2HJKxnOM ("Video unavailable. The uploader has not made this video available in your country.")
https://www.youtube.com/watch?v=DP0F9zPxHFQ ("Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.")
https://www.youtube.com/watch?v=8VajtrESJzA ("Private video. Sign in if you've been granted access to this video.")
https://www.youtube.com/watch?v=ayI2iBwGdxw ("Members-only content. Join this channel to get access to members-only content like this video, and other exclusive perks.")
https://www.youtube.com/channel/UCQkuGxxd00feSuocVzlf7Pg ("This account has been terminated due to a Trademark claim by a third party.")
https://soundcloud.com/frankvaldorsposaunenband/agent-808 ("This track is not available in your country.")

#### Is your feature request related to a problem? Please describe it

NewPipe shows the same message "Content unavailable" for all cases:

#### Additional context

<img src="https://user-images.githubusercontent.com/14265316/99974831-842e7d80-2db2-11eb-87d0-11cd69e03681.png" width=200>

#### How will you/everyone benefit from this feature?

It will let users to know the reason of the problem for finding a way to solve it.

**Comment by PrSunflower** [comment]
I agree. Sometimes I am having this error screen because the content isn't available in my country, sometimes I am having the same error screen because the video doesn't exist anymore.

**Comment by litetex** [comment]
I think this is fixed:
* Not working in your country
  <img src="https://user-images.githubusercontent.com/40789489/132068351-71caa3c4-8496-470e-99fd-cb4cab878090.png" width=200>
* Video unavailable due to terminated account
  <img src="https://user-images.githubusercontent.com/40789489/132068399-34c77c82-d4a1-4828-ad54-4c6f054a514d.png" width=200>
* Private video
  <img src="https://user-images.githubusercontent.com/40789489/132068288-cacd9b00-44dc-442e-b520-5a046e99905a.png" width=200>
* Members-only content
  <img src="https://user-images.githubusercontent.com/40789489/132068470-74915e7e-3938-47b3-832a-dc84a3c73301.png" width=200>
* Channel - Account terminated
  <img src="https://user-images.githubusercontent.com/40789489/132068528-3c0223af-51b1-41a6-a4ac-a4449a6a4414.png" width=200>
* https://soundcloud.com/frankvaldorsposaunenband/agent-808 works in my country 😆
