### ISSUE TITLE
does newpipe use up hidden storage ?

### ISSUE THREAD

**Issue by arayan22** [TeamNewPipe/NewPipe#504]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
 
I download a lot of videos. Occasionally they are incomplete due to an error. Or the device's memory gets full before download is completed. Does this take up extra memory ? Are there duplicates of files somewhere ?  My system memory keeps on getting used up (not by media files).

**Comment by theScrabi** [comment]
No as long as I know not.

**Comment by theScrabi** [comment]
No as long as I know not.

**Comment by mauriciocolli** [comment]
The only thing that NewPipe can consume, is some cache files that is implemented in the new player, this allows for quick seeking through the player (before if you seek to some other already loaded part of the video, it'd load everything again).

But I don't think the problem is this, because the maximum allowed size for the cache is **just 64 MB**, so it have to be something else.

Can you download some "SDcard analyzer" from Play Store and see what is consuming the space? If you notice something related with NewPipe, just tell me here.

**Comment by mauriciocolli** [comment]
If it's still happening, tell me.
