### ISSUE TITLE
Update README.md to include other ways to install

### ISSUE THREAD

**Issue by B0pol** [TeamNewPipe/NewPipe#5051]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

Update the README. It only lists F-Droid which is often late on releases (and today is late by months on releases due to a bug).

#### Is your feature request related to a problem? Please describe it

There are other ways to get NewPipe (our F-Droid repository, GitHub release page) and they should be listed, and explain how to choose one.

#### Additional context

See teamnewpipe/website#163

#### How will you/everyone benefit from this feature?

Users checking our README will know what are ways to install NewPipe.

**Comment by mhmdanas** [comment]
I'll open a PR for this soon.

**Comment by eladkarako** [comment]
GitHub downloads (although superior in every-way) can be a little intimidating for non-developers,  
as it does not have an obvious "download button" or a built in way to link to the latest download link of the artifact (APK-file name) without using a 3rd-party script for parsing the API).  

While using https://github.com/TeamNewPipe/NewPipe/releases/latest  
and manually clicking the assets, then the APK (and sometimes accept Chrome's newest-warning regarding downloading APK-file) is perfectly fine,  
some developers link to the automated Jenkins-build,  
or (like YouTube-DL, for example) provide a download link through their own domain,  
usually pointing to a small script that parses the GitHub API and provides a 302-redirect - directly to the file.  

For example https://youtube-dl.org/downloads/latest/youtube-dl.exe  
will (currently) 302-redirect to http://youtube-dl.org/downloads/2020.12.02/youtube-dl.exe  
which will (again, currently) 302-redirect to https://github.com/ytdl-org/youtube-dl/releases/download/2020.12.02/youtube-dl.exe  
(and then 302 redirect to one of the github-production-release-asset servers of s3.amazonaws.com but that's not important since that's an internally managed by  GitHub...)  

If the NewPipe domain where the blog is hosted has some sort of back-end (php/nodejs), you can easily provide a similar solution!  

Ps.  
A JSON with some details regarding the latest release,  
provided with <a href="https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS">CORS</a> headers (so it could be easily fetched with client-side JavaScript) will be greatly appreciated and will surely help to promote NewPipe in various tech-news/download-websites :]

**Comment by B0pol** [comment]
In fact there it's already said in updates section, but i was thinking about F-Droid badge and we could also edit this section
