### ISSUE TITLE
[Feature] Segmented videos

### ISSUE THREAD

**Issue by HTSamurai** [TeamNewPipe/NewPipe#5098]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. (but whenever i look nothing shows up, and then it gets closed. o_o)
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

In YouTube on the website and maybe the app you can see named parts of the video. I'd like this to be added to NewPipe. A setting could toggle a segmented bar and maybe when tapping somewhere on the bar at the bottom and it shows the point of the video in the middle, it could also show a segment. Maybe under the bar it can have the segment name like on youtube?

#### Is your feature request related to a problem? Please describe it
I can't find certain parts of a video very easilly so in videos that have this it could have a setting. 

#### Additional context
*Picture taken from YT official website*
![1607102426772](https://user-images.githubusercontent.com/71007160/101193858-135e4f80-3655-11eb-92cb-141b60b2f1e3.jpg)
*Look at the bottom*

#### How will you/everyone benefit from this feature?
This feature will help people find the right part of a video!

**Comment by vkay94** [comment]
Basically, this can be achieved when the Extractor supports it. The YouTube-page-source which is parsed does contain the information. It would be a YouTube-service exclusive feature (I doubt Soundcloud support such feature, doesn't it?) and I'm not sure whether it will be implemented because of the uniqueness - hopefully I'm wrong because I'd appreciate it too :D

**Comment by vkay94** [comment]
@HTSamurai I have tried to implement it with my personal fork branch of the extractor and added the functionality to the player. Here's a video preview: https://streamable.com/3e27wa

It works for all videos which provide the data (= timestamps in the description), otherwise the button isn't visible. 

Here's a debug apk if you like to try it for yourself ;): [app-debug-segment-test-02.zip](https://github.com/TeamNewPipe/NewPipe/files/5655676/app-debug-segment-test-02.zip)

It's not perfect but I wanted to try whether the extractor change can be used in the app ;)

**Comment by HTSamurai** [comment]
Wow this works really well, I love it! :)

**Comment by HTSamurai** [comment]
w o a h it works in popup

**Comment by HTSamurai** [comment]
I feel like this is so great it could be added to the main app

**Comment by HTSamurai** [comment]
AND it automattically scrolls to only upcoming bits? wow

**Comment by vkay94** [comment]
>Wow this works really well, I love it! :)

I'm glad you like it.

>w o a h it works in popup

That wasn't intentional to be honest, I just forgot that it will be there too by default xD (the "action bar" is actually too high for this window + the images - I think that's the reason why the playqueue button is missing in the popup :'))

>I feel like this is so great it could be added to the main app

I already opened an issue in the extractor repository (TeamNewPipe/NewPipeExtractor#476) and I'm waiting for feedback.

>AND it automattically scrolls to only upcoming bits? wow

Yes, when you open it. Precisely the current segment will be on top if there are enough upcoming segments.

**Comment by HTSamurai** [comment]
Thanks for making this, and also good job!

**Comment by HTSamurai** [comment]
And it looks darn good too, and I love the little preview pics!

**Comment by vkay94** [comment]
>Thanks for making this, and also good job!

You're welcome. I wanted to look into the extractor code some time ago anyway, so this missing function was a good opportunity ;).
Let's hope the idea won't be rejected (that's why it's an issue there instead of a pull request).

>And it looks darn good too, and I love the little preview pics!

It's just a copy of the playqueue layout - I didn't want to put effort into it, so copy&paste is a good way haha. The pictures are provided by YouTube automatically as you can see in web version by clicking on the title :)

PS.: You can edit posts, It'd be cleaner instead of multiple posts in a row, wouldn't it? :)

**Comment by HTSamurai** [comment]
Ah, thanks. How do i quote someone's comment?

**Comment by HTSamurai** [comment]
> @HTSamurai I have tried to implement it with my personal fork branch of the extractor and added the functionality to the player. Here's a video preview: https://streamable.com/e/3e27wa
> 
> It works for all videos which provide the data (= timestamps in the description), otherwise the button isn't visible.
> 
> Here's a debug apk if you like to try it for yourself ;): [app-debug-segment-test-02.zip](https://github.com/TeamNewPipe/NewPipe/files/5655676/app-debug-segment-test-02.zip)
> 
> It's not perfect but I wanted to try whether the extractor change can be used in the app ;)

thanks for the apk :)

**Comment by HTSamurai** [comment]
How do I send a screenshot? I click the image icon and it opens my camera, but the gallery button is replaced by a turn around camera button

**Comment by vkay94** [comment]
For what purpose?  I'm using Github in desktop version only so unfortunately I can't help you :(

**Comment by shivasagarrao** [comment]
@vkay94 

> https://streamable.com/e/3e27wa

Link not working.

**Comment by vkay94** [comment]
@shivasagarrao I checked it and they should be accessible. Probably you've got an adblocker which blocks the domain?

**Comment by shivasagarrao** [comment]
I disabled the adblocker but still link doesn't work(Maybe a problem with website).

![Screenshot from 2020-12-12 01-57-05](https://user-images.githubusercontent.com/46630255/101951719-7899de00-3c1d-11eb-84af-569754bdcf00.png)

**Comment by HTSamurai** [comment]
It says in #5274 "closes #5098" So I'm closing this.

**Comment by TobiGr** [comment]
No need to do this manually. It is closed automatically once the PR is merged

**Comment by HTSamurai** [comment]
Ah ok. Also, I looked at the PR, it looks done to me. Is segmented videos being added in the next newpipe version?
