### ISSUE TITLE
Minimal support of 0.19.8 + 0.20.6 versions (newduck)

### ISSUE THREAD

**Issue by yiiii777** [TeamNewPipe/NewPipe#5172]
For peoples, who loves 0.19 and hate 0.20 version.

This is almost original 0.19.8 version, but:

- new extractor from 0.20.6
- new soup from 0.20.6
- new datetime from 0.20.6
- a little patch in smali, to be compatible with new Extractor
- changed package name/icon to be installable with near original version

[newduck-20-6.txt](https://github.com/TeamNewPipe/NewPipe/files/5691208/newduck-20-6.txt) - script for building (read before launch)
[newduck20-6.zip](https://github.com/TeamNewPipe/NewPipe/files/5691213/newduck20-6.zip) - binary build

No recompilation, no need android sdk, no need libs or gradle.

**Comment by eladkarako** [comment]
> [newduck-20-6.txt](https://github.com/TeamNewPipe/NewPipe/files/5691208/newduck-20-6.txt) - script for building (read before launch)

Nice!  
Thank you for the updated instructions,  
I much prefer this, over being spoon-fed APKs (https://github.com/TeamNewPipe/NewPipe/issues/4918)  

keep up the good work!!!

**Comment by BlueAmulet** [comment]
Works great and also actually works on non java 8 devices unlike #4918
I've personally removed the newpipe->newduck changes cause it was preventing me from importing my content and settings from a different version.

**Comment by eladkarako** [comment]
> actually works on non java 8 devices unlike #4918
<details><summary>yep.</summary>
From the content of <code>newduck20-6.zip/newduck.apk/META-INF/MANIFEST.MF</code>,  
I can see that the APK was re-built using Java6 (<em><code>Created-By: 1.6.0_18 (Sun Microsystems Inc.)</code></em>),  

The 20.6 from #4918 was built with <code>Android Gradle 4.1.1</code> and whatever JDK version that was set on that machine (I can only assume &gt;/= Java8 since it is not explicitly specified) which is probably the only difference.  

BUT I've also noticed that APKTool recompiles <code>resources.arsc</code> in a way that generally works better in older versions of Android. <a href="https://github.com/iBotPeaches/Apktool/issues/2237#issuecomment-562550340">Possibly a positive side-effect of this bug</a>.
</details>
