### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by voiceofvraja** [TeamNewPipe/NewPipe#5197]
Ignore if I make some annoying mistake below :)

1. Ability to edit order or remove tabs from the hamburger menu, for example let users select what they want there or just let them completely remove it and have only homepage
2. Ability to remove like/dislike buttons if user want just like comments removal
3. Ability to sort a subscription videos by basic sorting options
4. Ability to see playlists from a channel

**Comment by mhmdanas** [comment]
Could you please open a separate issue for each of the feature requests? Also, it appears you are using something else than the GitHub website to open issues (e.g. third-party GitHub client). Could you please open the issues from [here](https://github.com/TeamNewPipe/NewPipe/issues/new/choose) in the website so that you can use the feature request template? Thanks!

**Comment by voiceofvraja** [comment]
Sure, I useed github mobile tho

**Comment by mhmdanas** [comment]
Well, remove "third-party" then. Templates aren't supported by the GitHub API, so GitHub clients that use the GitHub API won't be able to use the templates.

**Comment by voiceofvraja** [comment]
Sure, I am using the web version now. Nevermind :D
