### ISSUE TITLE
Ability to see channel's playlists

### ISSUE THREAD

**Issue by vrindavan** [TeamNewPipe/NewPipe#5203]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

Ability to see playlists from a channel

#### How will you/everyone benefit from this feature?

This is just for the user to see and add if the channel has any created playlists

**Comment by c-shubh** [comment]
Duplicate of #2414

**Comment by mhmdanas** [comment]
@c-shubh I think this issue should be kept open, as #2414 requests multiple featurees, while this issue requests one very specific feature.

**Comment by voiceofvraja** [comment]
Thanks :) @mhmdanas

**Comment by HTSamurai** [comment]
I like this as long as there would be a way to look at the other tabs on a channel page.

**Comment by BDaggerhart** [comment]
This honestly seems like a pretty necessary feature, I would like to see this as well.

**Comment by professor-eggs** [comment]
Would also love to see this

**Comment by Yuriy-II** [comment]
I also think this feature is essential. Some channels currently don't show in the channel video list videos, which are in Channel Playlists. Like this channel: https://www.youtube.com/channel/UCxQ_eGCCUjCUnvhp28Q8YGg
For me in NewPipe it displays only single title video.

**Comment by sebma** [comment]
Would love to have this feature.

**Comment by IriaSomobu** [comment]
Is anyone working on this issue?

**Comment by ShareASmile** [comment]
@Stypox ☝☝
Enlighten Please😄

**Comment by Stypox** [comment]
@IriaSomobu thank you for reaching out! @ShareASmile thank you for pinging ;-)

- *nobody working on it, right?* - right :-)
- *should I start working on this task?* - I would suggest starting with something simpler, since this would require a bit of knowledge of the codebase to be well implemented, but you may also do it now if you want to
- *from which part of task is better to start: extractor or app itself?* - definitely from the extractor: the app's design will depend on how the extractor provides the data
- *is there any Newpipe activity/fragment that I can reuse on channel playlists viewer?* - yes, every list fragment in NewPipe extends `BaseListFragment`. In particular I think you should take inspiration from the search fragment, since that list can contain multiple types of items without much effort: it extends `BaseListFragment<SearchInfo, ListExtractor.InfoItemsPage<?>>`.
- *had anyone tried to implement this feature before?* - @wb9688 already made some progress a while ago, you can as well bring back his PRs if you want: TeamNewPipe/NewPipeExtractor#279
- *any other tips?* - nothing comes to my mind as of now, but feel free to ask more things (and ping me if you do)

Btw, closing as duplicate of #2414

**Comment by opusforlife2** [comment]
_Really_ closing it this time. :P
