### ISSUE TITLE
Opening some types of URLs cause permanent buffering

### ISSUE THREAD

**Issue by Timsonrobl** [TeamNewPipe/NewPipe#5224]
### Checklist

- [x] I am using the latest version - 0.20.6 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

Steps to reproduce the bug
1. Go to youtu.be link for a video inside playlist with a time code. Example 'https://youtu.be/ut3n8-9JM5o?list=PLbQ-gSLYQEc4mnWapHJd0K-sPvLcEwOSS&t=274'
Such URLs are provided when you click RMB in web YouTube player and choose "Copy video URL at current time"

### Actual behaviour
Infinite buffering on black screen.

### Expected behavior
Opening video on specified time.

### Device info

 - Android version/Custom ROM version: 8.0
 - Device model: Samsung Galaxy S7

**Comment by shivasagarrao** [comment]
Am also facing this issue.

**Comment by XiangRongLin** [comment]
This issue is not limited to videos inside playlists. I think any video with an timestamp will cause this issue 
ex.: https://www.youtube.com/watch?v=nSNQ_Qh9Pss&t=203

@Stypox @TobiGr 
This is an regression from 19.8 to 20.8, because in pre unified version the link in the top comment and mine above work.

The reason for the endless buffering is that the `playQueue` is null and `BasePlayer.onPlay()` just silently returns without doing anything
https://github.com/TeamNewPipe/NewPipe/blob/8fe1a76ec6f88556ff8964df09040135c9c51e1e/app/src/main/java/org/schabi/newpipe/player/BasePlayer.java#L1128-L1134

Reason for `playQueue` being null is that `item.getRecoveryPosition()` returns the timestamp, which is not equal `PlayQueueItem.RECOVERY_UNSET`. This causes `initPlayback` to never be called, which would set the `playQueue`. I assume previously videos with timestamps were not handled here, but somewhere else.
https://github.com/TeamNewPipe/NewPipe/blob/8fe1a76ec6f88556ff8964df09040135c9c51e1e/app/src/main/java/org/schabi/newpipe/player/BasePlayer.java#L348

**Comment by XiangRongLin** [comment]
I opened a PR linked above to adress this, can you

**Comment by XiangRongLin** [comment]
#5301
this could be related. because it's the same problem of playQueue being null

**Comment by shivasagarrao** [comment]
@XiangRongLin I tested the apk and links with start time are loading perfectly now. Thanks for PR.
