### ISSUE TITLE
SAVE all comments under video to TXT, HTML, PDF file.

### ISSUE THREAD

**Issue by NewNewPipe** [TeamNewPipe/NewPipe#5296]
Hello.

I want to proposal a new very practical functionality for the already great NewPipe application.

Adding function / options to
SAVE all COMMENTS under the movie to
TXT, HTML, PDF file.

**Comment by mhmdanas** [comment]
Hi @NewNewPipe! Presumably you're the person I talked with on IRC the other day. Thanks for opening an issue! We have templates that all issues should follow one of. Since you don't know English, I can't blame you for removing the template. I created an issue for the ability to save comments for you. Thanks for the suggestion!
