### ISSUE TITLE
Found via Bountysource

### ISSUE THREAD

**Issue by theScrabi** [TeamNewPipe/NewPipe#534]
Hei there,

we had this [discusstion](https://github.com/TeamNewPipe/website/issues/5#issuecomment-298176132), and we came to the conclution that we should found NewPipe via [Bountysource](https://www.bountysource.com) rather than donating it via bitcoin. So I thought about it, and I'm good with it since it may boost our project a little further. What would you think?

Also should we put NewPipe on Bountysource now, or should we wait until the relaunch of the website?

rgds Schabi

**Comment by TheAssassin** [comment]
Well, I am not a big fan of Bountysource, neither the concept nor the site. But that doesn't matter here, as I want to reply to the second question.

You can register there whenever you want to, but I would wait for the relauch before we integrate the button on the site. You can, however, always add the button to GitHub, so that people can start using it already.

Please create an issue in the website repository so that we don't forget this little feature.

**Comment by theScrabi** [comment]
@TheAssassin I'll open that issue as soon as we have a boutnisource account.

So is the rest fine with a registration now?

**Comment by ponypower** [comment]
I'm cool.

**Comment by ponypower** [comment]
@theScrabi, I have a few constructive questions. I hope they get us thinking about the details a lilbit.
- How do you plan managing the budget in the future? Discussing how much there is and what subprojects to spend it on; publicly / privately with the teammembers / privately on your own ? What are the possible advantages and disadvantages of these different approaches?
- Has the project already got a budget from previous donations? How much is it?
- How much donation can the project expect in the future? What ways can we improve the publicity of the project to expect more donation?
- What factors will determine which task gets a bounty; progression priority / difficulty / time-consuming / every task ? When some tasks dont get bounties, is that possible that people will avoid working on them? What happens when some people argue the justification of a bounty?
- Should we make a clear and detailed project plan/roadmap with a financial/bounty plan? (Would be neat)

It's up to you to answer (or not) these questions publicly or privately.

**Comment by TobiGr** [comment]
@theScrabi Is there any progress with the Bountysource account? If not, don't worry. We can add a BitCoin donation button instead and replace it later. 
I'd like to design the donate page in the next two weeks (@ponypower feel free to help me). I need information on how we want to introduce the new donation system / the donations at all.

Things that we can say on the site:
- What do we do with the money? / Who is going to receive it? / Why do we want to save the money?
- Overview of upcoming features / roadmap. So people have a goal for what they donate. I'm not sure whether we can integrate information from the Bountysource account or whether we will have to list the bounty info on the site separately.
- Big thanks from the developers to motivate people to donate. This can be short statements by all active developers. e.g we can display one statement for five seconds and then change to another statement by a different developer to show how many people work to keep NewPipe alive.
- Any other ideas? Tell me!

**Comment by TobiGr** [comment]
@theScrabi could you please assign @ponypower again? I don't know how I unassigned him. Thanks

**Comment by TheAssassin** [comment]
Now we know that adding multiple assignees to an issue does not work in ForkHub. Either @theScrabi or me are going to fix that, @TobiGr.

**Comment by theScrabi** [comment]
Youre saing we need to fix forkhub xD, ... Why don't you use FastHub.

**Comment by TheAssassin** [comment]
Closing as Bountysource is available now. See https://newpipe.schabi.org/donate/ and https://www.bountysource.com/teams/newpipe.

**Comment by wb9688** [comment]
Could somebody do s/work the/work, they/ on that page? On that page under
Thank you! the word free looks exactly the same as the link GitHub, which
is a little bit confusing.

**Comment by TheAssassin** [comment]
@wb9688 please open an issue in the website repository, then it'll get fixed.
