### ISSUE TITLE
webm 360p not showing up

### ISSUE THREAD

**Issue by Snowden-rgb** [TeamNewPipe/NewPipe#5363]
### Checklist

- [x] I am using the latest version - 0.20.8 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1.Go to setting and choose default audio and video format as webm
2.Watch any video which is in webm format
3. see that every format except 360p is in webm format same goes for download

### Actual behaviour

360p should be available in webm format like all other resolutions

### Expected behavior

360p isn't in webm format

### Screenshots/Screen recordings

![bug1](https://user-images.githubusercontent.com/77095975/103867146-de7a6800-50ec-11eb-97db-68ff753bdfaa.jpg)
![bug2](https://user-images.githubusercontent.com/77095975/103867173-eafec080-50ec-11eb-84d0-8607a1415ef0.jpg)

### Device info

 - Android version/Custom ROM version: android 7 based on miui 11.2
 - Device model: mido

**Comment by Redirion** [comment]
did you try whether youtube-dl lists webm 360p as available stream format? My blind guess would be, that it just isn't available.

**Comment by Timmy183-ui** [comment]
Can confirm it is true, that particular video in stock yt app in 360p is available in webm.

**Comment by Snowden-rgb** [comment]
![Screenshot (2381)](https://user-images.githubusercontent.com/77095975/103966118-3b296180-5185-11eb-97c6-69b98f3bb3f9.png)

@Redirion  243 for 360p is in webm

**Comment by Redirion** [comment]
it appears that the NewPipeExtractor filters this itag out for some reason and it has been so for years (at least since 2018!): 
https://github.com/TeamNewPipe/NewPipeExtractor/blob/ab62464e86954a8c084985bb0ed1674df7af6735/extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/ItagItem.java#L63

@Stypox do you have an idea why 243 is commented out?

**Comment by XiangRongLin** [comment]
@Redirion It's been like this from the start. If you click on "view git blame" you can see that it hasn't been changed since it was first added.

So it should just be un-commented out and checked if it works

first added commit: https://github.com/TeamNewPipe/NewPipeExtractor/commit/b1989c0a834e5f5e79be30e841fa057efd169930#diff-a212131a6a0d14cd86f642641e8908370af8d135806cf72a4ad73900cff1e64cR70

**Comment by Redirion** [comment]
@XiangRongLin thank you. I only used "History" so I couldn't see further than the moment when it was moved 3 years ago.
Do you have time to build a test apk with a changed extractor that comments in this particular line?

**Comment by XiangRongLin** [comment]
https://github.com/XiangRongLin/NewPipe/actions/runs/472076189

**Comment by Redirion** [comment]
@XiangRongLin thank you! I tried it on my Phone (Pixel 4a) and it works. I was able to select WEBM 360p and it played back fine.
Do you want to do the PR for the Extractor?

**Comment by Snowden-rgb** [comment]
yes, it works in the debug apk. thanks @XiangRongLin

**Comment by Snowden-rgb** [comment]
one request @XiangRongLin 
until this issue is fixed upstream can you please provide debug apks with latest newpipe versions cause 360p is a sweet spot beetween quality and data consumption

**Comment by XiangRongLin** [comment]
> one request @XiangRongLin 
> until this issue is fixed upstream can you please provide debug apks with latest newpipe versions cause 360p is 

See my comment above or the linked PR

**Comment by Snowden-rgb** [comment]
the pr is merged now, will close the issue once we get v 0.20.9 which will have webm360p
