### ISSUE TITLE
We know F-Droid version is out of date

### ISSUE THREAD

**Issue by opusforlife2** [TeamNewPipe/NewPipe#5421]
There's nothing we can do about it from our side: https://gitlab.com/fdroid/fdroidserver/-/issues/797

We recommend installing Newpipe from [our custom F-Droid repo](https://github.com/TeamNewPipe/NewPipe#installation-and-updates). Not just while this issue persists, but in general. You'll get faster updates.

The problem is related to reproducible builds. When F-Droid builds the binary, it IS the same as ours, but for some reason, it is not signed correctly.

**Comment by mhmdanas** [comment]
Aight, @opusforlife2 just snapped.

**Comment by AnonymousSeal** [comment]
The Repo:
https://archive.newpipe.net/fdroid/repo?fingerprint=E2402C78F9B97C6C89E97DB914A2751FDA1D02FE2039CC0897A462BDB57E7501
To add to F-droid go to Settings > Repositories > +

**Comment by nbmrjuhneibkr** [comment]
If you're going to make a pinned issue for this, then may as well actually explain the cause of this issue, not just a workaround.

**Comment by mhmdanas** [comment]
@TobiGr mind editing the issue to shed some light on the issue itself?

**Comment by opusforlife2** [comment]
@nbmrjuhneibkr Good point.

**Comment by ovz93br43v7** [comment]
I was surprised when I saw in the F-Droid app that there is an update for newpipe legacy to 0.20.8 on 21th of January 2021. So the updates via F-Droid are working again now?

**Comment by mhmdanas** [comment]
No, NewPipe Legacy does not have this issue.

**Comment by ovz93br43v7** [comment]
Ok I thought because the version history of F-droid shows a gap between version no. for New Pipe Legacy:
0.20.8 - 21th January 2021
0.20.2 - 31th October 2020

**Comment by connectety** [comment]
I looked into the cause a bit.
Looking at [this f-droid data issue](https://gitlab.com/fdroid/fdroiddata/-/issues/2207), the cause seems to be, that f-droid does build the app without failures but fails to verify the app against the dev provided APK and thus does not publish it.

In [this f-droid server issue](https://gitlab.com/fdroid/fdroidserver/-/issues/827), which is linked in the f-droid data issue it is suggested verifications fail (for other apps too) because of issues with APKs signed with v2/v3 signatures.
The problem with this is, NewPipe is still on SDK 29 and not 30 which requires newer signatures. Also, apksigner does not show me a difference between the last published app and the one after it.

But looking at [this page](https://f-droid.org/wiki/index.php?title=org.schabi.newpipe/lastbuild_960&redirect=no) NewPipe v0.20.6 (960) was successfully built on the 2020-01-15 (which is kind of slow but kind of an f-droid thing). So this has to be a verification issue to some degree.

**Comment by mhmdanas** [comment]
NewPipe 0.20.11 has been built and published on the main F-Droid repo. The reproducible builds' signing issue still isn't fixed, so we unfortunately had to go back to "normal" F-Droid builds.

**Comment by opusforlife2** [comment]
:'(
