### ISSUE TITLE
Link to video in playlist plays list at 1

### ISSUE THREAD

**Issue by PhoenixIV** [TeamNewPipe/NewPipe#5435]
Opening a YouTube link with NewPipe in the form https://www.youtube.com/watch?v=69lIqDc8Xhs&list=PLbAkPmkjBX3gDGW4HkDQJTB_wHoIOJ9LS&index=62 (Example link) will play the first video in that list, not the one specified in the link.

**Comment by PhoenixIV** [comment]
Yo, guys, the templates were not shown to me when I created my issue and if that's your way of pushing of a helpful suggestion I am not gonna help you out any further.

**Comment by Stypox** [comment]
Then try to look up for the template next time: while filling in the template you would have found out that this is a duplicate. We don't have unlimited time so if someone makes a request we at least want him to put some effort into making sure it is a valid request. Sorry if I seemed rude, this is just the policy we decided to go with, otherwise we would be flooded with issues
