### ISSUE TITLE
mp3/m4a cover pic feature request

### ISSUE THREAD

**Issue by brnwlshubh** [TeamNewPipe/NewPipe#5443]
While downloading the m4a/mp3 file through Newpipe the cover photo of the file is empty/blank.
Please try to add thumbnail as a cover pic of the audio file which is downloaded through Newpipe.
It will look adorable while downloading and playing.

**Comment by mhmdanas** [comment]
Thanks for opening an issue! Could you please open a new issue that follows the template properly instead of removing it?

**Comment by brnwlshubh** [comment]
I didn't understand what you want to say.
Please explain me, what I have to do while opening new issue?

**Comment by mhmdanas** [comment]
When you press the "New issue" button, you should be presented with a list of templates, which are "bug report" and "feature request." In this case, since you are requesting a feature, you want to choose the "feature request" template by pressing the "Get started" button beside it. After you press it, in the issue's body there will be a template that asks you to check if you have done certain stuff, fill out certain sections, etc. The checklist is compulsory, but only the "describe the feature you want" and "How will you/everyone benefit from this feature?" sections should be filled at least. If you face any trouble don't hesitate to tell me.

**Comment by brnwlshubh** [comment]
Finally posted the issue.
Thank you for assisting me. @mhmdanas
