### ISSUE TITLE
30fps Rendering Mode for 720p60,1080p60 sources [personal experience of the performance old and new budget chips]

### ISSUE THREAD

**Issue by Plugdemholes-Imeanpatchdembugs** [TeamNewPipe/NewPipe#5483]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Experience
I've recently upgraded my ISP connection and since then I've run into an issue that, till recently, thought was a thing of the past.
Rendering @60fps on low-end budget chips. 
The tablet I'm currently using, has the Snapdragon 429, a chip released Q3 2018, that is still not capable of running sources of 1080p60 without hiccups or stops during playback (also with other apps).
With my old smartphone that uses the Snapdragon 410 from 1H 2014, I always wasn't able to use smooth playback of 720p60 sources.
I know the same issue from my Desktop PC (Intel i5-2500) from 2011 before I switched to new PC last year.

#### Assumption
When I look at the specs of the various Adreno gpus in these chips, then I would assume at least the Snapdragon 412, 425, 427 and anything lower-tier (older/ and before that) will have similar issues. And comparable MediaTek chips.

#### Describe the feature you want
30fps Rendering Mode for YT 720p60 and 1080p60 sources
extending viability of old devices that are only able to run only 720p30 and 1080p30 smoothly.

#### Is your feature request related to a problem? 
Until recently, I really thought that any kind of media device released since 2017 would be capable of 1080p60
that doesn't seem to be the case.

#### How will you/everyone benefit from this feature?
Old devices will be able to run 1080p(or 720p) plackback @30fps where YT doesn't seem to provide rendered 30fps versions anymore.

Update
#### Additional Info
I've taken a look what devices could be **affected currently**.

From what I can see basicly **current tablets up to 260 bucks** use the same or a similar competitors chip.
And for current **smartphones** it looks like the **sub-200 bucks categor**y could be affected, devices such as the 
Samsung Galaxy A20e, A41, Xcover 4s, A31, A40, A30s; 
Huawei P30, P30 Lite, Smart Pro, P40, P40 Lite; 
Honor 9X.
I can't verify that but that's basicly just by looking at the comparable specs on Wikipedia of the used graphics chips and then checking if these devices are capable of recording at 60fps.

**Comment by opusforlife2** [comment]
Wherever a 720p60 exists, a 720p30 stream exists as well. Can you test a few videos to confirm this?

**Comment by Plugdemholes-Imeanpatchdembugs** [comment]
Sure can do in about 90mins I can back to that.
Do you anything specific? 
And I do remember, even now years back, where YT didn't offer anymore 1080p30 streams when it was originally uploaded with 60fps.

**Comment by opusforlife2** [comment]
That's true. Youtube only offers 1080p60 streams when it can. But you will find in your tests that 720p is always available, even if 720p60 streams are present.

**Comment by opusforlife2** [comment]
Can you give an example where the 720p60 stream exists but not 720p?

**Comment by Plugdemholes-Imeanpatchdembugs** [comment]
So far I did only find, when I'm having MPEG4 enabled as codec, which I usually have, since its less noisy than the WebM encoded steams, videos where 720p60 is shown but only a 720p30 version in WebM listed, but when clicked it goes right back to MPEG4 720p60 stream. I think that was always my experience, since I switched permanently to MPEG4 streams, even on my old smartphone prior to 2019.

**Comment by opusforlife2** [comment]
Ah. I didn't know that.

So why not use the WebM 720p30 stream for your low end devices?

**Comment by Plugdemholes-Imeanpatchdembugs** [comment]
Because WebM is very noisy compared to MPEG4. ^^
And for my current device 720p60 isn't an issue anymore, but 1080p60 is. ^^"

**Comment by opusforlife2** [comment]
Okay. Then it depends on how complex the code needed would be. To me it looks like too much work for too little gain, but I'm not a developer. Let's see if anyone takes this up.

**Comment by Plugdemholes-Imeanpatchdembugs** [comment]
Neither do I know how complex this would be. My thinking was, drop every 2nd frame. ^^"

**Comment by Plugdemholes-Imeanpatchdembugs** [comment]
I've given a little update on what current devices could be affected from a slowdown of 1080p60 in my first thread post here.
So just to give a better impression if it's still relevant and for what current phones/tablets.

**Comment by Crystal-RainSlide** [comment]
For some videos, there can be no WebM as seen in NewPipe, only 1080P60 MPEG-4, 720P MPEG-4, and 360P MPEG-4.

These videos are mostly low in views.

Among them, the most random one I can find: https://www.youtube.com/watch?v=UAB5VV1S7zY

**Comment by opusforlife2** [comment]
@Crystal-RainSlide That has nothing to do with this issue. Anyway, that's a known limitation because of the lack of DASH playback in Newpipe.

Please look for the correct issue if you wish to get updates. Marking your comment as off-topic.

**Comment by moriel5** [comment]
This is certainly interesting, as there are even laptop GPUs that are unable to steam 720p60 without hiccups (such as the BayTrail iGPUs).

By the way, 60fps is not uncommonly, with channels such as Gamers Nexus being primarily 60fps (and yes, there are also 1080p30 streams for those, as I had seen when using youtube-dl to download such a video once for testing on a BayTrail laptop).

**Comment by moriel5** [comment]
@Crystal-RainSlide I believe that those are h.264/x264/AVC, not MPEG-4.

**Comment by TippyLion28** [comment]
Would love to see this. I prefer to watch some types of video in 30fps, find myself dropping down to 720p just to watch these.

**Comment by fdutheil** [comment]
Errr, is it even possible? This could be not doable, or even not really useful.
How do you plan to render half the rate of a stream if you are not actually fully decoding it? Isn't the decoding job the most compute intensive task either?

**Comment by moriel5** [comment]
@fdutheil Since I am unable to understand upon what you commenting, I'll say that I agree that it makes no sense to render only half of the rate of a given stream, however what we should do (and this has been mentioned) is expose the streams that are encoded as 30FPS (since those still exist) in addition to those that are encoded as 60FPS.

**Comment by litetex** [comment]
This issue is nonsense:
1. **When a GPU can't keep up it usually drops some frames** e.g. in games when rendering complex areas → you get framedrops. The same thing should happen on every smartphone as it's based on the same technology.
2. > The tablet I'm currently using, has the Snapdragon 429, a chip released Q3 2018, that is still not capable of running sources of 1080p60 without hiccups or stops during playback (also with other apps).

   How is this related to the issue? What are "hiccups"?
"stops during playback" - this is likely not related to the GPU, because a GPU doesn't randomly stop rendering...
3. The issue should be solved on device-level. We have no control over the rendering at all, since the delivered specifications from the remote side are submitted directly to the device e.g. if we receive a 60fps stream, that stream will be submitted to ExoPlayer as a 60fps stream otherwise certain things might get corrupted. Also if e.g. a 60fps device can limit it's rendering to 30fps itself the feature is utterly useless because it will still render with 60fps.
4. > And for current smartphones it looks like the sub-200 bucks category could be affected, devices such as the

   My Huawei P20lite works totally fine...
5. If a device that has a 60fps screen is unable to keep that screen at 60fps you a) likely bought a bad device or b) your device has a problem
6. Did you ever consider that maybe not the FPS are the problem but the resolution? You may also watch a 4k stream at 10fps and the device can't keep up because there are to many updates. Simply go a resolution step lower if you notice that your device can't keep up, e.g. 1080p60 -> 1080p -> 720p60 -> 720p -> 480p until it's smooth.

**Comment by moriel5** [comment]
@litetex While for the most part I agree with, I do disagree about the resolution being an issue as opposed to frame rate, since we have clear examples of GPUs that are unable to handle, say, 1080p60, however are perfectly alright with 1080p30 (such as the Intel BayTrail iGPUs), and as such the solution is not on a per-device case (although there might be other things in play that do require this), but rather just exposing the existing 30fps streams (they do exist, and some Invidious instances do expose them).

**Comment by litetex** [comment]
> have clear examples of GPUs that are unable to handle, say, 1080p60

If the GPU is unable to play a 1080p stream at 60fps it should do framedrops to a playable framerate e.g. 40fps - depending on the workload. If that's not the case your GPU has a malfunction or it's not a GPU problem.

> but rather just exposing the existing 30fps streams (they do exist, and some Invidious instances do expose them)

We show all available streams from the remote side in the resolution dropdown (expect when they are not implemented in some kind - but that's a another/new issue). 
When I open videos on YT they show the same resolution options as NewPipe has. If Invidious uses another extraction method or e.g. DASH (which we haven't implemented yet) well nice for them but NewPipe use another method.

**Comment by moriel5** [comment]
> If the GPU is unable to play a 1080p stream at 60fps it should do framedrops to a playable framerate e.g. 40fps - depending on the workload. If that's not the case your GPU has a malfunction or it's not a GPU problem.

That is true, however I have yet to see a solution that actually does that smoothly without VRR (these are already connected to driver issues).

but rather just exposing the existing 30fps streams (they do exist, and some Invidious instances do expose them)

> We show all available streams from the remote side in the resolution dropdown (expect when they are not implemented in some kind - but that's a another/new issue).
When I open videos on YT they show the same resolution options as NewPipe has. If Invidious uses another extraction method or e.g. DASH (which we haven't implemented yet) well nice for them but NewPipe use another method.

Fair enough, YouTube doesn't expose the 30fps streams either (there are userscripts that force it to expose them, though), and I have yet to verify whether they really upon DASH (I don't think so, at least not those up to 1080p30).

When I have time, I'll try looking into this, and if relevant, I'll create an issue for the upstream NewPipe Extractor.

**Comment by moriel5** [comment]
Updated previous post with information regarding removal of 30fps streams from videos originally 60fps.

If anyone creates a duplicate issue regarding this, they can be pointed to this.
