### ISSUE TITLE
Strange behaviour of "back" button

### ISSUE THREAD

**Issue by Vrihub** [TeamNewPipe/NewPipe#5517]
### Checklist

- [x] I am using the latest version - 0.20.8 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Watch a video, from one of the available video lists, e.g. "What's new"
2. Press the android "Back" button

### Actual behaviour

Newpipe displays one of the videos that I've already viewed (perhaps partially), instead of the video list which I was coming from.
Generally, if I press "back" several times I get back to the expected list, but this seems to happen by accident, after displaying one or more "old" videos (the last of which remains loaded in the minimized player at the bottom of the screen).

### Expected behavior

Newpipe should display the video list where I was before viewing the first video; that's the expected behaviour of the "back" button: take me one step back, not to totally unrelated video(s) that I watched in the past.

### Device info

 - Android version/Custom ROM version: 10
 - Device model: Samsung phone

**Comment by nbmrjuhneibkr** [comment]
Sadly, this is one of the "features" that was implemented on purpose in 0.20, because someone thought that it would be great to break established user experience and introduce something that defies common sense.
I submitted it once https://github.com/TeamNewPipe/NewPipe/issues/4462 , but it was closed. You're not allowed to call it a bug, apparently.
I submitted it again as a "feature request" (even though it's clearly something that worked fine before, but is broken now) https://github.com/TeamNewPipe/NewPipe/issues/4479 almost 4 months ago - no progress.

**Comment by Vrihub** [comment]
Thanks for the explanation, I apologize I failed to find similar issues in the tracker, so I will close this.

Ok, so "swipe down" is the new "back". Well, if this is meant to be a permanent feature (in fact there are some use cases for it, though it's not how most apps work) I think it should be better "documented" in the app (some help screen, intro app tour etc)
