### ISSUE TITLE
Fit / Fill / Zoom bug

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [TeamNewPipe/NewPipe#5613]
### Checklist

- [x] I am using the latest version - 0.20.10 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Open a random video
2. Watch the video in fullscreen
3. Choose Fit / Fill or Zoom
4. Go out of fullscreen
5. Close the video
6. Open another random video
7. watch the video in fullscreen
8. Notice that the option u chose changed to another one

### Actual behaviour
The value doesnt stay the same. 
if u choose **Zoom** then it will default to **Fill**
if u choose **Fill** it will default to **Fit**
if u choose **Fit** it will default to **Zoom**

### Expected behavior
Value must stay the same!

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/73130443/108190456-deb54c80-7109-11eb-892b-3498298d06e1.mp4

### Device info

 - Android version/Custom ROM version: Android 11 /  Graphene OS
 - Device model: Google Pixel 3a XL

**Comment by litetex** [comment]
It think I managed to find the problem by reviewing the code.
However I'm not 100% sure, because I don't have NewPipe setup locally for developing.

The problem is very likely on 
https://github.com/TeamNewPipe/NewPipe/blob/0d522aae6c452a6edc74e802e379d7cbab757ef6/app/src/main/java/org/schabi/newpipe/player/helper/PlayerHelper.java#L487-L488

When the a new resizeMode is set by calling ``nextResizeModeAndSaveToPrefs`` (from https://github.com/TeamNewPipe/NewPipe/blob/0d522aae6c452a6edc74e802e379d7cbab757ef6/app/src/main/java/org/schabi/newpipe/player/Player.java#L3613-L3617), it uses the old resizeMode to get the next/new one. 
However it stores the old one in the preferences.

So when switching from ZOOM to FIT, it returns FIT (which is used for the current video), but stores ZOOM in the preferences (used for the next videos)



This was probably introduced by commit https://github.com/TeamNewPipe/NewPipe/commit/f6e2dd1480a71fa61d8a285912beb11c9169c069 from @Stypox last month

**Comment by TobiGr** [comment]
Can you test the APK from #5792 and tell me, whether the bug is fixed?

**Comment by litetex** [comment]
@TobiGr 
LGTM:
https://user-images.githubusercontent.com/40789489/110525980-8cb68400-8115-11eb-8880-ebc190655e07.mp4

Tested with a virtual Pixel 3a
