### ISSUE TITLE
Requirements for Database

### ISSUE THREAD

**Issue by theScrabi** [TeamNewPipe/NewPipe#563]
So I got asked how to build the database.

My Idea for the design was this:
I want a central sql file which creates the database, and which will tell us the architecture of the database. Now this script should be put into android resources. There should be a class, some sort of `SQLLoadExecuter` that will load and run this script when the database does not yet exist.

Now every table in our database must contain a `serviceId` element.

Imaginable tables are:
- Search history
- Bookmarks/favourites
- subscribed channels
- history

Everything that is related to the database should be put into the package `org.schabi.newpipe.database?`

What do you think?

**Comment by mauriciocolli** [comment]
Yeah that was basically what I was thinking.

Regarding the sql file, I don't have much experience from db in android, but do we need it?
From my understanding we create a subclass of `SQLiteOpenHelper` and that deals with when it is created (like @BlenderViking did [here][1]).

---
I'm considering using some DB library, that would not only be easier to maintain, but faster to develop too (I'm testing some of them yet). 

So if we find one great library, should we use it (by the previous reasons) or should we develop our own "custom" database?


[1]: https://github.com/BlenderViking/NewPipe/tree/playlist_sqlite/app/src/main/java/org/schabi/newpipe/playlist

**Comment by theScrabi** [comment]
On android you basicly use SQLite, and thats build in. So before including some more libs I think we should use the standart. I worked with that before and I think it's not that hard to use.

Importend to me is having an sql file that will create the tables. Thats for us to see better how the database is build up.

**Comment by theScrabi** [comment]
@TheAssassin had the Idea of using KeyVelue store instead of an SQL database, in order to ensure our data keeps consisted even if we update it a lot. What do you thing?

**Comment by mauriciocolli** [comment]
But then how would that work? Serialize the object? Json? Use the "prefix" approach (e.g. `video<Id>_title`)?

**Comment by TheAssassin** [comment]
It doesn't necessarily have to be key-value only, something hierarchic (JSON-like) would be ideal.

The problems that I mentioned in the discussion with @theScrabi is that keeping the SQL schema in sync would require some database migration framework to be in place. I am not sure if there's some "standard" framework for this purpose for Android, but yeah, the way NewPipe development works might make it hard to keep the database in a consistent state.

A key-value or document database doesn't necessarily have to be in sync though, you don't have to ship all the migration code ever written with every future release just to make sure you fix your data scheme but just need some dynamic code that fixes legacy issues. In my experience, that's easier to maintain, and it's way harder to produce data loss with that. Just add/remove keys when they would actually be accessed.

But I'd say we should make this decision depend on these questions:

1) How easy is it to implement it in NewPipe? Is there a preexisting framework for that that can be used?
2) How can we keep the database "schema" in sync with NewPipe? Is there a migration framework available?
3) *(will follow once I find another question I'd like to see an answer for)*

A simple data scheme might look as follows:

```
{
  "bookmarks": [  // bookmarks serve as an example here
    {
      "name": "A YouTube video",  // YouTube video title
      "url": "https://youtube.com/...",  // full URL to it
      "created": "2017-01-23T12:34:56+00:00",  // ISO 8601 timestamp
      "lastAccess": "...",  // might be used for sorting, e.g. "last visited"
    },
    {
      ...
    }
  ]
}
```

A migration example: If you added the `lastAccess` in the last version and it wasn't existing before, just create it on first use. This approach will work forever. If you wanted to remove it eventually, you'd just have to check whether there's such a key in the key-value object, and if yes delete it. Quite straightforward, isn't it?

**Comment by TheAssassin** [comment]
Addendum:

A nice article discussing the use, advantages and disadvantages of SQLite3 on Android, also contains some links to alternatives: http://greenrobot.org/news/mobile-databases-sqlite-alternatives-and-nosql-for-android-and-ios/

Couchbase Lite looks like it might work, but someone should test it before using it in production. I like the built-in sync feature, although I don't want to urge anyone to implement that at the moment. I don't think we'd ever have a use case for that. https://github.com/couchbase/couchbase-lite-android

**Comment by BlenderViking** [comment]
Hi everyone,

@mauriciocolli 
My code structure was inspired by a SQLite code provide by this guide  ([Android Guides](https://github.com/codepath/android_guides/wiki/Local-Databases-with-SQLiteOpenHelper)).

But I made a DAO layer for helper to keep the code clean.

@theScrabi @TheAssassin 
We can store directly JSON database, only if we use : [SQLite Json field doc](https://www.sqlite.org/json1.html)
Because, this field allow query on json attributes. But I don't know if SQLite layer on android allow this.

We can also use an ORM on Android like Hibernate on JavaSE / JavaEE :  [ORM on Android](https://github.com/codepath/android_guides/wiki/Persisting-Data-to-the-Device#object-relational-mappers)

**Comment by TheAssassin** [comment]
You're suggesting to use an SQLite3 extension, which might not necessarily work, because it is quite optional.

Instead of using the very slow SQLite3 as a storage, there's plenty of better alternatives. I'd rather use one of these. A structured database with a tree as the basic data structure will be a lot faster. The ones I suggested work like that, ForestDB have documented that quite well.

An ORM doesn't solve any of the issues I mentioned as far as I can see it. Please elaborate.

**Comment by BlenderViking** [comment]
@TheAssassin 

I agree with you storing data has JSON on relational database without JSON extension isn't a good idea.

For the questions : 
> 1. How easy is it to implement it in NewPipe? Is there a preexisting framework for that that can be used? 
> 2. How can we keep the database "schema" in sync with NewPipe? Is there a migration framework available?

With an Orm it's easy to interact and use SQLite Database, because it's built with annotation processing that generates most of the boilerplate code for you, code use within a DB is fast, efficient, and type-safe. It removes the tedious (and tough-to-maintain) database interaction code. So for me yes it's not more difficult to implement it.

The Orm recommended by the previous codepath is [DBFlow ](https://github.com/Raizlabs/DBFlow)(OpenSource:  MIT License) and if you read the overview you can see this ([DBFlow-Guide](https://guides.codepath.com/android/DBFlow-Guide)): 

> One of the issues with existing SQL object relational mapping (ORM) libraries is that they rely on Java reflection to define database models, table schemas, and column relationships. DBFlow is one of the few that relies strictly on annotation processing to generate Java code based on the SQLiteOpenHelper framework that avoids this issue. **This approach results in increasing run-time performance while also saving you from having to write a lot boilerplate code normally needed to declare your tables, manage their schema changes, and perform queries.**

And little extra, it's support database encryption of stored data [SQLCipherSupport.md](https://github.com/agrosner/DBFlowDocs/blob/99495e3566e38785870f6c580caa3915709f8d1f/SQLCipherSupport.md)

So for me using an ORM, can be a good candidate for the database storage.

For the original question provide by @theScrabi.
For me the service_id should be set an media level, because with this it's allow create automatically playlist media with multiple provider (Build a playlist with a mix of media provide by Youtube, Dailymotion, etc..).
It's was build like this in the dead playlist v1 support.

So for me add on the core path for a media the `service_id` and the item `position` on the list can be useful on the Core part (The position for support external playlist import on database).

**Comment by TheAssassin** [comment]
@BlenderViking please elaborate on how to properly implement the database migrations so that your reply to question 2 is complete.

**Comment by BlenderViking** [comment]
I never used DBFlow. But I found this issues how a contributor explain how to update a database scheme : https://github.com/Raizlabs/DBFlow/issues/771#issuecomment-239823965

For code usage, you can look here: [MigrationTest.java](http://programtalk.com/vs/DBFlow/dbflow-tests/src/test/java/com/raizlabs/android/dbflow/test/sql/MigrationTest.java/).

So Migrations are defined by creating a Migration class or by placing a valid SQL statement file in your project’s “assets/migrations/{DatabaseName}/{versionName.sql}” directory.

**Comment by TheAssassin** [comment]
I did not ask for some links (I can google too), nor I asked for how to actually implement them, instead of linking to examples, you should present an actual plan that makes it easy for us to understand your thoughts, ideally with some short examples (in this case, e.g. a short database scheme).

What we need to know is, how much easier is it to use this compared to a NoSQL database? It looks like it's a lot more effort to implement and later maintain it using such an ORM. How does NewPipe benefit from using SQLite3 instead of some NoSQL solution? The migration API isn't really nice either, it's going to grow and grow and grow. There'll be a lot of unused code in future versions of NewPipe, and that's actually wasted disk space.

A valid answer could be "Android provides an API in the standard library." for example. That's actually a plus, but doesn't really matter as you wanted to use another layer on top anyway. Maybe you can explain what makes your suggestion more awesome than all the others so it's best to choose it instead of something else?

**Comment by BlenderViking** [comment]
I didn't think one of ORM / SQLite / NoSQL solution is more awesome. I just mentionned the possibility to use an ORM for avoid the building CRUD query with updated scheme. But for me, it's not more difficult to implement one on these choices.

But in my previous approch was working on a pure SQLite implementation with using only integrated SDK. I chosed this approach because, it's the most used database integration on Android => This is probably the easiest way for developers will understand the code linked to the database.

You can find the original design Database approch with query and dao layer on the link share by @mauriciocolli and the code + javadoc for interface with contains all existing tables and columns in my previous implementation : [here](https://github.com/BlenderViking/NewPipe/blob/playlist_sqlite/app/src/main/java/org/schabi/newpipe/playlist/dao/NewPipeSQLiteHelper.java#L31)

Regard,

**Comment by mauriciocolli** [comment]
Considering these "examples" of migrations in [Telegram][1] and [k9-mail][2], is this that we are trying to avoid?

I did test DBFlow, and it makes the whole process very easy ([rough example][3]), although the migrations are somewhat verbose as the examples above. But I really like the API, and as they say, just forget about the db.

And I didn't really test Couchbase (just build a project), but one negative point is that it needs `jni` libs to work, producing a big inflation in the size of the apk (6-10 Mb for all the variants), and another thing is that it uses sqlite3 under the hood (so, I didn't "benchmark" it, but I don't think sqlite is slow as @TheAssassin said).

One point that I think we should consider too is the process of export/import, that should be compatible with every version of the app (or at least a good retro-compatibility), and in this point, the Json-like format/idea of @TheAssassin really shines.

**PS**: About migrations, we won't update the database in every release of the app, this requires a thought beforehand, so we can minimize the amount of schema versions/changes.

**PS 2**: And another thing that we should consider is that we won't write much data in it, one video each 30s-1min in the view history, the bookmark won't be a lot too because it depends in interactions of the user (more slow) and the same goes for the individual items to the playlist.

The only thing (that I can think of in the moment) that will be more "intensive" is bookmarking/importing a playlist of, let's say, 1000 videos, but it'll be easily dealt with SQL transactions.

[1]: https://github.com/DrKLO/Telegram/blob/master/TMessagesProj/src/main/java/org/telegram/messenger/MessagesStorage.java#L241
[2]: https://github.com/k9mail/k-9/tree/05df114eb1ffeb9fc7960bb6afc48f0b38e30faf/k9mail/src/main/java/com/fsck/k9/mailstore/migrations
[3]: https://github.com/mauriciocolli/NewPipe/tree/test-database/app/src/main/java/org/schabi/newpipe/database/bookmark

**Comment by theScrabi** [comment]
@mauriciocolli it sounds like you are better with the SQLite idea?

**Comment by b1k3rdude** [comment]
-     Search history
-     Bookmarks/favourites
-     subscribed channels
-     history

I very much like the idea of this, but can I request that book marks are local and don't require a youtube account to work.

**Comment by TheAssassin** [comment]
Why would you think anyone wants to use YouTube data?

This whole issue is about how to save the data locally, as it's not that easy to do it right. Of course all the listed items are to be saved on your local device.

**Comment by TheAssassin** [comment]
@mauriciocolli I'm still afraid of the SQLish solution because it'll most likely add a lot of boilerplate code which will bloat the binary. How does the framework you suggested/examinated mitigate the problem of having to ship **all** migrations ever written?

Many apps have these kind of problems, on every release they consume a little more space. Look at the social network ones for instance, they passed the 100 MB line already quite some time ago. Ok, we're far from that, but not even these apps have that much functionality, it's most likely code for app upgrades that bloats them.

**Comment by coffeemakr** [comment]
I'm in favor of a SQLish solution because libraries like [room persistence](https://developer.android.com/topic/libraries/architecture/room.html) which provides tools for code genration, migration and testing (including migration).

When using JSON there will still be some code to check if a field exists once a new field is added in a newer version. If there are that many changes in the database one could just drop a very old table and create a new one. Also I don't think migrations are a problem for the apk size. For example Telegram uses a lot of native code which requires much space.

**Comment by theScrabi** [comment]
Im with @coffeemkr. Also we now have a SQL database, so we stay with it. Also I don't think there will be to much changes in the tables.

**Comment by grrrrr** [comment]
this might be wrong place to ask but as you are discussion Database inclusion, I would like to make request for using SQLCipher.   This would add a layer of privacy and security to the end user in case of theft or confiscation of device.    I am thinking of case use where people in countries where there is repressive regime and watching videos going against government may get them in trouble should their devices be taken for inspection or even something as simple as nosy parents our partners :)

https://guardianproject.info/code/sqlcipher/

> this project will make it easier than ever for mobile developers to properly secure their local application data, and in turn better protect the privacy of their users. The data stored by Android apps protected by this type of encryption will be less vulnerable to access by malicious apps, protected in case of device loss or theft, and highly resistant to mobile data forensics tools that are increasingly used to mass copy a mobile device during routine traffic stops.

**Comment by marklapasa** [comment]
I've worked with SQLite and I've worked with SugarORM and I have to say it's a joy to use use the latter. The former I have been prone to making the smallest mistake and hours wasted on debugging it. SugarORM is pretty good for developers who want to keep that Object oriented mindset instead of juggling SQL jargon in the code.

My 2 cents. 

Btw, loving NewPipe! Just started using it today.

**Comment by TheAssassin** [comment]
> Im with @coffeemakr. Also we now have a SQL database, so we stay with it. Also I don't think there will be to much changes in the tables.

Please close the issue then.
