### ISSUE TITLE
NewPipe not working on Android 7.0 Nougat

### ISSUE THREAD

**Issue by quoctrungdhqn** [TeamNewPipe/NewPipe#5720]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [ ] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [ ] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Device info

 - Android version/Custom ROM version: 7.0
 - Device model: Galaxy Nesus

**Comment by mhmdanas** [comment]
We can't help you with so little info. Can you fill out the template properly (the NewPipe version is very important too!).

**Comment by quoctrungdhqn** [comment]
@mhmdanas Checkout master branch, then build on android device 7.0 Nougat you will see the loading is shown all the time when searching video. Kiosk page also the same. The list of videos not shown.

**Comment by mhmdanas** [comment]
Please fill out the template with the info you provided so that people can understand the issue at a quick glance. The checklist is required, and you should at least fill the "steps to reproduce the bug," "actual behavior," and "expected behavior sections in addition to "device info." Screenshots would be great too, and if you're getting any errors, please put them in the "logs" section.

**Comment by quoctrungdhqn** [comment]
Fixed by this link:
https://developer.android.com/studio/write/java8-support#library-desugaring
