### ISSUE TITLE
fastlane dir uses invalid names for some locales

### ISSUE THREAD

**Issue by eighthave** [TeamNewPipe/NewPipe#5750]
[Fastlane](https://github.com/fastlane/fastlane/blob/633860a5aae0fa9c0b936797560efb24181b1bf7/fastlane_core/lib/fastlane_core/languages.rb#L14) uses [BCP47](https://www.w3.org/International/articles/bcp47/) locale tags, which use a `-` as the separator rather than `_`.    There are a number of locales that use the `_` here.  Please rename those dirs to use `-`.

@linsui FYI https://gitlab.com/fdroid/issuebot/-/issues/33#note_522152297

**Comment by TobiGr** [comment]
Translation and thus creation of the descriptions is done via Weblate.
This are our settings in the [metadata project](https://hosted.weblate.org/projects/newpipe/metadata/):
**File format:** App store metadata files
**Language code style:** Default based on the file format

@eighthave For this reason, I suggest to also notify Weblate since multiple projects in fdroiddata seem to be affected by this

Unfortunately, I could not change this through the settings, because changing the language code style to "BCP style using hyphen as a separator, including country code" fails with 
> There is more than one file for Norwegian Bokmål language, please adjust the filemask and use components for translating different resources.
>
> Path of files to translate relative to repository root, use * instead of language code, for example: po/*.po or locale/*/LC_MESSAGES/django.po.

**Comment by eighthave** [comment]
Since Weblate is based on git, I think you can just rename (`git mv`) the local 
dirs and Weblate will pick it up.  It has worked for me in the past with 
Guardian Project app and F-Droid.
