### ISSUE TITLE
Show copy link and other sharing options in one page just like YouTube app

### ISSUE THREAD

**Issue by SameenAhnaf** [TeamNewPipe/NewPipe#5784]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

My smartphone shows sharing apps in four rows. It's irritating as I often need to swipe from left to right for three or two times. It would be great if Newpipe had the ability to show sharing options within a single page

And, yes, "Copy Link" option should be added. I can't mention any link while browsing any website.
#### Additional context

![IMG_20210307_134941](https://user-images.githubusercontent.com/79245641/110233175-73aea700-7f4c-11eb-926c-9f0e506b1933.jpg)

**Comment by mhmdanas** [comment]
If I'm not mistake, YouTube uses its own custom share sheet. I'm not sure if we want to do that, as we might be removing some functionality of the default share sheet (which differs between Android systems and ROMs).

**Comment by SameenAhnaf** [comment]
The upper screenshot is from SnapTube app. Both have 28 options.

![IMG_20210308_141110](https://user-images.githubusercontent.com/79245641/110294213-c3a76f80-8019-11eb-863f-93df03a8bc72.jpg)
![IMG_20210308_142111](https://user-images.githubusercontent.com/79245641/110294230-c904ba00-8019-11eb-8df6-d9e12406a511.jpg)

**Comment by SameenAhnaf** [comment]
@mhmdanas I think, that would not be a problem. An option in the settings can be kept as "Show sharing options". Options could be kept "From system page" and "From Newpipe page".

**Comment by TiA4f8R** [comment]
@SameenAhnaf I already worked on this (see PR #5187) but your ROM due to OEMs customizations doesn't keep the option, like on EMUI too (even if now the share sheet after my PR is now from Android System Chooser and not Huawei System Chooser on EMUI devices).
Your idea to have an option to display a custom share sheet or not is a really good idea! I think if we implement a custom share sheet, we should take the Android stock design.
The negative aspect of this custom share sheet is that user can't select quick actions, like a contact or a people in social networks, because apps cannot access to them if I am not wrong. This is what @mhmdanas says above.

For now, you can install Share to Clipboard, available in F-Droid: https://f-droid.org/packages/com.tengu.sharetoclipboard/, and remove copying the extra subjects (like the title of a stream) in app settings. This is what I do myself because most of other apps got the Huawei Share Sheet instead of Android Share Sheet (by using the Android standard method for create choosers of intents, `Intent.createChooser()`, instead of using an `ACTION_CHOOSER` intent, see the PR for more details).

**Comment by SameenAhnaf** [comment]
@TiA4f8R Thanks for your valuable explanation and Share to Clipboard app link.
