### ISSUE TITLE
Comment support when

### ISSUE THREAD

**Issue by Fixallmyproblems** [TeamNewPipe/NewPipe#579]
the main reason I have been switching to thr official Youtube app more often and not full time Newpipe yet is solely because of two main reasons: No comment support and you can't login to your Youtube acc and view and get notifs from your subscriptions, just wondering when this will get added or if it's a priority or not, Newpipe is a wonderful app that I use everyday

**Comment by Michkost** [comment]
I don't know about comments support, but Youtube account support will never exist. The app itself was made to use YouTube without Google Services.

**Comment by i-kocevski** [comment]
The whole point of the app is to watch YouTube videos. Plain and simple, no fuss. That's why I love it. I suggest you look up WebTube on F-Droid it's another solution for using YouTube without Google dependencies. Another suggestion would be OGMods's OGYoutube.
Sorry I can't provide any links I'm typing this from my phone.

**Comment by theScrabi** [comment]
@i-kocevski you are right.

@Fixallmyproblems if you are just about reading commends I can highly suggest [SkyTube](http://skytube-app.com/)

**Comment by Elaram** [comment]
@theScrabi Do you know approximately when subscription configured by the app will be possible

**Comment by theScrabi** [comment]
If everything works out well it might be this summer.

**Comment by Elaram** [comment]
Perfect, I will definitively stick to this app then, thanks for the fast answer!

**Comment by Zero3K** [comment]
I also would like to be able to read comments without being able to reply.

**Comment by r2308145** [comment]
have to agree that comments (just for viewing) would be quite useful

**Comment by avently** [comment]
@theScrabi what do you think about the last to comments? I agree with the authors. Sometimes comments are more useful than video

**Comment by theScrabi** [comment]
I wouldn't want it. Id like it more focused on the media. Tho if someone writes a propper implementation for it id give it a try. Now one had to add this function to the extractor and than to the frontend.

**Comment by karyogamy** [comment]
I might give it a shot eventually, though there are much more important features we need to cover first. Speaking of media, maybe we should integrate the comment system with the existing player. For example, we can implement an optional [marquee comment overlay](https://user-images.githubusercontent.com/5570482/32510511-b481d722-c3a5-11e7-8a68-2c985f469c58.jpg) on top of the main video player, allowing users to see comments on the fly. Since this kind of system is hardly seen in any other video streaming app, this might also help us differentiate from the others.

**Comment by avently** [comment]
@karyogamy I'm working on reimplementing video activity and making it embedded in video details fragment. Looks much cooler than what we have now. Trying to fix some bugs related to new "architecture". So at least wait before doing comments in video player activity.

**Comment by karyogamy** [comment]
@avently Take your time, we have a long way before I even attempt a proof of concept (local playlist, live and subtitle support, etc.)

**Comment by r2308145** [comment]
rather than seeing comments on the fly or other experiments I would rather see them done in a more simple and classical way, for example using a blank space under the video with link to comment section... dont know if it can be implemented, but I can imagine it more looking like [something like this](https://imgur.com/a/ZnOeq)

**Comment by karyogamy** [comment]
@r2308145 That's the basic comment system, I'm pretty sure this will be there regardless of anything else fancier, especially now @avently is working on an embeded video view on the details page.

**Comment by TobiGr** [comment]
@Tvax wrote in #952:
> A cool feature to add would be the comments section of a video.
It could be displayed by swiping to the right on the "Recommended videos" section beside the video player !

**Comment by evg-zhabotinsky** [comment]
I'd say that allowing user to log in would be a good idea. As it stands now, it's really more convenient to to use the official app and "share" videos/playlists to NewPipe. None of the features are used in this scenario except just the floating video box for long videos when multitasking and background player for music.

**Comment by speednroll** [comment]
@evg-zhabotinsky because they insist on inserting the google login into newpipe, they have nothing to see

**Comment by trymeouteh** [comment]
This would be cool. I don't care if you can't comment but to be able to view them is always something I do on YouTube some some comments are funny or they kinda tell you if the video is trash

**Comment by theScrabi** [comment]
I see. Well wed first had to focus on supporting commends in the extractor, then we could add it the the ui.

**Comment by briansaturnino** [comment]
I'm disappointed. It's been well over a year since OP posted, and there is still no comment section.

**Comment by ostrolucky** [comment]
Get lost stalebot

**Comment by TobiGr** [comment]
@beskhu3epnm #1650

**Comment by TobiGr** [comment]
Basic support for reading top-level comments has been implemented by @yausername. Thanks!
More additional improvements might come sooner or later, but I think we can open new tickets for them when needed.

**Comment by NilsIrl** [comment]
Is there an issue for comment replies?
