### ISSUE TITLE
Can you add the multi-sharing feature in the background?

### ISSUE THREAD

**Issue by muhmd10** [TeamNewPipe/NewPipe#5816]
0.20.2     Multiple shares available ✔ 

0.20.11   No multiple shares ❌❌  

- Please on new Versions, can you add the multi-sharing feature ?  background    ✔

![PhotoGrid_Plus_1615641298136](https://user-images.githubusercontent.com/80586717/111032746-cab9ed80-841e-11eb-905f-ab39176a2b6e.jpg)
![PhotoGrid_Plus_1615641491785](https://user-images.githubusercontent.com/80586717/111032750-d3122880-841e-11eb-9f67-83347e0b7bbd.jpg)

### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [ ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [ ] This issue contains only one feature request. I will open one issue for every feature I want to request.

**Comment by SameenAhnaf** [comment]
I am sorry but could you please explain what feature are you talking about? Do you want to enqueue (this will let you play videos one after another) the videos opened by the links from other apps? Then, there's been already an issue #4779. So, I believe this is a duplicate.

Do you want to copy multiple video links at once? Well, that's not possible through Newpipe app as this is a keyboard related thing. However, you can do so by using "Clipboard" feature of Google Keyboard.

Also, fill the templates properly. You should check the checklist, follow the guidelines and you mention your request under "Describe the feature you want", not on the above.

**Comment by muhmd10** [comment]
https://www.mediafire.com/file/6s8c7y5462einj2/0.20.2__good.mp4/file

https://www.mediafire.com/file/ij6dusedl5pmq16/0.20.11_bad.mp4/file

13 Mar 2021 Cmt 18:39 tarihinde SameenAhnaf ***@***.***> şunu
yazdı:

**Comment by muhmd10** [comment]
https://www.mediafire.com/file/6s8c7y5462einj2/0.20.2__good.mp4/file 

https://www.mediafire.com/file/ij6dusedl5pmq16/0.20.11_bad.mp4/file

**Comment by SameenAhnaf** [comment]
@muhmd10 Thanks for the explanation. But what you are calling "Multi-sharing" is actually called " Enqeue". However, Newpipe app has the "Enqeue" option if you browse videos directly from the app.

You will have to play a video on background or popup. Then, go back and long press on the video. "Enqeue" option will appear on the top. Long press on the video title and "Enqeue" option will appear on the top.

At this moment, there's no such thing called "Multi-sharing" in Newpipe. That's why, it might confuse the developers. #4779 will ask for enqueue. So, you may close this issue if you can multi-share by double tap. If you want to do so in a single tap, rename the issue title into 

Add 'Start or enqeue on background' and 'Start and enqueue on popup' in preferred open action

Multi-sharing (or enqeueing) videos for both background and popup will be great.

Type under "
Clear all the texts on the above and mark the checklist by typing an 'x' (axe) between the third brackets for 3 options in checklist.

Copy and paste following texts to avoid confusion among the developers.

Type under "Describe the feature you want"

0.20.2 Enqeueing videos opened from other app ✔

0.20.11 No enqeuing videos opened from other apps❌❌

Please on new Versions, can you add the enqeueing videos on the background or popup? ✔

Type under "Additional context". Here, you will include screenshots or video links.

https://www.mediafire.com/file/6s8c7y5462einj2/0.20.2__good.mp4/file

https://www.mediafire.com/file/ij6dusedl5pmq16/0.20.11_bad.mp4/file

Type under "How will you/everyone benefit from this feature?"

Users will be enqeue videos automatically with an ease no matter where they are browsed.

**Comment by TiA4f8R** [comment]
@muhmd10 Please fill the template properly, your feature request is hard to understand.
Closing for now.
