### ISSUE TITLE
Add MX Player seek position gesture

### ISSUE THREAD

**Issue by SameenAhnaf** [TeamNewPipe/NewPipe#5831]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

Swiping from left to right could be added to seek forward and vice versa. This gesture will immensely be helpful. Following navigation options in settings will also be appreciated.

![IMG_20210314_161236](https://user-images.githubusercontent.com/79245641/111117316-91ee5580-8591-11eb-85e5-cde723dd3f09.jpg)

Please note this gesture should not be applicable if the swipe occurred from any edge. I found this problem in many players and Newpipe app should not have this.

#### How will you/everyone benefit from this feature?

Most of the time, we hold the phone in one hand on the width while watching landscape videos. It's a little irritating to miss this feature as the other hand needs to be used just to seek position

**Comment by MD77MD** [comment]
this is a most

**Comment by avently** [comment]
Oh, seriously? I implemented this feature some years ago. I thought you hate all my ideas, looks like I was wrong.

**Comment by SameenAhnaf** [comment]
@avently Not all of your ideas, but I think every feature should be optional. That's the core power of Newpipe! How? Let me explain.

For example, brightness, volume gesture, select playback options before opening the video and the list goes beyond. Many people like unified player, many people don't. I respect your requirement, opinion and idea. But you need to understand that every shoe doesn't fit every foot. The same goes for "Seek position" gesture and "Always switch to full screen" button. 

You suggested a third party app instead of the option for always keeping "Full screen" button. That's good. But every Tom, Dick and Harry won't find or even think of these alternatives.

Many people prefer having all the options. Many people prefer having only selected ones. Everyone is different.

Sorry for all the misunderstanding. I should not have lost my mind and blame a person for no reason. Many users took your changes in positive way indeed. But you also need to understand that many users will also prefer existing behaviour. So, instead of ditching a feature, let's keep all of the features optional. For example, my grandmother faces a hard time adopting new features. We never know others' needs.

**Comment by avently** [comment]
@SameenAhnaf I completely understand your love to have an option. The drawback is a code complexity that comes with multiple options.
If you look at NewPipe's code you will notice that in many places we have something like this:
```
If (userWantsToPlayAutomatically
&& isLandscape
&& !isTablet
&& !isInMultiWindow
) {
doSomething()
}
```

So based on one option we have other requirements that should match desirable behavior.
Let's say you added another option that should be taken into account too. The code now looks harder to read, to understand, and to not **** up.

```
If ((userWantsToPlayAutomatically
&& isLandscape
&& !isTablet
&& !isInMultiWindow)
|| (someotheroption
&& additionalCheck
|| (anotherOne && more)
)
) {
doSomething()
}
```

Imaging you have more options. And you have tons such places in code when you should act differently based on an option in the settings. Now imaging you see the code for the first time like any new developer. How much time you would spend in order to understand a logic behind such `if`'s? That's can be performed fast in a brain, you should visualize all possible ways where the app flow could go.

So when you meet the requirement to find one universal solution you now know why devs want one solution instead of options.

**Comment by SameenAhnaf** [comment]
@avently  Thanks for your valuable explanation. Every single code is precious. The same goes for each feature and codes. The best way to know if something is worth of change is poll.

Adding a feature is always a welcome addition. But changing the procedure for an action or ditching a feature should be brought under reconsideration. Polls can not only solve the conflicts but also let users think of better alternatives! It will also avoid creating more issues. 

Just look at this poll. Clearly, everyone likes 2.1. No new argument should be brought or most expectedly, none will find it disturbing
![Stitchcraft_20210328-195614](https://user-images.githubusercontent.com/79245641/112755065-df8ea780-9000-11eb-88e4-f9c7a5ab53c4.png)


Here, we can see variation of opinions. Most people want to hide full screen button but still make it optional. Plus, "Always showing full screen button" appears to be the second most popular option. If showing full screen button is made optional, uses will still have an option to choose whether to keep full screen button. Although first option will let the developer spend an extra amount of coding, everyone will enjoy the benefits without any future hassle.
![IMG_20210328_195914](https://user-images.githubusercontent.com/79245641/112755754-f4b90580-9003-11eb-92c9-316f21f05bca.jpg)


Nobody needs to make every single feature optional. We can do so only when it's needed. As I stated earlier, we never know others' needs. I don't know your needs. You don't know my needs. Only, the mentality of co-operation will let our app experience be great!

Again, I solely repent for my blunder and request your pardon. I hope you understand my words. I appreciate your time and efforts regarding our issues.

**Comment by r7l** [comment]
While i really love this app, i have a hard time to understand why it was decided that brightness would be such an important thing, to include it as a gesture during video play instead of a seek position gesture. You can easily pull down this Android menu and have a brightness slider from the OS if that's so important to anyone.

But skipping a minute in a video is the worst possible implementation in this player. You touch the video the wrong way, it drops either sound or brightness instead of showing the video scroll bar, since these gestures also act as "to 0" if you touch and move finger just 1 millimeter. It might also trigger the virtual android buttons and kick you out of the entire video, if you hit the bottom of the video where you would expect the progress bar to show up. That's just a general issue with Android virtual buttons and any other lower positioned in app option.

Maybe it's just me and my huge fingers. But even on my 10" tablet, i am not finding it easy to skip a couple minutes in order to skip through videos.

So i am +1 for seek position gesture!

**Comment by SameenAhnaf** [comment]
Closing in favor of#889.
