### ISSUE TITLE
Brief fullscreen white flash when opening app with dark theme.

### ISSUE THREAD

**Issue by krompus** [TeamNewPipe/NewPipe#590]
I'm not sure if it would be possible to fix this, but it would certainly be nice. :)

I love the black theme on my amoled screen, but this is a minor annoyance when opening links with Newpipe.

**Comment by mauriciocolli** [comment]
That is hard to fix, the only way to "hide" this problem is using a splash screen, that can be whatever we want, color or logo, but there're some problems like:

- I don't think there's a way to get which theme is selected this early (app startup)
   - Using a static splash screen, with defined colors, solves the problem (and I don't think we'd want to use dynamic colors anyway)
- If the user have a fast device, he will see a flashing splash screen, exactly the problem you describe
   - We can add a delay in the splash screen to solve it

The design guidelines recommends the use of splash screen, Google Maps for example, there's a delay of  200ms-500s to open, I don't know if it's because the initialization is heavy and lengthy or they introduced a delay to solve the problem I mentioned early.

Try to open Chrome, you'll see that they show a "placeholder", and I think that's a good solution too that we could use it.

**Comment by coffeemakr** [comment]
The window preview can also be disabled but that would maybe annoy users on slower devices because they won't see anything before the activity is fully loaded. But I'm not sure if this is a issue because there is no loading done before a search is entered.

**Comment by krompus** [comment]
Well, if a static splash screen with defined colours is the simplest solution, then perhaps we should vote on the colour? I vote for black, or dark grey as compromise. :3

**Comment by TobiGr** [comment]
The [big refactor](https://github.com/TeamNewPipe/NewPipe/pull/669) fixed this. Thanks to @mauriciocolli.
