### ISSUE TITLE
WebM video decoding is broken

### ISSUE THREAD

**Issue by codebam** [TeamNewPipe/NewPipe#597]
When playing WebM video the video freezes and eventually causes the player to crash. WebM audio and MPEG formats are not affected.

Steps to reproduce:
1. Change video format to WebM in settings
2. Play 1080p 60fps video in fullscreen landscape mode (not popup)

Details:
Device Nexus 6P
OS: Android 7.1.2 Copperhead OS, June security update

**Comment by codebam** [comment]
I've been looking into this. It seems that WebM decoding is very slow at high resolutions and high framerates, causing videos to freeze and crash. For example I cannot play anything above 1080p 30fps WebM on my 6P without the video freezing and player crashing.

**Comment by mauriciocolli** [comment]
Yes that's a problem that will probably be recurring, as almost no old phone has hardware decoding for the codec used (VP9) and will rely on software decoding, and as you can see in [this page](https://www.qualcomm.com/products/snapdragon/processors/comparison), your processor doesn't have vp8/vp9 support, so probably it's using it.

There's no fix for that and this issue is very device specific, so it's recommended to use mp4/x264 as this probably will be hardware accelerated (it's very common, and—in your case—it is).

**Comment by codebam** [comment]
Oh okay, thanks

**Comment by PacoBell** [comment]
Couldn't we at least drop video frames when the player can't render fast enough? That's what the YouTube app does now when it encounters high resolution/frame rate/speed videos. That UX is much more preferable to a frozen screen with okay audio.

**Comment by karyogamy** [comment]
The player is already dropping frames. The reason why the playback freezes is that all the frames are dropped because the video renderer can't catch up to the playback speed. This problem is already reported and being worked on: https://github.com/google/ExoPlayer/issues/2777

My guess is that the youtube app is either rolling their own MediaCodecVideoRenderer to periodically show dropped frames, or perhaps that DASH sources are more resilient towords freezing because they are chunked.

**Comment by PacoBell** [comment]
I would definitely be amenable to the former solution. Anything's better than nothing. Perhaps the average time needed to render a keyframe should be measured and compared to the current birate in order to calculate a reasonable rendering deadline and schedule. So relatively powerful hardware might only skip every other keyframe, but a slower device might have to display only every tenth keyframe or less. Regardless, this should be a dynamic process. I do notice that the YouTube app's "Stats for Nerds" does include a live count of dropped frames.
