### ISSUE TITLE
search shows no results

### ISSUE THREAD

**Issue by hp8wvvvgnj6asjm7** [TeamNewPipe/NewPipe#6009]
no results in search unless one clears the Recaptcha cookies. 
I have to do this multiple times per day since the last update.

**Comment by SameenAhnaf** [comment]
Use VPN for solving your problem. If recaptcha still appears again and again, change your VPN location and try again.

Showing constant recaptchas is a problem with your network. Extremely sorry, Newpipe can do nothing regarding this.

Also z please fill in the template properly. You are not supposed to remove it. Enter an 'x' (letter: exe) to check a checkbox. Describe in details what you want in "Expected behaviour" and what occurs in "Actual behaviour".

**Comment by hp8wvvvgnj6asjm7** [comment]
I use a VPN. This problem wasn't there before. Search yields no results!

**Comment by SameenAhnaf** [comment]
@hp8wvvvgnj6asjm7
>If recaptcha still appears again and again, change your VPN location and try again
