### ISSUE TITLE
1x1 grid view option

### ISSUE THREAD

**Issue by SameenAhnaf** [TeamNewPipe/NewPipe#6087]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

Users in #5153 asked for adding big thumbnail just like YouTube app. It was expected to be added for related videos, what's new feed, subscription feed and trending feed only. However, it could be a separate setting as well.

"1×1 Grid" should be applicable only for trending, subscription group, what's new feed and related videos if 'Auto' view mode is selected. List view will be applicable for channels and playlists at this moment.

One more thing, "1x1 grid video preview" setting will be great. This setting will play preview and other stuff automatically. An "Unmute" (Just like Facebook Watch) should be shown. Note that unmuting a video should start the video with other interface options right then without opening the video info. Video should play continuously unless a user scrolls down.
1. Off: Videos will be listed as usual. No unmute button should be shown.
2. On, for 3 seconds: Preview should be shown of 3 seconds repeatedly unless a user scrolls down.
3. On, for 6 seconds: Preview should be shown for 6 seconds repeatedly unless a user scrolls down.
4. Play video: Videos should start playing muted by default. Clicking on 'Unmute' should switch the video unmuted.

#### Additional context

Related issues: #6086, #5153, #5826, #6083

#### How will you/everyone benefit from this feature?

User experience will be just like YouTube app. Big thumbnail will be a joy to browse. Plus, auto view mode will be able to make a true sense.

**Comment by saebaryo-xyz** [comment]
Hey team, I also have difficulties using the app with small thumbnails instead if big ones in the original YT app and even Libretube or Skytube.

Any additional info is needed to have this feature worked on ?

Thanks!

**Comment by opusforlife2** [comment]
@SameenAhnaf This isn't adhering to the "one FR per issue" rule. Should be closed since #5153 is already there.

**Comment by mahendranv** [comment]
I did some changes in my fork and have achieved something similar. It is not a 1x1 grid but, rearranged the list item layout a bit.

![image](https://user-images.githubusercontent.com/6584143/199248090-a96ab0a9-3365-479a-916b-5a79f8c61f6f.png)

This one required bit of changes in Extractor as current implementation picks thumbs with low resolution.

### My suggestion 
There can be a new item view called **card** will be introduced. It behaves this way,
|Form factor| Portrait | Landscape|
|-|-|-|
|Phone|Full width card|Current list item view with larger thumbnail|
|Tablet|Two per row| 4 per row(trial and error)|

Another setting checkbox for thumbnail resolution can be introduced. This setting will be considered by extractor while parsing the API response. While max res selected, it'll pick maximum available resolution. Otherwise will follow the existing logic.

---

If it is OK, I can work on it and raise a PR. Auto playing the thumbnail can be raised as a separate FR as it would require quite some effort.

**Comment by mahendranv** [comment]
Based on how old is the video, the thumbnail URL behaves in two ways. The extractor should skim through list of thumbnails and pick ideal one as HQ one tends to consume data and load slowly.

With and w/o hash:
1. Sanitized URL has higher resolution. On few videos observed this behavior. This case should be studied just to ensure lower data consumption.
1280x720
https://i.ytimg.com/vi/qgVFDT8ELEQ/hq720.jpg
720x404
https://i.ytimg.com/vi/qgVFDT8ELEQ/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAfKJuxDdaL5U7eNcG2ratqbaV5Jw

2. Sanitized URL cropped the image to 4:3 and thus adds back bar on top and bottom. **Remedy**: The card layout will lock the imageView in 16:9 aspect ratio with center crop.
480x360 - This one has black bars on top and bottom [4:3]
https://i.ytimg.com/vi/nwP3TeK-fPs/hqdefault.jpg
480x270 - [16:9]
https://i.ytimg.com/vi/nwP3TeK-fPs/hqdefault.jpg?sqp=-oaymwEcCOADEI4CSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDY9pkLmLitAAF9lU7EVN2DwYwuBQ

**Comment by mahendranv** [comment]
[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/9911924/app-debug.zip)

Test build with package id `org.schabi.newpipe.demo` to ensure sideloadable along with production version. 
In appearance -> List view mode -> Card option will be available

- [x] Portrait mode - full width cards
- [x] High res thumbnails
- [ ] Adopt UI for TV
- [ ] Landscape mode (Show list item like YouTube)
- [ ] Thumbnail quality setting in preferences

**Comment by AudricV** [comment]
I already worked on multiple images extraction support, and there is already a PR for that in the extractor (`https://github.com/TeamNewPipe/NewPipeExtractor/pull/889`). You should not change something about images with this feature request, that's another one.

Also, it is the responsibility of clients to make size choices, the extractor needs to return everything extractable.

**Comment by mahendranv** [comment]
@SameenAhnaf 
## Progress update
- Full width thumbnails
- Text size follows system provided textAppearance elements -> The font size is bit larger than the other layouts. Color follows the same.
- Uses existing APIs - i.e thumbs are bit blurred. Will support once multiple thumbs PR merged in extractor 

### Feed screen stream listing
<img src="https://user-images.githubusercontent.com/6584143/200032805-0518136c-9fa0-4c02-b6b4-b72856b8ffb3.png" width="240"/>

### Playlist listing
<img src="https://user-images.githubusercontent.com/6584143/200034400-fab1a349-5076-418d-b552-20f874d49063.png" width="240"/>

### Playlist nested with streams in search screen
<img src="https://user-images.githubusercontent.com/6584143/200035106-38b9e3d8-059d-44b9-8e51-6ccdb8e3c760.png" width="240"/>

### Streams inside a playlist
<img src="https://user-images.githubusercontent.com/6584143/200034697-96836ca3-b2a7-44be-bfca-ef2b7d445583.png" width="240"/>

Reorder handle
https://user-images.githubusercontent.com/6584143/200036151-1e85527e-cd61-4d82-bf1b-b0371594abcb.mp4

**Comment by mahendranv** [comment]
Updated the feeds  - 
![image](https://user-images.githubusercontent.com/6584143/200133032-fe992c45-7f73-46fc-95c5-57fb275d31a4.png)
--
Having larger thumbnail benefits while discovering new content. For history do we need cards? 
It will reduce the number of on-screen items.
--
Setting 3:4 aspect for shorts might take larger screen real estate as shorts are shot on portrait orientation
--
In the channel tab, I don't see shorts are mixed there. I'll update if we get it from extractor. 

Here is how it's implemented in YT: No matter how many shorts the channel has, 6 shorts displayed in two rows and opening them goes to the player screen where endless swipe happens.

With larger titles in the shorts, the textview will fold to four or five lines right?

**Comment by mahendranv** [comment]
I like this portrait thumbs for Shorts. I'll try to include this tomorrow.

**

For other tickets mentioned in here: https://github.com/TeamNewPipe/NewPipe/issues/6087#issuecomment-1299050317

#8412 [Done] - Grid thumbnail size has been increased for tablets and TVs. If font size needs to be increased, can be done.
#6474 - Channel about screen / card can plan a separate PR

#7403 - I think this can be done with few focus and key press listeners setup. As a short term solution, we can provide this.
#5322 - For TVs, leanback would be the long term solution. We have [TV specific libs](https://developer.android.com/training/tv/start/libraries) that can enable us smooth navigation. But this might as well be a separate variant more focused for TV. Otherwise, might mess up tablet/phone counterpart.

**Comment by mahendranv** [comment]
> https://github.com/TeamNewPipe/NewPipe/issues/6087#issuecomment-1304606996

We have an extractor PR that can provide the image aspect ratio. https://github.com/TeamNewPipe/NewPipeExtractor/pull/889.
Once it's merged, portrait thumbs can be implemented. Doing this computation while loading image will make the UI clunky,

**Comment by tvnmguy** [comment]
> @SameenAhnaf please give feedback. 
> Test build: 
> [card_layout.zip](https://github.com/TeamNewPipe/NewPipe/files/9940700/card_layout.zip)
> 
> ## Progress update
> - Full width thumbnails
> - Text size follows system provided textAppearance elements -> The font size is bit larger than the other layouts. Color follows the same.
> - Uses existing APIs - i.e thumbs are bit blurred. Will support once multiple thumbs PR merged in extractor 
> 
> ### Feed screen stream listing
> <img src="https://user-images.githubusercontent.com/6584143/200032805-0518136c-9fa0-4c02-b6b4-b72856b8ffb3.png" width="240"/>
> 
> ### Playlist listing
> <img src="https://user-images.githubusercontent.com/6584143/200034400-fab1a349-5076-418d-b552-20f874d49063.png" width="240"/>
> 
> ### Playlist nested with streams in search screen
> <img src="https://user-images.githubusercontent.com/6584143/200035106-38b9e3d8-059d-44b9-8e51-6ccdb8e3c760.png" width="240"/>
> 
> ### Streams inside a playlist
> <img src="https://user-images.githubusercontent.com/6584143/200034697-96836ca3-b2a7-44be-bfca-ef2b7d445583.png" width="240"/>
> 
> Reorder handle
> https://user-images.githubusercontent.com/6584143/200036151-1e85527e-cd61-4d82-bf1b-b0371594abcb.mp4

1
![session-2022-11-07-143118 (1).jpg](https://user-images.githubusercontent.com/116799295/200270306-f735562d-ee0a-4de2-a962-fabea121934d.jpg)

2
![session-2022-11-07-143118.jpg](https://user-images.githubusercontent.com/116799295/200270353-c4bc2ff0-d645-42f3-ac7e-c71872fda83b.jpg)

I prefer 2nd one, because it follow/maintain other card layout uniformity

![IMG_20221107_143223.jpg](https://user-images.githubusercontent.com/116799295/200270741-55333959-39b6-4b6b-aae1-42e66ea27e0a.jpg)

![IMG_20221107_143356.jpg](https://user-images.githubusercontent.com/116799295/200270769-78101c79-f252-4b17-b9c6-b758bc90abdb.jpg)
