### ISSUE TITLE
Newpipe

### ISSUE THREAD

**Issue by codycox24** [TeamNewPipe/NewPipe#6218]
Download track issue

**Comment by fynngodau** [comment]
Could you please be more specific what the issue is, when it happens, and whether there are any errors shown to you? Please also use the [issue template](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/ISSUE_TEMPLATE/bug_report.md).

Since your report is currently not helpful for solving your problem, I will now close this issue.
