### ISSUE TITLE
Splitt settings into sub Settings

### ISSUE THREAD

**Issue by theScrabi** [TeamNewPipe/NewPipe#627]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

Our Settings activity has a lot stuff in it. Wouldn't it be useful to split the settings activity up into sub setting activities?

**Comment by TobiGr** [comment]
I was thinking about this for quite a while and didn't find the optimum solution. 
That's what I got:
 
**Video & Audio** [sub activity]
_Video & Audio_ [preference category] 
... 
_Popup_ [preference category]
... 
  
**Downloads** 
Video download path 
Audio donwload path 
Allowed charracters in filenames 
... 
  
**Appearance** 
... 
  
**Content & Language** 
Application language 
Preferred content language 
Show age restricted content 
  
**Other** 
Autoplay 
Search suggestions 
Search history 
Watch history 
 
With the upcoming changes to the settings by #624, #626 and #636, I got five sub activities. I didn't find a good place for the `popup`, so I put it into the `video & audio` view. But you can also split it into two sub activities. I renamed the `content` category because one simple but useful setting is missing: the application's language. I think this option can be added easily. (The language option could also be listed in `appearance`). Settings that will come with multi service support could be added as `services` or as `YouTube`, `SoundCloud`, `Vevo` etc. category.

**Comment by theScrabi** [comment]
Yea sounds good :)

**Comment by mauriciocolli** [comment]
Fixed in #669
