### ISSUE TITLE
Likes aren't shown in the YT videos comments

### ISSUE THREAD

**Issue by EnPeignoir** [TeamNewPipe/NewPipe#6323]
### Checklist

- [x] I am using the latest version - 0.21.2 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Go on a YT Video
2. Check likes
3. Observe

### Actual behaviour

Likes on comments are showing 0

### Expected behavior

Should report the number of likes of the comments

### Device info

 - Android version/Custom ROM version: Android 10 QP1A.190711.020 / MIUM 12.0.10
 - Device model: Xiaomi Note 9 (M2003J15SG)

**Comment by n-ce** [comment]
Yes. Same. Android 8.
![Screenshot_20210518-081713](https://user-images.githubusercontent.com/69345507/118582997-f1472c80-b7b1-11eb-9a07-91c9e23f98a8.png)

**Comment by litetex** [comment]
Looks like YT changed the data structure from [``likeCount``](https://github.com/TeamNewPipe/NewPipeExtractor/blob/6db4bea8ca51ac40a8f831527b274ad50895070e/extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/extractors/YoutubeCommentsInfoItemExtractor.java#L76) to ``voteCount``:

![grafik](https://user-images.githubusercontent.com/40789489/118718764-ec24c480-b827-11eb-8582-95ad12bc0af4.png)

![grafik](https://user-images.githubusercontent.com/40789489/118718925-1c6c6300-b828-11eb-8c0f-2e425bc047e2.png)


Very likely a [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor) problem.

**Comment by EnPeignoir** [comment]
From litetex in [https://github.com/TeamNewPipe/NewPipe/pull/6337#issuecomment-846170829](https://github.com/TeamNewPipe/NewPipe/pull/6337#issuecomment-846170829) : 
> This PR may no longer be required, because `likeCount` was fixed.
> However due to the fact that yt now returns localized strings like `3.3k`, `15k` or `3.3M` the number of likes may be inaccurate when the `likeCount` is bigger than 1000.
> The `likeCount` functionality will also break if the language to get the comments is not anymore hardcoded to `en` (which may happen in the future).

**Comment by konqueries** [comment]
Same Issue on nougat

**Comment by fynngodau** [comment]
The extractor should return a like count of "-1", causing a "-" to be displayed, instead of "0" if extraction fails.

**Comment by EnPeignoir** [comment]
> The extractor should return a like count of "-1", causing a "-" to be displayed, instead of "0" if extraction fails.
Why not just raise a Error ?

**Comment by fynngodau** [comment]
@EnPeignoir I looked at the code very briefly this morning: the YouTube comments extractor did throw a `ParsingException` on extraction failure, but apparently, we’re still getting a `0` out of some (other, not YouTube-specific) piece of code where it should return `-1`.

**Comment by litetex** [comment]
@fynngodau 
At first: my corresponding PR will primary fix the problem of this issues and nothing else.

However some notes to your statements:

> I looked at the code very briefly this morning: the YouTube comments extractor did throw a ParsingException on extraction failure, but apparently, we’re still getting a 0 out of some (other, not YouTube-specific) piece of code where it should return -1.

Currently ``0`` is returned, because it's the default return value if ``"likeCount"`` (which currently happens, because yt renamed it to ``voteCount``) isn't found in the returned json:
```java
	/**
	 * Returns the {@link Integer} at the given key, or 0 if it does not exist or is the wrong type.
	 */
	public int getInt(String key) {
		return getInt(key, 0);
	}

	/**
	 * Returns the {@link Integer} at the given key, or the default if it does not exist or is the wrong type.
	 */
	public int getInt(String key, int default_) {
		...
	}
```

> The extractor should return a like count of "-1", causing a "-" to be displayed, instead of "0" if extraction fails.

This is not possible anymore (and maybe it wasn't even possible in the past), because YT doesn't return the ``voteCount`` if a comment has no likes. 
So it's now impossible to distinguished between ``0 likes`` and ``yt changed the returned json``, which also  results in the situation where the property may not be found.

If the ``0`` is a problem, you could open a new issue/PR, where the returned string of https://github.com/TeamNewPipe/NewPipe/blob/0039312a64e7271fec2e0a295db1d6979e83cf3f/app/src/main/java/org/schabi/newpipe/info_list/holder/CommentsMiniInfoItemHolder.java#L142 is changed from ``"-"`` to ``""`` so that it resembles same behavior as a YT's comments which has 0 likes.

I personally don't have a problem if a comment has ``"0"``, ``"-"`` or ``""`` likes 😄

**Comment by fynngodau** [comment]
> This is not possible anymore (and maybe it wasn't even possible in the past), because YT doesn't return the voteCount if a comment has no likes.

Ah, I see, thanks for the explanation.

**Comment by EnPeignoir** [comment]
But it throws a ParsingException, so if NewPipe throws this error, we can change 0 by - ?

**Comment by litetex** [comment]
> But it throws a ParsingException
No, it returns 0, because no property was found 😉

**Comment by EnPeignoir** [comment]
Extract from a previous comment of this issue :
> the YouTube comments extractor did throw a `ParsingException`

Are you sure ? @litetex
