### ISSUE TITLE
Comments upvotes displayed wrong

### ISSUE THREAD

**Issue by mythe4th** [TeamNewPipe/NewPipe#6331]
Hi Guys, 

With the latest version of new pipe 21.2 i have the issue that in the comments of all videos the likes of a comment are displayed as 0 even though that is not true. 

Iam using a samsung galaxy s10 with standard one ui 3.1 and adroid 11. 

![Screenshot_20210519-130643_NewPipe](https://user-images.githubusercontent.com/83753664/118803022-22ebf080-b8a3-11eb-8a7d-e17178c5001a.jpg)

Hope you can fix this. 
Thanks

**Comment by skyGtm** [comment]
Duplicate: #6323

**Comment by mhmdanas** [comment]
@yashpalgoyal1304 the difference is that the `user-ignored-template-instructions` label is for when the template was present but the user chose to ignore it, not follow all of its instructions properly, or remove it (you can know by seeing if a label has been added automatically when the issue was opened), while the `doesnt-follow-template` one is for issues where the template chooser was not shown (e.g. when using a third-party GitHub client). I'll add descriptions to the labels to make this distinction clearer.
