### ISSUE TITLE
In-app updater

### ISSUE THREAD

**Issue by pakodx** [TeamNewPipe/NewPipe#6479]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### How will you/everyone benefit from this feature?

I would like to request an in app updater, like dentex YouTube downloader has
Clicking the push notifications opens a tab in the browser then immediately closes it and I have to look for the apk myself every time
Not to mention it's annoying to have that notification there
It would save a lot of time considering how often newpipe is updated

**Comment by ShareASmile** [comment]
The idea of an internal updater has already been rejected in #3141

**Comment by ProjectPatatoe** [comment]
I skimmed through #3141 and I think one thing that is not mentioned in there is that there can be a real problem with relying on fdroid alone with their slower updates. I switched from f-droid to manual apk because it could be days (I think once I waited a week) for f-droid to actually see that there is an update. This is a problem when something on the youtube side of things changed and newpipe is basically non-functional. 

The way it is now, I hit the notification, allow firefox to install unknown apps, update, and then disallow firefox again.

There's a reason this topic keeps coming up ):

**Comment by el-banto** [comment]
If you add the NewPipe repository then you won't have slow updates in fdroid.

**Comment by mhmdanas** [comment]
It is as @ShareASmile says.

**Comment by ShareASmile** [comment]
To add NewPipe Repository to to Fdroid App (or any Fdroid client like Foxy Droid) follow:-
https://newpipe.schabi.org/FAQ/tutorials/install-add-fdroid-repo/

**Comment by ProjectPatatoe** [comment]
> 
> 
> To add NewPipe Repository to to Fdroid App (or any Fdroid client like Foxy Droid) follow:-
> https://newpipe.net/FAQ/tutorials/install-add-fdroid-repo/

thanks! I didn't realized people were actually using f-droid repos like ubuntu's ppa
