### ISSUE TITLE
NewPipe For Android 2.3.6

### ISSUE THREAD

**Issue by Manav2007** [TeamNewPipe/NewPipe#6488]
Can we please get newpipe for android gingerbread? I know you will need to remove many features but I just want youtube I don't even want a miniplayer.

**Comment by AlexN1997** [comment]
Does NewPipe legacy work for you?
But android 2.3.6 is pretty outdated

**Comment by TobiGr** [comment]
Android 2.3.6 is 10 years old. You have a living security risk in your hands.
Apart from that, making NewPipe legacy compatible with that version is going to require pretty much work, because most dependencies are not compatible with gingerbread. Additionally, the maintainer of the legacy version has not been around since quite some time. It is more than just unlikely that NewPipe is going to be compatible with Android 2.3.6
