### ISSUE TITLE
y2u.be support (Youtube URL shortener service)

### ISSUE THREAD

**Issue by opusforlife2** [TeamNewPipe/NewPipe#6525]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

Support for opening y2u.be links within Newpipe. The scheme seems pretty simple, as the website has an example:

http://www.youtube.com/watch?v=j4dMnAPZu70 gets converted to http://y2u.be/j4dMnAPZu70

#### Is your feature request related to a problem? Please describe it

Saw this link shortener for Youtube being used in video descriptions recently.

#### How will you/everyone benefit from this feature?

Users will be able to open such links directly in Newpipe instead of having to go through the browser. No idea if there is tracking involved, but if so, that would be avoided too.

**Comment by SameenAhnaf** [comment]
If I am not wrong, Newpipe app actually has a browser embedded inside. So, isn't it possible to recognise if the URL is actually a redirecting URL? Not just from y2u, rather any platform.

Right now, users do have to open the URL on browser. Then, they have to copy or share the actual URL.

**Comment by mhmdanas** [comment]
@SameenAhnaf your suggestion is not possible to implement as I understand it. I believe the list of URL "formats" that NewPipe accepts when opened from other apps is statically specified (that is, NewPipe cannot decide at runtime whether it can open a URL or not).

**Comment by ChiefMikeK** [comment]
Why not just paste `j4dMnAPZu70` into the search bar ?

**Comment by mhmdanas** [comment]
@ChiefMikeK that would take the convenience out of it, wouldn't it? Instead of at most two steps (opening the URL and choosing NewPipe if you don't have it set to open YouTube URLs by default), it would take at least a couple more steps to do that, in addition to not being immediately obvious for non-technically-inclined users.

**Comment by SameenAhnaf** [comment]
@mhmdanas I think, you meant that Newpipe app can be set as default browser for supported links only. So, shared links should function the same way, right?

>it would take at least a couple more steps to do that, in addition to not being immediately obvious for non-technically-inclined users.

Yeah, it would seem quite strange that users can share but cannot choose Newpipe as a browser for those links. Even if the list of supported links become unspecified, many users will question the core function of Newpipe.

Because, Newpipe is not a stand-alone browser for all types of links like Chrome or Safari, rather a media streaming app from selected platforms only. Sorry, I absolutely missed that point and should have noticed before commenting.

**Comment by mhmdanas** [comment]
> I think, you meant that Newpipe app can be set as default browser for supported links only. So, shared links should function the same way, right?

Sorry, I don't follow you.

**Comment by B0pol** [comment]
> y2u.be is a third party service. It is not related to YouTube & Google inc.

**Comment by opusforlife2** [comment]
@B0pol Doesn't matter, does it? We're not even pinging that URL. Just taking the string part that matters to us, and opening a youtube.com link using that.
