### ISSUE TITLE
After Feed Update, Requires Manual Scroll Up to show Latest Videos

### ISSUE THREAD

**Issue by skyGtm** [TeamNewPipe/NewPipe#6650]
### Checklist

- [x] I am using the latest version - 0.21.6 (pre-release) 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to Reproduce:
_Bug Introduced in v0.21.6 (pre-release)_
_Note: This issue is created as per https://github.com/TeamNewPipe/NewPipe/issues/6577#issuecomment-877654793 on TobiGr's request https://github.com/TeamNewPipe/NewPipe/issues/6577#issuecomment-878303609_

1. Go to what's new section.
2. Pull down to refresh.
3. (If new videos are available) You have to manually scroll up to see the latest videos.

### Actual behavior

https://user-images.githubusercontent.com/50160188/125167877-60de0480-e1c2-11eb-88e4-115c6c0b2598.mp4

_**Ignore** the video pattern change. I don't know why that happened_

**Problem of Interest:**
_Before refresh:_
First video: 'Dear Apple'

_After refresh:_
First Video: (is still) 'Dear Apple'
Until you manually scroll up. You'll see new video above it.

### Expected behavior

After feed update, app must show latest videos at first. (without having to manually scroll)

### Device info

 - Android version/Custom ROM version: 9 Pie
 - Device model: Huawei Nova 3i

**Comment by litetex** [comment]
I also experience the same problem.

If I have time I'll try to create a PR which fixes it 😄

**Comment by litetex** [comment]
I found something odd:
Today I checked if the bug again and it was gone.

As it turns out when a video/item is removed (or at least more than getting added) from the list, everything works fine. 
However if none is getting removed scrolling to the top fails.

**Comment by foobar13373** [comment]
Can confirm. I sometimes even have to leave the feed screen after updating and re-enter it to make the new items appear.

**Comment by d-albrecht** [comment]
@infinitewaveparticle already mentioned this issue in my (duplicate) bug report (and therefore created the above link), but because we are both not sure whether my issue will be fixed at the same time, I wanted to speak up here. For whoever is ultimately working on this issue / fixing it: There are more views affected by this bug than just the "What's New" view. My bug report focused on Channel Groups (the various subsets of your complete subscription list that can be accessed in the "Subscription" tab). This view looks and feels exactly like the "What's New" view, so I assume that fixing one issue will immediately fix the other (hence, why I closed my issue as a duplicate), but in case they aren't related, the same bug has to be fixed in all similar views.
