### ISSUE TITLE
I can't download a video if I go through YouTube->share->NewPipe

### ISSUE THREAD

**Issue by Pass1Vlax** [TeamNewPipe/NewPipe#6667]
### Checklist

- [x] I am using the latest version - 0.21.6 
- [ ] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [ ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [ ] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Go to a YouTube video
2. Press on share
3. Swipe down to NewPipe
4. Select format and resolution

### Actual behavior
When I'm on a YouTube video which I want to download, I go to share, newpipe but nothing happens

### Expected behavior
 the video should start downloading after selecting the resolution and format

### Screenshots/Screen recordings
https://photos.app.goo.gl/nCYmhXXAkst7eKf47

### Device info

- Android version/Custom ROM version:MIUI12.5.1RJKMIXM Android 11
- Device model: Xiaomi Poco F2 Pro

**Comment by TiA4f8R** [comment]
> please tell me of I filled something wrong, it's my first time

The instructions in issue templates are compulsory. So you must check the check boxes and fill the steps to reproduce the bug, if you know how to reproduce this bug.

Did you set a valid download folder after the 0.21.6 update? There were changes with the storage for downloads (we are now using Storage Access Framework (SAF), check the blog post for more details).

**Comment by Pass1Vlax** [comment]
> > please tell me of I filled something wrong, it's my first time
> 
> The instructions in issue templates are compulsory. So you must check the check boxes and fill the steps to reproduce the bug, if you know how to reproduce this bug.
> 
> Did you set a valid download folder after the 0.21.6 update? There were changes with the storage for downloads (we are now using Storage Access Framework (SAF), check the blog post for more details).

I added the steps to reproduce the bug, I had filled it wrong and I set a valid download folder. I don't know how to select what you prementioned, I'd appreciate it if you could guide me a bit more 😅

**Comment by TacoTheDank** [comment]
I'm able to reproduce this issue on my Samsung Note 9 running Android 10. NewPipe version 0.21.6.

**Comment by TacoTheDank** [comment]
However, after re-setting the download directories in the download settings, it works now. @Pass1Vlax Have you tried setting them again, and then retrying?

**Comment by Pass1Vlax** [comment]
> However, after re-setting the download directories in the download settings, it works now. @Pass1Vlax Have you tried setting them again, and then retrying?

Still nothing. Maybe it's because we're on different android versions

**Comment by Pass1Vlax** [comment]
It suddenly worked but please take a look at it because some people might still have this issue

**Comment by Pass1Vlax** [comment]
It worked only for one video, it's not working again☹️

**Comment by Pass1Vlax** [comment]
Sometimes it downloads but doesn't show any notifications

**Comment by khumarahn** [comment]
Same here, setting download folders does not help.

**Comment by skyGtm** [comment]
@Pass1Vlax 
I think the SAF is enabled by default in v0.21.6, which might be causing this issue.
disable SAF from Settings > Download > Use system folder Picker(SAF) --> OFF , and see if it works.

For me its working after disabling SAF

**Comment by Pass1Vlax** [comment]
> @Pass1Vlax 
> I think the SAF is enabled by default in v0.21.6, which might be causing this issue.
> disable SAF from Settings > Download > Use system folder Picker(SAF) --> OFF , and see if it works.
> 
> For me its working after disabling SAF

I use Android 11 and it's enabled but it's not turning off.. It's dark and it's not switching![IMG_20210716_152055.jpg](https://user-images.githubusercontent.com/69008910/125946477-09941452-a920-4cc2-9eed-7ee3243ce23e.jpg)

**Comment by khumarahn** [comment]
For me, I disabled SAF and manually selected the download paths. But when I try to download a youtube video by "open in external app" from browser and selecting download, newpipe asks for download paths again and then does not download anything and does not give any error messages.
![Screenshot_NewPipe_20210716-142350](https://user-images.githubusercontent.com/5206045/125947387-c8b60964-84ec-4d09-887a-ad4f93ad1a9f.png)

**Comment by TacoTheDank** [comment]
@Stypox Would you perhaps be able to take a look at this sometime? Maybe you have some insight we don't, considering you did the SAF refactor 😊

**Comment by Stypox** [comment]
I could reproduce. @TacoTheDank this seems to be caused by this:
- `prepareSelectedDownload()` is called [here](https://github.com/TeamNewPipe/NewPipe/blob/ae39b31c683552502a815889626742d7e32f4bae/app/src/main/java/org/schabi/newpipe/download/DownloadDialog.java#L473)
- after `prepareSelectedDownload()` realises there is no directory set, [`launchDirectoryPicker()` is called](https://github.com/TeamNewPipe/NewPipe/blob/ae39b31c683552502a815889626742d7e32f4bae/app/src/main/java/org/schabi/newpipe/download/DownloadDialog.java#L715-L719), but then [there is a `return;`](https://github.com/TeamNewPipe/NewPipe/blob/ae39b31c683552502a815889626742d7e32f4bae/app/src/main/java/org/schabi/newpipe/download/DownloadDialog.java#L721)
- the controls goes back to the caller of `prepareSelectedDownload()`, which immediately [`finish()`es `RouterActivity`](https://github.com/TeamNewPipe/NewPipe/blob/ae39b31c683552502a815889626742d7e32f4bae/app/src/main/java/org/schabi/newpipe/download/DownloadDialog.java#L474-L476)
- even though `launchDirectoryPicker()` should have launched the File-picker activity and [be waiting for its result on a listener](https://github.com/TeamNewPipe/NewPipe/blob/ae39b31c683552502a815889626742d7e32f4bae/app/src/main/java/org/schabi/newpipe/download/DownloadDialog.java#L385-L393), the result never arrives since in the meantime the base activity (i.e. `RouterActivity`) was `finish()`ed

**Comment by Stypox** [comment]
@Pass1Vlax @khumarahn @skyGtm @TacoTheDank could you test #6701?

**Comment by Pass1Vlax** [comment]
> However, after re-setting the download directories in the download settings, it works now. @Pass1Vlax Have you tried setting them again, and then retrying?

Yes
