### ISSUE TITLE
[F-DROID] Why are updates on F-droid always late?

### ISSUE THREAD

**Issue by LavenderSolus** [TeamNewPipe/NewPipe#6695]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.

#### What's your question(s)?

0.21.6 was released days ago. I refreshed f-droid a lot, it's still not showing any update there, it's still at 0.21.5. The manually downloaded apk refuse to install. (Just "App not installed" message). What is happening? Am I doing something wrong?

**Comment by mhmdanas** [comment]
No, you are not. It may sometimes take up to a week for updates to appear on the main F-Droid repo. If you don't want to wait, please [use our custom F-Droid repository](https://newpipe.net/FAQ/tutorials/install-add-fdroid-repo/) (note that you will have to uninstall and re-install NewPipe due to different signatures, so please export your database first).
