### ISSUE TITLE
Porting NewPipe from Android to iOS via IPA format

### ISSUE THREAD

**Issue by Loki-L1130** [TeamNewPipe/NewPipe#6769]
We all have been discussing about Porting NewPipe to Platforms such as iOS in issue #1051. Many have been telling that NewPipe via Apple App Store is not Possible but Why can't it be done using installing IPA via Open-Source Alt-Store ?

This would be great as we are not compromising iOS via Jailbreak and using it Legitimately.

**Please do not close this as #1051 is already available**

**Comment by mhmdanas** [comment]
This has virtually no chance of happening, at least not with NewPipe the app. NewPipe uses all sorts of Android APIs everywhere. I imagine it might be possible to write a separate app that also uses NewPipeExtractor, avoiding Android APIs and running using a JVM on iOS, but Team NewPipe is almost certainly not interested in that.

**Comment by TheAssassin** [comment]
I think it needs to be stressed that Team NewPipe, knowing about the complexity, does not have the resources to work on such a project. Also, there is nobody who has the needed skills (you need to know about both iOS and Android) and has access to the hardware who is also *willing* to work on providing NewPipe on Apple devices.

It's easy to demand such a thing because it's easy to underestimate the effort and life time required for this thing to exist.

Should there ever be a third-party project that attempts "NewPipe on iOS", please don't hesitate to contact us and let us know about your existence.

Also, everyone, please refrain from opening issues other than #1051.
