### ISSUE TITLE
Replicating YoutubeKids

### ISSUE THREAD

**Issue by licaon-kter** [TeamNewPipe/NewPipe#677]
Is the (that) age restriction an accessible metadata?

FYI: https://play.google.com/store/apps/details?id=com.google.android.apps.youtube.kids

Thanks

**Comment by speednroll** [comment]
Maybe if they developed this other feature request the problem would be solved #1243

**Comment by doctormo** [comment]
I wanted to add something else too: YouTube wants users to watch as many videos as possible, one after another. Their suggested next video and auto play are all about getting people to watch more adverts. This is one reason why YouTubeKids, and certainly YouTube itself suffers from suggesting utter garbage to kids. NewPipe does not need to concern itself with any of that business model though and should not use the same patterns to show videos.

**Comment by licaon-kter** [comment]
Hey bot Y U not fix it then :) :)

**Comment by gkeegan** [comment]
This might actually be achievable, and could be a handy feature to include.

**Comment by opusforlife2** [comment]
Fixed by #2727?

**Comment by licaon-kter** [comment]
@opusforlife2 age restrict covers 18+ right?

**Comment by opusforlife2** [comment]
I cursory online search seems to suggest that this is for parents to use for their kids. No idea about the facts, which is why I posed it as a question.

**Comment by licaon-kter** [comment]
Kids means under 18?

Youtube Kids has more age options, 3,6,12, smth.

**Comment by opusforlife2** [comment]
Ah. Alright.

**Comment by wb9688** [comment]
@licaon-kter: Ah, AFAIK YouTube only marks 18+

**Comment by licaon-kter** [comment]
@wb9688 so the Kids apps pulls ratings from where?

**Comment by Stypox** [comment]
@licaon-kter it probably runs on a different API providing more detailed age-restriction data, but as wb9688 said this is not the case for standard YouTube, so this will not come to NewPipe unfortunately (feel free to reopen if more information is found ;-) )

**Comment by wb9688** [comment]
If you could provide an URL of a video that's allowed to be watched by e.g. 3yo kids, I could take a look if we're missing any such metadata

**Comment by mmaximo** [comment]
I'm interested in this topic also.
Could NewPipe get its videos from YT kids site https://www.youtubekids.com/? 
Would it be easier to implement?

**Comment by Stypox** [comment]
@mmaximo that would probably be doable, if someone is willing to implement it as a service.

**Comment by wb9688** [comment]
@mmaximo: I didn't know that was a thing, but yeah, that's possible.

**Comment by TobiGr** [comment]
This runs on a different API.
Some details:
`corpusPreference` (i.e. age groups):
-  `KIDS_CORPUS_PREFERENCE_PRESCHOOL` (0-4 years)
-  `KIDS_CORPUS_PREFERENCE_YOUNGER` (5-7)
-  `KIDS_CORPUS_PREFERENCE_OLDER` (8-12)

`enabled_categories` (i.e. allowed video categories):
- "approved_for_you",
-"camp",
-"collections",
-"explore",
-"favorites",
-"gaming",
-"learning",
-"move",
-"music",
-"reading",
-"shows",
-"spotlight"

<details><summary>Example request: younger, no search</summary> 
``` JSON
{
  "context": {
    "client": {
      "clientName": "WEB_KIDS",
      "clientVersion": "2.1.0",
      "hl": "en-GB",
      "gl": "DE",
      "experimentIds": [],
      "experimentsToken": "",
      "browserName": "Firefox",
      "deviceMake": "mozilla",
      "browserVersion": "79.0",
      "deviceModel": "firefox",
      "osName": "X11",
      "platform": "DESKTOP",
      "kidsAppInfo": {
        "contentSettings": {
          "corpusPreference": "KIDS_CORPUS_PREFERENCE_YOUNGER",
          "kidsNoSearchMode": "YT_KIDS_NO_SEARCH_MODE_ON"
        },
        "categorySettings": {
          "enabledCategories": [
            "approved_for_you",
            "camp",
            "collections",
            "explore",
            "favorites",
            "gaming",
            "learning",
            "move",
            "music",
            "reading",
            "shows",
            "spotlight"
          ]
        }
      }
    },
    "capabilities": {},
    "request": {
      "internalExperimentFlags": []
    }
  },
  "browseId": "FEkids_home"
}
```
</details>

**Comment by wb9688** [comment]
@TobiGr: Of course the requests for YouTube Kids are different. Note how in YT Music and new YT continuations, which seems similar, certain fields in the JSON are optional. This will need to be implemented in a way similar to that WIP PR for Invidious.

**Comment by eladkarako** [comment]
<blockquote> Could NewPipe get its videos from YT kids site https://www.youtubekids.com/?</blockquote>

Keep in-mind that youtubekids.com is not available for all of the countries,  
this is done by IP, regardless of user preference of language or location.

![2020-08-16_152212](https://user-images.githubusercontent.com/415238/90334173-54622380-dfd4-11ea-9e64-7c07c4919e09.png)

![2020-08-16_152521](https://user-images.githubusercontent.com/415238/90334209-be7ac880-dfd4-11ea-9671-2a40ac3cc721.png)

Unless you want NewPipe to proxy things <sup>(note: this <strong>would be awesome!</strong>)</sup>,  
enforcing safe-search (<code>f2=8000000</code> cookie based) is the common (not perfect!) way of handling things.  

Google <a href="https://chromium.googlesource.com/chromium/src/+/32352ad08ee673a4d43e8593ce988b224f6482d3/chrome/browser/net/safe_search_util_unittest.cc">used to have a unit test to check just that</a>.

Some security-applications (McAfee) used to also inspect the returned HTML for string of "restrict mode off" or something like that, YouTube is no longer write the state in the HTML (raw or DOM) and we don't actually crawl the HTML anyway.

<hr/>

There is a alternative way to force a safe search, 
as explained in here: https://support.google.com/websearch/answer/186669?hl=en  
(in the Linux section),  
you ping <code>forcesafesearch.google.com</code> and get one of the machine's IP,  
for example <code>216.239.38.120</code>,  
and then you "override" the DNS entry for <code>www.google.com</code> (and possibly other country-domains as well) in your HOSTS file:  
<pre>
216.239.38.120 www.google.com
#216.239.38.120 www.google.co.uk
#216.239.38.120 www.google.ru
#216.239.38.120 www.google.co.il
</pre>
so websites that uses <code>www.google.com</code>It would naturally resolve to the machine IP that Google search results (not sure if that includes YouTube) is always restricting the content, regardless of a user-settings.

I Don't know if this solution can be adjusted in anyway to NewPipe (in the way video search-queries are done), but it is worth mentioning since it is a solution that pipes through Google first, so you don't need to implement any client-side solutions.

**Comment by mmaximo** [comment]
> There is a alternative way to force a safe search,
> as explained in here: https://support.google.com/websearch/answer/186669?hl=en

Yes, I already do something like that. I use family-friendly dns servers from Cloudflare and [Cleanbrowsing](https://cleanbrowsing.org) on my children devices.

 But the thing is that, if you believe Google,  YT Kids' content is not only restricted, but curated. 
I haven't seen any inappropriate video popping up, something that I've witnessed even on restricted YouTube .

Thanks anyway

**Comment by eladkarako** [comment]
Of course YTK is better,  
I guess NewPipe can <a href="https://support.google.com/youtubekids/answer/6130573?co=GENIE.Platform%3DAndroid&hl=en">check if it is available</a>,  
and improve (- replace.) the results of the currently safe-search results with the one from YTK.  
And in case YTK is not available just fallback to the normal way.

This can be implemented as an additional (for example) menu entry of 'try using YouTube-Kids when available' that becomes available whenever the 'safe-search' option is turned on.
<hr/>
just fyi,  DNS is for blocking whole (sub)domains.

Overriding "google.com" is something else entirely in here:  
you are opt-in to use a specific server(s) from Google that has a slightly modified 'search service' deployed on it by Google, that totally ignores the user-settings (in user-account or cookies) and always return a safe-result-list.

Being free from cookies/settings/user-account is what made me suggest it to NewPipe,  
since it does not required any pre-authentication of any kind.

**Comment by mhmdanas** [comment]
Subsumed by #1950.

**Comment by licaon-kter** [comment]
@mhmdanas There's more info here than there, what's the thought on closing this and keeping that?

**Comment by mhmdanas** [comment]
Sure, the comments here have more info, but that issue is more specific. Besides, it's not like this issue was deleted; it was just closed.

**Comment by mhmdanas** [comment]
This issue was also referenced several times there, so this info is not hidden in any way.

**Comment by eladkarako** [comment]
Maybe a different approach that will be more easily to implement using NewPipe's current architecture,  
as it is practically impossible to provide a good kid-safe environment,  
perhaps a way to limit the user to just the content of a single playlist,  
search-results may be artificially limited to a pool of just those videos instead of the entirety of YouTube (regardless of the filter state).

<details><summary>Steps In Practice:</summary>  
a parent can the current system of NewPipe to import a playlist or create a new one him/herself with a curated list of videos (20-50 would be fine in most cases),  
That playlist can be then "marked" as the only content,  
and will be used as a background feed to the entire system of searched videos, or suggested "next-videos".  

Another enhancement is an extremely limited set of video controls instead of the regular UI,  
with possibly disabling hardware buttons as well so infants garbing hold of the device could not navigate away of the screen.  
Unlocking the limited mode is done by a click on a specific point in the screen  
similar to this:  
https://discover.hubpages.com/technology/How-to-Enable-Child-Lock-in-Android-MxPlayer
</details>

**Comment by mselmanyildirim** [comment]
Not an exact feature replication but I can share what I use for my children. It is a Newpipe [fork](https://github.com/mselmanyildirim/NewPipe-KidsMode) with some features disabled to make it safer for my kids. It may meet expectations of some of you.

Disclaimer: I'm the maintainer of the fork. Please have a look at the README to see my method and motivation. Thanks.
