### ISSUE TITLE
Does watching video through newpipe in YouTube add to view count?

### ISSUE THREAD

**Issue by Taratect** [TeamNewPipe/NewPipe#6791]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.

#### What's your question(s)?
I'm curious if YouTube videos view count rises by watching it on Newpipe. If so, do YouTubers make money off of it?

#### Additional context

There are many YouTubers who are underatted. I want to help them by increasing their reach ever so slightly. It'd be great if I could do that while preserving my privacy from Google by using newpipe.

**Comment by SameenAhnaf** [comment]
>I'm curious if YouTube videos view count rises by watching it on Newpipe.

Yes. If you watch a video for 30 seconds or more, it will be counted as a view.

>If so, do YouTubers make money off of it?

In almost all cases, no. Because, YouTube both earns itself and pays money to the creators from ads. But Newpipe blocks them.

However, you can still see sponsors while streaming videos. So, your contribution to views or just watching videos may potentially help the creators in the long run.

>I want to help them by increasing their reach ever so slightly. It'd be great if I could do that while preserving my privacy from Google by using newpipe.

I highly doubt if that's possible. There's even projects like Sponsorblock (that way, creators are left with no source of income 😱).

Maybe, a kind soul will work for your needs in near future. At this moment, it's not possible at all.

**Comment by TiA4f8R** [comment]
> I'm curious if YouTube videos view count rises by watching it on Newpipe.

@SameenAhnaf is wrong, view count is increased by third party requests and not by the requests to `googlevideo.com` servers (the view count is increased by requests made by the official clients to endpoints starting with `youtube.com/api/stats/`). But in the case you are using official YouTube clients, your view of the video only counts after watching 30 seconds of a video (if the video is longer than 30 seconds of course).

**Comment by mhmdanas** [comment]
I assume this question is answered by @TiA4f8R's comment. Closing.

**Comment by opusforlife2** [comment]
@mhmdanas @Poolitzer Worth putting in the FAQ, maybe?

**Comment by Poolitzer** [comment]
Sure, apart from them/that part of the website really needing an overhaul :P
