### ISSUE TITLE
Beta version of NewPipe

### ISSUE THREAD

**Issue by theScrabi** [TeamNewPipe/NewPipe#681]
ownCloud just released a [beta version](https://f-droid.org/packages/com.owncloud.android.beta/) of their ownCloud app on fdroid.
For them beta is just a different gradle build, as seen [here](https://github.com/owncloud/android/blob/db057f482e04cec65f30866571a9e6c7eafbd248/build.gradle#L190).

Maybe we can have something like this as well, so we can release versions with new features, but we don't have to fear if it's not a 100% stable. Also we can stick to a smaller release cycle again, which (in my opinion) will keep the community up a bit better.

**Comment by rancidfrog** [comment]
VLC also does this with their nightly and stable builds:
- org.videolan.vlc
- org.videolan.vlc.debug

**Comment by wb9688** [comment]
Doesn't F-Droid have something to mark releases as unstable?

**Comment by theScrabi** [comment]
I think it does, but id like it better if you had a separate app.
It's more obvious that you use a beta app than, and people can install both.

**Comment by theScrabi** [comment]
I just released a [pull request](https://github.com/TeamNewPipe/NewPipe/pull/685) for beta.

**Comment by wb9688** [comment]
Another thing to consider is: if we implement an experimental feature that
should only be in the beta, but not yet in release and after that, we make
a bugfix for something else (for example: YouTube's site completely changed
and it's important to fix that ASAP) that should be released, how will we
do that? With our current branching model, it simply isn't possible, so I'd
suggest adding a 'develop' branch, which is where we'll build betas from,
so that we can cherry pick stuff into 'master', which is where we'll build
releases from.

**Comment by theScrabi** [comment]
All right sounds like a good idea :)

**Comment by mauriciocolli** [comment]
We need this new branch, there's just too much change in the master so we can't release because it keeps changing.

With the new branch, I guess the workflow would be something like that?

`Pull requests > Dev branch > Beta branch > Master branch`

**Comment by theScrabi** [comment]
Ok. Now I'd say we just try to release v0.10.0 regular now, and the next version we try to setup beta.

Should we then consider version branching?

**Comment by wb9688** [comment]
@mauriciocolli: We won't need a separate dev and beta branch, since we'll just tag that branch when we want to release a new beta version. When we finally want to release a stable version, we'll merge beta back to master and tag it. When we want a hotfix for master, while not including new beta versions, we'll use yet another branch called hotfix, which we'll merge back to both branches and then tag a release.

I'd also like to make both master and develop (or whatever we'll call that branch) a [protected branch](https://help.github.com/articles/about-protected-branches/).

Besides that, I'd like to use [Semantic Versioning](http://semver.org/) for the version name of future releases. Btw can you guys [sign](https://help.github.com/articles/signing-tags-using-gpg/) future releases?

**Comment by mauriciocolli** [comment]
@wb9688 Yeah, after I write this I was thinking that was strange/unnecessary a branch just for beta (I guess it's there just for that pull request?), a "unique" dev branch makes more sense.

I also agree with the versioning name, it's pretty identifiable with other softwares (a very small detail, are we going to use `1.0.3-beta.4` or `1.0.3-beta4`?).

**Comment by wb9688** [comment]
@mauriciocolli: I guess with a dot, see item 11:
http://semver.org/#spec-item-11

**Comment by mauriciocolli** [comment]
@coffeemakr Yes I saw that, it just look a little weird (but as said, it's a very small detail, just ignore it).

**Comment by theScrabi** [comment]
Well I have an alternative design in peto, I just didn't have time to implement it yet.

**Comment by theScrabi** [comment]
I close this thread in favor of the [pull request](https://github.com/TeamNewPipe/NewPipe/pull/686).
