### ISSUE TITLE
Forcing 30 fps video

### ISSUE THREAD

**Issue by Multipanda** [TeamNewPipe/NewPipe#6835]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

I would love the option of forcing 30fps only with 1080p and 720p streams like you can with the h264ify browser extension. 

My old Samsung tab s often takes a long time to load videos and on some videos it continually needs to rebuffer.

I expect that it would improve performance a fair bit on older devices, and hopefully decrease buffering times as well as give better battery life for everyone if they use the setting.

**Comment by mhmdanas** [comment]
I believe 720p is 30 fps, but 720p60 (if present) is 60 fps. For 30 fps 1080p, see [this comment](https://github.com/TeamNewPipe/NewPipe/issues/4902#issuecomment-728993437). The situation might have changed though, so I'm keeping this open for now.

**Comment by Ammako** [comment]
At best you'll probably have to download the 1080p60 video and convert the file to 30fps before watching (in an external player.) Having NewPipe convert the 60fps video to 30fps in-place while streaming is not an option because your device would still be downloading the full 1080p60 video while you watch, with the additional overhead of video conversion happening at the same time. If your device couldn't handle 1080p60 it wouldn't be able to handle that either.

Not all videos are locked to 1080p60, it depends on the uploader. But yes, if 1080p60 is available then 1080p30 generally isn't available and that seems to still be true to this day.

Maybe NewPipe could offer to convert 1080p60 down to 1080p30 when downloading, so you could at least download what you want to watch, but video conversion might be out of scope.

Out of curiosity, is 1080p30 available in the official youtube app?

**Comment by Multipanda** [comment]
Seems a shame if that's the case. 
Was a while since I last used h264ify, and now I retest, the 30 fps option seems to not work with most videos at least with 1080p. came across a few where it offered 720p60, but not 720p, where the latter could then be forced with the extension.

**Comment by Atemu** [comment]
IIRC YT stopped offering 30fps versions of many resolutions when higher framerates exist a while ago. Don't think this would be particularly useful. Perhaps there could be an option to display all resolution+framerate combos available though.

**Comment by mhmdanas** [comment]
Since this seems to be out of our control, I'm closing this. Feel free to post a comment if you find something though.
