### ISSUE TITLE
HDR support

### ISSUE THREAD

**Issue by rugk** [TeamNewPipe/NewPipe#688]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

The official YouTube app now supports HDR for smartphone, which support HDR.

It would be nice if NewPipe can also do this.

source: https://www.golem.de/news/videos-youtube-bringt-hdr-auf-smartphones-1709-129965.html (German)

**Comment by karyogamy** [comment]
I think enabling HDR is just a one-liner, as shown [here](https://medium.com/google-exoplayer/tunneled-video-playback-in-exoplayer-84f084a8094d).

Actually, using tunneled playback is a good idea at the moment anyways, since currently NewPipe is hitting none of the drawbacks of tunneled playback (e.g. we use only SurfaceView and no need to transition seamlessly between contents).

**Comment by wb9688** [comment]
@theScrabi: This could be closed, since it's appearantly done as part of the queue PR. (Off-topic: is there a reason I don't have the rights to close an issue?)

**Comment by theScrabi** [comment]
Ok

**Comment by karyogamy** [comment]
Tunneled playback is enabled, but the extractor does not yet look at HDR contents. I've opened an [issue on the Extractor Repo](https://github.com/TeamNewPipe/NewPipeExtractor/issues/39) as a continuation of this issue.
