### ISSUE TITLE
Button for the loop

### ISSUE THREAD

**Issue by Angelk90** [TeamNewPipe/NewPipe#6914]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

![image](https://user-images.githubusercontent.com/20476002/129250470-7c330cea-2995-4a40-a74b-8b49cda0192b.png)

Button for the loop

As you can see from the image, a button is missing for loop playback of the video.

#### Is your feature request related to a problem? Please describe it

To be able to play a video in loop.

**Comment by mhmdanas** [comment]
I think such a button would not fit well in there, but somewhere in the player itself instead would be better.

**Comment by Angelk90** [comment]
@mhmdanas : 
If you take a look at this comment: https://github.com/TeamNewPipe/NewPipe/issues/1317#issuecomment-898258846, if you see in the second image, there is a bottomsheet menu I would recommend putting it there.

**Comment by CodeCubeNeo** [comment]
Any progress on this? It is a really basic feature, so I think it should be implemented.

**Comment by Stypox** [comment]
There is a button both in the notification (can be enabled in settings), in queue menu of the main player, and in the background/popup play queue activity. The only time when this button can't be accessed easily is when the player is in fullscreen and there is only one item in the queue, which causes the queue menu button to be hidden. But if you are watching fullscreen only one video, then there is a replay button in front of you if you want to replay the video, so there is no need for another button.

**Comment by TiA4f8R** [comment]
> But if you are watching fullscreen only one video, then there is a replay button in front of you if you want to replay the video, so there is no need for another button.

Indeed, but let's say you want to repeat automatically the content. Without using the player notification, you can't, you need to do this automatically. Maybe we should implement a menu like on the YouTube app to put such options.

**Comment by Stypox** [comment]
I get it, but I think it would just add one button that in most cases is redundant and for which there are alternatives. So I'd prefer not to add it.

**Comment by theridon** [comment]
It's not redundant because there isn't an alternative button when you're actually in the app. You have to drag down the notification bar to get this button which is inconvenient, unintuitive, and if you've disabled notifications, impossible. I think it would greatly benefit the userbase and app functionality to have a regular loop button in the app, say on the screen or below it.

**Comment by mhmdanas** [comment]
> I get it, but I think it would just add one button that in most cases is redundant and for which there are alternatives. So I'd prefer not to add it.

I agree with @theridon, and I am not convinced by your argument. By your logic, we could say that the pause/start button of the player is redundant, since the notification player has the exact same button, but we know that makes no sense.

**Comment by Stypox** [comment]
Maybe we could just make the queue button available even when there is only one item in the queue? From there a user could access the repeat button.

**Comment by Chipioki** [comment]
From UX perspective: I've been using newpipe for over a year now and I have always wondered why there's no loop function. I simply couldn't find it. Even after I had the idea to create a playlist, the repeat option was everything but intuitive.

Just do everyone a favor and add that button to the player, please. No one gets hurt, but many will be happy. Thank you!

**Comment by ttodua** [comment]
It's quite surprising the feature is not here.
I, my friends, family members, everyone had been asking, "how can I loop the video"?
this is so basic feature, that shouldnt necesuate to read docs and faqs to find out it. search on reddit, how many this exact questions had been open under "NewPipe" subreddit.
I think that just Author's personal subjective preference is that button was not there, otherwise all arguments and facts tell opposite. every existing player put there has that option, and how NewPipe redefined "what is better for users" , while users are actually asking in contrary. so, i think it's just developer of NewPipe who does not like that button.

**Comment by amark** [comment]
I still don't know how to loop, I am a developer, have read this thread.

Android notification pull down does not give me a loop option, only play and left/right.

Playlist shows I can loop(?) 1 time which isn't looping.

How do I loop? Can we please add?

**Comment by ttodua** [comment]
@Stypox is there any hope you revisit this and hear users voice to add an option/setting, so we can (by default, ok, be it hidden if you wish so) enable that button and then have setting for loop right aside other buttons on the video?

**Comment by ttodua** [comment]
> Open the queue using the queue button in the player controls. The loop button is there, along with the shuffle button.

i don't think anyone needs queue shuffling. (because if anyone enters queue they already see it's there). we speak about repeat button on the video itself. who on earth tries to add the current video to queue, then then manually cleaning up old videos from queue to **just loop one specific video**. joke.

**Comment by ttodua** [comment]
> @ttodua Did you try the method I gave you?

thanks for suggestion, i see it do work, but entering queue and setting the loop there is not a straightforward way in my opinion. it would have been a reasonable to allow users to customize themselves, if they want repeat button directly in video controls, so if there was optionality, it might have solved the problem. 
i think for users it's not straightfowrad to guess where the loop could be (unless they ask one by one and read  your comment)

**Comment by merlin555** [comment]
I also really need the loop mode.
