### ISSUE TITLE
Android TV Unrecoverable Playback Error

### ISSUE THREAD

**Issue by zubayy** [TeamNewPipe/NewPipe#6977]
### Checklist

- [x] I am using the latest version - 0.21.9 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Open any video on sideloaded Newpipe app on android tv
2. Try to use the "back button" (return button) on a TV remote
3. Crashes with "unrecoverable playback error"

### Actual behavior

It crashes with "unrecoverable playback error"

### Expected behavior

It shouldn't crash as it didn't crash in 0.21.8

### Device info

 - Android version/Custom ROM version: Android Pie
 - Device model: (Sony bravia) it also crashes on several other android tvs such as Sony, Samsung and LG

**Comment by Ammako** [comment]
For what it's worth, behaviour changed here with 0.21.9, on regular android. Pressing the Back button when watching a video or when the video has finished playing, instead of exiting out of it and going back to the previous page, it just reloads the current video but in a "non-started" state where it just shows the thumbnail with a Play icon over it, and I have to press Back a second time to actually go back.

It's possible this is related, because unrecoverable player errors can tend to happen under certain conditions, when opening a video, and pressing the Back button here essentially has the same effect as if you were freshly opening the video.

**Comment by zubayy** [comment]
@litetex does what @Ammako suggested help narrow down the issue? Pretty sure it's just related to TV remote buttons but it might be related to changes made to the back button that affect all devices, thanks for fixing dpad btw.
