### ISSUE TITLE
Marking videos as watched doesn’t work and causes the app to freeze

### ISSUE THREAD

**Issue by janTaja** [TeamNewPipe/NewPipe#6987]
### Checklist

- [x] I am using the latest version - 0.21.9 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Open a channel group
2. Long press any video in the feed
3. Press “Mark as watched”
4. Try to go back (using the button in the app or the device back button)

### Actual behavior

At Step 3 visually nothing happens, at Step 4 the app freezes and doesn’t react to any actions anymore. (If you close and reopen it, it goes back to normal)

### Expected behavior

The video being marked as watched and the app not freezing and instead going back to the subscriptions page

### Screenshots/Screen recordings

I can’t record a video right now, but I can add it in a few days if needed

### Device info

 - Android version/Custom ROM version: Android 8.0.0
 - Device model: Samsung Galaxy A3 (2017) / SM-A320F

**Comment by nschulzke** [comment]
I never found this with "Mark as Watched" on the feed views, but I ran into it when trying to extend Mark as Watched to other pages. I made a fix in PR #7160 that replaces a call to `getState(streamId).blockingFirst()` with a simpler `upsert()`, which fixed it for the other views. I can't be sure it'll fix your case (since I'm not seeing what you're seeing), but it's likely that it will.

**Comment by opusforlife2** [comment]
@janTaja Is your issue fixed?

**Comment by janTaja** [comment]
I think so, I haven't encountered it in a very long time.
