### ISSUE TITLE
Remove the "Fill" resize mode

### ISSUE THREAD

**Issue by rcmz** [TeamNewPipe/NewPipe#7023]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

The "Fill" resize mode stretches the video, which make it pretty unusable in my opinion.
Plus removing it would transform the resize mode button into a simple two way toggle between "Fit" and "Zoom" which would be more intuitive.
It would also be a first step to have a scale gesture as started in this PR https://github.com/TeamNewPipe/NewPipe/pull/1770

I guess the question is: are they some people that actually use the fill resize mode ?

**Comment by SameenAhnaf** [comment]
>are they some people that actually use the fill resize mode ?

I use it regularly for almost all videos.

>The "Fill" resize mode stretches the video, which make it pretty unusable in my opinion.

I often require most information out of the video for acquiring all information instead of the best view. Using 'Fit' creates huge black bars (Thanks to large aspect ratio of my phone) and 'Zoom' crops too much information.

>It would also be a first step to have a scale gesture as started in this PR #1770

We may consider https://github.com/TeamNewPipe/NewPipe/issues/3181#issuecomment-892359143 instead.

**Comment by rcmz** [comment]
I guess this answered my question ^^
