### ISSUE TITLE
Playlist shown as a video only instead of a list

### ISSUE THREAD

**Issue by tarun0** [TeamNewPipe/NewPipe#7057]
### Checklist

- [x] I am using the latest version - 0.21.9 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

Open  https://youtube.com/playlist?list=PL2jzazaAMNtV6kJpY6y_xp7A04zMGyzOK  with Newpipe 

### Actual behavior

Th UI should have shown the list of videos in the playlist.

### Expected behavior

It starts playing the first video and shows playlist within the player. So, there is no way to bookmark it.

### Logs

Opening the same url with version 0.21.8 is showing playlist videos just fine.

### Device info

 - Android version/Custom ROM version: EMUI Oreo 8.0.0 API 26 
 - Device model: Huawei Mediapad M5 lite (10 inch tablet)

**Comment by SameenAhnaf** [comment]
Did you check your "Preferred 'Open' Action" setting? Go to 'Settings'>Go to 'Video and Audio'>Scroll down to "Preferred 'Open' Action">Select "Show Info".

**Comment by litetex** [comment]
Like @SameenAhnaf said:

Setting "Preferred 'Open' Action" to 
* Show info -> shows the playlist
* Video player -> plays the first video

Works as expected for me.

However having no share option etc because we can't get back to the playlist looks like a valid problem for me.
Feel free to create a new issue or link an existing one for this one.

Closing this for now
