### ISSUE TITLE
For Features Request... 

### ISSUE THREAD

**Issue by max5354** [TeamNewPipe/NewPipe#7118]
### Checklist

- [ ] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [ ] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### How will you/everyone benefit from this feature?

Plz Add This Feature in Newpipe..... 🙏
1) Add Option To Play Video In Always Mp3... So we can use newpipe as a music streamer....... I know there is a option to play background but still if you add always play mp3 instead of video  feature then it is great for user.... 
2) and if possible then add audio quality feature ...that contain 128kbps, 256kbps, 320kbps... So we listen our YouTube playlist song in high quality.......
3) and plz add your own 10 band equalizer....... With preset like Bass, Treble, extreme Bass, Dance, classical etc....... 
4) and if possible then create your Telegram group or channel so we can discuss about our issues and features request instantly..... And in channel you can upload beta version...... For testing instantly.............. 
5) and youtube playlist extension is changed.......i can't able to import my YouTube playlist...... So plz fix this..... So we can import our YouTube playlist... 
🙏Plz plz plz add this feature this features is very helpful for users...... 🙏

**Comment by tsiflimagas** [comment]
Number 5 is fixed and will be there in v0.2.10. For the rest of your requests, they're pretty much not going to happen, or are already suggested in a better way. Also, get your writing together. Writing "plz" a thousand times and appending ten dots to every line makes it, let's say, uncomfortable to read. Many young users of telegram use to write this way in Android ROM groups, and they end up getting warned/banned. Probably a reason why no. 4 hasn't been made till now.

**Comment by mhmdanas** [comment]
This issue is not going to be kept open because you have not followed the template properly. However, I'll reply on your requests anyway.

1. I'm not sure I get what you're saying, but NewPipe doesn't fetch any video stream when playing in the background player, only the audio stream.
2. See #1059.
3. Almost certainly not happening; please use another app for such things.
4. Telegram has been discussed before, but it was decided to settle on IRC. It's still possible to use Telegram if it has an IRC bridge, in case you insist. See #2965 for the discussion.
5. As @tsiflimagas pointed out, this should be fixed in the next version. You can try out the release candidate APK from #7066.

I appreciate that you went to the effort of opening this issue, but if you would follow the template properly (by checking for duplicates, requesting only one feature per issue, etc.) and tone down your writing style a bit as @tsiflimagas suggests, I think that would make it easier for all of us.
