### ISSUE TITLE
Long pause can't resume

### ISSUE THREAD

**Issue by Thejus-M** [TeamNewPipe/NewPipe#7136]
### Checklist

- [x] I am using the latest version - 0.21.10 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Actual behavior

The pause, next and previous don't work and need to close the player.But sometime i won't even be able to watch the video

### Expected behavior

I expect it to behave like the previouly

### Screenshots/Screen recordings

Sorry

### Device info

 - Android version/Custom ROM version: LineageOS 18.1
 - Device model: Redmi Note 7 Pro

**Comment by Rikests** [comment]
Could this be the same bug described in #7086? 
Can you describe what were you doing before your play pause button stopped working and how to reproduce this issue?

**Comment by Thejus-M** [comment]
Well ,think this is a little different.I never closed the app, played in app or use external display.
Well have no idea about how to reproduce the bug,sorry,😅.
Early the bug was rare,the it became frequent so ,wrote the bug report,but now it has again decreased,i am not sure is it is when played from the playlist that it comes more.
And another some harmless bug is that when a video is played and pause the video and close the phone the video plays
which works everytime.

**Comment by litetex** [comment]
Thank you for the issue!

We have to narrow the problem down as this information is not enough to do anything.

Could you install a debug version of the app, e.g.: https://github.com/TeamNewPipe/NewPipe/suites/3892035779/artifacts/96999393 (currently the latest [develop-version](https://github.com/TeamNewPipe/NewPipe/commit/b753705a84701c9fe6de860d0bdcd534b41de1f8)) and try to (somehow) reproduce the problem.

When the problem occurs try to collect logs using a tool like logcat 😄

**Comment by andrei-belkin** [comment]
### Checklist
- [x] I am using the latest version - 0.21.10
- This is the exact same bug as the one reported in this issue, just with more details.
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Open a video
2. Play the video in any mode (main, pop-up, audio)
3. Wait for 10 minutes to pass on the clock (the playback time doesn't matter)
4. Pause the playback
5. Controls are now stuck

### Actual behavior
Once the video is paused after 10 minutes, player controls are stuck. You can't unpause or seek neither by double-tapping, using the seekbar or the seek buttons. Toggling fullscreen doesn't help. Seeking with the seekbar changes the seekbar progress and the video progress time, but doesn't help the problem.

To trigger the issue, two conditions must be met: 10 minutes must have passed since you first pressed Play and the video must be paused.
You can pause it after two seconds of playback, wait 10 minutes and the issue will occur. You can let the video play for half an hour, pause it and the issue will occur.

Workarounds:
- Changing playback format (to pop-up, main or audio)
- Opening the same video from the video list (search list, playlist, subscriptions feed, etc)
- Opening a different video

All of these workarounds reset the video playback progress to 0 and unstuck it.

### Expected behavior
Nothing should get stuck. You should be able to pause, unpause and seek normally.

### Screenshots/Screen recordings
https://imgur.com/a/gNmh7za

### Logs
N/A

### Device info
 - Android version/Custom ROM version: GrapheneOS latest build as of Oct 1st 2021 (RQ3A.210905.001.2021092220)
 - Device model: Google Pixel 4a

**Comment by litetex** [comment]
@andrei-belkin
What is this comment for?
Has this anything in common with this issue?

**Comment by andrei-belkin** [comment]
@litetex If you would be so kind as to actually read my comment, you'd see that it's the exact same issue. I just thought I'd add more details, information and a screen recording to it.
I didn't want to make a separate issue to avoid making a duplicate.

**Comment by litetex** [comment]
@andrei-belkin 

> Long pause can't resume
> The pause, next and previous don't work and need to close the player.But sometime i won't even be able to watch the video

I don't know if this matches exactly with you comment as the issue description is very vague. That's why I'm asking 😄 
Anyway I think - after watching your video - they kind of look like the same. So thanks for the comment I guess 👍 

PS: Could you catch any logs as described in https://github.com/TeamNewPipe/NewPipe/issues/7136#issuecomment-929578262 when this happens?

**Comment by andrei-belkin** [comment]
@litetex, could you provide a link to the latest debug version of the app, please?

**Comment by litetex** [comment]
Why was the issue reopened?

**Comment by opusforlife2** [comment]
Hmmm. Strange that the bot only waited for a week before closing this again, @mhmdanas.

Anyway, @andrei-belkin whenever you post your results, we'll reopen this.

**Comment by mhmdanas** [comment]
> Hmmm. Strange that the bot only waited for a week before closing this again, @mhmdanas.

The label was added 2 weeks ago though?

**Comment by opusforlife2** [comment]
Oh. I was looking at the date of my comment and assumed things. Sowwie.

**Comment by Foxite** [comment]
If it helps, I have the same issue, but I don't know how to reproduce it consistently (which became apparent when I tried to reproduce it while watching logcat). I don't really have another device to test it on, but here's some info about my device that may be worth mentioning:
- Android 11
- LineageOS for microG 18.1 (a very outdated build actually, I will update shortly and update this comment if it still happens)
- Not rooted
