### ISSUE TITLE
Reorder while refreshing

### ISSUE THREAD

**Issue by jithinjames916** [TeamNewPipe/NewPipe#7151]
When we try to reload after watching all the video, the new vedios should be loaded on the top... But now watched vedios & new videos get mixed up.. difficult to spot some videos...

If an ability to add external downloader option, it could be great too

**Comment by SameenAhnaf** [comment]
Expected to be fixed by #7050. Also, please fill in the template properly and only one suggestion at a time. 

>If an ability to add external downloader option, it could be great too

I didn't get it. #533 asks for automatically downloading new videos.

**Comment by litetex** [comment]
I'm going to close this issue as there is no template, multiple feature requests/bug reports inside of it and many/all statements are duplicated.

> But now watched videos & new videos get mixed up..

That shouldn't happen as new videos are ordered by there upload time.
If this is not a special case issue (like your phones clock not working correctly because you remove the battery) please open a new bug report with a proper template and proper information/examples.
