### ISSUE TITLE
[Request] Add Android TV compatibility

### ISSUE THREAD

**Issue by oroboros** [TeamNewPipe/NewPipe#717]
It would be nice to be able to use this instead of the official Youtube app on Android TV. This would entail some tweaking, like adding a leanback launcher icon and DPAD input support, etc.

**Comment by wb9688** [comment]
I don't have an Android TV device myself. Android's emulator doesn't work
good at my machine either. So I can't do that, maybe someone else of the
team can. You could also try adding it yourself and submit a PR.

**Comment by o-l-a-v** [comment]
NewPipe seems to work on nVidia Shield TV. Haven't done to much testing yet though.

In order to have a shortcut in the Android TV Launcher, "Leanback", we'll need a banner / icon with dimensions 320x180px. I've made some mockups for an Android TV icon, you can use it if you want to. PDN (Paint.NET) and PSD included in the attachment.
For now, I'm using "Android TV App Launcher Builder" - http://atvlauncher.trekgonewild.de/index.php, in order to have a shortcut to newpipe on my Android TV device. It creates an APK functioning as a shortcut to org.schabi.newpipe.
[NewPipe_Leanback.zip](https://github.com/TeamNewPipe/NewPipe/files/1649275/NewPipe_Leanback.zip)

**Comment by raccoonquest** [comment]
This would be very nice. 
As far as I can tell, the app (0.13.7) works perfectly as is, including navigation using the remote on my Nvidia Shield TV (AND IS SUPERIOR to the official YouTube Android TV app). 

I don't really want a fancy Android TV version. The app is great as it is. The only problem is the lack of the Leanback Launcher shortcut icon (using this is a non-starter for the non-technical people in my family), although I will look into the "Android TV App Launcher Builder" @o-l-a-v mentioned above.

**Comment by oroboros** [comment]
The leanback launcher is a simple hack that can be done on the user end - so it makes sense just to add it into New Pipe (literally a couple lines of code and an icon). It would still need DPAD input support, for pure Android TV (like Mibox).

**Comment by h-2** [comment]
Is there still work happening here? I would really like to use this instead of the Google App.

What works for me:

  - [x] the app itself is installable via F-Droid
  - [x] the app works, including video, audio, 4k-webm (software decoding I guess?)
  - [x] navigation with remote works, although not comfortable

Important stuff that's missing:

  - [ ] Being listed as an App. This is the biggest problem. As of AndroidTV Oreo there is no easy access to the general app list at all anymore. I can only start the App by opening the Amaze file manager, going to App Manager, scrolling through the gigantic list of Apps and selecting NewPipe. This is a real deal-breaker.
  - [ ] the remote's keyboard is not supported, instead an on-screen keyboard pops up

I'd be willing to pay someone 50€ to implement the above two things, either via IBAN/SEPA or Paypal or Paydirekt or whatever platform they like.

Minor/UI stuff:
  - [ ] the interface could be made more tv-like simply by having the burger menu always be expanded. This is what other Free Software apps like the Amaze file manager do, for example.
  - [ ] some UI elements are not reachable with the remote alone
  - [ ] some of the remote's buttons could be used to ease navigation, e.g. pressing play/pause works when playing a video, but play could be used to start playing a video, too, when on its page
  - [ ] when playing a video, the UI overlay is in portrait mode, instead of landscape; even stuff like volume control by the system is turned 90°
  - [ ] the video thumbnails are poor quality which is very visible on 4k@65"
  - [ ] Android Channels support. This is not crucial, but would be nice to have as all of the media apps now have it.

**Comment by sorryusernameisalreadytaken** [comment]
I would love to see AndroidTV support for this awesome app too.

It is so hard to get rid of all thoose google application. This app could be a wonderfull solution.

**Comment by Stypox** [comment]
Closing this in favour of #1363. It's better to keep all things in one place.
