### ISSUE TITLE
 IP Address disclosure 

### ISSUE THREAD

**Issue by reyis4402** [TeamNewPipe/NewPipe#7352]
Pithus

``Mod: Removed description about "Pithus" that is not relevant for this issue``

Analysis report for Newpipe shows weak encryptions and IP address disclosure

https://beta.pithus.org/report/ddc951e38698286900f136d945abc6af4710b4fd7c2e3be8acab91f5df9fa261

**Comment by mhmdanas** [comment]
> weak encryptions

Have little knowledge about that, so won't comment.

> IP address disclosure

Nothing we can do about that; use a VPN/Tor to avoid that.

Also, please follow the template when opening an issue.

**Comment by litetex** [comment]
Sorry but I think this site is mostly useless and gets into the direction scare-ware.

> weak encryptions

![grafik](https://user-images.githubusercontent.com/40789489/140103393-574c3783-881f-45a7-9d2e-c83dfb047fae.png)
This is done to check if the app is a release APK or not. And then run the update check (or not).
Not a security problem.

![grafik](https://user-images.githubusercontent.com/40789489/140103441-a19fdfd8-1208-4f43-a43c-fde81ff4e15a.png)
Not our part, report it by Mozilla.


> IP address disclosure

Yes, this happens when you communicate with something over the internet if you don't use a VPN.

![grafik](https://user-images.githubusercontent.com/40789489/140104002-fd06baf4-51d3-4b92-93bb-4384a8281c48.png)
Not our part, report it by Mozilla.


Also (may include sarcasm):
![grafik](https://user-images.githubusercontent.com/40789489/140103764-60bb90bb-31ac-4536-b1d0-868611974d08.png)
Okay so I assume Kotlin is insecure 😆

![grafik](https://user-images.githubusercontent.com/40789489/140104356-3509d141-e88a-4e7d-92bf-ee2a2b1bf927.png)
Uhm yeah... If you want to save videos to your SD card the app needs write permissions.
Also why is a CVSS 5.5 score classified as "high"?
![grafik](https://user-images.githubusercontent.com/40789489/140105047-1b663d4e-d51a-4e89-a377-b872023312e4.png)
