### ISSUE TITLE
Links don't open in NewPipe

### ISSUE THREAD

**Issue by sasukeiscool** [TeamNewPipe/NewPipe#7436]
YouTube links in the form of http://youtube.com and http://www.youtube.com
automatically opens in browser and not in NewPipe (not due to system settings)

**Comment by SameenAhnaf** [comment]
I think, you should keep the discussion in https://github.com/TeamNewPipe/NewPipe/issues/2256 as your mentioned site redirects to recommendations' tab.

**Comment by litetex** [comment]
> YouTube links in the form of http://youtube.com and http://www.youtube.com

Did you maybe configure the default link action to open up inside the browser?

**Comment by opusforlife2** [comment]
@sasukeiscool Please fill out the template.

**Comment by doodhout** [comment]
This ticket is closed, but the issue remains when using Android 12.

And worse, even when adding the necessary links in the Open By Default section of NewPipe android app properties, those links still only open in my browser without ever asking me whether or not I want to open them in NewPipe.

I don't know if this is at all fixable from within NewPipe, but nevertheless I want to find out because it's an annoying problem.
