### ISSUE TITLE
please fix this (list view mode: grid)

### ISSUE THREAD

**Issue by Gamefire238** [TeamNewPipe/NewPipe#7551]
I like the grid view, but somehow it still looks like this, I don't know if it's a bug or it's not finished yet? Please understand...
![Screenshot_20211219_183936](https://user-images.githubusercontent.com/78879425/146672242-7f8f8666-1d33-4ab4-9fea-0298462b4952.jpg)
 
vivo y12
android 11

**Comment by litetex** [comment]
I think this works as expected.
The problem likely cause by your device's screen. It's to small (or maybe due to the low dpi) to show tile side by side in grid mode.
On a Pixel3a it works fine:
![grafik](https://user-images.githubusercontent.com/40789489/146837416-9f301f40-dad4-4262-9e7a-3ed2c449c062.png)

Btw: As far as I know grid view mode was originally invented for tablets...

**Comment by SameenAhnaf** [comment]
@litetex Changing `Display Size` from `Device Settings` makes such an incident to happen. Also, this bug is inevitable on screen under 5"  in all cases.

If https://github.com/TeamNewPipe/NewPipe/issues/6087 is a logical reason to abandon increasing thumbnail in list view, that is even more logical in case of grid view 😆
