### ISSUE TITLE
Poweramp Equalizer not working with recently version ! 

### ISSUE THREAD

**Issue by joliegrace** [TeamNewPipe/NewPipe#7580]

**Comment by TiA4f8R** [comment]
Please fill in the issue bug report template. We are not able to help us with so little information.

**Comment by szc126** [comment]
For me, LineageOS (Android 5.1.1) AudioFX did not work with 0.21.15 and I had to revert to 0.21.13.

**Comment by joliegrace** [comment]
> Please fill in the issue bug report template. We are not able to help us with so little information.

**Comment by joliegrace** [comment]
@TiA4f8R before I using Newpipe for listening music only, I using with Poweramp Eq but from 0.21.15 Poweramp Eq not working anymore :( current I still using old version 21.13.

**Comment by joliegrace** [comment]
@szc126 same issue with me. System AudioFx and external Eq bold not working from 21.15

**Comment by opusforlife2** [comment]
@joliegrace Please fill out the template you deleted. It's not optional.

**Comment by kaixxx** [comment]
Since I have the same problem I'll fill out the form for the lazy original poster. I would really like to see this issue beeing addressed! It makes listening to music with NewPipe a very poor experience at the moment. 







### Checklist


- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1) Play music (or anything) in NewPipe
2) Go to the system sound settings of your phone. Try any of the effects (surround sound, equalizer...). 

### Actual behavior
The effects are not working, sound quality is poor :(

### Expected behavior
nice fat grooves :)

### Device info

 - Android version/Custom ROM version: 8.0.0 Stock Rom
 - Device model: Sony Xperia X Compact

**Comment by opusforlife2** [comment]
@kaixxx It's better to open a new issue with your info. I'll close this one. (P.S.: you haven't typed in your version)
