### ISSUE TITLE
Include channel groups in subscription export

### ISSUE THREAD

**Issue by pc00per** [TeamNewPipe/NewPipe#7625]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### What feature do you want?

Include channel groups in subscription export backup file.

#### Why do you want this feature?

Current subscription export file does not export channel groups. Always had to recreate older groups manually again.

**Comment by mhmdanas** [comment]
Is there a reason you don't export all of your data (Settings > Content > Export database)? That includes the subscription groups too.

**Comment by pc00per** [comment]
> Is there a reason you don't export all of your data (Settings > Content > Export database)? That includes the subscription groups too.

Yes, I do know exporting whole database gonna include. I'm just curious if the subscription export would include channel groups too.
Btw, not needed this now. Closing the issue. Thank you vm.

**Comment by CelularBat** [comment]
I would like to open this Feature Request.

**Why ?**

- Because you sometimes want to import your subscribers without importing other settings ( I guess for this case this option exists, however without ability to import groups this option is incomplete) 
- Because of compatibility with any other apps with subscribers groups:
I've just imported list of subscribers from FreeTube, about 70 channels grouped into 15 groups - and now I need to recreate groups manually.

**Comment by opusforlife2** [comment]
You can check for duplicates and open a new issue.
