### ISSUE TITLE
Play/Pause buttons are not centered in fullscreen mode / Arc size of double tap gestures is not the same

### ISSUE THREAD

**Issue by SameenAhnaf** [TeamNewPipe/NewPipe#7731]
### Checklist
- [x] I am using the latest version - dev branch after #4833 merged 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

View a video (with a cosshair) in fullscreen mode.
Or use the double tap gesture.

### Actual behavior

Note that the play/pause button are not centered.
There's a striking difference in arc size. Double tap to rewind tends to smudge with `Pause` icon.

### Expected behavior

The play/pause button are not centered.
Size of the arcs should be the same. Don't smudge the arc with `Pause` icon to keep the UI a little more clean.

### Screenshots/Screen recordings

| Rewind Gesture | Fast Forward Gesture |
| --- | --- |
| <img src="https://user-images.githubusercontent.com/79245641/151863574-e3519933-c293-4c03-9e77-085d1f1fe3f6.jpg" /> | <img src="https://user-images.githubusercontent.com/79245641/151863775-f1c561e5-6c2f-43f6-a1eb-518e16367749.jpg" /> |

Further examples with a crosshair from a minecraft video:
| Demo1 | Demo2 |
| --- | --- |
| ![grafik](https://user-images.githubusercontent.com/40789489/153716352-5fa8aadf-97b8-40e2-a4c6-60cc6e00d6d6.png) | ![grafik](https://user-images.githubusercontent.com/40789489/153716380-9517bf29-b5cb-420c-bc0b-50d4299b74e0.png) |

Portrait mode works as expected:
![grafik](https://user-images.githubusercontent.com/40789489/153716335-6e52cac6-4f9e-4b36-9d63-470d3e7ae04b.png)

**Comment by litetex** [comment]
The arc size is perfect.
The buttons are off-centered (because of the system menu/buttons) inside the full screen mode and that is the problem.

<details><summary>I noticed that while I watched video which have a crosshair, e.g. </summary>

![grafik](https://user-images.githubusercontent.com/40789489/152872194-5d1bd870-19e1-4a19-a8b7-ca051d108d90.png)
![grafik](https://user-images.githubusercontent.com/40789489/152872312-6e9b4ae3-5fbd-487a-9d37-037e17d9bd29.png)
![grafik](https://user-images.githubusercontent.com/40789489/152872501-81797a53-adca-4c2f-a91e-836f54e4a9c8.png)

</details>

**Comment by opusforlife2** [comment]
@litetex Then could you update the title and description, please?

**Comment by litetex** [comment]
Done

**Comment by TobiGr** [comment]
Fixed by #7893
