### ISSUE TITLE
Automatic download video/audio option (Forgotten #4195) 

### ISSUE THREAD

**Issue by xMxster** [TeamNewPipe/NewPipe#7769]
### Checklist

*This feature was already requested, but seems forgotten*
- [ ] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### What feature do you want?

Detect when a video has been watched multiple times and download it (or the audio, depending to a opt-in config) 

Optional settings to opt in, configured how many times in a certain time span has it been watched... And a list containing what was been recently download using this feature

#### Why do you want this feature?

- We could consume less phone data, therefore save money

- Less network bloating

- Small but meaningful way to save energy

**Comment by mhmdanas** [comment]
It's not that the issue is "forgotten," just that nobody has made a PR yet. The only thing this actually indicates is a lack of interest from a programmer able to work on the feature. Thus, there isn't really a point to opening duplicate issues. Just react with a thumbs-up to that issue please, and avoid opening duplicate issues again. If you want to add some points to #4195, feel free to make a comment. Thank you.

**Comment by xMxster** [comment]
Oh okay. Thanks for that.

Sadly I don't quite understand Java nor kotlin.

When I start to study it, I'll do it!

Thanks for reading
