### ISSUE TITLE
Notify new NewPipe versions (and impacting bugs) in the app

### ISSUE THREAD

**Issue by m0nkeyc0de** [TeamNewPipe/NewPipe#7814]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### What feature do you want?
It would be great to have a kind of popup in NewPipe telling a new version is released and which bugs are fixed. 
You could check once a day the latest release number on github and compare it to current running version. Signaling impacting bugs through this channel could also be a great idea. 

I'm not familiar at all with Android development but if this is accepted I can give a try (it shouldn't be that hard). 
#### Why do you want this feature?
It could reduce the number of useless issues that (lazy) people like me open for nothing. Everybody wins:
- developers may have less toil in github, which means more time to develop cool features
- users may know there is a bug which is (going to be) fixed and can relax because their favorite app will work again

**Comment by m0nkeyc0de** [comment]
#7812 gave me this idea...

**Comment by mhmdanas** [comment]
> It would be great to have a kind of popup in NewPipe telling a new version is released

I think this part is already done, at least in the GitHub version.

**Comment by Isssuemaker** [comment]
+1

**Comment by litetex** [comment]
> It would be great to have a kind of popup in NewPipe telling a new version is released

This was already implemented (only active in release APKs).
https://github.com/TeamNewPipe/NewPipe/blob/377914f1d858e95f5d721c30362b4dd4d82b0a93/app/src/main/java/org/schabi/newpipe/CheckForNewAppVersion.java

Update checks are executed when the app is started and an update check was not done since ~6h (depends on the ["expires"-Header](https://github.com/TeamNewPipe/NewPipe/blob/377914f1d858e95f5d721c30362b4dd4d82b0a93/app/src/main/java/org/schabi/newpipe/CheckForNewAppVersion.java#L195)).
