### ISSUE TITLE
Playlist Restarts From Beginning And Stops Playback When Newpipe Encounters A Deleted/Removed Video

### ISSUE THREAD

**Issue by WorriedAboutClams** [TeamNewPipe/NewPipe#7851]
### Checklist

- [x] I am using the latest version - 0.21.16 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Start playing a playlist in Background, Play All, or Popup (Play All and Popup have slightly different behavior listed below)
2. Skip to a video immediately BEFORE a deleted or removed (aka unplayable) video
3. Skip to the next video (tap "next track")

### Actual behavior

If playing in the background, "Current video" in playlist goes back to first video in playlist and playback stops. Manually pressing play causes Newpipe to start playing the first video in the playlist.

If playing through "Play All" or the popup, playback stops on the deleted video. Manually pressing play again skips to the next video in the playlist and starts playback.

### Expected behavior

This is a new issue, previous versions of Newpipe would simply skip deleted/removed/unplayable videos and continue playback on the next available video. This is how it should work.

If you're using Newpipe to play music, listen to an audio book, or anything else where progress through a playlist and uninterrupted play are important (gonna go out on a limb and guess this is 99% of the point of playlists in any app, period), this is an extremely annoying issue. It is not feasible to go through, for example, a music playlist with 500 videos every single time you want to listen, checking for deleted videos. Simply reverting Newpipe's behavior to what it was in previous versions would fix the issue - if Newpipe encounters a deleted or otherwise unplayable video, skip it and play the next one, rather than shutting everything down and jumping back to the beginning of the playlist.

### Device info

 - Android version/Custom ROM version: Android 11
 - Device model: Motorola Moto G Stylus 5G

**Comment by degarb** [comment]
I agree. However, I noticed in the latest that videos are restarting when I hit recent apps button (it has always seemlessly toggled into popup player) , when I turn off and on my screen (which it used to seemlessly toggle to background audio playing, and back to the video player when I unlock the screen).

This new behavior has greatly crippled my ability to watch video because nearly anything that I do on the phone causes me to loose my place In my playlist and in the 3 minute to 3 hour video that I am watching and listening to.

I have even seen it rewind to previously watched videos, after the latest release.

I sure hope that they fix this newly broken behavior of not seemlessly and automatically transitioning between the video player, the pop up and the background.

Yes, and hiccups in the data stream also seems now to rewind and loose the place in the video, or even, the playlist.

I notice this more because I use NewPipe for lectures and learning before falling to sleep. At the tipping point of half consciousness, I turn off the screen to listen to the lectures until I fall asleep. I do not the alertness to go into NewPipe and take it out of full screen and find the background button.  I also might start watching a playlist and need to immediately switch to another app, but I still want to be able to listen to or watch the popup - - and it is a hassle to manually minimize and hunt down the pop up button, especially when need to frequently repeat this toggle.

**Comment by WorriedAboutClams** [comment]
Update for NewPipe 0.22.0: the old (correct) behavior seems to be restored. When a playlist encounters a deleted or unavailable video, NewPipe gives an error notification and continues playback on the next available video. Closing since the issue has been fixed as of 0.22.0.
