### ISSUE TITLE
Parcel too large in Notification

### ISSUE THREAD

**Issue by coffeemakr** [TeamNewPipe/NewPipe#799]
Serious issue that keeps occurring.

Steps to reproduce unknown.

Exception example: `java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 570604 bytes` thrown in notificationManager.notify (BackgroundPlayer.updateNotification)

https://sentry.schabi.org/sentry/newpipe/issues/49/

Some user comments:
- Had to fast forward a bunch of times
- listening to music in the background and browsing in chrome. nothing extraordinary
- this issue occurs oftenly since I updated to nougat 7.1... (phone is ZTE Axon 7 with MiFavor overlay), even when the app is freshly restarted

**Comment by theScrabi** [comment]
Uch nasty one :/

**Comment by karyogamy** [comment]
This should be fixed in #680. Indeed, it is a nasty bug. This is because we are not recreating the notification when updating them, which introduces leaks when we update to frequently (especially with a large bitmap). Most other music apps don't update notifications like us, where the time progress is being updated every second. This problem only occurs when you have left the screen on for a long time though AND the notification has been updated a bunch of times. If you leave the screen on for long enough with music playing and look at logcat, you will see the system is trying to gc but to no avail, and eventually crash with parcel to large. 

This is solved by simply recreating the notification builder every time it is being updated, see [BackgroundPlayer](https://github.com/karyogamy/NewPipe/blob/playlist/app/src/main/java/org/schabi/newpipe/player/BackgroundPlayer.java).

**Comment by coffeemakr** [comment]
> This  is because we are not recreating the notification when updating them, which introduces leaks when we update to frequently (especially with a large bitmap).

That's what I thought. 

>  is solved by simply recreating the notification builder

Alright. So commit bd9ee18e562b00b73640525414d771f19ca84f05 and 86c16fa5d8397aca49813d2e2e158a36eb526a6a should fix this. Thanks.
