### ISSUE TITLE
Screen darkening

### ISSUE THREAD

**Issue by TheGator1** [TeamNewPipe/NewPipe#8083]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.22.1

### Steps to reproduce the bug

Just starting happening today on my Samsung Galaxy tab S7+, Android 12, when I go to full screen it just started darkening the video making it unwatchable, and unable to make it lighter. Without full screen it stays at the correct screen brightness. Rebooted the tablet to see if it was the reason and it's still darkened on full screen. On my pixel 6 I do not see this issue.

Andrew

### Expected behavior

Screen brightness not to go dim, was working fine till today and when I hit the square in the lower right to go to full screen, the screen just goes very dark and I  adjust ing the brightness for the video does nothing

### Affected Android/Custom ROM version

Android 12

### Affected device model

Samsung Galaxy tab S7+

**Comment by litetex** [comment]
Works as intended.
When you enter the fullscreen mode the brightness gesture becomes active. You can disable it in the settings, then it should use the system brightness.

See also #4072

**Comment by TheGator1** [comment]
Thank you, now will l have to donate, great app.

Andrew

**Comment by litetex** [comment]
> Thank you, now will l have to donate, great app.

No problem. Also thanks for the donation 😄

**Comment by shuttittuppitt** [comment]
My device = Samsung galaxy tab A7 (tablet)
Android OS = Android 11
NewPipe = 0.23.0 (downloaded it from here)
@litetex
"Works as intended"
Please tell us that that's a joke. Congratulations. Version 0.23.0's default settings made my screen darker than I thought it was possible to get! Version 0.23.0 is the FIRST version that this has ever happened to me, & I don't remember ever having changed ANY of the settings in any older versions.

I hope that in future versions, the "Brightness gesture" option will be turned OFF by default, because having to come here (read = github) to find out how to STOP NewPipe from doing this is going to be something that a LOT of users will have to do (right after 0.23.0's DEFAULT behavior AMBUSHES them).
