### ISSUE TITLE
NewPipe vs LibreTube

### ISSUE THREAD

**Issue by NKentatE** [TeamNewPipe/NewPipe#8229]
### Checklist

- [ ] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [x] I have taken the time to fill in all the required details. I understand that the question will be dismissed otherwise.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### What is/are your question(s)?

When new pipe affected and fixed in 0.22.2, but when i check with libre tube it does affect and not have any issues how is it possible.

**Comment by TiA4f8R** [comment]
LibreTube uses [Piped instances](https://github.com/TeamPiped/Piped), especially their [back-end](https://github.com/TeamPiped/Piped-Backend/) (with the API they provide), which use [NewPipe Extractor](github.com/TeamNewPipe/NewPipeExtractor/) to extract contents (a [custom one, in fact](https://github.com/FireMasterK/NewPipeExtractor/)).

So Piped back-ends just have to update the extractor, if it breaks, and the LibreTube app has nothing to do (because it relies on Piped's API), contrary to NewPipe, which needs to ship the new extractor version in the app.

Let me know if you want to know the technical details of why the extractor version used by Piped didn't break the extraction of streams :)

**Comment by NKentatE** [comment]
Thanks
