### ISSUE TITLE
Can't seem to play many Youtube streams

### ISSUE THREAD

**Issue by lico9182** [TeamNewPipe/NewPipe#8281]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.22.2

### Steps to reproduce the bug

Go to certain videos, and click play, all that happens is the loading buffer circle shows, the video never starts playing

### Expected behavior

Clicking a video nd clicking on play should load the stream and play, only shows buffer circle 

### Actual behavior

This is not happening on all streams, some do play, on the streams that don't the comments do load 

### Affected Android/Custom ROM version

12

### Affected device model

Samsung z flip 3 5g 

### Additional information

Samsung One ui 4.1, Surface Duo Androd 11 , both devices are having these issues

**Comment by lico9182** [comment]
Newpipe seemed to work better on the previous version

**Comment by TiA4f8R** [comment]
> on the streams that don't the comments do load

Do you have an error report generated by the app for this issue?

About the other (first) issue, you didn't follow template instructions: it's easy to see that this issue has been reported couple of times by searching on the issue tracker and looking at pinned issues. That's not videos which are not playing, that's throttling from YouTube, for which you can solutions on these issues (like seeking for instance).

Avoid this behavior in the future for any repository you want to open an issue (so always search for exisiting issues before opening a new one, follow instructions of issue templates, if the repository is using them) (I am saying this to you because it seems you are new to GitHub, even if that's off-topic).

**Comment by gitrdn** [comment]
I'm able to play the videos specified by OPs in issues 8282 and 8285 so posting my problem here. the following vid won't play (I can see comments), but will play in a browser:

https://www.youtube.com/watch?v=5GclFYUVyLc

The error I get is a simple flash notification near bottom of screen that says "An error occurred, see the notification." I then have to go to the notification shade to click the newpipe error notification to see the normal newpipe error screen that normally would pop up by itself.  

all the other vids i've just tried to play (around 10 of them) on same or other channels will play, so I don't understand the "network error" designation. 

since this vid is more than an hour, I also tried playing other longish or longer vids (for instance, this 5 hour vid: https://www.youtube.com/watch?v=pJ9M5ubO83k), and they play fine, though there may be other problem vids which I've not yet encountered.

## Exception
* __User Action:__ play stream
* __Request:__ Player error[type=0] occurred while playing https://www.youtube.com/watch?v=5GclFYUVyLc
* __Content Country:__ US
* __Content Language:__ en
* __App Language:__ en_US
* __Service:__ YouTube
* __Version:__ 0.22.2
* __OS:__ Linux samsung/greatqlteue/greatqlteue:9/PPR1.180610.011/N950U1UEU5DSD4:user/release-keys 9 - 28
<details><summary><b>Crash log </b></summary><p>

```
com.google.android.exoplayer2.ExoPlaybackException: Source error
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:580)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:214)
	at android.os.HandlerThread.run(HandlerThread.java:65)
Caused by: com.google.android.exoplayer2.ParserException: Invalid NAL length
	at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.readSample(Mp4Extractor.java:605)
	at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:249)
	at com.google.android.exoplayer2.source.BundledExtractorsAdapter.read(BundledExtractorsAdapter.java:127)
	at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1049)
	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:417)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)

```
</details>
<hr>
