### ISSUE TITLE
Captcha requested

### ISSUE THREAD

**Issue by XjFred** [TeamNewPipe/NewPipe#8512]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.0

### Steps to reproduce the bug

1.Search for a video
2.Captcha requested
3.Solve Captcha but the video won't play
4.Back to 1.

### Expected behavior

Play the video without asking captcha, as usual.

### Actual behavior

Keep asking to solve Captcha continuously and won't play video

### Affected Android/Custom ROM version

Android 10 /e/OS

**Comment by XjFred** [comment]
![Uploading Screenshot_20220614-225850_NewPipe.png…]()

**Comment by vehosah** [comment]
> I changed my VPN location and it solves the problem.

Good for you, it didn't work for me

**Comment by ShareASmile** [comment]
@vehosah why are you necro posting on a 3 years old issue which is a closed one, contains outdated info? 

Also we have noticed that you have posted on other old issues in the repo in addition to this one, please refrain from doing so. As ideas/workarounds floated years ago have become irrelevant with time because they contain outdated info and lot of big changes have happened since then from the YouTube website behavior and in the app side from code wise as well as parsing mechanism wise.
