### ISSUE TITLE
Default resolution of Some live youtube videos is 1080p?

### ISSUE THREAD

**Issue by ajmz** [TeamNewPipe/NewPipe#8527]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the question will be dismissed otherwise.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### What is/are your question(s)?

Some live youtube videos played by NewPipe after the end of live broadcast, the default resolution is 1080p, and the low resolution set by the system cannot be selected automatically, but YouTube itself can play the low resolution.

**Comment by ajmz** [comment]
Thanks. So it means the live stream quality selector is still under improvement?

**Comment by AudricV** [comment]
Yes, even if the way in the linked pull request of the issue Sameen linked above is not optimal in terms of code, but works. I will see what I will do of this feature later.

Right now the app and the extractor (in the version shipped with the latest app release) are not capable to watch fully ended livestreams for now (which are considered as live contents).

This will change with the next release (ended live contents will have a separate status, even if you will see them as normal videos), in which you will be able to watch ended livestreams entirely, with the video resolution you want (among the available ones of course). Note that these streams will be not downloadable (see the `Technical details, if you like` section).

You can already try the changes in #8153.

<details>
<summary>Technical details, if you like</summary>

YouTube uses DASH to play contents, except when you browser doesn't support the MediaSource API or as a fallback on mobile app clients if no DASH stream cannot be fetched, old formats are used (the ones you can hear audio with the video when you play video streams in external players (itags 17 (3GPP 144p with very low fps), 18 (MP4 360p with at most 30 fps), 22 (MP4 720p with at most 30 fps, which has some server issues, mostly on recent contents)).

A lot of these DASH streams can be played as progressive streams too (mostly on partner creators and on musical auto-generated contents), even if this way is more and more throttled. That's the current way used for playback in the app, and this will change in the next update (we will switch to DASH), and the current way will be used as a fallback if "generating" DASH sources fails.

But on livestreams and ended livestreams, that's not the case, streams are not progressive. Hopefully, YouTube returns a HLS manifest and a DASH manifest (not usable for running livestreams). Those ones are incomplete (limited to last 2 or 4 hours for ended livestreams).

However, I found a way to create a DASH manifest which allows playback of the full duration (which require fetching the first sequence twice: one by the creation process in order to get the duration and the number of segments and one by the player for playback). This way will be used for ended livestreams with the next update.

If you want to get more details of how manifests are generated, please take a look at the corresponding extractor pull request.

Non-progressive streams will be not downloadable in the app because the downloader only supports progressive contents (and support of downloading DASH, HLS and maybe SmoothStreaming contents will require a lot of work).
</details>

Closing as already resolved 😉
