### ISSUE TITLE
A word that is not allowed to be translated

### ISSUE THREAD

**Issue by Nizami20052022** [TeamNewPipe/NewPipe#8557]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

![Screenshot_20220627-222432_NewPipe SponsorBlock](https://user-images.githubusercontent.com/104249296/176010514-5bf38b50-38ad-4e1a-b7e7-40701a9b4113.jpg)

### Why do you want this feature?

Let me translate this word.

**Comment by SameenAhnaf** [comment]
Sign up on Weblate with your GitHub account. Go to [Newpipe Weblate](https://hosted.weblate.org/projects/newpipe/#languages) and click on your language to contribute to translation.

**Comment by Nizami20052022** [comment]
![Screenshot_20220628-121101_Chrome](https://user-images.githubusercontent.com/104249296/176128501-1fb24bbd-0366-4722-a098-265a62afc3ae.jpg)

**Comment by Nizami20052022** [comment]
Read-only strings

**Comment by Nizami20052022** [comment]
This sentence cannot be translated because it is not allowed.

**Comment by AudricV** [comment]
You can now do it.

It seems that the translation was blocked because the source string was marked as `To be verified` (which should be not the case at all).

I also deleted the translation from your glossary, because it seems to be used as a translation of the string and not as a definition. Free feel to revert this part if required :)

Closing as fixed, thanks for the report which blocked the translation of this string in all languages!
