### ISSUE TITLE
Pop-up window resizing doesn't seem to work

### ISSUE THREAD

**Issue by mission712** [TeamNewPipe/NewPipe#856]
- [X] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

The pop-up resizing doesn't seem to work anymore in 0.11.2. When I opened the popup video and tried resizing it, it first snapped to full width, and then did nothing when I pressed+held on the sides of the video. I can reproduce it on multiple videos.

**Comment by wb9688** [comment]
The gestures have changed, iirc you now resize it by pinch-zooming.

**Comment by Duppadaadadii** [comment]
IMHO, using two fingers to do anything is clumsy. I think that better option would be to hold down the pop-up icon and zoom in and out. Both would also work. Double tap and drag to zoom would also be better.

I just find using two fingers always a pain.

Same as why propably most people use chromium based browser rather than Firefox on mobile, because of the double tap and drag to zoom.
