### ISSUE TITLE
NewPipe Stops Playing

### ISSUE THREAD

**Issue by H3cTorox** [TeamNewPipe/NewPipe#8703]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0230

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.23.0
* __OS:__ Linux Android 8.1Go - 23
<details><summary><b>Crash log </b></summary><p>

```
java.lang.OutOfMemoryError: OutOfMemoryError thrown while trying to throw OutOfMemoryError; no stack trace available

```
</details>
<hr>

### Expected behavior

Should play on

### Actual behavior

Stops playing

**Comment by AudricV** [comment]
> `java.lang.OutOfMemoryError: OutOfMemoryError thrown while trying to throw OutOfMemoryError; no stack trace available`

The stack means everything: your device runs out of memory. As written in the stack trace, it seems you have Android Go, which is made for low RAM devices, so your device should not have a lot of RAM. But I can't check this because you didn't fill the device model part of the issue template.

There is nothing we can do about this. Make sure to close apps which eat a lot of RAM (including in background) and try to disable images loading.

> - [x] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).

> - Version: 0.23.0

0.23.0 is not the latest version, please update to the latest one and fill in properly the issue template by describing more clearly your issue the next time. Thank you.
