### ISSUE TITLE
Install Issue on New Phone

### ISSUE THREAD

**Issue by HighlyFavoredBA** [TeamNewPipe/NewPipe#8827]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the question will be dismissed otherwise.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### What is/are your question(s)?

On my new Samsung A53 phone, when I click on Install Unknown Apps, it shows Already Installed Apps, and Nothing else happens.

 I had NewPipe on my last phone for 2 or so months.  Videos cut out a Lot more than on YT.  However. I like No ads a Lot!  😎

**Comment by HighlyFavoredBA** [comment]
NObody on here has had an Instalation Issue like what I mentioned?  And NObody on here Knows a Solution?  🙃

**Comment by AudricV** [comment]
I'm afraid this is out of scope of NewPipe's issue tracker. You will have better chances to search an answer on the web.
Closing as out of the application scope (note that other users which have this issue and wants to share their potential solution could always comment here and answer you).

**Comment by ShareASmile** [comment]
> when I click on Install Unknown Apps, it shows already installed Apps

Then find and Turn on Install Unknown Apps option for that app from which you are trying to install NewPipe Apk, if it is the Browser using which you  download NewPipe Apk from  then Turn ON above option for that Browser from the list, 

otherwise if you are clicking on already downloaded apk from My Files app of Samsung inbuilt File Manager then find My Files from List then Turn ON the option to Install Unknown Apps from that.

I hope that clears things up hopefully.

**Comment by HighlyFavoredBA** [comment]
Today, I Finally figured out what was explained in the Last NewPipe reply to me.

I gave the Samsung My Files app Permission to let me Install NewPipe.  :--)

In the past, I remember it being Different.

Truly, Andrew

-- Sent with https://mailfence.com  Secure and private email
