### ISSUE TITLE
Adding a Blue Theme

### ISSUE THREAD

**Issue by CharleeBrown** [TeamNewPipe/NewPipe#8965]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

The only change would be the color of the components. The overall functionality of the project would remain the same.

### Why do you want this feature?

My favorite color is blue, and there were no blue themes.  Also, I want to start contributing to open source projects and this seems like a good opportunity.

### Additional information

<img alt="Screenshot_20220912-150830_NewPipe Debug" src="https://user-images.githubusercontent.com/4854484/189911587-1745b1cb-b294-403c-88fe-fef07379f1d3.jpg" height=600 />

**Comment by MDP43140** [comment]
tbh that white text with bright cyan-blue background is unreadable, i prefer black text with white background, changing just the accent color to blue

**Comment by CharleeBrown** [comment]
@MDP43140 How's this?

![Screenshot_20220913-140150_NewPipe Debug](https://user-images.githubusercontent.com/4854484/189987960-ca0c25fd-b3e6-4753-8c91-52f340c4eacd.jpg)

![Screenshot_20220913-140150_NewPipe Debug](https://user-images.githubusercontent.com/4854484/189988286-f23c4403-e1f9-4141-bbec-0a1d058346b3.jpg)
![Screenshot_20220913-140317_NewPipe Debug](https://user-images.githubusercontent.com/4854484/189988288-5130076e-1d09-42cd-94cb-0ff32bd79ac4.jpg)

**Comment by MDP43140** [comment]
maybe its a bit better to reduce the cyan saturation a little bit, and also the "Trending", "NewPipe Debug", title color should be white

**Comment by Stypox** [comment]
I don't think a new theme should be added to newpipe. Usually apps only provide light, dark and black themes. As per other themes:
- they would be used by only really few people
- they require maintenance effort
- they can possibly create more situations to handle in the code, hence more bugs
- if we start adding one colorful theme, why not adding more? People will start making requests, but we can't have tens of themes in NewPipe.

It's great that you want to start contributing to NewPipe! However I would not begin with this task because of the complexity of building a theme in Android. You may look at other tasks flagged as [good-first-issue](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22), instead.

**Comment by GameOverFlowChart** [comment]
Actually, using that experience could be used to implement Material You. Material you adapts the colours of the ui to the favourite colours of the user and avoids problems like unreadable colour combinations while every user has its own favourite colour. We don't need to reinvent the wheel, Material You was introduced to solve exactly this kind of problems. Use adaptivity instead of making decisions for the end user.

**Comment by tsiflimagas** [comment]
Then you may upvote #7595.
