### ISSUE TITLE
Option to remove partially watched videos from the 'Whats new' feed.

### ISSUE THREAD

**Issue by killerrook** [TeamNewPipe/NewPipe#9126]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Option to hide partially watched videos along with fully watched videos from the what's new feed of subscribed channels.

### Why do you want this feature?

Sometimes you don't find some video worth watching or listening and you skip it in the current playing queue but it still remains in the what's new feed, which is somewhat annoying.

**Comment by ishitak0712** [comment]
Hi there, I am a computing student from the Australian National University. Can I take on this issue? Thanks.

**Comment by opusforlife2** [comment]
@ishitak0712 Could you give an idea of how you're thinking of doing this?

**Comment by opusforlife2** [comment]
I was thinking of a simple menu with radio buttons, which lets a user choose between full, partial, or both.

**Comment by opusforlife2** [comment]
The duration of partially watched videos is a bit tangential to this particular issue, though. To discuss letting users set custom durations for it, you can open a new issue.

**Comment by ishitak0712** [comment]
Yes that is what I was thinking too. Defining a threshold value over which the video is considered watched. 5 seconds seems good to me.

**Comment by Stypox** [comment]
Currently this is the code that controls whether an item's "viewed" state is saved, and whether an item is considered as "finished".

<img src="https://user-images.githubusercontent.com/36421898/197837295-aa61bba8-0782-4f17-b52e-1c66a7ae0563.png" height="400px"/>

- if `isValid` returns false, then the progress is not saved to the database at all, in order to prevent saving progress about videos opened by accident
- `isFinished` controls three things:
  - whether items are hidden from the feed in case the user chose to remove hidden files
  - whether watched playlist items are removed when the user requests to remove fully watched items
  - whether the player will resume a video from the last saved position when it is opened, or whether it will start from the beginning (starting from the end of the video is usually something unwanted)

Note that the `isFinished` implementation is not only in the [StreamStateEntity](https://github.com/TeamNewPipe/NewPipe/blob/master/app/src/main/java/org/schabi/newpipe/database/stream/model/StreamStateEntity.java) file mentioned above, but also in an SQL query in [FeedDAO](https://github.com/TeamNewPipe/NewPipe/blob/master/app/src/main/java/org/schabi/newpipe/database/feed/dao/FeedDAO.kt).

So any code change related to `isFinished` should take into account all three use cases, and should behave the same in the three places. Providing a way for the user to choose thresholds for all three behaviors is a bad idea, both because there would be three times as many bugs, and also because this is so nitpicking that really few users would use it.

So what I'm proposing is to make the "hide watched" button a tristate button with this behavior:
- "Show watched items" - show everything
- "Hide fully watched items" - like current behavior, show only items where `isFinished` is false
- "Hide watched items" - show only items that do not have a `StreamStateEntity` attached to them in the database (that is, only items that were never opened, or that were opened just for few moments and `isValid` returned false and therefore they were not saved to the database)

**Comment by Jared234** [comment]
@Stypox @ishitak0712 Is this ticket still being worked on or can I give it a try?

**Comment by Jared234** [comment]
Ok, so I have almost completed implementing this feature. I still have a couple of questions regarding the layout/design of this option. I implemented three different visibility options: Show All, Hide Fully Watched, Hide Watched.
I thought that a simple menu might be enough for this feature. Or do you want me to open an extra dialog for it?
This is how it looks like:
![Screenshot_20230202-160831](https://user-images.githubusercontent.com/26669009/216371276-a9d44799-d686-4a95-a757-8c538ac8dfdb.png)
![Screenshot_20230202-160841](https://user-images.githubusercontent.com/26669009/216371302-89fb8028-913e-4a77-8431-cf9eb2506c3f.png)
![Screenshot_20230202-160854](https://user-images.githubusercontent.com/26669009/216371325-e2983cb8-f534-4e03-a56b-8397212a0f40.png)

If this is fine, I will open a PR.

**Comment by Jared234** [comment]
I don't think that checkboxes are necessary. Correct me if I am wrong, but I don't think there a use case where you e.g. only want to hide the partially watched and not the fully watched streams.
And what do you mean with the `Upcoming` option?

**Comment by Jared234** [comment]
Oh.. ok, then I agree that checkboxes make sense. Thanks!
I will implement these changes and then open a PR.

**Comment by Jared234** [comment]
Hmm ... I prefer the solution approach of @SameenAhnaf. If we were to use a button with 3 states, would it even be possible to hide, for example, fully viewed and upcoming videos at the same time?
I have also completed the implementation of this solution and will now open the PR, so you can have a look at it. But of course we can discuss this further.
