### ISSUE TITLE
Distribute NewPipe through the XDA Labs store as well

### ISSUE THREAD

**Issue by Maxr1998** [TeamNewPipe/NewPipe#925]
I'd love if you could also publish NewPipe on XDA Labs: https://labs.xda-developers.com/
It's an app store from the XDA developers community allowing developers to freely distribute their apps.

**Comment by theScrabi** [comment]
All right, sounds good, but I'd like to host it my self.

**Comment by Maxr1998** [comment]
Well, it isn't really resolved yet, I would really appreciate if you change your opinion - XDA Labs is a really nice store..

**Comment by zilexa** [comment]
Another vote for XDA Labs. Reason?
Users don't want 1 app store per app. The apps I currently use that are outside of the regular Play Store:
Blokada, Mixplorer, Youtube Vanced and NewPipe, Shazam Lite (made by a XDA forum reader, only available via download sites, still trying to convince him to publish to XDA Labs). 

I stopped using F-Droid since it kept giving me notifications to update apps that were already up to date. Even right after updating them via F-Droid. And since F-Droid doesn't contain all apps I use, I would need to have 2 stores (XDA and F-Droid) for just 4 apps.

**Comment by peat80** [comment]
Would be really nice to have NewPipe on the XDA Labs Store. F-Droid is horrible slow with releasing updates...

**Comment by AlexN1997** [comment]
XDA-Labs has been shut down, so this issue can be closed
https://www.xda-developers.com/update-xda-labs/
