### ISSUE TITLE
Add an option to use yt API

### ISSUE THREAD

**Issue by ccuser44** [TeamNewPipe/NewPipe#9299]
Add an option to use the yt API instead of using scraped HTML data.

When Newpipe is first installed the user should be prompted to ask which one to use. Like this:

- Youtube API. Better performance. Less buggy.

- Scraped HTML. Better Privacy. More buggy.

The option should also be configurable later in the settings.

This would allow the user to choose which one to prioritise.

Also this would probably reduce the buggy behavior associated with NewPipe and create a better user experience (for those who enable it).

**Comment by SC1040-TS2** [comment]
> It will trigger anti features on fdroid moreover it will increase app size which in turn means the app will become bulky. It even will sabotage the privacy friendly claims of Newpipe.

NewPipe already trips the Non-Free Network Services anti-feature parameter due to promoting its use as a Youtube replacement.

The more realistic concern is whether integrating the Youtube API would infringe on Google's policies for apps.

**Comment by lameventanas** [comment]
I'm interested in this, as a backup whenever things break

**Comment by opusforlife2** [comment]
If you're a developer then you're welcome to discuss the pros and cons with us in the IRC channel. There's no point in speculating as a regular user.

**Comment by TobiGr** [comment]
Apart from the problems regarding YouTube's terms of service, we do not want to focus on using YouTube's external API. Those require an API key which allows to track the users. And NewPipe's main goal is to provide a privacy friendly access to streaming data. Therefore, we will not implement it.

**Comment by aaferrari** [comment]
> Those require an API key which allows to track the users

Even so, it might be possible to implement one of these approaches:
* Add a section in the settings where the user can enter their own API key, as it happens with [Minitube](https://flavio.tordini.org/minitube). That way everyone decides whether or not to sacrifice their privacy.
* Something like [AuroraStore's anonymous logins](https://aurora-oss.vercel.app/guides/anonymous-logins/), which should more or less maintain the privacy of the users. I don't know how legal is this in the case of Youtube, so I would prefer to know the opinion of an expert on the subject.

Any other way of doing this would only open the door to repeat the history of HookTube (according to [this](https://datahorde.org/the-history-of-invidious/) it was a site similar to Invidious but after a while YouTube's legal department forced them to take it down because it worked with Youtube's API).

**Comment by WorkHard4470** [comment]
@TobiGr This requires a permit to use YouTube API.

**Comment by opusforlife2** [comment]
@WorkHard4470 Don't ping specific people if it is not needed. Since even a comment generates a notification and will be seen, you don't need to.
