### ISSUE TITLE
Downloader Enhancement for future Offline Mode

### ISSUE THREAD

**Issue by MarvAmBass** [TeamNewPipe/NewPipe#95]
Hey there,

I've noticed that you only download the file and store it on the SDCard.

Maybe we could improve this and store it with the necessary channel/video informations in subfolders of each uploader or something.

Maybe you're able to subscribe to a channel with the option to download all new videos to the device (so you can watch it later where bandwidth is rare)

After that you are able to display them nicely inside the app - like the other online videos.

**Comment by timofonic** [comment]
That's very interesting.

I have a very twisted idea, but that would be a lot more than the scope of this project. I would like my own "federated servers", mobile becoming one of them too.

I'll explain it later...

**Comment by theScrabi** [comment]
@timofonic Ow boy.
@MarvAmBass Nice idea. Didn't think of a combination of donwload and channels, and auto downloading. How ever for now I want to create a database containing information about downloaded videos. So that you can manage and watch videos directly from new pipe.
Also the download part is the next thing I want to take care of :)

**Comment by FaizKhan5** [comment]
Close this
