### ISSUE TITLE
[YouTube] Views are not shown for some videos in some channels

### ISSUE THREAD

**Issue by SameenAhnaf** [TeamNewPipe/NewPipe#9566]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.1

### Steps to reproduce the bug

Go to channel feed of https://m.youtube.com/channel/UC9d2mNoH8coSqtnotE81Tww

### Expected behavior

The number of views should be shown properly. 

### Actual behavior

Some videos don't show views. 

### Screenshots/Screen recordings

<img alt="IMG_20221219_224555" src="https://user-images.githubusercontent.com/79245641/208477174-e6b704c2-865c-4de8-a58e-c633cbe2a348.jpg" width=319 />

**Comment by lonewolf2208** [comment]
I would like to work on this

**Comment by AudricV** [comment]
This issue happen because these videos have a top badge (`Learn English with Cassé`, `English Fluency Coaching`, ...) and every top badge seems to be considered as a YouTube Premium badge.

The [check comes from this line](https://github.com/TeamNewPipe/NewPipeExtractor/blob/d5437e0bc5b7f9a2f8698c751fc1dfe0b750f127/extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/extractors/YoutubeStreamInfoItemExtractor.java#L283) and has been added with this commit: https://github.com/TeamNewPipe/NewPipeExtractor/commit/3187116a63cda7ddc2e7f68d3571fc7f353f476e.

I don't think it is relevant anymore, but this needs to be verified.

**Comment by pshirshov** [comment]
This is one more broken channel: https://www.youtube.com/@FeyginLive

NewPipe doesn't show any its videos newer than 4 months.

**Comment by lonewolf2208** [comment]
Hello, @AudricV  Could you please explain the purpose of the top badges. As soon as I remove the topbadges extractor's if conditions, the views are visible.
![WhatsApp Image 2023-01-14 at 1 51 48 AM](https://user-images.githubusercontent.com/72886809/212412209-9c993f7c-39d0-421e-a1d7-c54b38fb5443.jpeg)
![image](https://user-images.githubusercontent.com/72886809/212412266-d86cf5b5-ccf8-49f6-a72a-5675aaa9f45b.png)
Does this looks fine ?

**Comment by AudricV** [comment]
@lonewolf2208 Like I said in my previous comment, I don't know, but this needs to be verified, as I didn't introduce this code.

Free feel to test the changes on several places (channels, searches, playlists, ...).

**Comment by TobiGr** [comment]
Fixed in TeamNewPipe/NewPipeExtractor#1016
