### ISSUE TITLE
Bad WiFi leads to "Failed to play this stream"

### ISSUE THREAD

**Issue by momo42** [TeamNewPipe/NewPipe#967]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

First of all: I don't think this problem is related to this other bug https://github.com/TeamNewPipe/NewPipe/issues/883. So I decided to open a new issue.

At home I have very bad WiFi. This regularly manifests in noticeable short (1 - 2 sec.) hangs while loading websites in browser and some packet loss on the console. I did a lot of testing but was not able to fix this wifi issue. It's probably because of the many neighbor wifis.

Here is the problem: All other streaming apps on my devices incl. Netflix, Amazon Prime, Kodi (Addons) etc. deal well with it. Only NewPipe tends to hang while watching Youtube with "Failed to play this stream" followed by a black screen. Sometimes I'm able to get back to the menu to restart the stream but most of the times NewPipe hangs completely and its faster to close and restart NewPipe.

I think it has to do with the buffering behavior of NewPipe. I visually noticed that NewPipe loads some seconds video and when the buffer is depleted it loads the next few seconds. If my wifi drops packets in exact this moment, when the red (buffer) line is completely depleted, NewPipe runs out of video...

I really like NewPipe but this bug drives me crazy. (In fact its more an inability to handle bad connections.) Usually I'm not able to watch a 30 min. video to the end without restarting the app. Before you ask: When I'm at university (or somewhere else with better wifi) this error doesn't occur.

From my amateurish point of view this issue could be solved with a larger "safety margin" for the buffered amount of video. I don't know how other apps handle this but in fact I only have this problem with NewPipe. So please(!) add an option to adjust the minimum buffer size!

My affected devices all run the latest nightly of LineageOS 13 (Android 6.0.1).

Thank you very much for your attention!

**Comment by momo42** [comment]
Are there any news on this? :-)

**Comment by wb9688** [comment]
NewPipe tries to buffer minimally 15 seconds and maximally 30 seconds.
Maybe changing those values (which isn't possible in NewPipe, but only in
the code in PlayerHelper, so you'll need to compile it yourself for testing
it) would be better. @karyogamy might know more.

**Comment by karyogamy** [comment]
Increasing the buffer should be able to delay the failures for some time. Another solution right now is to increase the number of allowable retry in the data source, hoping the network problem is solved within the retries. I've created a [new data source factory](https://github.com/karyogamy/NewPipe/blob/77da40e507ecebc8c0b361d1ed846cf0fa3ca356/app/src/main/java/org/schabi/newpipe/player/helper/PlayerDataSource.java) to do some manipulations on media source creation in the player and increased the retry count to `Integer.MAX_VALUE`. This probably have some bad side effects, so I'll be testing it around.

@wb9688 
In the same file, I've also added custom cache keys to allow cache reuse for streams under the same general url (rather than stream url). Perhaps this will suit your need, as per our conversation. You will still need network connections to load the stream info though, since it contains some essential metadata.

**Comment by wb9688** [comment]
@karyogamy: Thanks! That's pretty much what I wanted. And the stream info
is small enough for me, just being able to really cache the streams itself
is all I wanted (well, except for some settings for maximal buffer and
cache size, but I can create options in the settings for that myself).

**Comment by ale5000-git** [comment]
What about when there are network problems waiting like 2 seconds and then retry buffering (with infinite attempts) instead of failing?

It is useful for unstable Wi-Fi networks.

**Comment by momo42** [comment]
I'm on v0.11.6 (F-Droid) now but don't see any improvements. I'm not a developer and I'm not able to understand your code changes or compile something. Is there any progress in this topic? I really like NewPipe. So I'd like to use it at home too. :-)

**Comment by karyogamy** [comment]
This should be fixed in the new 13.0-beta release, though it might take some time to get to the F-droid beta page, although the your existing data (e.g. subscriptions) won't be carried over.

@theScrabi 
Have we released a new stable version yet? If not, maybe we should consider doing so since anything is better than the current 11.6-stable now, with the subtitle NPE and whatnot. Also, this will let the database import/export feature out, which will encourage more user to use the beta. 

Having said that, I think it's strange how our beta release is more stable than the "stable" release for such a long time. Perhaps we should rethink the release strategy and make more periodic updates rather than waiting out all the bugs before stable release? Or maybe having the team (and beta users) to have a vote to green-light a stable release?

**Comment by momo42** [comment]
Thank you guys! Generally I know how to download and install the beta apk to test it but will it break my existing installation? And is it possible to switch back to f-droid when the final is released? Please excuse my dump questions! I'm just a (happy) user and don't know the technical stuff under the hood. :-) Beside of that I definitely vote for a new F-Droid release! :-)

**Comment by wb9688** [comment]
Beta build should be a separate NewPipe Beta app, which you can install
alongside NewPipe.

**Comment by momo42** [comment]
Ok, I'll test it on we. :)
