### ISSUE TITLE
Legal qzestion

### ISSUE THREAD

**Issue by Hashik-Donthineni** [TeamNewPipe/NewPipe#969]
- [nope] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

I have a few questions, can some one answer? Is this app legal according to Google? Will they sue you if you are a developer for this kind of app? what happens if the app is uploaded to Google play? This is the most important question, What part of the app are illegal?

**Comment by Hashik-Donthineni** [comment]
I am sorry if this isn't the place I have to ask questions, but I can't find your forums.

**Comment by wb9688** [comment]
This app is legal in at least Germany and the Netherlands. Google can't sue
the developers, since we're protected by the GPL. This app violates the
Play Store's ToS, so you can't upload this app there.

@TheAssassin can explain it better than me though.

**Comment by theScrabi** [comment]
@Hashik-Donthineni I take from your commend that you would want to fork NewPipe and put it into playstore right?

Well if so it was a shameful task!!! because you take the work from others and get credit for it just for your self. It was better if you contributed to NewPipe it self, and than distribute NewPipe as it is :)

Anyway NewPipe is not violating against Google as long as you don't have a contract with them. When you load it up to playstore you do violate this contract, and you will get in trouble. So don't.

**Comment by Hashik-Donthineni** [comment]
You quickly want to jump to conclusions and call me shameless, don't you? I have other plans which I don't want to disclose the work is done with the consent of the owner of the content. I just want to ask if it is legal to "Scrap" their website(Youtube) and get the content from the site, I don't want to use the API cause the usage is limited. I am fairly new around GitHub or any source control, it forked automatically when I tried to edit the code. I really liked your app and I am looking forward to contributing to your app, altho you judged me quickly that doesn't change my mind to say otherwise about the app, it's great.
I have few other questions if you are willing to answer, isn't providing a download button legal? that involves stealing work of others or something, I've read on their site that downloading content is illegal.

**Comment by wb9688** [comment]
>isn't providing a download button legal?

It's legal in some countries, like Germany and the Netherlands, because of
the laws there with "home copies". In other countries, it might be illegal.

**Comment by Hashik-Donthineni** [comment]
Thanks for the response, @wb9688 What about scrapping and using their content? Can I place it in play store?. Since there aren't any ads, the creators of the video aren't getting any revenue, to think of it in an intuitive sense it shouldn't be legal but counter-intuitively "Ad blocks" on chrome are legal.

SideNote: I really wish this app provides an option to enable and disable ads on YT videos, the revenue should be given to the creators and the users are perfectly happy and can choose to disable them.

**Comment by theScrabi** [comment]
I am pretty sure that once you have a contract with google you will also be bound to googles [terms of service](https://developers.google.com/youtube/terms/api-services-terms-of-service) for youtube, and its api.

I guess scraping is possible, but you will still be bound to the same restrictions as the api.

**Comment by TheAssassin** [comment]
> isn't providing a download button legal?

You can put there what you want. It is the users' responsibility to determine what they may and may not do with the app. The GPL explicitly excludes any kind of warranty. I know that users tend to just "do" what applications allow them to do, and don't really pay attention, but really, that's their own problem. It's like with pentesting software for example, you can use that legally and unlawfully, and you're in charge of how you use it.

Google won't be able to "sue" you for developing such an application. Even if it was put in their app store, all they could do is kick you and the app from it, but that's it. I don't know about any law explicitly prohibiting the violation of the terms of Google's services, but that's what would be required to be able to sue people for this reason. So I wouldn't worry about that.

> Since there aren't any ads, the creators of the video aren't getting any revenue

By the way, watching ads are not really a "way" to properly send revenues to content creators. I would say, rather look for a donation button, and send them real money, that'll help them more than the 5% share they receive from the ads (because, news flash, Google and YouTube get most of that money).

> to think of it in an intuitive sense it shouldn't be legal but counter-intuitively "Ad blocks" on chrome are legal. I want to copy specific implementations and the API(since it's open source) but not the whole app or the idea, don't get me wrong.

Ad blockers are not there because people don't want people to get paid. Ads are a way to receive money for work. But advertisement on the Internet has a *lot* of issues, which you don't have in other media, e.g., press, or commercials on TV.

First and most important, ads on other media are a "one way" thing. When you consume them (e.g., watch a commercial on TV, or read an ad in a newspaper, your privacy isn't compromised, the creator doesn't get any notification, but you read it anyway, and since they know how many people buy those newspapers or watch TV at specific times, they can estimate the market share and/or number of people watching it, and calculate the revenue of the content creator.

However on the Internet, advertisement got *really* annoying (in comparison with a newspaper, where the ad is static, integrated in the content, and clearly visible as an ad), the worst one's are flashing in weird colors to catch attention. Also, they compromise users' privacy, by sending information about the consumer back not to the content creator, but the ads company. Your personal information is sent, you can't move across pages anonymously etc., they can track you, which is just something they can't in any other kind of media.

There's even another form of advertising named "malvertising", where those ads actually infect the viewer's computers with malware of all kinds.

There is a reason Google, a company making the vast majority of their money with advertisement (really, why do people always forget about that, same goes for Facebook), started a project to define a set of rules which need to be met in order to continue their business (it's called an "ad blocker", Google say they're only blocking annoying ads, but realistically spoken, one can expect them to block any kind of ads they don't like, Google love to exploit their market power).

Call an ad blocker a "measure of self protection". Finally, the Internet, which started as a free and open community that was compromised by companies trying to spy on people and enforce stupid business models, got usable again.
(Not to mention ad blockers often apply anti tracking filter lists, too, of course.)

I am a strong advocate of "Ethical advertising" by the way, which also prohibits tracking and alike, and aims for making ads on the internet more newspaper-ish (i.e., static pictures). See e.g., https://docs.readthedocs.io/en/latest/ethical-advertising.html, for more information.

**Comment by Hashik-Donthineni** [comment]
@TheAssassin Thanks for taking your time to answer the question, means a lot.

> The GPL explicitly excludes any kind of warranty.
What if the app isn't under GPL?

So, in a nutshell. 
-It's completely legal to scrap their website and use the videos(I need to be certain about this).
-Providing download button is also legal (as long as we are under GPL, little bit clarification would be much appreciated in this aspect).

You have explicitly mentioned that "NewPipe violates their policy of GooglePlay", why is that? judging by what you said, it must be completely legal/acceptable.

Really, thanks again.

**Comment by TheAssassin** [comment]
@Hashik-Donthineni Google Play do prohibit applications like ours which access e.g., YouTube, or other Google pages, without using their API, IIRC (especially since they introduced their YouTube pro or however it's called, because NewPipe offers similar features for free).

  - NewPipe won't get into the Play store, as it violates the Play store terms. Contributors and fans of NewPipe occasionally have illegal copies removed from the Play store for this reason (see #539).
  - Accessing the YouTube page is legal, it's public information, they offer it publicly, at most one could violate their terms because they wouldn't want you to access their API or so, but I doubt they'd be legally successful about it. It's not even an API, the app mimics their player by accessing a file their player would fetch, too, which contains meta information about the different streams available on the server (bitrate, resolution, etc., which their client uses to automatically detect which one to use). 
  - Offering most kinds of functionality is legal (some aren't, e.g., you may not necessary write a tool for hacking stuff, and then publish it on the internet, that's prohibited in Germany (§§ 303b (5) (a.k.a. *hacker paragraph*), 202c StGB), but as long as it serves research purposes, it's unlike you get sued and/or sentenced). In any case, the license especially says you as the dev are not liable for anything that the app does with people's devices, or what people do with your app.

**Comment by TheAssassin** [comment]
> What if the app isn't under GPL?

Nearly any open-source license contains a paragraph saying something about "this software comes with no warranties, etc.".

**Comment by Hashik-Donthineni** [comment]
Ok, that makes it lucid enough to me. It's wrong on Google's part to take down apps like that.

**Comment by speednroll** [comment]
@Hashik-Donthineni I thought that with that answer that he leave @TheAssassin the whole question was explained :joy:

**Comment by Hashik-Donthineni** [comment]
Nope, he mentioned why NewPipe is being taken down. Other people are copying their functionality and their app but they are still up and running [Here check this out](https://play.google.com/store/apps/details?id=com.rain.audio.rocket)

**Comment by TheAssassin** [comment]
> Nope, he mentioned why NewPipe is being taken down. Other people are copying their functionality and their app but they are still up and running Here check this out

Not really. NewPipe hasn't ever been (and won't ever be) published in the Google Play store.

To my knowledge, however, illegal copies of NewPipe have been taken down with either the argument that they violate the GPL license (hence a DMCA takedown request), or because they violate the Google Play ToS.

**Comment by TheAssassin** [comment]
Just to finally clarify this: NewPipe is *not* illegal. But it might violate some of Google's ToS (which is nothing to worry about), and definitely violates the Google Play ToS (which is why it won't be put there, apart from us being unwilling to silently accept Google's attempts to put more and more walls around the garden called Android).

**Comment by Hashik-Donthineni** [comment]
Ok, that makes it clear. Thank you.

**Comment by Elidio** [comment]
I took some time to read the ToS of Youtube:

_The following restrictions apply to your use of the Service. You are not allowed to:

3. access the Service using any automated means (such as robots, botnets or **scrapers**) except (a) in the case of public search engines, in accordance with YouTube’s robots.txt file; or (b) with YouTube’s prior written permission; _ 

NewPipe is a scraper, and therefore, using it **DOES** constitute a violation of the ToS. 

Now, the next question is, how illegal it is to violate YT Terms of Service? And is it illegal to write and make available software that enables ToS violations?

As for the first question, I guess it's at worse a civil case (ie: youtube can ban you at best and sue you at worst, but it will not land you in jail). There is of course the question of detecting the use of our beloved scraper. I thing Google does have the tech to do it, but I think it's unlikely that they will come for the users...

**Comment by RiedleroD** [comment]
ToS are not law - it just means that if you violate them, youtube is free to withhold their services to you (i.e. terminate your account & block your IP if they're extra mean) - it only becomes illegal if you agree to the ToS by using their services through their official clients (i.e. the website, the regular app, etc.)

Cease and Desist letters don't have to have any reason to exist; just the threat of a legal battle which Google would 100% lose would stop any development being done on Newpipe, since nobody here can afford a lawsuit, even if they're in the right. That's raging capitalism for you.

worst case scenario (legally): google figures out how to check if someone is using NewPipe, blocks their IP from using youtube and terminates their google account. Very unlikely to ever occur though.

worst case scenario (generally): google doesn't give a fuck and sends a C&D despite not being in the right. We lose. Game over.
